### PR TITLE
Perf data

### PR DESCRIPTION
**Pull request by joakim-hove**
Assemble all the per perforation data in one datastructure.

### CODE REVIEW

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by joakim-hove** [comment]
Comments to this?

**Comment by blattms** [comment]
benchmark please

**Comment by bska** [comment]
> Comments to this?

Please address the [new warnings](https://ci.opm-project.org/job/opm-simulators-PR-builder/2543/gcc/new/) first.

**Comment by blattms** [comment]
I am probably not educated enough to comment in the part from OPM and don't have a clear picture what the final goal is. But here are my two cents, anyway:

As someone coming from high performance computing, I am usually fond of plain old data in big arrays (rather than arrays of classes with multiple small arrays), like it was before, as it usually minimizes cache misses. I am a bit unsure whether this plays a role here or not (might depend on the number of wells and the number of perforation for each well). But minimizing cache misses usually does not hurt.

I am not sure what problem you are solving here. If the problem is getting rid of the outrages numbers of indexing in the code,  one could have used a of view approach on the global arrays. PerfDataView, a view on the data of a single well, would have references to the global arrays and the well index and could be used like your PerData (without introducing additional allocations and cache misses).

**Comment by bska** [comment]
> I am usually fond of plain old data in big arrays (rather than arrays of classes with multiple small arrays), like it was before, as it usually minimizes cache misses.

Whether to use "array of structures" or "structure of arrays" depends greatly on the expected/common access pattern in the performance sensitive inner loops.  Especially on whether you expect to touch "all" items associated to a single entity (e.g., well, group, connection) before moving on to the next entity or whether you're processing a single item (e.g., reservoir volume flow rates) for all entities before moving on to another item.  I haven't looked too closely at all of the well code, but my impression is that it's a bit of a mix between the two.

**Comment by joakim-hove** [comment]
> I am usually fond of plain old data in big arrays (rather than arrays of classes with multiple small arrays)

It is of course in the mind of the beholder; but my preference is generally "array of structs" rather than the opposite. The reason I prefer "array of structs" is that I find it easier to work with (to test and reason about in particular, and also changes - e.g. adding a new field stay more localized). I realize that "struct of (large) arrays" might be more performant, but at least for the well code all[1] loops over perforations only iterate over the perforations of one well - i.e. the vectors in the new `PerfData` class - I therefor do not think decreased cache hit rate should be a problem.

> I am not sure what problem you are solving here.

Making the code easier to work with, more compact and testable, and in particular simpler to initialize the structures from a restart file.

> If the problem is getting rid of the outrages numbers of indexing in the code, 

Yes - that is certainly large part of it.

> one could have used a of view approach on the global arrays. 

Yes - that would have been possible - but more complex.


[1]: All that I am aware of at least ....

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by ytelses** [comment]
Benchmark result overview: 




| Test    | Configuration                                     | Relative |
| ------- | ------------------------------------------------- | -------- |
| opm-git | OPM Benchmark: flow_mpi_extra - Threads: 1        | 1.005    |
| opm-git | OPM Benchmark: flow_mpi_extra - Threads: 8        | 0.999    |
| opm-git | OPM Benchmark: flow_mpi_norne - Threads: 1        | 1.005    |
| opm-git | OPM Benchmark: flow_mpi_norne - Threads: 8        | 1.043    |
| opm-git | OPM Benchmark: flow_mpi_norne_4c_msw - Threads: 1 | 0.933    |
| opm-git | OPM Benchmark: flow_mpi_norne_4c_msw - Threads: 8 | 1.017    |
* Speed-up = Total time master / Total time pull request. Above 1.0 is an improvement. *



View result details @ https://www.ytelses.com/opm/?page=result&id=1229

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by blattms** [comment]
What is more beautiful is indeed in the eye of the beholder. IMHO we might close the door for some optimizations in the future (once the rest of the well code is performant).

> loops over perforations only iterate over the perforations of one well

There always seems to be an outer loop over the wells if I am not mistaking. We never process only one well. That means that were actually reading the complete large arrays as the order of the wells seems to be static. It could be of course that the order of processing the wells was not from front to back...

**Comment by blattms** [comment]
I am shutting up now... At least currently there is no penalty.

**Comment by joakim-hove** [comment]
> IMHO we might close the door for some optimizations in the future (once the rest of the well code is performant).

I see that point - my thinking is that if/when we want to do optimizations of this kind, that will  be simpler if the code in question is easy to reason about (famous last words ....).

**Pull request merged**
