### PR TITLE
fixed: make sure Damaris is enabled before executing test

### PR DESCRIPTION
**Pull request by akva2**
Not just that it has been found.

### CODE REVIEW

**Comment by akva2** [comment]
jenkins build this please

**Comment by akva2** [comment]
jenkins build this hip please

**Comment by bska** [comment]
jenkins build this please

**Comment by akva2** [comment]
okay, this will do, the hip build failed due to deprecation warnings but the post builder has no warning threshold so it won't hamper normal operation.

**Review by bska — APPROVED** [review]
> okay, this will do, the hip build failed due to deprecation warnings but the post builder has no warning threshold so it won't hamper normal operation.

Okay, understood.  In that case I'll merge into master.

**Pull request merged**
