### PR TITLE
change default to use inner iter for stw wells

### PR DESCRIPTION
**Pull request by totto82**
This is to compare with #3326

### CODE REVIEW

**Comment by totto82** [comment]
jenkins build this please

**Comment by totto82** [comment]
benchmark please

**Comment by ytelses** [comment]
Benchmark result overview: 




| Test    | Configuration                                     | Relative |
| ------- | ------------------------------------------------- | -------- |
| opm-git | OPM Benchmark: flow_mpi_extra - Threads: 1        | 0.534    |
| opm-git | OPM Benchmark: flow_mpi_extra - Threads: 8        | 0.517    |
| opm-git | OPM Benchmark: flow_mpi_norne - Threads: 1        | 1.036    |
| opm-git | OPM Benchmark: flow_mpi_norne - Threads: 8        | 1.067    |
| opm-git | OPM Benchmark: flow_mpi_norne_4c_msw - Threads: 1 | 0.999    |
| opm-git | OPM Benchmark: flow_mpi_norne_4c_msw - Threads: 8 | 1.003    |
* Speed-up = Total time master / Total time pull request. Above 1.0 is an improvement. *



View result details @ https://www.ytelses.com/opm/?page=result&id=1219

**Comment by totto82** [comment]
jenkins build this please

**Comment by totto82** [comment]
benchmark please

**Comment by totto82** [comment]
Initial testing of this is promising. If successful I plan to remove the use-inner-itereations-wells and --use-inner-iterations-ms-wells and instead add something like --max-newton-iterations-with-inner-well-iterations = 3

**Comment by totto82** [comment]
The norne prediction family tests for msw and stw looks good. Forcing 3 inner iterations for stw gives some improvements and restricting the number of inner iterations to 3 for msw does not seem to have a big impact. It would be really nice to avoid one parameter for msw and one for stw.

**Comment by ytelses** [comment]
Benchmark result overview: 




| Test    | Configuration                                     | Relative |
| ------- | ------------------------------------------------- | -------- |
| opm-git | OPM Benchmark: flow_mpi_extra - Threads: 1        | 0.993    |
| opm-git | OPM Benchmark: flow_mpi_extra - Threads: 8        | 0.973    |
| opm-git | OPM Benchmark: flow_mpi_norne - Threads: 1        | 1.014    |
| opm-git | OPM Benchmark: flow_mpi_norne - Threads: 8        | 1.046    |
| opm-git | OPM Benchmark: flow_mpi_norne_4c_msw - Threads: 1 | 1.138    |
| opm-git | OPM Benchmark: flow_mpi_norne_4c_msw - Threads: 8 | 0.805    |
* Speed-up = Total time master / Total time pull request. Above 1.0 is an improvement. *



View result details @ https://www.ytelses.com/opm/?page=result&id=1222

**Pull request closed without merging**
