### PR TITLE
reconstructing the if structure for has_energy in function StandardWell<TypeTag>::calculateSinglePerf()

### PR DESCRIPTION
**Pull request by GitPaean**
It is from the discussion in https://github.com/OPM/opm-simulators/pull/3853 . 

The version in this  PR is slightly easier to read and saves some unnecessary calculations.

It should not change the running results in any manner.

### CODE REVIEW

**Comment by GitPaean** [comment]
jenkins build this please

**Comment by GitPaean** [comment]
jenkins build this please

**Comment by GitPaean** [comment]
jenkins build this please

**Comment by totto82** [comment]
Thanks. Will merge this now and rebase #3853 on top of this.

**Pull request merged**
