### PR TITLE
remove cutoff for extrapolation

### PR DESCRIPTION
**Pull request by totto82**
Needs more testing

### CODE REVIEW

**Comment by totto82** [comment]
jenkins build this please

**Comment by atgeirr** [comment]
Removing this means allowing extrapolation further out than 3 times the length of the last interval in the table. That does not seem unreasonable, but I think it makes sense to keep some limit. What about limiting the `value` used to compute the factor to no more than (say) `values.back() + 3.0 * (values.back() - values.front())`, that is using the length of the whole defined interval, rather than the length of the last piece of it?

**Comment by blattms** [comment]
This indeed fixed the issue reported, but we should send the user a message if the interpolation limit is reached

**Comment by totto82** [comment]
Thanks for the feedback. I will do the following. Remove the cutoff but add a warning if the table is extrapolated 10% more than its complete range.

**Comment by atgeirr** [comment]
> Remove the cutoff but add a warning if the table is extrapolated 10% more than its complete range.

Sounds like a good plan.

**Comment by totto82** [comment]
jenkins build this please

**Comment by totto82** [comment]
jenkins build this please

**Comment by blattms** [comment]
This has been hanging for a quite a while. Did you check the failures and should we proceed with the update_data drill?

**Comment by totto82** [comment]
From my side this is ok. I will rerun jenkins.

**Comment by totto82** [comment]
jenkins build this please

**Comment by totto82** [comment]
benchmark please

**Comment by ytelses** [comment]
Benchmark result overview: 




| Test    | Configuration                              | Relative |
| ------- | ------------------------------------------ | -------- |
| opm-git | OPM Benchmark: flow_mpi_extra - Threads: 1 | 1.018    |
| opm-git | OPM Benchmark: flow_mpi_extra - Threads: 8 | 1.026    |
| opm-git | OPM Benchmark: flow_mpi_norne - Threads: 1 | 1.012    |
| opm-git | OPM Benchmark: flow_mpi_norne - Threads: 8 | 0.977    |
* Speed-up = Total time master / Total time pull request. Above 1.0 is an improvement. *



View result details @ https://www.ytelses.com/opm/?page=result&id=1801

**Comment by totto82** [comment]
More testing indicates that extrapolation of vfp table is not a rare event. Even thought removing the factor 3 limit seems to do no harm,  the output becomes very noise. I will need to investigate further. This PR is thus not yet ready.

**Comment by bska** [comment]
> This PR is thus not yet ready.

Okay.  Do you want to set it back to "draft" state to avoid someone accidentally merging the change?

**Comment by totto82** [comment]
jenkins build this please

**Comment by totto82** [comment]
> Okay. Do you want to set it back to "draft" state to avoid someone accidentally merging the change?

No, I rather want to merge this without outputting the extra debug info. I haven't find a case where removing the cutoff of 3 leads to problems. For some/many? cases the maximum flow potential in the well is far above the maximum entry in the "FLO" in the vfp-table. If we want to warn for every time this happens it will be too much. We need to find a better way to warn the user than outputting every time the vfp table is extrapolated, but that should be in another PR.

**Comment by bska** [comment]
> > Okay. Do you want to set it back to "draft" state to avoid someone accidentally merging the change?
> 
> No, I rather want to merge this without outputting the extra debug info.

I only responded to you [stating that this PR was not ready for merging](https://github.com/OPM/opm-simulators/pull/4098#issuecomment-1263435600).  I did not look at any of the details.

**Comment by totto82** [comment]
Approved by @atgeirr in private communication so I will start the update of data process (including the glift case)

**Comment by totto82** [comment]
jenkins build this update_data please

**Comment by totto82** [comment]
jenkins build this opm-tests=817 please

**Pull request merged**
