### PR TITLE
Add Regression Test for JFUNC Feature

### PR DESCRIPTION
**Pull request by bska**
There are no such tests in the test suite and we've already had one instance of the feature breaking during code refactoring.

Thanks to [at]tskille for providing the test case (OPM/opm-tests#888).

### CODE REVIEW

**Comment by bska** [comment]
Note: I'm keeping this in "draft" mode until we've verified that we're close enough to the reference to actually enable the regression testing.

**Comment by tskille** [comment]
This test model ( JFUNC-01)  has been tests and compared with results from the commercial simulator. Initial volumes and simulation results are in excellent agreement.  Thanks @bska for making sure that this model is included in the regression testing.

**Comment by bska** [comment]
> This test model ( JFUNC-01) has been tests and compared with results from the commercial simulator. Initial volumes and simulation results are in excellent agreement

Great news, thanks a lot for doing the testing @tskille.  I'll enable the test now.

**Comment by bska** [comment]
jenkins build this update_data please

**Comment by bska** [comment]
jenkins build this opm-tests=900 please

**Comment by bska** [comment]
Merging this now to prepare for merging the upstream PR.

**Pull request merged**
