### PR TITLE
Use EclipseState based Schedule constructor

### PR DESCRIPTION
**Pull request by joakim-hove**
Small step in the 3D refactoring saga

### CODE REVIEW

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by joakim-hove** [comment]
OK - the issue with bogus SATNUM values should be fixed here: #2191 (not tested yet)

But the norne init time is still an issue. Looking into it.

**Comment by joakim-hove** [comment]
The issue with init time is probably related to this: https://github.com/OPM/opm-material/pull/365 looking into it.

**Comment by joakim-hove** [comment]
OK: https://github.com/OPM/opm-material/pull/368 should fix the init time.

**Comment by joakim-hove** [comment]
Where can I find the relperm diagnostic output which @bska posted further up?

**Comment by akva2** [comment]
you have to run norne.

**Comment by joakim-hove** [comment]
> you have to run norne, then inspect console output.

OK - thanks; and that seems to be "No news is good news".

**Comment by blattms** [comment]
Is this constructor supposed to be used elsewhere instead of the one using the deck and the grid, too (i.e. apart from tests)?

**Comment by joakim-hove** [comment]
> Is this constructor supposed to be used elsewhere instead of the one using the deck and the grid, too

That is just a matter of convenience; but if you have an `EclipseState` handy at callsite I would say yes. The reason for this small change is the ongoing 3D refactor; with this PR opm-simulators can be fully shielded from code changes due to that refactor.

**Comment by blattms** [comment]
But the grid we are simulating one might have subtle difference to the one
in the EclipseState. For a sequnetial run just recall the issues we saw when
we tried to remove filterConnections. In a parallel run we are only using a
part of the grid. Will that work?

**Comment by joakim-hove** [comment]
>But the grid we are simulating one might have subtle difference to the one in the EclipseState

Ahhh ... I had forgot. We'll stick to updating tests.

**Pull request merged**
