### PR TITLE
removing some white spaces. 

### PR DESCRIPTION
**Pull request by GitPaean**
mostly to test the jenkins update_data system.

### CODE REVIEW

**Comment by GitPaean** [comment]
jenkins build this please

**Comment by GitPaean** [comment]
The previous change looks like running into compiler version difference. Locally it was warning related to extra `;`, while jenkins thinks it is necessary.  So I changed this PR by just removing some white spaces.

**Comment by GitPaean** [comment]
jenkins build this please

**Comment by GitPaean** [comment]
jenkins build this update_data please

**Comment by GitPaean** [comment]
jenkins build this update_data please

**Comment by GitPaean** [comment]
Just as https://github.com/OPM/opm-tests/pull/84 shows, jenkins always update all the `.SMSPEC` files. 

Any rational behind this or it is a bug?

@akva2

**Comment by joakim-hove** [comment]
I have not looked into this in detail, but observe that the test is based on a 'higher semantic level' than the data update, i.e we can very well have a situation where files - the "private implementation" - have changed without the actual tested values having changed. Hence you can ask for - and also get - file updates without real data updates. 

Maybe that is what you are seeing?

**Comment by joakim-hove** [comment]
No - "99.5% certain

**Comment by GitPaean** [comment]
For SPE1CASE2, I used the master branch to make two runs and `convert.x` to ascii text format. 
There are something different here, 
```
 'INJ     ' 'PROD    ' ':+:+:+:+' ':+:+:+:+'
 'NUMS    '          32 'INTE'
      -32676           1           1          -1          -1          -1
          -1          -1          -1          -1           0    67882208
    67882672           6    67883600    67884064           0         170
          -1           0         144           1           1         192
           0           0           1           1           1           2
           1         300
```
and 
```
 'INJ     ' 'PROD    ' ':+:+:+:+' ':+:+:+:+'
 'NUMS    '          32 'INTE'
      -32676           1           1          -1          -1          -1
          -1          -1          -1          -1           0    62737632
    62738096           6    62739024    62739488           0         170
          -1           0         144           1           1         192
           0           0           1           1           1           2
           1         300
 'UNITS   '          32 'CHAR'
```

**Comment by GitPaean** [comment]
I made more runs with the same master branch. There are some values always different. 

```
 'NUMS    '          32 'INTE'
      -32676           1           1          -1          -1          -1
          -1          -1          -1          -1           0    62737632
    62738096           6    62739024    62739488           0         170
          -1           0         144           1           1         192
           0           0           1           1           1           2
           1         300

```

**Comment by GitPaean** [comment]
So, even with the same code and same build, we have several big values always change for each different running.  Maybe there are some memory leaking there?

**Comment by bska** [comment]
> Maybe there are some memory leaking there?

Or dereferencing unassigned pointers or printing uninitialised memory or...

**Comment by bska** [comment]
Can you share the `KEYWORDS` and `WGNAMES` arrays too?

**Comment by joakim-hove** [comment]
Again - have not looked, but the use of the  NUMS array is context dependent, and many of the elements are unused.

My hunch is that some unused values have unitiialized values, if that is the case it does not really harm - but should of course be fixed. I will look into that possibility.

**Comment by GitPaean** [comment]
> Can you share the KEYWORDS and WGNAMES arrays too?

updated above.

**Comment by GitPaean** [comment]
The difference between the four bigger values are all
```
  464   928   464
```
Maybe we use the memory address as values?

**Comment by joakim-hove** [comment]
The offending values are related to well variable, so although not nice the randomness is not really harming.

Anyway - will look into it.

**Comment by bska** [comment]
> Maybe we use the memory address as values?

Probably not.  It's (much) more likely that we're simply printing `SummaryNode::num()` and that the underlying structure doesn't have any assigned value.  As Joakim says, this makes no difference to postprocessors but as long as we're using `NUMS` to check if two results sets differ then we need to make sure that those values are actually well defined.

**Comment by joakim-hove** [comment]
We are not actually checking NUMS - it is not before we explicitly invoke an update_data command this makes a difference. The tests do not look on muns

**Comment by bska** [comment]
> The tests do not look on muns

Then we might as well not include SMSPEC files in the `update_data` result set.

**Comment by GitPaean** [comment]
jenkins build this please

**Comment by GitPaean** [comment]
jenkins build this update_data please

**Comment by atgeirr** [comment]
Since this (or rather, the opm-data PR) will make less noise with update_data, it should be good to merge.

**Pull request merged**
