### PR TITLE
Add support for maximum total gas (alq + gas rate) in GLIFTOPT

### PR DESCRIPTION
**Pull request by totto82**
Dont increase gaslift if the groups alq + gas production rate is above the given target (GLIFTOPT item 3)

We also need to add the logic where we decrease gaslift if the groups alq + gas production rate is above target. That will be a later PR.

### CODE REVIEW

**Comment by totto82** [comment]
jenkins build this please

**Comment by totto82** [comment]
Now also the reduction part is added to the PR

**Comment by totto82** [comment]
jenkins build this please

**Comment by totto82** [comment]
jenkins build this please

**Review by bska — APPROVED** [review]
This looks good to me.  I'll merge into master.

**Pull request merged**
