### PR TITLE
Fixes unsused parameter warnings for ebos stuff

### PR DESCRIPTION
**Pull request by blattms**

### CODE REVIEW

**Comment by atgeirr** [comment]
Two questions perhaps mostly perhaps for @andlaus:
 - Here DUNE_UNUSED_PARAMETER has been used, I think we have an OPM_UNUSED that you made, why should we (or not) prefer one to the other? (In general we should be consistent if we use a macro for this.)
 - I see the rock compressibility object is not used. Is that handled in a different way in ewoms? I assume it *is* handled, otherwise we would not get matching results on Norne etc.

**Comment by blattms** [comment]
Concerning OPM_UNUSED: 
1. I get *a lot* of warnings in ebos even thought it is used there at exactly these places. 
2. It might be a matter of choice, but I prefer DUNE_UNUSED_PARAMETER as it seems more portable.
3. I do not expect to find such a macro in opm-material.

**Comment by totto82** [comment]
`

> I see the rock compressibility object is not used. Is that handled in a different way in ewoms? I assume it is handled, otherwise we would not get matching results on Norne etc.

Yes, this is handled in ewoms. The reason for many of the unused variables is that they have been kept for easy comparison. The fluid object and geo-props and probably some other input parameters should also be removed and replaced by similar calls to ebos. Currently a lot of the parameters are initialized twice once for ebos and once for flow. 
`

**Comment by andlaus** [comment]
> I think we have an OPM_UNUSED that you made, why should we (or not) prefer one to the other? (In general we should be consistent if we use a macro for this.)

generally, they are equivalent. the reason for the OPM version historically was that Dune has not been a hard dependency for opm-core up until about a year ago. Also, IIRC only the OPM version have `OPM_DEBUG_UNUSED` and `OPM_OPTIM_UNUSED` which only mark some variable as unused if debugging or optimization flags are used. (these can be also implemented in terms of DUNE_UNUSED_PARAMETER, though.)

Finally, OPM_UNUSED is shorter than DUNE_UNUSED_PARAMETER while expressing the same information? (though what you prefer is basically a matter of taste, IMO.)

for the rest of your questions @totto82's answer recaps the situation nicely, IMO.

@blattms:

> It might be a matter of choice, but I prefer DUNE_UNUSED_PARAMETER as it seems more portable.

that's only true for code that uses Dune but not OPM. IIRC they even use the same CMake test and the same HAVE_* macro..

**Comment by andlaus** [comment]
> I do not expect to find such a macro in opm-material.

as so often: historic reasons. it should be moved to opm-common soon. (or deleted if there is some consensus in that regard.)

**Comment by andlaus** [comment]
ok, I had a closer look at the dune stuff: DUNE_UNUSED and OPM_UNUSED are equivalent, DUNE_UNUSED_PARAMETER is less generic (i.e., it can only be used in situations where static casts are allowed) but requires no buildsystem support. to sum this up: if you're using a compiler that supports ´__attribute__((unused))` (e.g., clang or GCC, likely also ICC), but OPM_UNUSED still does not work as advertised, then you probably see a build system bug or config.h is not included in that particular compile unit.

**Comment by atgeirr** [comment]
I prefer to have the OPM... macros used in the OPM modules (although I often avoid the issue entirely by commenting out the variable name etc. instead). The exception would be opm-grid's dune-grid-interface-following grid classes (CpGrid, PolyhedralGrid), since they already are very much Dune things.

So @blattms would you mind modifying to use those macros (or no macros, that will always be fine with me...)?

And @andlaus we should move that macro header to opm-common. Could you please make a PR for that? We should then merge it (and its followups) quickly to minimize disruption.

**Comment by blattms** [comment]
> So @blattms would you mind modifying to use those macros (or no macros, that will always be fine with me...)?

Yes I do mind, because these do not seem to work on my
system. Somebody else needs to this.

```
In file included from /home/mblatt/src/dune/opm/ewoms/ewoms/disc/ecfv/ecfvdiscretization.hh:39:0,
                 from /home/mblatt/src/dune/opm/ewoms/ebos/eclwriter.hh:36,
                 from /home/mblatt/src/dune/opm/ewoms/ebos/eclproblem.hh:53,
                 from /home/mblatt/src/dune/opm/opm-simulator/opm/autodiff/BlackoilModelEbos.hpp:27,
                 from /home/mblatt/src/dune/opm/opm-simulator/opm/autodiff/SimulatorFullyImplicitBlackoilEbos.hpp:28,
                 from /home/mblatt/src/dune/opm/opm-simulator/examples/flow_ebos.cpp:30:
/home/mblatt/src/dune/opm/ewoms/ewoms/disc/common/fvbasediscretization.hh: In instantiation of ‘void Ewoms::FvBaseDiscretization<TypeTag>::prefetch(const Element&) const [with TypeTag = Ewoms::Properties::TTag::EclFlowProblem; Ewoms::FvBaseDiscretization<TypeTag>::Element = Dune::cpgrid::Entity<0>]’:
/home/mblatt/src/dune/opm/ewoms/ewoms/disc/common/fvbaselinearizer.hh:402:25:   required from ‘void Ewoms::FvBaseLinearizer<TypeTag>::linearize_() [with TypeTag = Ewoms::Properties::TTag::EclFlowProblem]’
/home/mblatt/src/dune/opm/ewoms/ewoms/disc/common/fvbaselinearizer.hh:179:24:   required from ‘void Ewoms::FvBaseLinearizer<TypeTag>::linearize() [with TypeTag = Ewoms::Properties::TTag::EclFlowProblem]’
/home/mblatt/src/dune/opm/opm-simulator/opm/autodiff/BlackoilModelEbos.hpp:1431:59:   required from here
/home/mblatt/src/dune/opm/ewoms/ewoms/disc/common/fvbasediscretization.hh:567:45: warning: unused parameter ‘elem’ [-Wunused-parameter]
     void prefetch(const Element& OPM_UNUSED elem) const
                                             ^
```

**Comment by andlaus** [comment]
> although I often avoid the issue entirely by commenting out the variable name etc. instead.

I'd actually prefer that method as well, but it comes with the problem that the parameters become undocumentable with doxygen...

@blattms 
> Yes I do mind, because these do not seem to work on my system.

does your config.h for opm-simulators feature `#define HAS_ATTRIBUTE_UNUSED 1`? (and is some `-DHAVE_CONFIG_H` flag passed to the compiler?)

**Comment by blattms** [comment]
yes and yes:
```
mblatt@boromir:~/src/dune/opm/opm-simulator/opm-parallel-dbg$ grep
HAS_ATTRIBUTE_UNUSED config.h
#define HAS_ATTRIBUTE_UNUSED 1
mblatt@boromir:~/src/dune/opm/opm-simulator/opm-parallel-dbg$ grep
HAVE_CONFIG_H CMakeFiles/flow_ebos.dir/*.cmake
CMakeFiles/flow_ebos.dir/DependInfo.cmake:  "HAVE_CONFIG_H=1"
```

**Comment by andlaus** [comment]
> yes and yes:

if you add a `#warning` before `Unused.hpp:36` is it printed by the compiler?

**Comment by blattms** [comment]
Sorry, but I have already invested much more time into this than I ever expected. I will simply stop caring about warnings in ewoms.

**Comment by andlaus** [comment]
checking if the code sees the `HAS_ATTRIBUTE_UNUSED` macro should not take too much of your time, though? As so often, I suspect that the build system stumbled over some corner case.

**Comment by atgeirr** [comment]
Well, I'll merge this in any case, and when the macro move has been merged we can change which macro we use. If they *don't work* (looks like it?) that is cause for concern!

**Pull request merged**
