### PR TITLE
More tests

### PR DESCRIPTION
**Pull request by akva2**
Fix some holes in the test suite
- regression test for onephase_energy
- parallel test for onephase

### CODE REVIEW

**Comment by akva2** [comment]
jenkins build this update_data please

**Comment by akva2** [comment]
jenkins build this update_data please

**Comment by akva2** [comment]
jenkins build this opm-tests=546 please

**Comment by bska** [comment]
New reference solutions have been merged.  Merging this now to bring overall system back to a consistent state.

**Pull request merged**
