### PR TITLE
enable spe1 and spe9 parallel tests for flow_ebos

### PR DESCRIPTION
**Pull request by akva2**
the spe3 test will not pass, most likely due to all the convergence failures.

### CODE REVIEW

**Comment by akva2** [comment]
jenkins build this please

**Comment by akva2** [comment]
right jenkins happy. i'll hold until @andlaus @blattms comments on the spe3 failure.

**Comment by andlaus** [comment]
not sure what it is. I will probably not be able to debug this before 2017.04, but I propose to declare the MPI capability of flow_ebos as experimental for this release, so users should expect their MPI-mileage to vary.

**Comment by atgeirr** [comment]
Will this require Zoltan for the tests to be successful (it does not for legacy flow, so probably not)? I'll test tomorrow and merge if not.

I guess we will eventuallty reach a point where MPI and Zoltan will be required rather than optional?

**Comment by akva2** [comment]
it requires zoltan and mpi to run, precisely as it requires zoltan and mpi for legacy. if those are not enabled, these tests are not enabled. simple as that.

**Comment by andlaus** [comment]
> it requires zoltan and mpi to run

MPI yes, but why Zoltan? Up to now, I thought that Zoltan was only needed to get a good partitioning of the grid. While a sub-optimal grid partitioning leads to bad performance, it should not affect the output if there are no other bugs? (remember that the results  supposed to be identical to the sequential ones.)

**Comment by akva2** [comment]
if there is non-zoltan partition code, then we don't need zoltan i guess. it's hard to guess at these things for a third party. in any case i have made a mpi = user have some partitioning code available assumption anyways (since it could be metis, at least it could a while back and i didnt bother to complicate the logic - which turns out to be good thing then..)

**Comment by atgeirr** [comment]
I have MPI, not Zoltan on my system, but this runs nicely through. I suspect a similar Norne test might not. Merging!

(I have Zoltan on an Ubuntu VM for experimenting with the parallel stuff though.)

**Comment by blattms** [comment]
Did we also test spe3 with flow_mpi, previously?

Anyway, I will look into these issues.

**Comment by akva2** [comment]
yes, and flow_mpi still pass fine for the spe3 case.

**Comment by blattms** [comment]
@akva2 Sorry for having a brain like swiss chese. How do I run thes comparison test manually?

**Comment by akva2** [comment]
the answer depends on how manually you want to run them ;)

you can of course just execute the one ctest entry as normal, i.e.
```
ctest -R "parallelECLFiles_flow_ebos+SPE3CASE1"
```

but i assume you want more manual than that.

the command executed by the test is
```
/home/akva/kode/opm/sibling/opm-simulators/tests/run-parallel-regressionTest.sh "/home/akva/kode/opm/sibling/opm-simulators/../opm-data/spe1" "/home/akva/kode/opm/sibling/opm-simulators/build/tests/results/parallel/flow_mpi+spe1" "/home/akva/kode/opm/sibling/opm-simulators/build/bin" "SPE1CASE2" "0.02" "1e-5" "/home/akva/kode/opm/sibling/opm-output/build/bin/compareSummary" "/home/akva/kode/opm/sibling/opm-output/build/bin/compareECL" "flow_mpi" "/home/akva/kode/opm/sibling/opm-simulators/../opm-data/spe1/SPE1CASE2"
```

i assume you can grok what the paths are (and the necessary changes for the data files).

**Comment by blattms** [comment]
Nevermind, found that one out myself:

compareECL full/path/case1/without_extension full/path/case2/without_extension  abs_tol rel_tol

**Comment by blattms** [comment]
FYI on my system the picture looks quite similar for flow_mpi and flow_ebos:

ebos:
```
Comparing 'case1-ebos-1/SPE3CASE1' to 'case1-ebos-2/SPE3CASE1'.
Comparing SEQNUM...done.
Comparing INTEHEAD...done.
Comparing LOGIHEAD...done.
Comparing DOUBHEAD...done.
Deviation results for keyword DOUBHEAD of type DOUB:
Average absolute deviation = 0
Median absolute deviation  = 0
Average relative deviation = 0
Median relative deviation  = 0

Comparing IWEL...done.
Comparing ZWEL...done.
Comparing OPM_XWEL...
Occurrence in first file    = 0
Occurrence in second file   = 0
Grid coordinate             = (1, 1, 1)
(first value, second value) = (2.2734e+07, 2.27343e+07)

Program threw an exception: [/home/mblatt/src/dune/opm/opm-output/opm/test_util/EclFilesComparator.cpp:370] Deviations exceed tolerances.
The absolute deviation is 253.745, and the tolerance limit is 0.02.
The relative deviation is 1.11613e-05, and the tolerance limit is 1e-05.
```

flow_mpi:
```
Comparing 'case1-legacy-1/SPE3CASE1' to 'case1-legacy-2/SPE3CASE1'.
Comparing SEQNUM...done.
Comparing INTEHEAD...done.
Comparing LOGIHEAD...done.
Comparing DOUBHEAD...done.
Deviation results for keyword DOUBHEAD of type DOUB:
Average absolute deviation = 0
Median absolute deviation  = 0
Average relative deviation = 0
Median relative deviation  = 0

Comparing IWEL...done.
Comparing ZWEL...done.
Comparing OPM_XWEL...
Occurrence in first file    = 0
Occurrence in second file   = 0
Grid coordinate             = (1, 1, 1)
(first value, second value) = (2.27341e+07, 2.27334e+07)

Program threw an exception: [/home/mblatt/src/dune/opm/opm-output/opm/test_util/EclFilesComparator.cpp:370] Deviations exceed tolerances.
The absolute deviation is 625.507, and the tolerance limit is 0.02.
The relative deviation is 2.75141e-05, and the tolerance limit is 1e-05.
```

**Comment by akva2** [comment]
interesting. it passes on jenkins and my box but that could be a good cluestick i guess.

**Comment by andlaus** [comment]
to me it seems like this is the usual discrepancy due to compiler, build flags, libraries, hardware, etc.. is it possible to increase the tolerances for the MPI tests but leave them as they are for the sequential ones?

**Comment by akva2** [comment]
yes, however the failures on my machine is way more severe than what is given above, they are 10^2 times the discrepancies for mpi in relative so i didn't really consider that avenue.

```
6: === Executing comparison for summary file ===
36: Comparing '/home/akva/kode/opm/sibling/opm-simulators/build/tests/results/parallel/flow_ebos+spe3/SPE3CASE1' to '/home/akva/kode/opm/sibling/opm-simulators/build/tests/results/parallel/flow_ebos+spe3/mpi/SPE3CASE1'.
36: Comparing 177 steps.
36: For keyword FOPR
36: (days, reference value) and (days, check value) = (104.286, 1035.72) and (156.429, 1034.32)
36: The absolute deviation is 1.40039. The tolerance limit is 0.02
36: The relative deviation is 0.00135209. The tolerance limit is 1e-05
36: Program threw an exception: [/home/akva/kode/opm/sibling/opm-output/opm/test_util/summaryRegressionTest.cpp:117] Deviation exceed the limit.
```

i cannot trigger markus errors on my box but that ^ is definitely above what you'd expect from round-off.

**Comment by blattms** [comment]
I can reproduce the problems and agree with @akva2 that this might be
something more serious.

BTW: My previous observations with differences for flow_mpi were for
runs with 2 processes (while jenkins uses 4).

**Comment by akva2** [comment]
Right that makes sense the tols are as tight as 4 allowed not randomly chosen :)



Sendt fra min Samsung-enhet


-------- Opprinnelig melding --------
Fra: Markus Blatt <notifications@github.com>
Dato: 19.04.2017 16:53 (GMT+01:00)
Til: OPM/opm-simulators <opm-simulators@noreply.github.com>
Ko: Arne Morten Kvarving <Arne.Morten.Kvarving@sintef.no>, Mention <mention@noreply.github.com>
Emne: Re: [OPM/opm-simulators] enable spe1 and spe9 parallel tests for flow_ebos (#1150)

I can reproduce the problems and agree with @akva2 that this might be
something more serious.

BTW: My previous observations with differences for flow_mpi were for
runs with 2 processes (while jenkins uses 4).

**Comment by andlaus** [comment]
I appreciate it if you have a closer look @blattms, but personally I'm not very worried about a difference of about 1.5 (bbl/day?) in the field oil total production rate after 104 days if the total is 1035.72. this might be due to discrepancies in the linear solver.

what I'm more worried about, though: why is the time in one run 104.286 days while it is 156.429 days for the other? was there a convergence failure in on run but not in the other? is it a bug in the comparison script?

**Comment by akva2** [comment]
yes, there is clearly a different convergence history and that cause the havoc you see in the comparison, as well as a few extra dew point convergence issues compared to the serial run later on in the run (probably caused by prior differences);

serial:
```
36: Time step    0 at day 0/5475, date = 01-Jan-2015
36:   Substep 0, stepsize 17.2071 days.
36:     Switching control mode for well PROD from SURFACE_RATE to BHP
36:     Switching control mode for well INJ from SURFACE_RATE to BHP
36:     Switching control mode for well PROD from BHP to SURFACE_RATE
36:     Switching control mode for well INJ from BHP to SURFACE_RATE
36:     Oscillating behavior detected: Relaxation set to 0.900000
36:     Switching control mode for well INJ from SURFACE_RATE to BHP
36:     Switching control mode for well INJ from BHP to SURFACE_RATE
36:     Substep summary: well its =  2, newton its = 15, linearizations = 16 ( 0.440 sec), linear its = 253 ( 1.720 sec)
36:   Substep 1, stepsize 34.9357 days.
36:     Substep summary: well its =  1, newton its =  3, linearizations =  4 ( 0.103 sec), linear its =  49 ( 0.324 sec)
```

vs parallell

```
36: Time step    0 at day 0/5475, date = 01-Jan-2015
36:   Substep 0, stepsize 17.2071 days.
36:     Switching control mode for well PROD from SURFACE_RATE to BHP on rank 0
36:     Switching control mode for well INJ from SURFACE_RATE to BHP on rank 3
36:     Switching control mode for well PROD from BHP to SURFACE_RATE on rank 0
36:     Switching control mode for well INJ from BHP to SURFACE_RATE on rank 3
 36:     Oscillating behavior detected: Relaxation set to 0.900000
36:     Switching control mode for well INJ from SURFACE_RATE to BHP on rank 3
36:     Switching control mode for well INJ from BHP to SURFACE_RATE on rank 3
 36:     Switching control mode for well INJ from SURFACE_RATE to BHP on rank 3
36:     Switching control mode for well INJ from BHP to SURFACE_RATE on rank 3
 36: Problem: Failed to complete a time step within 15 iterations.
36: Problem: Solver convergence failed, cutting timestep to 5.678357 days.
36: 
36:   Substep 0, stepsize 5.67836 days.
36:     Switching control mode for well INJ from SURFACE_RATE to BHP on rank 3
 36:     Switching control mode for well INJ from BHP to SURFACE_RATE on rank 3
36:     Substep summary: well its =  2, newton its =  7, linearizations =  8 (10.384 sec), linear its = 156 (37.473 sec)
36:   Substep 1, stepsize 11.3567 days.
36:     Substep summary: well its =  1, newton its =  3, linearizations =  4 ( 5.581 sec), linear its =  55 (13.420 sec)
36:   Substep 2, stepsize 35.1078 days.
36:     Substep summary: newton its =  3, linearizations =  4 ( 4.812 sec), linear its =  55 (11.490 sec)
```

this means different summary steps are written to the file and we end up comparing apples to oranges. 

the issue here can be as simple as the 15 required newton its in serial (is 15 the default max maybe, i didn't investigate). this was my educated guess at the cause of this. but now that i have shared it i doubt you certainly will not be investigating it any closer than you did without the information ;)

**Comment by atgeirr** [comment]
Comparing different time points (due to different numbers of steps taken) makes no sense for an acceptance test, while for regression testing it certainly shows something has changed etc. The tests in question however are acceptance tests, and therefore they should not care about the timestep history taking us from A to B (although performance could be impacted).

A slightly different tack needs to be taken for acceptance tests: instead of comparing at every timestep, we must compare only at report steps. Libecl has tools to make this relatively easy (the view mechanism that can give you a view to only data associated with a certain timestep), but it would require some rewriting to move away from the current occurrence-based (i.e. compare the ii-th occurrence of a keyword in the two files) approach. Perhaps an easier path can be to compare timesteps that exist in both files, ignoring those that are only in one of them (rather than flagging that as an error) although that runs the risk of comparing two unrelated cases and getting the answer that they are equivalent...

**Comment by joakim-hove** [comment]
Not weighing in an opinion on the actual question, but:

1. The summary loader has functionality to look up results only at report steps out of the box.

2. For *rates* of various kinds the acceptance  comparison becomes tricky anyway when timesteps are not identical

**Comment by andlaus** [comment]
@atgeirr: I suspect the reason for this is that the linear solver uses a slightly different number of iterations in the parallel case than for the sequential one. this implies slightly different substep sizes because -- as I currently understand it -- the adaptive time stepper looks at the number of linear iterations and thus comparing the results of a parallel run with those of a sequential one is bound to fail!?

@joakim-hove: aren't the summary results written are updated after each substep? anyway, even if this is not the case, if the substeps differ, the results should differ slightly at the report times as well.

**Comment by totto82** [comment]
Just for information. 
In the current default setting. (timestep.control = pid) The adaptive time stepper does not use linear iteration (nor non-linear iterations) for adjusting the time step.

**Comment by akva2** [comment]
i've been playing with tolerances. i can get every field below the threshold (relative 1e-5), with one exception

```
36: 1 summary keyword(s) exhibit failures
36:      WBHP:INJ
36:              Fails for: 26 / 177 steps.
36:              Largest absolute error: 2.253420e+00
36:              Largest relative error: 1.284570e-03
```

everything else pass. but i cannot get this one under control. still looking into more details, but i've started to be convinced this is just a very sensitive case issue.

**Comment by blattms** [comment]
Copying from #1154:
For our case the deviation in time stepping starts at timestep 115, substep 11. The parallel version does not converge here while the sequential one does. Hence the time step gets smaller in the parallel case.

**Comment by blattms** [comment]
I need to add: That was for my patched version where I use a sequential direct solver even for the parallel case. (Where a deviation should never happen...)

But I am sure that for the iterative solver my explanation holds.

**Comment by atgeirr** [comment]
> That was for my patched version where I use a sequential direct solver even for the parallel case. (Where a deviation should never happen...)

That is odd! To be 100% sure: the parallel simulator does not converge for that step due to exceeding 15 nonlinear iterations, even when using a sequential direct solver, and the sequential simulator succeeds with the same sequential direct solver?

**Comment by blattms** [comment]
Yes. And it is a bit weired, I agree. I see deviations in the residuals. they start to appear in the well flux residuals during the nonlinear solves. Often they disappear for later steps again. Eventually they do not and the deviations carry over to the mass residuals, too.

**Comment by alfbr** [comment]
> A slightly different tack needs to be taken for acceptance tests: instead of comparing at every timestep, we must compare only at report steps.

Report steps are often few and far between. More importantly, ministeps typically occur exactly when we have numerical problems, i.e., at time values where we probably really do want to have checks in place. Hence, neglecting that data completely for acceptance tests is not something we should do light-heartedly.

**Pull request merged**
