### PR TITLE
Rockcomp

### PR DESCRIPTION
**Pull request by totto82**
This replaces #1756

### CODE REVIEW

**Comment by totto82** [comment]
jenkins build this ewoms=504 please

**Comment by andlaus** [comment]
I'm happy with this one. Since `flow` should be unaffected by this, I'll merge it tomorrow if there are no objections.

**Comment by andlaus** [comment]
jenkins build this please

**Comment by andlaus** [comment]
okay, as far as I can see this basically boils down to the "forever hold your peace" part. merging.

**Pull request merged**
