### PR TITLE
Remove more state

### PR DESCRIPTION
**Pull request by andlaus**
this PR mainly removes reservoir and well state objects from the API of non-legacy flow. So far, the API has been kept for compatibility reasons with `flow_legacy` and dummy objects were passed by `flow`. the only exception was the well state object which is used for restarts. The code which sets this object up is moved to the place where it belongs, i.e. the well model. (the well_state is an implementation detail of the well model and it should not spill.)

Besides this, the output writer code has been removed because all that was left of the opm-simulators class since the ECL output code moved to core ebos was a shallow layer for API compatibility.

### CODE REVIEW

**Comment by andlaus** [comment]
jenkins build this please

**Comment by totto82** [comment]
Thanks for the clean-up. Did you do any changes to the code except the clean-up of the legacy stuff? ie.e are the new *Ebos* files essential copies of the old ones?

**Comment by andlaus** [comment]
> ie.e are the new Ebos files essential copies of the old ones?

yes, that's the reason why this patch adds net lines of code: the `NonlinearSolver` and `AdaptiveTimestepping` classes are very closely tied to the API of `flow_legacy`, so I forked them to `NonlinearSolverEbos`. (the code is currently identical except for the state removal.) Also, the init routines of the well model needed to be separated.

**Comment by totto82** [comment]
Great. That was my guess from reading through it. I think this can be merged, I will wait until Friday to give @GitPaean or @atgeirr time to comment.

**Comment by atgeirr** [comment]
I had a look, but it is hard to tell if there is new stuff here. Are all moved/copied parts, in particular the init code for wells, also unchanged? I got that impression, but just asking to be sure.

If so, then we could expect bitwise identical results as without this PR. Is that the case?

**Comment by andlaus** [comment]
There are no intentional changes, but because the restart stuff is really opaque to me and the current master has a few pretty severe abstraction violations, mistakes are possible.

> If so, then we could expect bitwise identical results as without this PR. Is that the case?

I would not expect bitwise identical results because *anything* can change a few bits, even adding a print statement to an unused function. That said, all unit tests pass and the restarted  SPE9 case works (as far as I can tell even in parallel).

**Comment by bska** [comment]
This PR adds two new files

  * `opm/autodiff/NonlinearSolverEbos.hpp`

  * `opm/simulators/timestepping/AdaptiveTimeSteppingEbos.hpp`

but doesn't mention either in `CMakeLists_files.cmake`.  That's going to break `make install`.

**Comment by atgeirr** [comment]
> This PR adds two new files
> 
> opm/autodiff/NonlinearSolverEbos.hpp
> 
> opm/simulators/timestepping/AdaptiveTimeSteppingEbos.hpp
> 
> but doesn't mention either in CMakeLists_files.cmake. That's going to break make install.

Oops! My fault for merging, will push PR.

**Pull request merged**
