### PR TITLE
Fix SOIL restart initialization

### PR DESCRIPTION
**Pull request by totto82**

### CODE REVIEW

**Comment by atgeirr** [comment]
Looks like this was forgotten when we moved Compat.hpp. Thanks for catching!

**Comment by akva2** [comment]
test coverage please.

**Comment by atgeirr** [comment]
@akva2 not sure what you want? This is exercised by the existing restart tests, right? (And according to Travis, they seem ok:
```
      Start 21: compareECLRestartFiles_flow+SPE1CASE2_ACTNUM
21/23 Test #21: compareECLRestartFiles_flow+SPE1CASE2_ACTNUM ...   Passed    0.82 sec
      Start 22: compareECLRestartFiles_flow+SPE9_CP_SHORT
22/23 Test #22: compareECLRestartFiles_flow+SPE9_CP_SHORT ......   Passed   17.39 sec
```

**Comment by akva2** [comment]
since no tests detected the regression we do not have a restart test needing SOIL initialization.

**Comment by atgeirr** [comment]
OK, so you want a test that would fail without this PR? Not sure how simple that is, since it only affects certain initial values (during simulation we use so = 1 - sw - sg) it might require a longer run of a complex case to discern, such as "Model 2", and we cannot put that model into these tests in any case.

I could be wrong, and all we need to do to provoke this is to reduce some tolerance. I could try that, can you point me to where I should modify?

**Comment by akva2** [comment]
wouldn't any 3 phase model do? SOIL is oil saturation right? without this, a restart would have random SOIL and consequently the results would differ significantly from the non-restarted run, with this it would get the appropriate data? or i am missing something.

**Comment by atgeirr** [comment]
The oil saturation would only be random during parts of the initialization phase, probably causing slight errors in initial values of well quantities etc. Since it is never a primary variable it is always set to the correct value after every nonlinear update, so the effect would be slight.

**Comment by akva2** [comment]
ah, i get it. only way to tell would be to construct some test i guess. i agree if we have to fiddle too much with tolerances it would indeed be rather synthetic.

**Comment by atgeirr** [comment]
So should we play the "game of tolerances" (if so: please point me to the right place) or just merge this?

**Comment by akva2** [comment]
merge.

**Pull request merged**
