### PR TITLE
Feature/ms wells wip

### PR DESCRIPTION
**Pull request by lisajulia**

### CODE REVIEW

**Comment by lisajulia** [comment]
jenkins build this failure_report please

**Comment by GitPaean** [comment]
jenkins build this failure_report please

**Comment by GitPaean** [comment]
jenkins build this failure_report please

**Comment by GitPaean** [comment]
not sure why yours jenkins request did not get triggered twice.

**Comment by lisajulia** [comment]
10 failing tests now

**Comment by GitPaean** [comment]
Yeah. It means some easier case are okay. 

[mpi.wellstate](https://ci.opm-project.org/job/opm-simulators-PR-builder/6800/testReport/junit/(root)/mpi/wellstate/) this one shows some direct error message. 

other regression looks like involving group controls except [mpi.compareECLFiles_flow+BASE_MSW_WSEGVALV](https://ci.opm-project.org/job/opm-simulators-PR-builder/6800/testReport/junit/(root)/mpi/compareECLFiles_flow_BASE_MSW_WSEGVALV/)

**Comment by lisajulia** [comment]
jenkins build this please

**Comment by lisajulia** [comment]
jenkins build this please

**Comment by lisajulia** [comment]
jenkins build this please

**Comment by lisajulia** [comment]
jenkins build this please

**Comment by lisajulia** [comment]
Resolved 3 of the 9 failing tests, the remaining 6 are: 

The program runs through, but the results are actually different:
-     mpi.compareECLFiles_flow+0A3_GRCTRL_LRAT_LRAT_BASE_MODEL2_MSW
-     mpi.compareECLFiles_flow+BASE_MSW_WSEGVALV
-     compareECLFiles_flow+9_3E_GAS_MIN_EXPORT_MSW

There is a problem with the perf index in getMobility right before
"Production Group RES control mode changed from ORAT to GRAT":
-     mpi.compareECLFiles_flow+9_3D_GINJ_GAS_MAX_EXPORT_MSW

There is a problem with the perf index in getMobility right before:
"Well PROD3 control mode changed from GRUP to THP":
-     mpi.compareECLFiles_flow+9_4C_WINJ_GINJ_VREP-W_REIN-G_MSW
-     mpi.compareECLFiles_flow+9_4D_WINJ_GINJ_GAS_EXPORT_MSW

**Comment by lisajulia** [comment]
Created #5680, this PR here is based on 5680, with the additional output of the global matrices B and C for comparision purposes.

**Comment by lisajulia** [comment]
jenkins build this please

**Comment by lisajulia** [comment]
Failing here:
Both changes: 
- mpi.compareECLFiles_flow+0A3_GRCTRL_LRAT_LRAT_BASE_MODEL2_MSW
- mpi.compareECLFiles_flow+9_3D_GINJ_GAS_MAX_EXPORT_MSW
- mpi.compareECLFiles_flow+9_3E_GAS_MIN_EXPORT_MSW
- mpi.compareECLFiles_flow+9_4C_WINJ_GINJ_VREP-W_REIN-G_MSW
- mpi.compareECLFiles_flow+9_4D_WINJ_GINJ_GAS_EXPORT_MSW

Sum communication:
- mpi.compareECLFiles_flow+9_2B_DEPL_GCONPROD_2L_MSW
- mpi.compareECLFiles_flow+9_4A_WINJ_MAXWRATES_MAXBHP_GCONPROD_1L_MSW
- mpi.compareECLFiles_flow+9_4B_WINJ_VREP-W_MSW

Multiplication with B:
- mpi.compareECLFiles_flow+BASE_MSW_WSEGVALV

**Comment by lisajulia** [comment]
Closing this now, since #5746 and #5680 have been merged.

**Pull request closed without merging**
