### PR TITLE
PARAOPTS and SOLVDIRS should only give warning

### PR DESCRIPTION
**Pull request by alfbr**
The keywords do not change the results (unless there is numerical issues), so Flow should not treat them as critical.

### CODE REVIEW

**Comment by alfbr** [comment]
jenkins build this please

**Review by bska — APPROVED** [review]
Yes, this makes sense to me.  Thanks a lot for the contribution.  I'll merge into master.

**Comment by atgeirr** [comment]
Thanks, indeed these options are irrelevant for OPM Flow. One could argue that a few of the PARAOPTS options could be interpreted, but it is better to ignore the keyword in my opinion.

Merging!

**Comment by atgeirr** [comment]
Already merged I see... At least that makes two of us who agree!

**Pull request merged**
