### PR TITLE
[FlexibleSolver] Added missing headers determine IsComm.

### PR DESCRIPTION
**Pull request by blattms**
Seems needed for some compilers

### CODE REVIEW

**Comment by blattms** [comment]
Is "not seeing the diff/commits when creating a PR" a new github feature?

**Comment by blattms** [comment]
Not finished yet as the problem is for sequential builds.

**Comment by blattms** [comment]
Amended and checked for a local sequential build. Does that fix your problem @bska

**Comment by blattms** [comment]
jenkins build this serial parallel please

**Comment by bska** [comment]
> Does this fix your problem @bska?

Yes it does.  Thank you so much for the quick turn-around.  I'll merge this as soon as the current build check comes back green.

**Comment by bska** [comment]
> I'll merge this as soon as the current build check comes back green.

It's green.  I'm merging into master now.  Thanks a lot for the quick fix!

**Pull request merged**
