### PR TITLE
use stricter tolerances for WINJMULT_MSW/WINJDAM_MSW parallel tests

### PR DESCRIPTION
**Pull request by akva2**
so we can use standard rel_tol tolerances and not the very relaxed values currently in use

### CODE REVIEW

**Comment by akva2** [comment]
jenkins build this please

**Comment by GitPaean** [comment]
It is good to be able to use ` standard rel_tol tolerances`.  Have you tried whether CPR linear solvers can help these cases?  (was inspired by https://github.com/OPM/opm-tests/pull/1092)

**Comment by akva2** [comment]
not really and that would be a bit tangential to my current goal. we need to stabilize the tests (in particular WINJDAM_MSW) as they caused headache in https://github.com/OPM/opm-common/pull/3763

**Comment by bska** [comment]
Closing this now as an equivalent change was merged as part of #4989.

**Pull request closed without merging**
