### PR TITLE
start regression testing for krnum cases

### PR DESCRIPTION
**Pull request by tskille**

### CODE REVIEW

**Comment by alfbr** [comment]
jenkins build this please

**Comment by bska** [comment]
Have you verified that the simulation results here agree with some other reference to a satisfactory degree?  If so, I think we should generate Flow's reference solutions and get these into the regression test suite.

**Comment by tskille** [comment]
Yes this has been verified. The results have been compared with a commercial simulator.

**Comment by bska** [comment]
>> Have you verified that the simulation results here agree with some other reference to a satisfactory degree?
>
> Yes this has been verified. The results have been compared with a commercial simulator.

Understood.  Thanks a lot for the confirmation.  In that case I'll generate reference solutions for these models and put them into the regression test suite.

**Comment by bska** [comment]
Sorry, I hit the wrong button...

**Comment by akva2** [comment]
jenkins build this update_data please

**Comment by akva2** [comment]
jenkins build this opm-tests=836 please

**Comment by bska** [comment]
The reference solutions have been installed on the CI system.  I'm merging this now to bring the new cases into the test suite.

**Pull request merged**
