### PR TITLE
Upgrade pybind11

### PR DESCRIPTION
**Pull request by joakim-hove**
Fix: https://github.com/OPM/opm-common/issues/2350

### CODE REVIEW

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by blattms** [comment]
We need to be very careful with this and test it on all supported systems. Especially the different supported CMake versions might be troublesome.

There is a (IMHO rather high) maintenance cost for embedded sources.

The clean way of solving #2350 would be to support the pybind11 on the system and prefer that.

**Comment by joakim-hove** [comment]
> There is a (IMHO rather high) maintenance cost for embedded sources.

I agree

> The clean way of solving #2350 would be to support the pybind11 on the system and prefer that.

I have no strong feeling on this - whatever works.

**Comment by blattms** [comment]
Stale and superseded by #5644

**Pull request closed without merging**
