### PR TITLE
New defaults

### PR DESCRIPTION
**Pull request by lisajulia**

### CODE REVIEW

**Comment by atgeirr** [comment]
Looks like your fix addressed the actionx_compdat tests but not the actionx_compdat_nldd test. Will you investigate that one as well? Especially as you are adding a parallel version of that test in #5510.

**Comment by lisajulia** [comment]
> Looks like your fix addressed the actionx_compdat tests but not the actionx_compdat_nldd test. Will you investigate that one as well? Especially as you are adding a parallel version of that test in #5510.

Yes, I plan to :).
Also I just saw that I should have started jenkins as "jenkins build this opm-tests=5157 please"...

**Comment by lisajulia** [comment]
jenkins build this opm-tests=5157 please

**Comment by lisajulia** [comment]
jenkins build this opm-tests=1205 please

**Pull request closed without merging**
