### PR TITLE
dont scale d factor from wdfaccor with connection factor

### PR DESCRIPTION
**Pull request by totto82**
The d factor is already scaled by the rate for WDFACCOR. 

Depends on https://github.com/OPM/opm-common/pull/3781

### CODE REVIEW

**Comment by totto82** [comment]
jenkins build this please

**Comment by bska** [comment]
jenkins build this please

**Review by bska — APPROVED** [review]
Thanks.  This is a substantially improved API.  I'll merge once the build check goes through.

**Review by bska — APPROVED** [review]
This is a great improvement in the interface.  Thanks a lot!

**Pull request merged**
