### PR TITLE
Add output of FLOWS- and FLORES-

### PR DESCRIPTION
**Pull request by totto82**
Depends on https://github.com/OPM/opm-common/pull/3823 and https://github.com/OPM/opm-models/pull/854

### CODE REVIEW

**Review by bska — DISMISSED** [review]
Regardless of the merits of the rest of this PR, there is no way we're going to use the magic indices 0..5 in these statements.  Find a better way.

**Comment by totto82** [comment]
@bska I have updated the PR following you comment.

**Comment by totto82** [comment]
jenkins build this please

**Comment by totto82** [comment]
I will self-merge this later today if no further comments. It should have been merged together with the Prs in opm-common opm-models.

**Comment by atgeirr** [comment]
Will take a look and merge if ok before end of the day.

**Pull request merged**
