### PR TITLE
Use FIP, EGRID and INIT output code in ebos. 

### PR DESCRIPTION
**Pull request by totto82**
This PR makse #1384 redundant. 

1) Remove unused output code
2) Pass output_dir and double_si_restart parameters to ebos 

Depends on OPM/ewoms#278, OPM/opm-grid#302, OPM/opm-output#235

Test failure is expected and new reference data is needed before this is merged.

### CODE REVIEW

**Comment by totto82** [comment]
jenkins build this opm-output=235 ewoms=275 opm-grid=302 please

**Comment by totto82** [comment]
jenkins build this opm-output=235 ewoms=278 opm-grid=302 please

**Comment by totto82** [comment]
Comments on the test failures: 

The failures are caused by either
1) hysteresis and rs/rv etc. is only outputted if enabled in the new code.  
2) block and region output is removed from opm-output and only reimplemented for flow (not legacy) 
*) I will have to investigate the FIP failures for these cases a bit more. Update follows..... 

- [1] -    mpi.compareECLFiles_flow+SPE1CASE2
- [2] -    mpi.compareECLFiles_flow_legacy+SPE1CASE2
- [1] -    mpi.compareECLFiles_flow+SPE1CASE2_2P
- [2] -    mpi.compareECLFiles_flow_legacy+SPE1CASE2_2P
- [1] -    mpi.compareECLFiles_flow+SPE1CASE2_OILGAS
- [2] -    mpi.compareECLFiles_flow_sequential+SPE1CASE1
- [1] -    mpi.compareECLFiles_flow+SPE3CASE1
- [1] -    mpi.compareECLFiles_flow+SPE9_CP_SHORT
- [2] -    mpi.compareECLFiles_flow_legacy+SPE9_CP_SHORT
- [1] -    mpi.compareECLFiles_flow+SPE9_CP_GROUP
- [*] -    mpi.compareECLFiles_flow+2D_H__
- [*] -    mpi.compareECLFiles_flow+3D_MSW
- [*] -    mpi.compareECLFiles_flow+2D_THREEPHASE_POLY_HETER
- [1] -    mpi.compareECLFiles_flow+SPE5CASE1

**Comment by joakim-hove** [comment]
> block and region output is removed from opm-output and only reimplemented for flow (not legacy)

I guess `flow_legacy`should either be maintained and working, or removed.

**Comment by totto82** [comment]
> I guess flow_legacyshould either be maintained and working, or removed.

The death process has started, but there is still some features in the legacy code that is not implemented in the new code. For instance CPR preconditioning. It is good to have the legacy code running, while porting the remaining features, but I don't think region and block summary output is very critical for the current usage of flow_legacy.

**Comment by atgeirr** [comment]
I have reviewed some parts of this. As always it is not trivial to see that code moved from one class to another is or behaves identically, and of course there are also actual behaviour changes. Still, it looks ok to me.

Changing the regression test data for the reasons given above is ok with me. I do think that @joakim-hove made a good point about not losing existing tests when moving things to ewoms, that should be done before we are finished.

**Comment by totto82** [comment]
I have added tests for the handling of general block, region and field summary data in opm-output. The actually calculation of FIP, average pressure, block values etc is tested both in serial and in parallel in the integration tests. Could  @joakim-hove and/or @atgeirr provide me a list of what you want me to test. Then it would be easier for me to know what you actually want.

**Comment by atgeirr** [comment]
> provide me a list of what you want me to test.

I based my comment on what was said in the opm-output PR, if the concerns raised there have been taken care of I am satisified. However based on your list I think that the FIP calculations etc. should be unit tested, and are fairly easy to make a unit test for. Possible that would require making them separate functions, but that would only be good! Do you think that would be excessive work?

The integration tests are very helpful, but they are much less stable over time than unit tests would be.

@joakim-hove, anything to add?

**Comment by joakim-hove** [comment]
> The actually calculation of FIP, average pressure, block values etc is tested both in serial and in parallel in the integration tests.  

Yes - and as part of merging this PR you intend to update the reference data; which kind of illustrates my point.

As I have already said I would encourage you to port the existing tests from opm-output to ewoms; just do it instead of inventing excuses.

**Comment by totto82** [comment]
Ok. I just wanted to be sure what you want. Making tests is not trivial work you know.

**Comment by totto82** [comment]
I have added a test_ecl_output in ewoms. This should cover the main part of the removed tests from opm-output.

**Comment by totto82** [comment]
@atgeirr  Can I ask Jenkins to update_data now? Or do I need to wait until other issues are resolved?

**Comment by totto82** [comment]
I noticed that opm-output needs to be rebased after last change.

**Comment by atgeirr** [comment]
jenkins build this opm-output=235 ewoms=278 please

**Comment by atgeirr** [comment]
Rather weird test failure:
```
make[2]: *** No rule to make target '/var/lib/jenkins/workspace/opm-simulators-PR-builder/deps/ewoms/tests/data/equil_livegas.DATAq', needed by 'tests/data/equil_livegas.DATAq'.  Stop.
```
Where does the extra q come from?

**Comment by andlaus** [comment]
> Where does the extra q come from?

from OPM/ewoms#278. seems to be an "impartial editor shortcut" artefact.

**Comment by totto82** [comment]
Sorry. I most av accidentally added it while adding the data for the ecl_output test. I have pushed a fix

**Comment by totto82** [comment]
jenkins build this opm-output=235 ewoms=278 please

**Comment by atgeirr** [comment]
jenkins build this opm-output=235 ewoms=278 update_data please

**Comment by atgeirr** [comment]
jenkins build this opm-output=235 ewoms=278 opm-data=304 please

**Comment by atgeirr** [comment]
All green, merging!

**Pull request merged**
