### PR TITLE
Remove unused #include of exceptions

### PR DESCRIPTION
**Pull request by joakim-hove**
See: https://github.com/OPM/opm-material/pull/428

### CODE REVIEW

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by atgeirr** [comment]
Not sure which of these PRs cause the problem, but I get a compile error in NonlinearSolverEbos.hpp line 233 now?!?

**Comment by joakim-hove** [comment]
OK - I don't know how that happened; anyway here goes: https://github.com/OPM/opm-simulators/pull/2799

**Comment by blattms** [comment]
You forgot to specify "opm-material=428" to jenkins?

**Pull request merged**
