### PR TITLE
always inner well iterations in prediction mode

### PR DESCRIPTION
**Pull request by totto82**
I had hoped to always force inner well iterations, but I have not been able to solve the issue with the model2 regression. This restrict the forcing to the predictive simulations where it is needed!

### CODE REVIEW

**Comment by totto82** [comment]
jenkins build this please

**Comment by totto82** [comment]
benchmark please

**Comment by ytelses** [comment]
Benchmark result overview: 




| Test    | Configuration                                     | Relative |
| ------- | ------------------------------------------------- | -------- |
| opm-git | OPM Benchmark: flow_mpi_extra - Threads: 1        | 0.978    |
| opm-git | OPM Benchmark: flow_mpi_extra - Threads: 8        | 1.031    |
| opm-git | OPM Benchmark: flow_mpi_norne - Threads: 1        | 1        |
| opm-git | OPM Benchmark: flow_mpi_norne - Threads: 8        | 1.062    |
| opm-git | OPM Benchmark: flow_mpi_norne_4c_msw - Threads: 1 | 1.003    |
| opm-git | OPM Benchmark: flow_mpi_norne_4c_msw - Threads: 8 | 0.998    |
* Speed-up = Total time master / Total time pull request. Above 1.0 is an improvement. *



View result details @ https://www.ytelses.com/opm/?page=result&id=1217

**Comment by totto82** [comment]
I was a bit puzzled by the performance change for any of these models. Norne and model 2 are in history modus and norne_4c is msw. The reason for the impact for norne and model 2 is that the injectors uses WCONINJE and not WCONINJH i.e. they are in prediction modus. I will make a new PR where the default for all standard wells are inner iterations and run a benchmark for comparison.

**Pull request closed without merging**
