### PR TITLE
FlowExp: spring cleaning

### PR DESCRIPTION
**Pull request by akva2**
Various cosmetics to align with opm standards.

### CODE REVIEW

**Comment by akva2** [comment]
jenkins build this please

**Comment by GitPaean** [comment]
Thanks for this. One colleague raised the point that we should really enforce the clangformat throughout OPM repos. What do you think?

**Comment by akva2** [comment]
i'm no big fan of clang format. there will always be exceptions where violating rules is an advantage for readability and then you get forever stuck fighting an obnoxious tool.

**Comment by GitPaean** [comment]
Thanks for the efforts. Just taking this PR for example, most of the changes can be done automatically. I do think if we can avoid spending human time on this is nice.  I am getting the PR in now.

**Pull request merged**
