### PR TITLE
Use fmt::format() for two messages

### PR DESCRIPTION
**Pull request by joakim-hove**
Mainly a dummy to provoke a `update_data`for: https://github.com/OPM/opm-tests/pull/487

### CODE REVIEW

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by joakim-hove** [comment]
jenkins build this opm-tests=487 please

**Comment by joakim-hove** [comment]
jenkins build this opm-tests=487 update_data please

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by joakim-hove** [comment]
This was mainly introduced as a dummy for a update_data; but it is a small improvement anyway - merging.

**Comment by blattms** [comment]
This will break modules using opm-simuiators as your are using fmtlib in a header!
You will need to put the logging into its own function and that needs to go into a cpp file

**Comment by joakim-hove** [comment]
> This will break modules using opm-simuiators as your are using fmtlib in a header!

Ahhh ;-( Thanks for pointing out.

> You will need to put the logging into its own function and that needs to go into a cpp file

I'll just revert it.

**Pull request merged**
