### PR TITLE
More macro replacement

### PR DESCRIPTION
**Pull request by akva2**
Continuation of using the new property system from opm-models.

### CODE REVIEW

**Comment by akva2** [comment]
jenkins build this please

**Comment by akva2** [comment]
jenkins build this please

**Comment by blattms** [comment]
Wow, I like the syntax changes. Thanks @berndflemisch @akva2. merging.

**Comment by berndflemisch** [comment]
Nice to see this happen, thanks! I got sidetracked by strange things like work and holidays since I did this for opm-models. I can contribute again something after September 6. Maybe we manage to separate parameters from properties before the release.

**Pull request merged**
