### PR TITLE
Add logging in ebos

### PR DESCRIPTION
**Pull request by totto82**
With this .PRT and .DBG files are created also for ebos.

Does not impact Flow. 

Depends on OPM/opm-models#553

### CODE REVIEW

**Comment by totto82** [comment]
jenkins build this opm-models=553 please

**Comment by totto82** [comment]
jenkins build this opm-models=553 please

**Comment by totto82** [comment]
jenkins build this opm-models=553 please

**Comment by totto82** [comment]
@andlaus Do you want to review this?

**Comment by andlaus** [comment]
as you wish, but in the end the people who are active in OPM need to be happy with it, not me ;)

as a general remark, it would IMO be much better to put this kind of functionality into the vanguard instead of copy-and-pasting the main function, i.e., add a `setupLogging()` static method into the [base vanguard](https://github.com/OPM/opm-models/blob/master/opm/models/io/basevanguard.hh) and call this from `start()`. In most cases this method would just be empty, but complicated beasts like `ebos` can still roll their own stuff...

**Comment by dr-robertk** [comment]
This is a good feature for although the implementation may not be perfect yet. But since feature is needed I will merge it.

**Comment by blattms** [comment]
backported to release with PR #2063

**Pull request merged**
