### PR TITLE
Add Opm::PropertyTree

### PR DESCRIPTION
**Pull request by akva2**
this is a thin wrapper around boost::property_tree.
with this we avoid parsing property tree headers in all simulator objects.

### CODE REVIEW

**Comment by akva2** [comment]
jenkins build this please

**Comment by akva2** [comment]
jenkins build this please

**Comment by bska** [comment]
Quick question: Is the `PropertyTree.hpp` header intentionally not added to `make install` file set?

**Comment by akva2** [comment]
no, that's an oversight.

**Comment by akva2** [comment]
jenkins build this please

**Comment by joakim-hove** [comment]
Looks good!

**Pull request merged**
