### PR TITLE
Add support for serializing std::optional

### PR DESCRIPTION
**Pull request by joakim-hove**
Add serialize support for `std::optional<T>` - use coming here: #2573

### CODE REVIEW

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by joakim-hove** [comment]
Can this be merged?

**Comment by akva2** [comment]
i'm surprised this does the job, as there are no explicit instances of the template in the cpp file. so none will be generated leading to linker errors when you try to use it.

**Comment by joakim-hove** [comment]
> i'm surprised this does the job [....]

Well - it was probably a false positive, now though .... :-)

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by joakim-hove** [comment]
How about now?

**Comment by joakim-hove** [comment]
OK - this has been vetted in private communication; merging.

**Pull request merged**
