### PR TITLE
Increase max_iter for ctests SPE5 and 2D_THREEPHASE_POLY_HETER

### PR DESCRIPTION
**Pull request by totto82**
With this change no simulations have "failed steps" with current master.

### CODE REVIEW

**Comment by atgeirr** [comment]
jenkins build this please

**Comment by totto82** [comment]
You guess you will need to update the ref. data with this PR since it changes the time-stepping.

**Comment by atgeirr** [comment]
> You guess you will need to update the ref. data with this PR since it changes the time-stepping

I know, just wanted to verify that as a first step...

**Comment by atgeirr** [comment]
jenkins build this update_data please

**Comment by atgeirr** [comment]
jenkins build this opm-data=282 please

**Pull request merged**
