### PR TITLE
Solve the well model twice as a preprocessing step

### PR DESCRIPTION
**Pull request by totto82**
After the first solve the explicit quantities are updated and the well model solved again
This options was earlier only used at the initial step

### CODE REVIEW

**Comment by blattms** [comment]
out of curiosity: Does this result in better convergence/performance, etc.?

**Comment by totto82** [comment]
> out of curiosity: Does this result in better convergence/performance, etc.?

On norne the effect on runtime is small. For larger cases I don't know. The motivation for the change is to get more accurate results. But It should not hurt for the convergence either I think.

**Comment by alfbr** [comment]
Thanks, will test!

**Comment by alfbr** [comment]
benchmark please

**Comment by ytelses** [comment]
Benchmark result overview: 




| Test    | Configuration                              | Relative |
| ------- | ------------------------------------------ | -------- |
| opm-git | OPM Benchmark: flow_mpi_extra - Threads: 1 | 1.005    |
| opm-git | OPM Benchmark: flow_mpi_extra - Threads: 8 | 1.005    |
| opm-git | OPM Benchmark: flow_mpi_norne - Threads: 1 | 1.016    |
| opm-git | OPM Benchmark: flow_mpi_norne - Threads: 8 | 1.005    |
* Speed-up = Total time master / Total time pull request. Above 1.0 is an improvement. *



View result details @ https://www.ytelses.com/opm/?page=result&id=941

**Pull request closed without merging**
