### PR TITLE
split out typetag independent code from BlackoilWellModel

### PR DESCRIPTION
**Pull request by akva2**

### CODE REVIEW

**Comment by akva2** [comment]
jenkins build this please

**Comment by akva2** [comment]
jenkins build this please

**Comment by akva2** [comment]
jenkins build this please

**Comment by akva2** [comment]
jenkins build this please

**Comment by joakim-hove** [comment]
@akva2 : Do you have a prioritized merge order for the various pull requests?

Any reason this is not merged?

**Comment by akva2** [comment]
well, i don't have a prioritized merge order as such, but things needs to be merged in the correct order (they depend on each other).

no review i guess is the reason for no merge. no reason from my side, once it is green.

**Comment by joakim-hove** [comment]
> [...] (they depend on each other).

Exactly - and then it was my hunch that this first in the dependency list?

Unless someone beats me to it I will take a look later today; and will *most probably* merge it right away.

**Comment by akva2** [comment]
this is on a separate branch really, but it is ripe for picking in any case.

**Comment by akva2** [comment]
jenkins build this please

**Comment by akva2** [comment]
jenkins build this please

**Comment by akva2** [comment]
jenkins build this please

**Review by bska — APPROVED** [review]
These huge changesets are really hard to review, but I think this is correct because I recognize most of the logic here.  I'll take a leap of faith that we've not introduced any subtle errors and merge this now.

**Pull request merged**
