### PR TITLE
WIP: Testing out various tolerances.

### PR DESCRIPTION
**Pull request by alfbr**
Still more work to be done tightening up solutions with multisegment wells. This PR starts off trying out four different choices for four of the locally failing tests with multisegment wells. I need Jenkins solutions available to check if any of them fixes local failure at my end. Will remove the WIP tag once we have a working set of tolerances.

### CODE REVIEW

**Comment by alfbr** [comment]
jenkins build this update_data please

**Comment by GitPaean** [comment]
jenkins build this opm-tests=295 please

**Comment by alfbr** [comment]
Thanks @GitPaean ! Since this is work in progress, and may need many iterations before it is potentially merged, I think maybe https://github.com/OPM/opm-simulators/pull/2553 is a better candidate. It should be ready for merging now.

**Comment by alfbr** [comment]
No dice on any, let's try tightening further.

**Comment by alfbr** [comment]
jenkins build this update_data please

**Comment by alfbr** [comment]
jenkins build this update_data please

**Comment by alfbr** [comment]
Numerical defaults have been dramatically changed since this work was done, so these changes are obsolete. Closing.

**Pull request closed without merging**
