### PR TITLE
Warn about parallel logging fallout only on request / Use uppercase logfiles

### PR DESCRIPTION
**Pull request by blattms**
One PR three changes:

1. Use always uppercase *.PRT and *.DBG. 
2. When construcing the logfile names always strip the extension.
3. Only warn about and append parallel logging fallout if explicitly requested using new option --enable-logging-fallout-warning

Coments:
1) Seems consistent as all other output files seem to use that convention, too.  There was a comment/Issue about this but I cannot find it.
2) Is needed as we can start flow like `flow MODEL.` (omitting DATA) and would get MODEL..DBG and MODEL..PRT files.
3) Only annoys users that are not developing flow using MPI

### CODE REVIEW

**Comment by alfbr** [comment]
This is a welcome improvement. Unfortunately, this PR breaks the build at my end.

**Comment by bska** [comment]
> 2. When constructing the logfile names always strip the extension.

Does this handle pathological cases like
```
${flow} CASE.R01
```
which is supposed to run the scenario `CASE.R01.DATA`?

**Comment by blattms** [comment]
@bska Thanks for the hint. That was indeed a problem. We can only strip "." and ".DATA". Should be fixed.

@alfbr Sorry, somehow I must have missed compiling this branch. There was a parenthesis missing. Will fire up jenkins just to be sure.

**Comment by blattms** [comment]
jenkins build this please

**Comment by alfbr** [comment]
Any chance for a merge?

**Comment by bska** [comment]
> Any chance for a merge?

Sure, this seems like a good improvement.  I'll install into master.

**Pull request merged**
