### PR TITLE
Handle empty region in average calculator

### PR DESCRIPTION
**Pull request by totto82**
This should fix model 2 regression. 
A more elegant solution would be to make the RegionMapping.hpp parallel aware. But that is a task for another time and person. @bska or @blattms Cool if one of you could take a look at this some time.

### CODE REVIEW

**Comment by totto82** [comment]
jenkins build this please

**Comment by totto82** [comment]
I have tested this on model2 and it fixes the problem. Merge?

**Comment by alfbr** [comment]
I can confirm that it fixes my crash on the CO2 model too. Since this is a bug making multiple models break, I support merging now.

**Comment by blattms** [comment]
I am having some problems following. Looking at the patch and the comment, it seems like this bug should have also surfaced in a sequential run as the sum over all processes is already taken (and hence the porvolume should always be at as big in a parallel run as in a sequential one.

To me it seems that the function is already "parallel aware" (with lots of global communication, etc.), but is might not be very scalable as it is. Is that what you meant @totto82?

**Comment by bska** [comment]
> To me it seems that the function is already "parallel aware"

Kind of.  The very foundational "region -> cell set" mapping is not aware of multiple processes.  Making this fully aware of parallel environments is a moderately big undertaking&mdash;my best guess is a that it will require at least a 3 full work days&mdash;but I expect the final outcome to be a lot better than the hacky facility we have at the moment.

**Comment by blattms** [comment]
> The very foundational "region -> cell set" mapping is not aware of multiple processes

IMHO it shouldn't be aware of that. The only information that might help is what processes might have cells of a region. But maybe that is what you meant, anyway

**Comment by alfbr** [comment]
> I am having some problems following. Looking at the patch and the comment, it seems like this bug should have also surfaced in a sequential run 

Yes, I can confirm that the bug was there in sequential runs, and that this PR fixes it for sequential runs.

**Comment by totto82** [comment]
What I want is to be able to 
```
for (auto reg : regions)
 comm.sum(...)
```

without hanging since `regions ` means something different on the different ranks

**Pull request merged**
