### PR TITLE
fixed: linking of some cuda tests with shared libraries

### PR DESCRIPTION
**Pull request by akva2**
need to link against the cudart library

### CODE REVIEW

**Comment by akva2** [comment]
jenkins build this mpi-shared please

**Comment by bska** [comment]
> jenkins build this mpi-shared please

Hm, the [build succeeded](https://ci.opm-project.org/job/opm-simulators-PR-builder/6300/), but the [build log](https://ci.opm-project.org/job/opm-simulators-PR-builder/6300/console) has output of the form

> ```
> 18% tests passed, 293 tests failed out of 358
> 
> Total Test time (real) = 904.88 sec
> 
> The following tests FAILED:
>	 65 - compareSeparateECLFiles_flow+pyaction_gconprod_insert_kw (Failed)
>	 66 - compareSeparateECLFiles_flow+pyaction_gconsump_insert_kw (Failed)
>	 67 - compareSeparateECLFiles_flow+pyaction_gruptree_insert_kw (Failed)
>	 68 - compareSeparateECLFiles_flow+pyaction_mult+_insert_kw (Failed)
>	 69 - compareSeparateECLFiles_flow+pyaction_multx+_insert_kw (Failed)
>	 70 - compareSeparateECLFiles_flow+pyaction_multx-_insert_kw (Failed)
>	 71 - compareSeparateECLFiles_flow+pyaction_next_insert_kw (Failed)
>	 72 - compareSeparateECLFiles_flow+pyaction_wconprod_insert_kw (Failed)
>	 73 - compareSeparateECLFiles_flow+pyaction_wefac_insert_kw (Failed)
>	 74 - compareSeparateECLFiles_flow+pyaction_wesegvalv_insert_kw (Failed)
>	 75 - compareSeparateECLFiles_flow+pyaction_wtest_insert_kw (Failed)
>	 76 - compareECLFiles_flowexp_blackoil+SPE1CASE2 (Failed)
>	 77 - compareECLFiles_flow+SPE1CASE2 (Failed)
>	 78 - compareECLFiles_flow+SPE1CASE2_2P (Failed)
>	 79 - compareECLFiles_flow+SPE1CASE2_OILGAS (Failed)
>	 80 - compareECLFiles_flow+SPE1CASE2_GASWATER (Failed)
>	 81 - compareECLFiles_flow+SPE1CASE1 (Failed)
> ...
> ```
Is this expected?

**Comment by akva2** [comment]
well, yes and no. i have not yet changed the jenkins job to upload results from the mpi-shared configuration so that's why the job passed. but obviously that is an oversight on my behalf.

**Comment by akva2** [comment]
jenkins build this mpi-shared please

**Comment by akva2** [comment]
jenkins build this mpi-shared please

**Comment by akva2** [comment]
jenkins build this mpi-shared please

**Comment by akva2** [comment]
this does the job it set out to do as such, but you won't see a green status. combined with https://github.com/OPM/opm-common/pull/4087 python tests pass, but some of the usual suspects (ie MSW tests) fail to produce the reference results due to their snowflake nature.

**Comment by akva2** [comment]
can this be merged?

**Comment by hakonhagland** [comment]
@akva2 It looks good to me :)

**Pull request merged**
