### PR TITLE
Added 9_1A through 9_2A tests.

### PR DESCRIPTION
**Pull request by alfbr**
These tests have been checked to provide correct results with Flow. I therefore suggest we put them under automated regression testing.

### CODE REVIEW

**Comment by alfbr** [comment]
jenkins build this update_data please

**Comment by bska** [comment]
jenkins build this please

**Comment by bska** [comment]
Just a little bit of extra cost in the regression tests, but the benefits of having these run far outweighs that cost.  I'll launch a data-update run and merge when that comes back green.

**Comment by bska** [comment]
jenkins build this update_data please

**Comment by bska** [comment]
jenkins build this opm-tests=291 please

**Comment by bska** [comment]
Thanks for the additional regression tests.  I'll merge this into master now.

**Pull request merged**
