### PR TITLE
Use multivariable broadcast facility to broadcast rates

### PR DESCRIPTION
**Pull request by akva2**
This was the motivation for https://github.com/OPM/opm-simulators/pull/3674
Sits on top of that and should be processed after

### CODE REVIEW

**Comment by akva2** [comment]
jenkins build this please

**Comment by akva2** [comment]
jenkins build this please

**Comment by akva2** [comment]
jenkins build this please

**Review by bska — APPROVED** [review]
Thanks.  This looks good to me and I'll merge into master.

**Pull request merged**
