### PR TITLE
Merge pull request #1 from OPM/master

### PR DESCRIPTION
**Pull request by kingaj12**
merging my fork

### CODE REVIEW

**Comment by atgeirr** [comment]
Hello again @kingaj12! We requested some information from you in #1449 but have received no comments from you. Without any further explanations or information I will not be able to prioritize them for review, and ultimately they will be closed. We are interested in what you are doing, but need communication to deal with it properly.

**Comment by alfbr** [comment]
Just want to add that support for HDF is indeed of interest, so @kingaj12 please pop us a mail or anything :-)

**Comment by andlaus** [comment]
it seems like all of us are on the same line with you technically and we want such a facility as well. the issues raised are of a more formal nature: E.g. to spare us some potential legal problems, we need you to use your real name as the author of all commits, or at least we need to know who you are.

> (... I haven't really been able to nail down what state is stored where, and navigating the template hierarchy is daunting ... ;( .. could use some help there. It seems like you are moving to an ewoms abstraction, but I don't know how to work with that yet.)

your impression is correct: nowadays most of flow is basically a frontend for eWoms. basically the only objects which hold state that are relevant for you are [EclProblem](https://github.com/OPM/ewoms/blob/master/ebos/eclproblem.hh#L295) and the current solution of the [BlackOilModel](https://github.com/OPM/ewoms/blob/master/ewoms/disc/common/fvbasediscretization.hh#L1073).

> Anyway, I think the road to merging is going to take a while. There is a lot to do. Perhaps we can talk about a minimum viable product? I noticed that there is a PR for adjoints but I have not looked very carefully at it. Maybe that's a place to start.

I think that we are on the same card here, too. For us, it is more important that it is done *well*, not that is finished *quickly*.

**Comment by kingaj12** [comment]
OK good.  Sounds like we are in agreement!  I posted some information on my profile.  If you need any other information, send me an email.

**Comment by kingaj12** [comment]
Dear all - I have been informed by my client that I should not put this code into the open domain.  I am sorry for the misunderstanding.  Please, can you delete this request?  Thanks.

**Comment by GitPaean** [comment]
Hi, I am not sure anyone here can help you to delete this PR. Maybe you can contact Github staff for help, like support@github.com . 

We can help you delete all the conversations, and you can clean the commits with forceful push.

**Comment by kingaj12** [comment]
OK thanks.  Sorry about all the fuss.  what does a "forceful push" mean?
 
----- Original message -----From: Kai Bao <notifications@github.com>To: OPM/opm-simulators <opm-simulators@noreply.github.com>Cc: Alan King <kingaj@us.ibm.com>, State change <state_change@noreply.github.com>Subject: Re: [OPM/opm-simulators] Merge pull request #1 from OPM/master (#1454)Date: Mon, May 14, 2018 4:17 PM 
Hi, I am not sure anyone here can help you to delete this PR. Maybe you can contact Github staff for help, like support@github.com .
We can help you delete all the conversations, and you can clean the commits with forceful push.

**Comment by GitPaean** [comment]
You can remove all your development commits in your branch (make sure you make a copy before that, to clean the commits, one easy way is to delete the old branch, create a new branch based on master with the same name.), then


git push HEAD origin --force



Then the commits shown in the PR will disappear, or be replaced by the newly pushed commits, which is nothing.

________________________________

**Comment by andlaus** [comment]
> Dear all - I have been informed by my client that I should not put this code into the open domain.

I think that this is sad, but you're free to do so as long as you adhere to the license. (Basically, you need provide all your source code under the terms of the GPLv3 to anybody which you distribute code that is derived from OPM. Note that if your client does not redistribute this code themselves, the GPL does not restrict them in any way but selling binary programs without providing source code will put them into murky legal waters.)

**Pull request closed without merging**
