### PR TITLE
Add SPE1CASE2_OILGAS test case

### PR DESCRIPTION
**Pull request by totto82**

### CODE REVIEW

**Comment by totto82** [comment]
jenkins build this update_data please

**Comment by akva2** [comment]
update data won't update data unless you update the update script.

**Comment by totto82** [comment]
Would this work?

**Comment by totto82** [comment]
jenkins build this update_data please

**Comment by akva2** [comment]
jenkins build this opm-data=287 please

**Comment by atgeirr** [comment]
Thanks, merging!

**Pull request merged**
