### PR TITLE
update the thp value for flow_ebos

### PR DESCRIPTION
**Pull request by GitPaean**
For the wells having a THP constraints, their THP values should be updated always. Otherwise, the control switching will not work correctly. 

The PR makes the flow_ebos having the same results with flow, while not tested against Eclipse yet. 

And also, the output of thp values not correct. They are always zero, will looking into it later.

### CODE REVIEW

**Comment by andlaus** [comment]
no objections as far as I'm concerned. @totto82: you have the button.

**Comment by GitPaean** [comment]
The output of the THP is solved by OPM/opm-core#1142 .  So this PR is ready for review.

**Comment by totto82** [comment]
Thanks. I have tested in on a SPE1 based case and it works. I will merge this tomorrow morning if nobody complains.

**Comment by atgeirr** [comment]
After merging #1055 the code here must be moved.

**Comment by GitPaean** [comment]
The PR has been changed based on the current master branch. 

The test show the behavior still correct compared with `flow`.

**Pull request merged**
