### PR TITLE
Use termininal_output_ to only print time step status once for parallel runs

### PR DESCRIPTION
**Pull request by blattms**
Previously each process printed this to the terminal

### CODE REVIEW

**Comment by bska** [comment]
I like it and I have just one question.  Do we need `step_msg` outside the `if (output_terminal_)` conditional on line [184](https://github.com/blattms/opm-simulators/blob/047ae8f44490143fa8f68497c5e34666f41b30c2/opm/autodiff/SimulatorBase_impl.hpp#L182-L185)?  If not, it's probably better to move the declaration into the conditional.

**Comment by blattms** [comment]
Nope. That was an oversight. Will fix.

**Comment by blattms** [comment]
@bska Done.

**Comment by bska** [comment]
> Done.

Thanks!  Travis approves, so I'll merge into master.

**Pull request merged**
