### PR TITLE
fixed: VAPPARS is supported, remove from unsupported features list

### PR DESCRIPTION
**Pull request by akva2**
Unless I'm missing something?

### CODE REVIEW

**Comment by atgeirr** [comment]
> Unless I'm missing something?

I don't think you are.

**Comment by atgeirr** [comment]
jenkins build this please

**Comment by akva2** [comment]
failures are due to timing issues, but.. let's rerun.

**Comment by akva2** [comment]
jenkins build this please

**Comment by akva2** [comment]
merge?

**Comment by bska** [comment]
> merge?

Yes.  I'm merging into master now.

**Pull request merged**
