### PR TITLE
amgcl to prefix path

### PR DESCRIPTION
**Pull request by akva2**
This is just a PR to allow me experimenting with getting amgcl setup on jenkins without bypassing the build job queue.

### CODE REVIEW

**Comment by akva2** [comment]
jenkins build this please

**Comment by akva2** [comment]
jenkins build this please

**Comment by akva2** [comment]
jenkins build this please

**Comment by blattms** [comment]
does that mean you are patching it (amgcl/vexcl) to work with cl2.hpp/opencl.hpp? It seemst to expect the old header (did not really investigate, just jusdging from the error messages that I saw on my system)

**Comment by akva2** [comment]
well i am looking into how much patchery it takes. seems like more than just replacing the header is needed. likely some of them defines we have in our opencl.hpp. feels like it might be too much hassle right now.

**Comment by akva2** [comment]
yeah this is not happening.

**Comment by akva2** [comment]
jenkins build this please

**Comment by akva2** [comment]
@blattms okay, it is success with vexcl master. i'll enable it in the builds now.

**Pull request closed without merging**
