### PR TITLE
Added exception handling to cusparse test

### PR DESCRIPTION
**Pull request by Tongdongq**
Same as the last commit of https://github.com/OPM/opm-simulators/pull/3300

### CODE REVIEW

**Comment by blattms** [comment]
jenkins build this please

**Comment by Tongdongq** [comment]
Test '125 - compareECLFiles_flow+NORNE_ATW2013_B1H_RE-PERF' has failed.
Could https://github.com/OPM/opm-simulators/pull/3397 have introduced this error?
https://ci.opm-project.org/job/opm-simulators-PR-builder/2625/

**Comment by bska** [comment]
> Test '125 - compareECLFiles_flow+NORNE_ATW2013_B1H_RE-PERF' has failed.
> Could #3397 have introduced this error?

Yes, #3397 did introduce that error.  It is fixed now, following OPM/opm-tests#560.

**Comment by blattms** [comment]
jenkins build this please

**Comment by bska** [comment]
jenkins build this update_data please

**Comment by bska** [comment]
jenkins build this opm-tests=567 please

**Pull request merged**
