### PR TITLE
Adjust reduction rate when well control is considered for GRUP

### PR DESCRIPTION
**Pull request by totto82**
The reduction rate is computed differently for cases without wells under GRUP
For a well to check whether to switch to GRUP it needed to use the reduction rate
that would have been computed if this particular well was under GRUP control
and thus recompute the reduction rate without entering the no-grup path

### CODE REVIEW

**Review by atgeirr — APPROVED** [review]
A few typos... "hiearchy"

**Comment by totto82** [comment]
jenkins build this please

**Comment by totto82** [comment]
jenkins build this update_data please

**Comment by totto82** [comment]
jenkins build this opm-tests=654 please

**Pull request merged**
