### PR TITLE
Update well rates from target during well/group control update

### PR DESCRIPTION
**Pull request by totto82**
If a well/group control change all wells belonging to the same group are potentially affected. Calling updateWellStateFromTarget between every update makes the rates more consistent and thus avoids oscillations.

### CODE REVIEW

**Comment by ytelses** [comment]
Benchmark result overview: 




| Test    | Configuration                                     | Relative |
| ------- | ------------------------------------------------- | -------- |
| opm-git | OPM Benchmark: flow_mpi_extra - Threads: 1        | 1.025    |
| opm-git | OPM Benchmark: flow_mpi_extra - Threads: 8        | 0.999    |
| opm-git | OPM Benchmark: flow_mpi_norne - Threads: 1        | 1.01     |
| opm-git | OPM Benchmark: flow_mpi_norne - Threads: 8        | 1.035    |
| opm-git | OPM Benchmark: flow_mpi_norne_4c_msw - Threads: 1 | 0.621    |
* Speed-up = Total time master / Total time pull request. Above 1.0 is an improvement. *



View result details @ https://www.ytelses.com/opm/?page=result&id=1321

**Comment by totto82** [comment]
> flow_mpi_norne_4c_msw

is very unstable in terms of convergence. 

```
RegularizationFactorMsw="10" # default: "1"
ShutUnsolvableWells="true" # default: "0"
TimeStepAfterEventInDays="1" # default: "-1"
```

reduces the number of problems from 75 to 6. 

The same parameters gives improvement for several of the problematic norne prediction models as well. 
Time to revisit some defaults?

**Comment by alfbr** [comment]
> Time to revisit some defaults?

Puh, I was afraid you would conclude that. Yes, it certainly seems like we should. The timing is probably fairly good too.

**Comment by totto82** [comment]
jenkins build this please

**Comment by totto82** [comment]
benchmark please

**Comment by ytelses** [comment]
Benchmark result overview: 




| Test    | Configuration                                     | Relative |
| ------- | ------------------------------------------------- | -------- |
| opm-git | OPM Benchmark: flow_mpi_extra - Threads: 1        | 1.027    |
| opm-git | OPM Benchmark: flow_mpi_extra - Threads: 8        | 0.996    |
| opm-git | OPM Benchmark: flow_mpi_norne - Threads: 1        | 1.011    |
| opm-git | OPM Benchmark: flow_mpi_norne - Threads: 8        | 1.038    |
| opm-git | OPM Benchmark: flow_mpi_norne_4c_msw - Threads: 1 | 0.624    |
* Speed-up = Total time master / Total time pull request. Above 1.0 is an improvement. *



View result details @ https://www.ytelses.com/opm/?page=result&id=1347

**Comment by ytelses** [comment]
Benchmark result overview: 




| Test    | Configuration                                     | Relative |
| ------- | ------------------------------------------------- | -------- |
| opm-git | OPM Benchmark: flow_mpi_extra - Threads: 1        | 1.022    |
| opm-git | OPM Benchmark: flow_mpi_extra - Threads: 8        | 1.002    |
| opm-git | OPM Benchmark: flow_mpi_norne - Threads: 1        | 1.006    |
| opm-git | OPM Benchmark: flow_mpi_norne - Threads: 8        | 1.042    |
| opm-git | OPM Benchmark: flow_mpi_norne_4c_msw - Threads: 1 | 0.701    |
| opm-git | OPM Benchmark: flow_mpi_norne_4c_msw - Threads: 8 | 0.632    |
* Speed-up = Total time master / Total time pull request. Above 1.0 is an improvement. *



View result details @ https://www.ytelses.com/opm/?page=result&id=1347

**Comment by totto82** [comment]
jenkins build this please

**Comment by totto82** [comment]
benchmark please

**Comment by ytelses** [comment]
Benchmark result overview: 




| Test    | Configuration                                     | Relative |
| ------- | ------------------------------------------------- | -------- |
| opm-git | OPM Benchmark: flow_mpi_extra - Threads: 1        | 0.999    |
| opm-git | OPM Benchmark: flow_mpi_extra - Threads: 8        | 0.996    |
| opm-git | OPM Benchmark: flow_mpi_norne - Threads: 1        | 0.984    |
| opm-git | OPM Benchmark: flow_mpi_norne - Threads: 8        | 1.004    |
| opm-git | OPM Benchmark: flow_mpi_norne_4c_msw - Threads: 1 | 1.005    |
* Speed-up = Total time master / Total time pull request. Above 1.0 is an improvement. *



View result details @ https://www.ytelses.com/opm/?page=result&id=1349

**Comment by ytelses** [comment]
Benchmark result overview: 




| Test    | Configuration                                     | Relative |
| ------- | ------------------------------------------------- | -------- |
| opm-git | OPM Benchmark: flow_mpi_extra - Threads: 1        | 0.991    |
| opm-git | OPM Benchmark: flow_mpi_extra - Threads: 8        | 1.001    |
| opm-git | OPM Benchmark: flow_mpi_norne - Threads: 1        | 0.995    |
| opm-git | OPM Benchmark: flow_mpi_norne - Threads: 8        | 1.012    |
| opm-git | OPM Benchmark: flow_mpi_norne_4c_msw - Threads: 1 | 1.013    |
* Speed-up = Total time master / Total time pull request. Above 1.0 is an improvement. *



View result details @ https://www.ytelses.com/opm/?page=result&id=1349

**Comment by totto82** [comment]
jenkins build this please

**Comment by totto82** [comment]
benchmark please

**Comment by ytelses** [comment]
Benchmark result overview: 




| Test    | Configuration                                     | Relative |
| ------- | ------------------------------------------------- | -------- |
| opm-git | OPM Benchmark: flow_mpi_extra - Threads: 1        | 1        |
| opm-git | OPM Benchmark: flow_mpi_extra - Threads: 8        | 1.003    |
| opm-git | OPM Benchmark: flow_mpi_norne - Threads: 1        | 0.998    |
| opm-git | OPM Benchmark: flow_mpi_norne - Threads: 8        | 1.011    |
| opm-git | OPM Benchmark: flow_mpi_norne_4c_msw - Threads: 1 | 1.014    |
* Speed-up = Total time master / Total time pull request. Above 1.0 is an improvement. *



View result details @ https://www.ytelses.com/opm/?page=result&id=1351

**Comment by ytelses** [comment]
Benchmark result overview: 




| Test    | Configuration                                     | Relative |
| ------- | ------------------------------------------------- | -------- |
| opm-git | OPM Benchmark: flow_mpi_extra - Threads: 1        | 0.999    |
| opm-git | OPM Benchmark: flow_mpi_extra - Threads: 8        | 1.005    |
| opm-git | OPM Benchmark: flow_mpi_norne - Threads: 1        | 0.998    |
| opm-git | OPM Benchmark: flow_mpi_norne - Threads: 8        | 1.011    |
| opm-git | OPM Benchmark: flow_mpi_norne_4c_msw - Threads: 1 | 1.015    |
* Speed-up = Total time master / Total time pull request. Above 1.0 is an improvement. *



View result details @ https://www.ytelses.com/opm/?page=result&id=1351

**Comment by totto82** [comment]
Seems like the `OPM Benchmark: flow_mpi_norne_4c_msw - Threads: 8` is broken on master. I will remove the last commit since that didn't fix the problematic case and start preparing for a merge.  `flow_mpi_norne_4c_msw` runs fine locally with both 1, 8 and 64 threads.

**Comment by totto82** [comment]
jenkins build this please

**Comment by totto82** [comment]
I have checked the test failures and will start the update of data later today if no objections.

**Comment by totto82** [comment]
jenkins build this update_data please

**Comment by totto82** [comment]
jenkins build this opm-tests=613 please

**Pull request merged**
