### PR TITLE
changed: split out non-typetag dependent code from WellInterface

### PR DESCRIPTION
**Pull request by akva2**
This is a first step in reducing the amount of rebuilds due to changes in well code.

I realize there's a lot of things going on with wells, so I leave it to those doing "real" changes to time when to merge this. I'll handle any rebasing until then.

### CODE REVIEW

**Comment by akva2** [comment]
jenkins build this please

**Comment by akva2** [comment]
jenkins build this please

**Comment by akva2** [comment]
jenkins build this please

**Comment by joakim-hove** [comment]
> I realize there's a lot of things going on with wells, so I leave it to those doing "real" changes to time when to merge this. I'll handle any rebasing until then.

I have two PR's in flight which I would like to get in #3216 and #3233 (they can be merged before merging); but I do not insist on anything - I can also rebase!

**Comment by totto82** [comment]
As I understand this PR it split-out the non-typetag dependent code. Do you plan to move more code in to the generic class?
As it is now it separate out part of the code that would probably not change much. I.e. the impact of the this in reduced compilation time would not be too large I think. But in general I support your effort. These well model files are too big anyway so splitting them up in smaller chunks has some benefits in its own.

**Comment by akva2** [comment]
well, currently i have identified two parts; completely typetag independent code (the generic class), and fluidsystem dependent parts (separate PR). i don't think there's much more in-between there, the rest of the code pretty much needs simulator specifics.

**Comment by akva2** [comment]
great. there's some rebase errors in here right now, but i'll get it up to date soon.

**Comment by akva2** [comment]
jenkins build this please

**Comment by joakim-hove** [comment]
OK - this has been lingering for over a week; @totto82  has approved. I'll merge and bring out my rebase kit!

**Pull request merged**
