### PR TITLE
ISTLSolverEbos: instance for ALUGrid

### PR DESCRIPTION
**Pull request by akva2**
To enable https://github.com/OPM/opm-common/pull/3219

### CODE REVIEW

**Comment by akva2** [comment]
jenkins build this serial please

**Comment by blattms** [comment]
I have the feeling, that this won't work if ALUGrid is not there, but a build with it is requested. Problem is that it will fail only when compiling and not already when configuring.

**Comment by akva2** [comment]
HAVE flag is for availability, not what user requested. the USE flag is properly handled in https://github.com/OPM/opm-simulators/blob/master/ebos/eclproblem.hh#L31

**Comment by akva2** [comment]
ah now i get what you mean. maybe we should just make eclproblem #error ?

**Comment by akva2** [comment]
i opted to disable in the buildsystem if alugrid is not found. this is the normal way to handle these things.

**Comment by akva2** [comment]
jenkins build this please

**Comment by bska** [comment]
@blattms: Unless you have any reservations about the build system portion of this PR I think we should merge it.  Right now it's blocking all other PRs from progressing because it's impossible to get a clean build.

**Comment by blattms** [comment]
Sorry, for the delay, but the information about blocking something was not clear to me from the available channels (such as PRs, lists, chats,...) Not really sure whether it was this PR that was blocking, but I simply merged all related ones and hope it is resolved now.

**Comment by blattms** [comment]
@akva2 Is there a bot deleting your branches after merging in such a timely manner, or is there an option like in gitlab for requesting this that I fail to see?

**Comment by akva2** [comment]
nah, i'm just very dilligent and if i am at a device at that time i immediately go and delete the branch because if not i'll surely forget about it..

**Pull request merged**
