### PR TITLE
Refactor `execute()` in `FlowMainEbos.hpp`

### PR DESCRIPTION
**Pull request by hakonhagland**
A resubmission of commit 77a151b in PR #2403 and PR #2440 to work with the current master.

Currently, `execute()` calls `runSimulator()` to run the simulation. When the Python `step_init()` is implemented (in a later commit), it will instead call an `executeStepInit()` method that will need to do the same initialization as in the current `execute()` except that it should call a `runSimulatorInit()` method instead of `runSimulator()`. In order to avoid code duplication for `execute()` and `executeStepInit()`, `execute()` is here refactored into an `execute_()` method.

### CODE REVIEW

**Comment by hakonhagland** [comment]
jenkins build this please

**Comment by atgeirr** [comment]
I have to admit this looks a bit overcomplicated, what is wrong about splitting into "setup", "run" and "cleanup" functions, then calling them from Python separately?

**Comment by hakonhagland** [comment]
> wrong about splitting into "setup", "run" and "cleanup" functions, then calling them from Python separately?

@atgeirr I was trying to keep the original structure of the `execute()` method:

```
int execute( ... )
{
    try {
        // call methods for setup
        // ...

        int retval = runSimulator();

        // call methods for clean up
        // ....
        
        return retval;
     }
     catch (const std::exception& e) {
         // handle exceptions
     }
}
```
If we try the other approach as you suggest, then we instead write `execute()` llike this (in pseudo code):
```
int execute( ... )
{
    try {
        setup();
        int retval = runSimulator(output_cout);
        cleanup();
        return retval;
    }
    catch (const std::exception& e) {
        exeception_handler();
    }
}
```
Then we need to introduce additional python wrappers:
```
int setup_python()
{
    try {
        setup();
        // Note: We do not want to call runSimulator() here since 
        // we only want to initialize
        runSimulatorInit();  
    }
    catch (const std::exception& e) {
        exception_handler();
    }
}

int step_python()
{
    try {
        // Note: We do not want to call runSimulator() here since 
        // we only want to do a single report step
        runSimulatorStep();
    }
    catch (const std::exception& e) {
        exception_handler();
    }
}

int cleanup_python()
{
    try {
        cleanup();
    }
    catch (const std::exception& e) {
        exception_handler();
    }
}
```

I can try implement try this approach also, but currently I liked my original approach better :wink:

**Comment by atgeirr** [comment]
> I can try implement try this approach also, but currently I liked my original approach better

Let me think a little bit. In general, I want the API used from Python to be so nice that we will use the same API from C++, avoiding two different ways of doing things. If I cannot find a better way quickly, we'll merge this.

**Comment by atgeirr** [comment]
> If I cannot find a better way quickly, we'll merge this.

I'll admit defeat on this one... As long as the python API is not written in stone we can always improve and refactor if we see better ways. I'll merge.

**Pull request merged**
