### PR TITLE
Single well state2

### PR DESCRIPTION
**Pull request by joakim-hove**
These commits were "forgotten" when merging #3458

### CODE REVIEW

**Comment by joakim-hove** [comment]
jenkins bulid this please

**Comment by bska** [comment]
jenkins build this please

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by akva2** [comment]
jenkins is in a bad state atm, github doesn't currently accept the auth token, i'm busy figuring out why.

**Comment by akva2** [comment]
jenkins build this please

**Comment by joakim-hove** [comment]
replaced by: https://github.com/OPM/opm-simulators/pull/3487

**Pull request closed without merging**
