### PR TITLE
Partially Supported Keywords RUNSPEC and some Aquifer Keywords

### PR DESCRIPTION
**Pull request by OPMUSER**
Partially Supported all RUNSPEC keywords, plus AQUANCON, AQUCON and AQUCT

### CODE REVIEW

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by akva2** [comment]
looks like this changes the entire file to typewriter compatibility...

**Comment by OPMUSER** [comment]
I'm going to re-do this so I would like to delete this pull request. I 
actually checked the range values of items that we did support instead 
of only checking items that we do not support - apologies.

**Comment by akva2** [comment]
sure. and just in case: don't take my pointing out issues as hostility, i'm only trying to help.

**Pull request closed without merging**
