### PR TITLE
Segment index

### PR DESCRIPTION
**Pull request by joakim-hove**
Make sure that iterations over segments go over the index for one well. To simplify further refactoring.

### CODE REVIEW

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by atgeirr** [comment]
I am not a great fan of the update_bhp() etc. API, is this a temporary stage? How do you intend it to end up?

**Comment by joakim-hove** [comment]
> I am not a great fan of the update_bhp() etc. API, is this a temporary stage? How do you intend it to end up?

I have the comment over here: #3268

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by joakim-hove** [comment]
jenkins build this please

**Pull request merged**
