### PR TITLE
hide opencl in wellcontributions

### PR DESCRIPTION
**Pull request by akva2**
This is relatively hacky code to see if it helps the ocl + cuda situation.

### CODE REVIEW

**Comment by akva2** [comment]
jenkins build this cuda please

**Comment by akva2** [comment]
jenkins build this cuda please

**Comment by akva2** [comment]
jenkins build this cuda please

**Comment by akva2** [comment]
jenkins build this cuda please

**Comment by Tongdongq** [comment]
I can build this with CUDA and OpenCL.
However it segfaults because `setOpenCLEnv()` is called before the `ocldata` is initialized in `alloc()`.

**Comment by akva2** [comment]
yeah, probably some stupids like that in here. this was just a test, i am working on a proper refactor. sadly neither the ocl or the cuda solver works at all on my aging gpu so i can't runtime test.

**Comment by akva2** [comment]
can you please try #3691

**Comment by akva2** [comment]
closing this now to avoid more confusion

**Pull request closed without merging**
