### PR TITLE
refactoring the pressure assemble equations for ICD

### PR DESCRIPTION
**Pull request by GitPaean**
to reduce some code duplication. It should not change the results in any way.

### CODE REVIEW

**Comment by GitPaean** [comment]
jenkins build this please

**Comment by GitPaean** [comment]
jenkins build this please

**Comment by bska** [comment]
I like it.  Unless @atgeirr wants to say something about this I suggest we merge it as is.  Reducing code complexity is always welcome.

**Comment by atgeirr** [comment]
> I like it. Unless @atgeirr wants to say something about this I suggest we merge it as is. Reducing code complexity is always welcome.

Sorry for not commenting earlier, I have no reason to go against this, refactoring is good. Thanks for the patch and the review, I'll merge now.

**Pull request merged**
