### PR TITLE
output temperature when TEMP is set

### PR DESCRIPTION
**Pull request by totto82**
For isothermal simulations (enableEnergy=false) but with non-constant temperature (RTEMPVD) we may want to output the temperature.

### CODE REVIEW

**Comment by totto82** [comment]
jenkins build this please

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by totto82** [comment]
Can we merge this?

**Review by bska — APPROVED** [review]
This looks like a reasonable change.  I'll merge into master.

**Pull request merged**
