### PR TITLE
Added adjoint possibilities

### PR DESCRIPTION
**Pull request by hnil**
Depends on ewoms #447
Introduce changes to make adjoint possible. 
The most controversial is using boost::serialize for serializing the states.
Else the code is mostly seperateted from the forward run.
Better code flow could probably be done with reorganization of begin: step, iteration ++

The current code has limited validity for adjoint, but forward run should not be affected.
This which will be addrest in future tests code chages is:
- slightly wrong initialization of wells with may perforations
- backward time stepping with changing wells
(Both of which worked in previous pull request, but is lost after merge due to other code changes.)

Test case pull request in opm-tests is in progress.

### CODE REVIEW

**Comment by hnil** [comment]
jenkins build this ewoms=447 please

**Comment by hnil** [comment]
jenkins build this ewoms=447 please

**Comment by hnil** [comment]
jenkins build this ewoms=447 opm-tests=81 please

**Comment by atgeirr** [comment]
jenkins build this ewoms=447 opm-tests=81 please

**Comment by hnil** [comment]
jenkins build this ewoms=447 opm-tests=81 please

**Comment by hnil** [comment]
jenkins build this ewoms=447 opm-tests=81 please

**Pull request closed without merging**
