### PR TITLE
Suggestion: remove test_ecl_output

### PR DESCRIPTION
**Pull request by joakim-hove**
The test `test_ecl_output.cc` tests summary output from a simulation. It is a slightly schizofrenic test, with some traits of a regression test and some traits of a unit test; the summary output is quite extensively unit-tested in opm-common and there are numerous much more extensive regression tests here in opm-simulators; i.e. it does not really add any value test coverage wise.

Lately I (and @atgeirr) have spent quite some time debugging problems with this test (#3605, #3692) which was very weakly related to the problem at hand. 

All in all - I suggest removing it.

### CODE REVIEW

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by joakim-hove** [comment]
Ehhh - I f... up a bit. I merged: https://github.com/OPM/opm-simulators/pull/3698 and then when I was going over to: https://github.com/opm/opm-tests/pull/672 to merge the corresponding data update (yeah I know - wrong order); turned out the data update was no longer green.

Will abuse this PR to create a new data update.

**Comment by joakim-hove** [comment]
jenkins build this update_data please

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by akva2** [comment]
replaced by #4299

**Pull request closed without merging**
