### PR TITLE
add flow solvent dynamic test

### PR DESCRIPTION
**Pull request by totto82**
Depends on OPM/opm-tests#456

### CODE REVIEW

**Comment by totto82** [comment]
jenkins build this opm-tests=456 please

**Comment by totto82** [comment]
jenkins build this update_data please

**Comment by totto82** [comment]
jenkins build this update_data please

**Comment by totto82** [comment]
jenkins build this opm-tests=467 please

**Comment by totto82** [comment]
Can I merge this. I really want the test case added to jenkins.

**Comment by atgeirr** [comment]
> Can I merge this. I really want the test case added to jenkins.

Yes I'll merge. Did not really see much information on what this case tests though?

**Comment by alfbr** [comment]
> Yes I'll merge. Did not really see much information on what this case tests though?

Actually, this is the best documented test case in the suite, have a look in the DATA-file header.

**Comment by atgeirr** [comment]
> Actually, this is the best documented test case in the suite, have a look in the DATA-file header.

Saw it now, thanks.

**Pull request merged**
