### PR TITLE
Zoltan partitioner with all perforated cells of a well merged to one vertex

### PR DESCRIPTION
**Pull request by michal-toth**
This adds a new option to partition for a parallel run.

Running flow with the parameter --partition-method=3 will use Zoltan partitioner with the grid represented by a graph (class GraphOfGrid [OPM/opm-grid#790](https://github.com/OPM/opm-grid/pull/790). All cells potentially perforated by a  well are represented by a single vertex, therefore the partitioning is unable to split a well into several processes.

This should lead to better partitioning results on problems with a complex well structure, where other partitioners might split wells over several processes after which some well cells have to be remapped (when distributed wells are not allowed).

### CODE REVIEW

**Comment by blattms** [comment]
If there are PRs that need other ones for compilation then please mention those. It helps reviewers and testers saving time finding matching PRs.

I guess this needs OPM/opm-grid#790?

**Comment by michal-toth** [comment]
This branch will compile with master branch of opm-grid too. After all, it is just an extra branch for a runtime parameter.

**Comment by blattms** [comment]
Please write a nice title and description that will help your colleagues that are updating the manual.

**Comment by blattms** [comment]
jenkins build this please

**Comment by blattms** [comment]
Will merge this after another jenkins run.

**Comment by blattms** [comment]
jenkins build this please

**Pull request merged**
