### PR TITLE
Simplify Logic for Exchanging PI/II Values in ACTIONX/WELPI

### PR DESCRIPTION
**Pull request by bska**
This commit switches to using the new guarantees provided by `ActionX::wellpi_wells()` (PR OPM/opm-common#4296), namely that the well names are returned in sorted order on all ranks, to simplify how we exchange the PI/II values.  In particular, given this guarantee, we can calculate the maximum values across all ranks because zero values correspond to missing entries and non-zero values correspond to known entries.

### CODE REVIEW

**Comment by bska** [comment]
I'm creating this PR in draft mode because it depends on the upstream work in PR OPM/opm-common#4296.  I will keep the PR in a draft state until such time as it is ready for review.

**Comment by bska** [comment]
The upstream PR was merged into the master branch.  I'm marking this as "ready for review" and I'm running a  build check.

**Comment by bska** [comment]
jenkins build this serial please

**Review by akva2 — APPROVED** [review]

**Comment by bska** [comment]
PR approved and build check is green.  I'll merge into master.

**Pull request merged**
