### PR TITLE
Tracer rst init

### PR DESCRIPTION
**Pull request by joakim-hove**
Will load and initiialize tracer model from restart vectors. NB: This is code I am not veeeery familiar with, and the implementation is on a strict minimum change basis.

test update: https://github.com/OPM/opm-tests/pull/689

### CODE REVIEW

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by joakim-hove** [comment]
jenkins run norne opm-common=2875 please

**Comment by joakim-hove** [comment]
Comments to this?

The test failure is due to stale data in a NORNE restart file: [https://github.com/OPM/opm-tests/blob/master/norne/restart/NORNE_ATW2013.UNRST] - that particular file is not part of the update data machinery - so that must be updated with a manual PR to opm-tests when this is ready to be merged.

**Comment by joakim-hove** [comment]
jenkins build this opm-common=2875 opm-tests=689 please

**Comment by joakim-hove** [comment]
jenkins build this opm-common=2876 opm-tests=689 please

**Comment by joakim-hove** [comment]
jenkins build this opm-common=2879 opm-tests=689 please

**Comment by joakim-hove** [comment]
Getting the tracer functionality to work 100% with restart has been challenging. This PR along with https://github.com/OPM/opm-common/pull/2879 is a significant step in the right direction, although probably not all the way. I would like to merge this later today.

**Comment by totto82** [comment]
Thanks. The code changes look good. Please merge when green.

**Pull request merged**
