### PR TITLE
Cell Data: Don't Warn About Supported Output Directives

### PR DESCRIPTION
**Pull request by bska**
This commit ensures that we don't issue misleading warning about output creation directives such as

 * `BASIC`
 * `FREQ`
 * `RESTART`

that could be, and typically are, put into keywords like `RPTRST` and `RPTSCHED`.  Previously, we would interpret these directives as names of cell vectors and we would get very confusing diagnostic messages of the form
```
Keyword 'BASIC' is unhandled for output to file
```
which suggests that `BASIC` is unsupported despite the output system supporting the directive for quite some time.  While here, also apply the same reasoning to the vectors we always output such as `SWAT`, `SGAS`, or `PRESSURE`.

### CODE REVIEW

**Comment by bska** [comment]
jenkins build this please

**Comment by bska** [comment]
jenkins build this please

**Comment by bska** [comment]
jenkins build this please

**Comment by bska** [comment]
jenkins build this please

**Comment by bska** [comment]
jenkins build this please

**Comment by bska** [comment]
jenkins build this please

**Comment by atgeirr** [comment]
Looks good, merging!

**Pull request merged**
