### PR TITLE
Provide Simulator's Dynamic CTF in data::Connection

### PR DESCRIPTION
**Pull request by bska**
This is in preparation of implementing the WELPI feature.

### CODE REVIEW

**Comment by bska** [comment]
Note: this PR depends on and must be merged in concert with the upstream PR OPM/opm-common#1995 in the opm-common repository.

**Comment by bska** [comment]
jenkins build this opm-common=1995 please

**Comment by bska** [comment]
jenkins build this opm-common=1995 please

**Comment by bska** [comment]
jenkins build this opm-common=1995 please

**Comment by bska** [comment]
May I solicit a review of this PR please?

**Comment by akva2** [comment]
FWIW it looks fine to me.

**Comment by GitPaean** [comment]
It looks fine to me.

**Comment by bska** [comment]
Two approvals and the upstream PR was already approved.  I am going to merge these into master now.

**Pull request merged**
