### PR TITLE
Add pyaction/PYACTION_WTEST_INSERT_KW.DATA to pyactionComparisons.cma…

### PR DESCRIPTION
**Pull request by lisajulia**
…ke so it is compared with actionx/ACTIONX_WTEST.DATA

### CODE REVIEW

**Comment by lisajulia** [comment]
Needs https://github.com/OPM/opm-tests/pull/1163

**Comment by bska** [comment]
jenkins build this please

**Comment by lisajulia** [comment]
jenkins build this please

**Review by bska — APPROVED** [review]
Very good.  I'll merge into master.

**Pull request merged**
