### PR TITLE
fix building with dunefem

### PR DESCRIPTION
**Pull request by totto82**
We need a test build with dunefem!

### CODE REVIEW

**Comment by totto82** [comment]
jenkins build this please

**Comment by akva2** [comment]
sorry. This is all good. I asked for dune-fem test, markus said he'd do it but never heard back so thought it was all good and thus copy-pasted broken stuff all over..

As for dune-fem, last time i looked into it I struggled to find a release that works fine with dune 2.6 so I gave up. I'll try harder.

**Comment by totto82** [comment]
I use dune 2.7 and always build with dune-fem. Maybe it is time to move to 2.7?

**Comment by akva2** [comment]
move will happen with next debian release which is just around the corner.

**Comment by totto82** [comment]
> This is all good.

I take that as a approval.

**Pull request merged**
