### PR TITLE
Reset Non-Linear Iteration Count Before 'beginTimeStep'

### PR DESCRIPTION
**Pull request by bska**
While here, also fix a couple of misprints in a nearby comment.

### CODE REVIEW

**Comment by bska** [comment]
jenkins build this please

**Comment by totto82** [comment]
For me the test failures looks reasonable if it caused by #3037.  @blattms commented: 

> I was a bit too fast for jenkins. At least I checked the diff and it seem very ok.. Anyway fingers crossed.

Does that mean that Jenkins was not green when #3037 was merged.

**Comment by akva2** [comment]
jenkins wasn't green because he merged before the job finished, but he was lucky in that there were no failures.

**Comment by totto82** [comment]
Thanks for the clarification. Then we need to understand why this fails.

**Comment by totto82** [comment]
I think it should be safe to do a reference update on this, but I will do a manual check on the last two failures to be sure that it does not have unwanted side effects.

**Comment by totto82** [comment]
```
mpi.compareECLFiles_flow+9_4B_WINJ_VREP-W_STW
mpi.compareECLFiles_flow+MOD4_UDQ_ACTIONX
```
has visible changes in the results, but they are qualitatively the same. It shows that NUPCOL impacts the results. I will initiate an update to get this fix in.

**Comment by totto82** [comment]
jenkins build this update_data please

**Comment by bska** [comment]
jenkins build this opm-tests=475 please

**Comment by bska** [comment]
jenkins build this opm-tests=475 please

**Comment by bska** [comment]
New reference solutions have been installed on the CI system.  Merging this now to bring the system back to a consistent state.

**Pull request merged**
