### PR TITLE
put parts of ISTLSolverEbos in separate compile unit

### PR DESCRIPTION
**Pull request by akva2**
in particular this means simulator objects are now not dependent on FlexibleSolver.hpp and BdaBridge.hpp

Sits on top of https://github.com/OPM/opm-simulators/pull/4019

### CODE REVIEW

**Comment by akva2** [comment]
jenkins build this serial please

**Comment by akva2** [comment]
jenkins build this serial please

**Comment by akva2** [comment]
jenkins build this serial please

**Comment by akva2** [comment]
jenkins build this serial please

**Comment by akva2** [comment]
jenkins build this serial please

**Comment by Tongdongq** [comment]
Will do.

**Comment by bska** [comment]
> I had to include `dune/common/unused.hh` in `amgcpr.hh` to make it compile.

Thanks for alerting us to that fact, there really should not be a need to do that.  I've created #4025 to use the C++17 `[[maybe_unused]]` attribute instead of the `DUNE_UNUSED` macro.

**Comment by blattms** [comment]
jenkins build this serial please

**Comment by blattms** [comment]
Sorry, but this needs a rebase...

**Comment by akva2** [comment]
rebased.

**Comment by akva2** [comment]
jenkins build this serial please

**Pull request merged**
