### PR TITLE
[WIP] Perform more analysis of summary regression test failures

### PR DESCRIPTION
**Pull request by akva2**
This adds a script that performs more analysis on a failed summary regression test failure.
It will
  - print number of failed keywords.
  - Print number of levels each keyword failed at.
  - Print maximum deviations for each keyword. 

In particular this is useful as it will check that "old" keywords still pass the test for failures caused by addition of new keyword(s).

The maximum deviations will measure the severity of failures on a per-field basis for human considerations.

Equivalent functionality for the other comparison types will follow but let's shake down the monkeys for this one first.

@alfbr this should cover both cases we discussed on Tuesday.

Requires https://github.com/OPM/opm-output/pull/161

### CODE REVIEW

**Comment by atgeirr** [comment]
This seems useful, is this something I'll typically run myself from the command line, or do you intend to use it from Jenkins etc.?

**Comment by akva2** [comment]
it's all integrated in make test. it's still WIP, i should probably mark it as such (working on it atm).

**Comment by akva2** [comment]
there we go. requires https://github.com/OPM/opm-output/pull/168

i have used this to confirm that https://github.com/OPM/opm-output/pull/167 only has added data, as comparison is now performed for 'old' keywords, ref http://pastebin.com/YhMcfA0p

**Comment by akva2** [comment]
an example of how it looks with a "actual" failure (provoked); http://pastebin.com/m9a1YsMY

**Comment by akva2** [comment]
@alfbr should be ready for your judgement.

**Comment by alfbr** [comment]
Great, I will try to review it today.

**Comment by alfbr** [comment]
Fantastic, this is a huge step forward. Just one question before merge:
The diagnosis (i.e., the output from the scripts) will only be visible on Jenkins I assume. If we can make it available on github too, for ease of inspection, I think that would be of great value. Typically as a message from the jenkins user to a thread where the test is triggered. I am not familiar with the github plugin to jenkins, so no idea how easy it would be to accommodate that in a nice way.

**Comment by akva2** [comment]
There is a yuge (trump style) link added to the pr with build logs, test results broken down on a per test basis, history of test results over time, ..  added to the pr page every time somebody triggers a jenkins build. Inlining all this info on github seems like a lot of work for absolutely no gain when everything is one click away in a nice hiearchical way where somebody else maintains the code for us..

**Comment by alfbr** [comment]
Thanks for the clarification, merging!

**Pull request merged**
