### PR TITLE
change default MinTimeStepBeforeShuttingProblematicWellsInDays to 0.01

### PR DESCRIPTION
**Pull request by totto82**
With the recent improvements in the convergence of the well model the simulator is able to keep alive wells that needs to die. Increasing this parameter will help them die a bit earlier. 

It goes without saying that this needs proper testing before it can be merged. I have tested it on the norne family where it shows good improvement on some of the cases.

### CODE REVIEW

**Comment by totto82** [comment]
benchmark please

**Comment by ytelses** [comment]
Benchmark result overview: 




| Test    | Configuration                              | Relative |
| ------- | ------------------------------------------ | -------- |
| opm-git | OPM Benchmark: flow_mpi_extra - Threads: 1 | 0.998    |
| opm-git | OPM Benchmark: flow_mpi_extra - Threads: 8 | 0.991    |
| opm-git | OPM Benchmark: flow_mpi_norne - Threads: 1 | 0.999    |
| opm-git | OPM Benchmark: flow_mpi_norne - Threads: 8 | 0.991    |
* Speed-up = Total time master / Total time pull request. Above 1.0 is an improvement. *



View result details @ https://www.ytelses.com/opm/?page=result&id=1058

**Comment by totto82** [comment]
@atgeirr @alfbr Any comment on this. Do we want this in the release?

**Comment by atgeirr** [comment]
> Any comment on this. Do we want this in the release?

I think so. Initially this parameter was 0.25, which was far too high, and then it was 0.001 This nudges it back a little, no problem.

**Comment by atgeirr** [comment]
jenkins build this please

**Comment by alfbr** [comment]
> @atgeirr @alfbr Any comment on this. Do we want this in the release?

I think so, but please allow me time to discuss with my colleagues later today. We may want to test this across multiple data sets.

**Comment by alfbr** [comment]
This is fine from our end, feel free to merge.

**Pull request merged**
