### PR TITLE
addd simple salt/brine implementation

### PR DESCRIPTION
**Pull request by trinemykk**
connected to OPM/opm-common#1254 in opm-common, OPM/opm-material#367 in opm-material and OPM/opm-models#583 in opm-models

### CODE REVIEW

**Comment by akva2** [comment]
jenkins build this opm-common=1254 opm-material=367 opm-models=583 please

**Comment by totto82** [comment]
jenkins build this opm-common=1254 opm-material=367 opm-models=583 please

**Comment by totto82** [comment]
benchmark please

**Comment by akva2** [comment]
jenkins build will still fail due to missing installation as i pointed out in the opm-models PR.

**Comment by bska** [comment]
Closing this now since the rebased version of this PR (#2270) was merged into master.

**Pull request closed without merging**
