### PR TITLE
compositional

### PR DESCRIPTION
**Pull request by GitPaean**

### CODE REVIEW

**Comment by GitPaean** [comment]
jenkins build this opm-common=4045 opm-models=901 please

**Comment by GitPaean** [comment]
jenkins build this opm-common=4045 opm-models=901 please

**Comment by bska** [comment]
> opm-common=4045 opm-models=901

For future reference: We usually prefer to trigger multi-repository builds from the most upstream repository&ndash;in this case from opm-common.  The reason is that the CI system, as a cost saving measure, will bypass unit tests in upstream repositories when the build is triggered from a downstream repository.  This is **generally** not what we want although there may of course be special concerns in any one individual situation.

**Comment by GitPaean** [comment]
> For future reference: We usually prefer to trigger multi-repository builds from the most upstream repository–in this case from opm-common. The reason is that the CI system, as a cost saving measure, will bypass unit tests in upstream repositories when the build is triggered from a downstream repository. This is **generally** not what we want although there may of course be special concerns in any one individual situation.

Yes. I was just confirming the compilation error related to `flowexp_comp`.

**Comment by GitPaean** [comment]
Okay. The failure is related to `DamarisWriterType`. Local compilation does not have `HAVE_DAMARIS` enabled.

**Comment by GitPaean** [comment]
jenkins build this opm-common=4045 opm-models=901 please

**Comment by GitPaean** [comment]
PR in opm-common is tested alone.  Triggering the test from here to reproduce the running regression failures.

**Comment by GitPaean** [comment]
I will deal with the upstream PRs in opm-common individually. So the jenkins is triggered here only for this PR. (opm-model PR is tiny and will likely b revised)

**Comment by GitPaean** [comment]
jenkins build this opm-common=4045 opm-models=901 please

**Comment by GitPaean** [comment]
jenkins build this opm-common=4045 opm-models=901 please

**Pull request closed without merging**
