### PR TITLE
Read write perforation rates, pressure, phase reates, and control of wells.

### PR DESCRIPTION
**Pull request by blattms**
With this PR we should finally write all the data of the wells in a parallel run.

Still, we might want to use data::Wells for the gathering in the future. Currently this code in limited to Blackoil.

### CODE REVIEW

**Comment by blattms** [comment]
@akva2 would you mind testing whether you are able to run your parallel tests (#904) with this PR?

**Comment by akva2** [comment]
pass, pass and pass. great work!

**Comment by blattms** [comment]
That is quite a relieve. Thanks for testing.

**Comment by atgeirr** [comment]
Thanks for the patch, and finding the slicing bug! Merging.

**Pull request merged**
