### PR TITLE
changed: print some banners during test comparisons

### PR DESCRIPTION
**Pull request by akva2**
to make output more readable

### CODE REVIEW

**Comment by bska** [comment]
Note: I'm abusing this PR to perform a regression test of the results we'd get if we merge OPM/opm-grid#267

**Comment by bska** [comment]
jenkins run norne spe polymer opm-grid=267 please

**Comment by bska** [comment]
> jenkins run [...]

Hm, that didn't trigger.  Did I do something wrong?

**Comment by akva2** [comment]
weird, i don't see any reason why that wouldn't run. let's try again.

**Comment by akva2** [comment]
jenkins run norne spe polymer opm-grid=267 please

**Comment by atgeirr** [comment]
As the tests this PR were "abused" for were successful it need not remain open for that reason, so I'll merge it now.

**Pull request merged**
