### PR TITLE
Add MultisegmentWellGeneric

### PR DESCRIPTION
**Pull request by akva2**
avoid rebuilding this for all simulators when code  is only dependent on Scalar. specialized for double

Sits on top of https://github.com/OPM/opm-simulators/pull/3348
Downstream of https://github.com/OPM/opm-common/pull/2493

### CODE REVIEW

**Comment by akva2** [comment]
jenkins build this please

**Comment by akva2** [comment]
jenkins build this opm-common=2493 please

**Comment by akva2** [comment]
jenkins build this please

**Comment by akva2** [comment]
jenkins build this please

**Comment by akva2** [comment]
jenkins build this please

**Review by bska — APPROVED** [review]
Looks good to me.  I'll merge this into master now.

**Pull request merged**
