### PR TITLE
Adapt to enum changes

### PR DESCRIPTION
**Pull request by joakim-hove**
Followup to: https://github.com/OPM/opm-common/pull/972

### CODE REVIEW

**Comment by joakim-hove** [comment]
jenkins build this opm-common=972 please

**Comment by joakim-hove** [comment]
jenkins build this opm-common=972 please

**Comment by joakim-hove** [comment]
jenkins build this opm-common=972 please

**Comment by joakim-hove** [comment]
jenkins build this opm-common=972 please

**Comment by bska** [comment]
```
opm/simulators/wells/WellInterface.hpp:32:70: fatal error: opm/parser/eclipse/EclipseState/Schedule/ScheduleEnums.hpp: No such file or directory
```
You've only updated `WellInterface_impl.hpp` in this PR.

**Comment by joakim-hove** [comment]
> You've only updated WellInterface_impl.hpp in this PR.

Hmm - yes you are right; I *have* updated the `WellInterface.hpp` as well - but I must have missed it in git.

**Comment by joakim-hove** [comment]
jenkins build this opm-common=972 please

**Comment by joakim-hove** [comment]
Is master all green now?

**Comment by akva2** [comment]
no. jenkins bump to dune 2.6 has left a few regtest broken + a unit test in opm-grid (i have opened a pr for that one).

**Comment by joakim-hove** [comment]
Ok - thank you.

**Comment by akva2** [comment]
the regtests that broke are due to uninitialized data output by libecl. since this code will be replaced soonish, i suggest we just update and move on for now.

**Comment by GitPaean** [comment]
> mpi.compareECLFiles_flow+SPE1CASE2_OILGAS
> mpi.compareECLFiles_flow+2D_OILWATER_POLYMER

The change of DUNE version can break the two phase case due to different algorithms of inverting a small matrix.

**Comment by akva2** [comment]
i see, so there may be two things at play then.

**Comment by atgeirr** [comment]
> The change of DUNE version can break the two phase cases due to different algorithms of inverting a small matrix.

True, but in this case there have also been observed some valgrind anomalies from libecl. Both sources could contribute.

**Comment by atgeirr** [comment]
I think we should just do an update_data now, but not let the valgrind observation die either.

**Comment by akva2** [comment]
https://github.com/equinor/libecl/pull/651 takes care of the valgrind issue.

**Comment by joakim-hove** [comment]
jenkins build this opm-common=972 please

**Pull request merged**
