### PR TITLE
If deck has keyword NOSIM, simulator should stop.

### PR DESCRIPTION
**Pull request by qilicun**
If ``exit()`` is not good, please make comment for a better solution.

### CODE REVIEW

**Comment by jokva** [comment]
Please don't use the raw deck for this. `IOConfig` has an `initOnly` method you can query.

Somewhat poorly named I suppose, but that can be fixed.

**Comment by atgeirr** [comment]
I will close this, since the feature is already implemented, including the option to override the deck-specified NOSIM (or not) on the command line. See lines 433-438 and 722 in FlowMain.hpp.

**Comment by qilicun** [comment]
@atgeirr You're right, sorry for the noise.

**Comment by atgeirr** [comment]
No problem @qilicun!

**Pull request closed without merging**
