### PR TITLE
Changed to TimeMap api - using std::time_t

### PR DESCRIPTION
**Pull request by joakim-hove**
Downstream of: https://github.com/OPM/opm-parser/pull/1092

### CODE REVIEW

**Comment by atgeirr** [comment]
Looks fine, feel free to merge when upstream is done and tests are green.

Just one tiny condition: make a sanity-test run of SPE1 or something to verify that printed dates remain the same.

**Comment by joakim-hove** [comment]
jenkins build this opm-parser=1092 ewoms=198 please

**Comment by joakim-hove** [comment]
> Just one tiny condition: make a sanity-test run of SPE1 or something to verify that printed dates remain the same.

Of course I can do that - but seriously; we have tests for this?!

**Comment by atgeirr** [comment]
> Of course I can do that - but seriously; we have tests for this?!

No, which is why I asked you to verify it...

**Comment by joakim-hove** [comment]
>> course I can do that - but seriously; we have tests for this?!

>No, which is why I asked you to verify it...

Hopefully we have soon: https://github.com/OPM/opm-output/pull/195

**Comment by joakim-hove** [comment]
> Hopefully we have soon: OPM/opm-output#195

Well - that was a slightly larger job than I though: so although I still think we *should* have such a test I have done a manual sanity check of SPE1 now.

**Comment by atgeirr** [comment]
> Well - that was a slightly larger job than I thought: so although I still think we should have such a test I have done a manual sanity check of SPE1 now.

I agree, and appreciate both the test and the interim manual check! I guess this should be merged, then?

**Pull request merged**
