### PR TITLE
Avoid use of sstream in deferred logger header / macros

### PR DESCRIPTION
**Pull request by akva2**
Instead use {fmt} at callsites where available or simple string::operator+(..).

Waiting for #4292

### CODE REVIEW

**Comment by akva2** [comment]
jenkins build this please

**Comment by akva2** [comment]
let's hold this for @totto82 sanity.

**Comment by akva2** [comment]
jenkins build this please

**Review by bska — APPROVED** [review]
Thanks a lot. I'll merge into master.

**Pull request merged**
