### PR TITLE
Remove NEXTSTEP from Unsupported List

### PR DESCRIPTION
**Pull request by OPMUSER**

### CODE REVIEW

**Comment by OPMUSER** [comment]
@joakim-hove I still cannot get this to work with --enable-tuning=true. I thought the problem was with NEXTSTEP being in the:
[
`/OPM/GitHub/opm-simulators/opm/simulators/utils/UnsupportedFlowKeywords.cpp](url)`

file. So I removed it locally and rebuilt, but I still get the same error message:

```
Error: The keyword NEXTSTEP is not supported in the ACTIONX block
In ACTIONX_NEXTSTEP.DATA line 398.

Error: Problem with keyword NEXTSTEP
In ACTIONX_NEXTSTEP.DATA line 398
The keyword {keyword} is not supported in the ACTIONX block
In {file} line {line}.

Error: Unrecoverable errors were encountered while loading input
```

Any ideas?

Test deck attached.

[ACTIONX_NEXTSTEP.zip](https://github.com/OPM/opm-simulators/files/7690386/ACTIONX_NEXTSTEP.zip)

**Comment by OPMUSER** [comment]
Yea, I know I sent this via  https://github.com/OPM/opm-common/pull/2892 as well, but I never saw an email and I was not sure if the PR was closed what would happen. I have deleted the comments from 2892.

**Comment by OPMUSER** [comment]
Still waiting on this to be merged. 

@joakim Also how do you set an alias for a keyword? For example, NEXT is an alias for NEXTSTEP.

**Comment by joakim-hove** [comment]
> Also how do you set an alias for a keyword? For example, NEXT is an alias for NEXTSTEP.

We do not have a fully general system for aliases - but https://github.com/OPM/opm-common/pull/2902 should handle the specific situation

**Comment by OPMUSER** [comment]
Did you merge #3736 to make NEXTSTEP active in master?

**Comment by joakim-hove** [comment]
> Did you merge #3736 to make NEXTSTEP active in master?

I'll do it now. But this will not change very much - the only effect of merging this PR is that a (misleading IMO) warning is removed.

**Pull request merged**
