### PR TITLE
Refactor of connections & completions

### PR DESCRIPTION
**Pull request by joakim-hove**
See: OPM/opm-common#426

Trivial rename

### CODE REVIEW

**Comment by joakim-hove** [comment]
jenkins build this opm-grid=330 ewoms=328 opm-common=421 please

**Comment by akva2** [comment]
maybe want to do the same ^^ to commit message.

**Comment by joakim-hove** [comment]
jenkins build this opm-grid=330 ewoms=328 opm-common=426 please

**Comment by joakim-hove** [comment]
OK - this is *pure rename*; I will self merge this chain tomorrow.

**Pull request merged**
