### PR TITLE
Add integration test for reporforated norne model

### PR DESCRIPTION
**Pull request by joakim-hove**
Based on: https://github.com/OPM/opm-tests/pull/380/

### CODE REVIEW

**Comment by joakim-hove** [comment]
jenkins build this opm-common=2042 update_data please

**Comment by joakim-hove** [comment]
jenkins build this update data please

**Comment by joakim-hove** [comment]
jenkins build this update data please

**Comment by joakim-hove** [comment]
jenkins build this update data please

**Comment by joakim-hove** [comment]
jenkins build this update data please

**Comment by alfbr** [comment]
I confirm that this test case is now correct in Flow, so this can be merged. Thanks a lot for the effort!

**Comment by akva2** [comment]
here, have a free complementary underscore.

**Comment by joakim-hove** [comment]
> here, have a free complementary underscore.

:-)

Question: When completely different files are changed we can have multiple opm-tests PR's in flight simultaneously?

**Comment by joakim-hove** [comment]
jenkins build this update_data please

**Comment by akva2** [comment]
aye. as long as they don't conflict, it's no problem.

**Comment by joakim-hove** [comment]
jenkins build this opm-tests=423 please

**Pull request merged**
