### PR TITLE
Replace well switching logger

### PR DESCRIPTION
**Pull request by fgfuchs**
Replace well switching logger with the more general deferred logger functionality

### CODE REVIEW

**Comment by andlaus** [comment]
does this fix #1703? if yes. +1 from my side!

**Comment by atgeirr** [comment]
> does this fix #1703? if yes. +1 from my side!

It is not intended to make any behaviour changes, as the WellSwitchingLogger is used correctly (if not in the way we may want it to). Next stop for this line of work is making all other logging in the well code correct in the parallel setting, changing behaviour as requested in #1703 will be a separate thing.

**Comment by atgeirr** [comment]
jenkins build this please

**Comment by atgeirr** [comment]
jenkins build this serial please

**Comment by blattms** [comment]
benchmark

**Comment by fgfuchs** [comment]
I think I have a couple more changes that are necessary...

**Comment by atgeirr** [comment]
@blattms do you expect that communicating strings rather than just flags will have a measurable performance impact, or are you mostly using this PR to test the benchmarking system?

**Comment by atgeirr** [comment]
Since there were no further comments, discussion or issues I will merge this now. Thanks!

**Pull request merged**
