### PR TITLE
Output solvent saturation

### PR DESCRIPTION
**Pull request by totto82**
This PR moves Compat.hpp to opm-simulators and modifies it to store SSOL if present. 

This PR supersedes #835

### CODE REVIEW

**Comment by akva2** [comment]
shall i assume this goes in before my work and rebase accordingly ?

**Comment by atgeirr** [comment]
> shall i assume this goes in before my work

I think that is probably the easiest, so yes (yell if you disagree).

**Comment by akva2** [comment]
not problem, i have (temporarily) rebased this on @totto82 branches, but it seems there will be changes to the infrastructure invalidating the actual changes in any case.

**Comment by atgeirr** [comment]
jenkins build this opm-output=94 opm-core=1071 please

**Comment by atgeirr** [comment]
jenkins build this opm-core=1071 please

**Comment by atgeirr** [comment]
Apparently I merged this too quickly, as I assumed the jenkins test I ran was sufficient. It was not, since it did not include the opm-upscaling module (that makes sense, since the module is not related to opm-upscaling as either upstream or downstream), and there is a file there that needs to be updated. I assume that had I ran the check from opm-core I would have seen this. Correct, @akva2?

The problem now is that we have moved a file to here that I did not realize was used in opm-upscaling. Not sure what is the best long term solution, nor what is the best short-term solution.

In the short term we may revert the PRs, but that is always messy. @akva2 since you are maintainer of the module I broke, I leave that decision to you: revert this and OPM/opm-core#1071 if you think that is the best solution.

I promise to try to resolve this tomorrow.

**Comment by totto82** [comment]
Maybe my first solution of moving BlackoilSolventSolutionState to opm-core would have been better.

**Comment by alfbr** [comment]
It sounds like this is an issue that should be resolved outside opm-core, please consider spending the necessary efforts to land a long term solution.

**Comment by atgeirr** [comment]
> Maybe my first solution of moving BlackoilSolventSolutionState to opm-core would have been better.

In the long run I don't think so. Will find a fix.

**Comment by atgeirr** [comment]
A quick fix has been proposed in OPM/opm-upscaling#203.

**Comment by akva2** [comment]
@atgeirr correct, opm-upscaling is a downstream of opm-core, opm-core is an upstream of opm-simulators but opm-upscaling is not a downstream of opm-simulators.

**Pull request merged**
