### PR TITLE
Added more cases/models to the regression test. 

### PR DESCRIPTION
**Pull request by kristfho**
A regression test have been added for the two cases SPE1CASE2 and SPE3CASE1. For this to work, the reference solutions must be updated (in this [PR](https://github.com/OPM/opm-data/pull/121) ).

### CODE REVIEW

**Comment by kristfho** [comment]
Ready for review. Should be merged after OPM/opm-common#161.

**Comment by pgdr** [comment]
jenkins build this opm-common=161 please

**Comment by atgeirr** [comment]
jenkins build this opm-common=161 please

**Comment by akva2** [comment]
replaced by #821

**Pull request closed without merging**
