### PR TITLE
Mark PINCH option 2 NOGAP as fully supported.

### PR DESCRIPTION
**Pull request by blattms**
All the test cases that were provided to me are actually already supported by current master.

### CODE REVIEW

**Comment by blattms** [comment]
jenkins build this please

**Comment by blattms** [comment]
I will double check this.

**Comment by blattms** [comment]
jenkins build this please

**Comment by blattms** [comment]
:see_no_evil: I benchmarked the wrong PR. Oh my....

**Comment by ytelses** [comment]
Benchmark result overview: 




| Test    | Configuration                              | Relative |
| ------- | ------------------------------------------ | -------- |
| opm-git | OPM Benchmark: drogon - Threads: 1         | 1.001    |
| opm-git | OPM Benchmark: drogon - Threads: 8         | 1.116    |
| opm-git | OPM Benchmark: smeaheia - Threads: 1       | 0.914    |
| opm-git | OPM Benchmark: smeaheia - Threads: 8       | 1.077    |
| opm-git | OPM Benchmark: spe10_model_1 - Threads: 1  | 0.993    |
| opm-git | OPM Benchmark: spe10_model_1 - Threads: 8  | 1.003    |
| opm-git | OPM Benchmark: flow_mpi_extra - Threads: 1 | 1.01     |
| opm-git | OPM Benchmark: flow_mpi_extra - Threads: 8 | 1.033    |
| opm-git | OPM Benchmark: flow_mpi_norne - Threads: 1 | 0.999    |
| opm-git | OPM Benchmark: flow_mpi_norne - Threads: 8 | 0.987    |
* Speed-up = Total time master / Total time pull request. Above 1.0 is an improvement. *



View result details @ https://www.ytelses.com/opm/?page=result&id=2082

**Pull request merged**
