### PR TITLE
Fixing vfp related running with flow_ebos

### PR DESCRIPTION
**Pull request by GitPaean**
the output of the THP is still not yet correct, and not sure how it got broken.

### CODE REVIEW

**Comment by GitPaean** [comment]
jenkins run spe norne polymer please

**Comment by GitPaean** [comment]
Not sure if it is the correct way to fix the problem and I am not aware of the motivation of moving the wellModel().init() from BlackoilEbos to Simulator side.

**Comment by GitPaean** [comment]
jenkins run spe norne polymer please

**Comment by atgeirr** [comment]
All green, going in!

**Pull request merged**
