### PR TITLE
Use the failure flag of the tasklet runner to detect a failure while …

### PR DESCRIPTION
**Pull request by lisajulia**
…writing output and throw an error if that happens.

### CODE REVIEW

**Comment by lisajulia** [comment]
jenkins build this opm-models =909 please

**Comment by lisajulia** [comment]
@bska: Can you have a look here? Thanks!

**Comment by lisajulia** [comment]
jenkins build this please

**Review by bska — APPROVED** [review]
This is good and I'll merge into master.  We do need to take the next step of guarding the call to `doWriteOutput()` at some point, but that can be follow-up work.

**Pull request merged**
