### PR TITLE
Removed use of explicit regular falsi. Use the standard solver

### PR DESCRIPTION
**Pull request by hnil**
Removed two implementations of regular falsi in the same file.
Changed to use the standard solver also used in the wellmodel handeling.

### CODE REVIEW

**Comment by GitPaean** [comment]
I requested @bska to review this. I think he has better view about the equilibration.

**Comment by bska** [comment]
jenkins build this please

**Comment by hnil** [comment]
We could tighten the tolerances. The problem with the original was that it could be extreem. To be even more safe we could only check s1-s0 not accept answeres where  f(s) is small. In anycase if difference in saturations initialization of 1e-10 matters for the results, the simulation is in trouble.. It may ofcoarse be that the answere was realy uncertation due to using f(s) as stopping criteria..

**Comment by hnil** [comment]
This pullrequest get a large field case work independent of processor number however it will change most result slightly. But the problem is quite generic since this problem is the "worst of all" for regular falsi approach. What is need to get it merged? The difference between processor numbers  should be attacked by communicating the range of the ode to be solved for initialization in as a separate issue

**Comment by bska** [comment]
> What is need to get it merged?

Well, technically we just need to update the reference data.  However, the model 2 changes&mdash;while nominally small&mdash;for most of the cases I checked should be reviewed more closely.  There's been quite a bit of effort lately to ensure that we reproduce ECLIPSE's results for those and I don't want to just discount the new differences out of hand.

I'm also a little concerned that the [Norne pore-volume test](https://ci.opm-project.org/job/opm-simulators-PR-builder/942/testReport/junit/(root)/mpi/comparePORV_flow_NORNE_ATW2013/) now fails.  I would expect that to be unaffected by our fluid-initially-in-place calculation.  I'll try to rerun the build check, but we may need to at least rebase this onto current master if it isn't already so.

**Comment by bska** [comment]
jenkins build this please

**Comment by atgeirr** [comment]
Rerunning the test after the merging of OPM/opm-common#1782

**Comment by atgeirr** [comment]
jenkins build this please

**Comment by GitPaean** [comment]
jenkins build this please

**Comment by GitPaean** [comment]
jenkins build this please

**Comment by GitPaean** [comment]
I am checking result for the failed cases.

**Comment by GitPaean** [comment]
benchmark please

**Comment by GitPaean** [comment]
@alfbr , would you mind to trigger a performance benchmark for this PR? Thanks.

**Comment by alfbr** [comment]
benchmark please

**Comment by alfbr** [comment]
> @alfbr , would you mind to trigger a performance benchmark for this PR? Thanks.

Doesn't matter if it is me or you, there is some limit on the Github API that causes it to stop. Hopefully fixed now.

**Comment by GitPaean** [comment]
benchmark please

**Comment by ytelses** [comment]
Benchmark result overview: 




| Test    | Configuration                              | Relative |
| ------- | ------------------------------------------ | -------- |
| opm-git | OPM Benchmark: flow_mpi_extra - Threads: 1 | 0.946    |
| opm-git | OPM Benchmark: flow_mpi_extra - Threads: 8 | 1.127    |
| opm-git | OPM Benchmark: flow_mpi_norne - Threads: 1 | 1.051    |
| opm-git | OPM Benchmark: flow_mpi_norne - Threads: 8 | 0.954    |
* Speed-up = Total time master / Total time pull request. Above 1.0 is an improvement. *



View result details @ https://www.ytelses.com/opm/?page=result&id=873

**Comment by ytelses** [comment]
Benchmark result overview: 




| Test    | Configuration                              | Relative |
| ------- | ------------------------------------------ | -------- |
| opm-git | OPM Benchmark: flow_mpi_extra - Threads: 1 | 0.969    |
| opm-git | OPM Benchmark: flow_mpi_extra - Threads: 8 | 1.122    |
| opm-git | OPM Benchmark: flow_mpi_norne - Threads: 1 | 1.033    |
| opm-git | OPM Benchmark: flow_mpi_norne - Threads: 8 | 0.965    |
* Speed-up = Total time master / Total time pull request. Above 1.0 is an improvement. *



View result details @ https://www.ytelses.com/opm/?page=result&id=874

**Comment by alfbr** [comment]
Finally the results are in. There are significant effects on performance here. Interesting too see that there are both improvements and degradations. Great if we could have one without the other :-)

**Comment by atgeirr** [comment]
@GitPaean This must be updated since you merged the temporary fix.

**Comment by atgeirr** [comment]
Noticed that I asked the wrong person to rebase, sorry @GitPaean.

After discussion with @hnil I will rebase this, and make a new PR.

**Comment by bska** [comment]
I'm closing this now since the rebased PR #2800 was merged in its place.

**Pull request closed without merging**
