### PR TITLE
Add UDQ_WCONPROD model to integration testing

### PR DESCRIPTION
**Pull request by joakim-hove**
When https://github.com/OPM/opm-common/pull/870 is merged I consider the UDQ/UDA features sufficiently mature to enable integration testing. Some random plots shown below - more can be provided.

Although I am probably the most trigger happy self-merger around I will *not* push this one in - but I sincerely hope someone else will do!

PS: When this is in I might go and get really drunk - this has been a long haul.

Figure_1
Figure_2
Figure_3
Figure_4

### CODE REVIEW

**Comment by joakim-hove** [comment]
jenkins build this opm-common=870 please

**Comment by GitPaean** [comment]
to me, the results are good. The difference are from different time step size.  Is there a TUNING setup in the deck?

**Comment by joakim-hove** [comment]
> Is there a TUNING setup in the deck?

This is the [UDQ_WCONPROD](https://github.com/OPM/opm-tests/blob/master/udq_actionx/UDQ_ACTIONX.DATA) deck from opm-tests - does not contain a TUNING keyword.

**Comment by GitPaean** [comment]
> This is the UDQ_WCONPROD deck from opm-tests - does not contain a TUNING keyword.

okay. it is the default time stepping different between OPM and the commercial simulator.

**Comment by GitPaean** [comment]
OPM/opm-common#870 does not depend on this PR, while this PR depends on OPM/opm-common#870 . you need to get OPM/opm-common#870 in first. 

Probably a update_data will be required.

**Comment by GitPaean** [comment]
I do not understand why the jenkins is happy although there is no reference result there yet.

**Comment by joakim-hove** [comment]
Many master is used to control the tests?

**Pull request merged**
