### PR TITLE
Add test based on ACTIONX

### PR DESCRIPTION
**Pull request by joakim-hove**
The ACTIONX testcase has for a long time been in opm-tests - but it is not run?

### CODE REVIEW

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by joakim-hove** [comment]
jenkins build this update_data please

**Comment by joakim-hove** [comment]
jenkins build this update_data please

**Comment by joakim-hove** [comment]
jenkins build this opm-tests=288 please

**Comment by joakim-hove** [comment]
Can this be merged?

**Comment by akva2** [comment]
moar tests, more good. yes.

**Pull request merged**
