### PR TITLE
removing some whitespaces

### PR DESCRIPTION
**Pull request by GitPaean**
mostly to test the master branch with jenkins.

### CODE REVIEW

**Comment by GitPaean** [comment]
jenkins build this please

**Comment by GitPaean** [comment]
```
/opm-simulators/tests/DuneIstlTestHelpers.hpp:59:33: warning: extra ‘;’ [-Wpedantic]
 BOOST_GLOBAL_FIXTURE(MPIFixture);
```

Warning on my machine. But If I removed the `;`, it became a failure in jenkins.

**Comment by GitPaean** [comment]
Hi, @atgeirr , the master branch looks fine.  I am not sure what is the difference of this test and the test from what you refereed to.

**Comment by bska** [comment]
>  the master branch looks fine.

Not really: https://ci.opm-project.org/job/opm-simulators/529/testReport/

**Comment by GitPaean** [comment]
> Not really: https://ci.opm-project.org/job/opm-simulators/529/testReport/

Yes. That is my question.  Is https://ci.opm-project.org/job/opm-simulators-PR-builder/945/  testing the same thing with that report? Maybe that test was carried fore the https://github.com/OPM/opm-tests/pull/22 was merged. Now the master branch looks like okay as shown in https://ci.opm-project.org/job/opm-simulators-PR-builder/945/

**Comment by atgeirr** [comment]
To test if jenkins job 529 was misleading I started another build there, we'll see.

**Comment by atgeirr** [comment]
It seems opm-simulators is ok, and job 529 was misleading. I'll merge this, though. No need to let a good fix go to waste...

**Pull request merged**
