### PR TITLE
use specialized fluidstate in the aquifer model

### PR DESCRIPTION
**Pull request by totto82**
Depends on OPM/ewoms#404

### CODE REVIEW

**Comment by totto82** [comment]
jenkins build this opm-material=312 ewoms=404

**Comment by totto82** [comment]
jenkins build this opm-material=312 ewoms=404 please

**Comment by andlaus** [comment]
ah, this fixes the jenkins complaint in OPM/ewoms#404. if nobody objects or presses green first, I'll merge tomorrow.

**Comment by andlaus** [comment]
okay, seems like nobody raised their voice, so everybody is probably going to forever hold their peace in this regard.

**Pull request merged**
