### PR TITLE
SimulatorFullyImplicitBlackoilEbos: rename to SimulatorFullyImplicitBlackoil

### PR DESCRIPTION
**Pull request by akva2**
And yet another class

### CODE REVIEW

**Comment by akva2** [comment]
jenkins build this please

**Comment by akva2** [comment]
jenkins build this please

**Review by bska — COMMENTED** [review]
Weird.  The `SimulatorFullyImplicitBlackoil.cpp` file was renamed without changes.  Do we not include the associate header in that file?

**Comment by bska** [comment]
> There is only a few free functions in there

Right, but aren't these then, technically, built without a declaration in scope?

> and if we include the header we would pull in everything and the kitchen sink unnecessarily.

I appreciate that.  Maybe we could have a separate header for just the two free functions?

**Comment by akva2** [comment]
Lacking definition is not really a problem for the duck when it comes to free functions But we absolutely can rename and add a separate header, it just did not end up that way. Suggested file name?

**Comment by bska** [comment]
> Lacking definition is not really a problem for the duck when it comes to free function

Sorry, I don't understand what you mean by "duck" here.

> But we absolutely can rename and add a separate header, it just did not end up that way. Suggested file name

Cool.  How about `SimulatorReportBanners.[hc]pp`?  Tangentially, function `outputTimestampFIP()` appears to be unused now.  The only references I can find to that function are in the header and `.cpp` file being renamed here.

**Comment by akva2** [comment]
Hahaha. That's what happens when you write with one arme while playing with your 4 year old with the other. s/duck/linker/g

**Comment by akva2** [comment]
jenkins build this please

**Review by bska — APPROVED** [review]
Excellent.  Thanks a lot for the updates.  This looks good to me now and I'll merge into master.

**Pull request merged**
