### PR TITLE
Use new EquilRecord from opm-common

### PR DESCRIPTION
**Pull request by joakim-hove**
Followup to: https://github.com/OPM/opm-common/pull/1035

See alternative: #2019

### CODE REVIEW

**Comment by joakim-hove** [comment]
I would like to merge this and:  OPM/opm-common#1035 - comments?

**Comment by bska** [comment]
> I would like to merge this and: [OPM/opm-common#1035](https://github.com/OPM/opm-common/pull/1035) - comments?

Just one.  The new `EquilRecord` constructor has the signature
```C++
EquilRecord(double, double, double, double, double, double, bool, bool, int);
```
I worry that that will be very hard to use correctly and very easy to use incorrectly.  At minimum, all clients/call-sites will have to refer very closely to the declaration of `EquilRecord` to ensure that object is correctly formed.

How many locations do we expect to create `EquilRecord` objects from?

**Comment by joakim-hove** [comment]
> How many locations do we expect to create EquilRecord objects from?

*Two*; the main location is [here]( https://github.com/OPM/opm-common/blob/master/src/opm/parser/eclipse/EclipseState/InitConfig/Equil.cpp) - that should ideally have been private - and the only `EquilRecord` instantiaton - but in addition there is one instantiation here in this test. This test is somewhat awkward because the test is created directly with SI data (i.e. you can not easily embed a test deck and parse it), and at the same time it uses quite low level structures.  

I agree that the current signature is easy to get wrong, but it is at least not any worse than the current approach based on manually crafted `DeckRecord` instance with "wrong" dimensions.

**Comment by joakim-hove** [comment]
> Maybe we can use this opportunity to actually make it private? E.g.,

Yes - that looks like good solution.

> I think that might even solve the "embed testable dataset" problem.

I don't really see how that will help with the testdata problem; the testdata problem is not particularly large - it is *just* to create a deck with inputs manually. I'll do that.

**Comment by joakim-hove** [comment]
OK - I'll close this now; and instead redirect to #2019 - which is kind of funny, but gets the job done.

**Comment by joakim-hove** [comment]
> OK - I'll close this now; 

I'll reopen this and beg on my knees that this can be merged as is. I agree it is not very nice; I still think it is an improvement of the current state - and something must be done in order to merge OPM/opm-common#1021.

The alternative approach in #2020 failed in mysterious ways; think it was due to multiple instances of the `ebos/vanguard` structure - something I was not exactly thrilled by going into.

**Comment by atgeirr** [comment]
I agree this is still nicer than the master, so I'll merge as requested.

**Pull request merged**
