### PR TITLE
Communicate well rates by directly iterating over container

### PR DESCRIPTION
**Pull request by joakim-hove**
The purpose of this change is to simplify change of container used for wellrates (`std::map<std::string, T> -> WellContainer<T>`) in a subsequent PR.

### CODE REVIEW

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by joakim-hove** [comment]
> Why not simply refactor the functors to prevent code duplication?

yes that would have been a possibility - and maybe a better choice. The reason I did it the way I did was that I need to take multiple baby steps in order to keep control; and this way of doing it enabled smaller steps.

**Comment by blattms** [comment]
I think this broke distributed wells. At least I cannot see that rates for wells that are not owned are neglected. This happened in the else branch and you chose to remove the if-else branches for whatever reasons.

**Comment by blattms** [comment]
The else branch disregards the calculated well rates and calls the functor with zero rates.

**Comment by joakim-hove** [comment]
> I think this broke distributed wells.

Are you saying this because a case is now failing - or mainly from code inspection.

> At least I cannot see that rates for wells that are not owned are neglected.

That I disagree - in the second loop there is an `if (owner)` check, and in the case owner is false zero is used explicitly.

**Pull request merged**
