### PR TITLE
changed: probe for cl/opencl.hpp and use if found

### PR DESCRIPTION
**Pull request by akva2**
this to avoid a spam of warnings

### CODE REVIEW

**Comment by akva2** [comment]
jenkins build this please

**Comment by akva2** [comment]
jenkins build this please

**Comment by akva2** [comment]
jenkins build this please

**Comment by akva2** [comment]
jenkins build this please

**Comment by akva2** [comment]
i tried to provide vexcl/amgcl on jenkins but it has the same issue of including cl/cl.hpp so it's not doable without patching.

**Comment by akva2** [comment]
jenkins build this please

**Comment by akva2** [comment]
jenkins build this please

**Review by blattms — COMMENTED** [review]
Thanks. Looks good.

I was aware of that but could not find the motivation to fix it yet (I'm blaming NVIDIA for that :wink:, it makes feel a little like Linus sometimes :wink:).

**Pull request merged**
