### PR TITLE
add vapwat to gaswater simulators and output mol fractions YMFWAT

### PR DESCRIPTION
**Pull request by totto82**

### CODE REVIEW

**Comment by totto82** [comment]
jenkins build this please

**Comment by totto82** [comment]
jenkins build this opm-common=3404 please

**Comment by totto82** [comment]
jenkins build this opm-common=3404 please

**Comment by totto82** [comment]
jenkins build this opm-common=3404 please

**Comment by totto82** [comment]
jenkins build this opm-common=3404 please

**Review by bska — APPROVED** [review]
Thanks.  I'll merge into master.

**Comment by OPMUSER** [comment]
@totto82 What is YMFWAT and where is the output sent? There is nothing in the print file, init file, restart file, or summary file.

I ran @goncalvesmachadoc test case CO2STORE_GASWAT.DATA with `EnableOpmRstFile="true" # default: "0"`

**Comment by totto82** [comment]
It is the mol fraction of water in the gas phase. You will need to enable VAPWAT in the deck for water to vaporize. (and yes you need enable-opm-rst-file=true for it to be outputted to the restart file.   So it is similar as XMFCO2 (mol fraction of CO2 in water phase)

**Comment by OPMUSER** [comment]
@totto82 I set up a test case, attached, but I keep on getting:

```
Current Working Directory  /media/sf_D_DRIVE/Linux/OPM/OPM-TESTS-DBX/co2store
flow --parameter-file=CO2STORE_GASWAT-02.param | tee CO2STORE_GASWAT-02.LOG
Running /home/david/OPM/GitHub/opm-simulators/build/bin/flow
Program threw an exception: Could not initialize the problem: Cannot initialise: when no explicit RVWVD table is given,
datum depth must be at the gas-oil-contact. In EQUIL region 1 (counting from 1), this does not hold.
Failed: 3437
```
Note RVWVD is in the deck:

```
--                                                                              
--       WATER VAPOR RATIO VS DEPTH (OPM FLOW KEYWORD)       
--
--       DEPTH    RVW                                                
--                STB/MSCF                                                  
--       ------   --------                                                               
RVWVD            
         1000.0   0.001     
         3000.0   0.001                                      / RVW VS DEPTH EQUIL REGN 01 
```

I also ran GASWATER_VAPWAT_PRECSALT.DATA in the spe1_precsalt directory and didn't get the mole fractions on the restart file.

Both jobs were run sequentially as opposed to parallel.

**Comment by totto82** [comment]
Did you set item 12 in EQUIL to 1?

**Comment by totto82** [comment]
You will have to add DISGASW for the flow executable to pick the right version. I will make a PR with a fix.

**Comment by OPMUSER** [comment]
@totto82 That worked, thanks.

**Pull request merged**
