### PR TITLE
for the cells having zero thickness we use the cell center depth to do the equilibration

### PR DESCRIPTION
**Pull request by GitPaean**
In the targeting case, those cells happen to be numerical aquifer cells. 

The approach was along the direction suggested by @bska

### CODE REVIEW

**Review by bska — COMMENTED** [review]
I think this makes sense.  I **suppose** we could bypass the accumulation loop altogether for zero-thickness cells using code like
```C++
if (cellZSpan_[cell].second > cellZSpan_[cell].first) {
    // do accumulation
}
else {
    // fall back to centre point approach
}
```
but this is a good compromise.  Moreover, zero-thickness cells are unlikely to be plentiful in most models so the above is probably not worth the additional complexity.

Would you mind adding a comment to the `else` branch to say something like
```C++
// Fall back to centre point method for zero-thickness cells.
```
to make it clear that we're dealing with a very special case?

**Comment by bska** [comment]
jenkins build this please

**Comment by GitPaean** [comment]
Thanks for the comments. I was also thinking the approach you mentioned.  Since you agree that the current way is acceptable, let us get in.

**Comment by GitPaean** [comment]
jenkins build this please

**Review by bska — APPROVED** [review]
Thanks for the updates and for analysing the underlying issue.  I'll merge this into master now.

**Pull request merged**
