### PR TITLE
Added working PINCH test cases as regressions.

### PR DESCRIPTION
**Pull request by akva2**
This hopefully will prevent breaking things when further work for PINCH is done.

The following tests are still known to fail with current master: T2A_NOPINCH T2A_GAP T2A_NOGAP T4A1_NOGAP T4A1_GAP

Fixed version of https://github.com/OPM/opm-simulators/pull/4671

### CODE REVIEW

**Comment by akva2** [comment]
jenkins build this update_data please

**Comment by akva2** [comment]
jenkins build this opm-tests=981 please

**Comment by akva2** [comment]
jenkins build this update_data please

**Comment by akva2** [comment]
jenkins build this opm-tests=981 please

**Comment by akva2** [comment]
i'm going to do some testing using this PR (to simplify the process).

**Comment by akva2** [comment]
jenkins build this update_data please

**Comment by bska** [comment]
> i'm going to do some testing using this PR (to simplify the process).

Okay.  Would you mind setting the PR to "draft" state until you've completed your testing, please?

**Comment by akva2** [comment]
jenkins build this update_data please

**Comment by akva2** [comment]
jenkins build this opm-tests=981 please

**Comment by bska** [comment]
The new reference solutions have been installed on the CI system.  Merging this now to activate the regression tests.  Thanks a lot for expanding our test suite to include PINCH.

**Pull request merged**
