### PR TITLE
Removed stale test code

### PR DESCRIPTION
**Pull request by joakim-hove**
Debug code which has long ago served it's purpose.

### CODE REVIEW

**Comment by atgeirr** [comment]
Are these no longer useful for debugging purposes? Do they no longer run? I think we will still need to investigate issues related to grid topology, grid geometry, transmissibilities etc.

**Comment by joakim-hove** [comment]
> Are these no longer useful for debugging purposes?

I think no; has anyone other than me used it?

**Comment by atgeirr** [comment]
I thought they were used for debugging the transmissibility issues by @totto82 and @andlaus but I might be mistaken.

**Comment by totto82** [comment]
I have not used them.

**Pull request merged**
