### PR TITLE
fixed: missing TEST_ARGS in test specifications

### PR DESCRIPTION
**Pull request by akva2**
Thus these options have had no effect.

### CODE REVIEW

**Comment by akva2** [comment]
jenkins build this update_data please

**Comment by akva2** [comment]
jenkins build this failure_report please

**Comment by akva2** [comment]
jenkins build this opm-tests=1235 please

**Comment by bska** [comment]
Good catch&ndash;I missed this in #4520...  In any case, the new reference solutions have been installed on the CI system so I'll merge this PR into the master branch.

**Pull request merged**
