### PR TITLE
Added missing global sum for FIP totals.

### PR DESCRIPTION
**Pull request by blattms**
I missed this in PR #1001

### CODE REVIEW

**Comment by andlaus** [comment]
thanks. in flow_ebos you do not need to resort to the `parallelISTLInformation` can also use `grid_.comm()` because the grid is always a Dune grid. do you want to have it merged as-is or do you prefer to change this?

**Comment by atgeirr** [comment]
I'd like to keep it as is for now, for commonality between the ebos-legacy codes. Eventually we might do a refactoring of this, sounds like it could be a big simplification at some point.

**Comment by blattms** [comment]
Why is `grid_.comm()` any simpler than `pinfo.communicator()`?

**Comment by andlaus** [comment]
its not simpler, but it is one abstraction less. (also, creating the `pinfo` object may cause some headaches in the future.)

**Pull request merged**
