### PR TITLE
Pass the salt concentration to the water PVT

### PR DESCRIPTION
**Pull request by totto82**
This must be merged together with OPM/opm-material#423

I have also added BDENSITY and SALTVD to the missing feature list. They are only partially implemented and never used.

### CODE REVIEW

**Comment by totto82** [comment]
jenkins build this opm-material=423 please

**Comment by totto82** [comment]
The test failure is expected. The brine test only inject salt for a small time so the effect is minimal. I have also tested an example where the salt changes the water pvt more and results look reasonable.

**Comment by totto82** [comment]
jenkins build this update_data please

**Comment by totto82** [comment]
I want to self merge this and the opm-material changes later today if nobody objects. It fixes bug in the brine model and should not affect the rest of the code.

**Comment by totto82** [comment]
jenkins build this opm-tests=346 please

**Comment by totto82** [comment]
jenkins build this opm-material=423 update_data please

**Comment by bska** [comment]
jenkins build this opm-material=423 opm-tests=347 please

**Comment by totto82** [comment]
jenkins build this opm-material=423 opm-tests=347 please

**Comment by bska** [comment]
I'm merging this now.  Thanks a lot.

**Pull request merged**
