### PR TITLE
only compute guiderates at the beginning of a timestep

### PR DESCRIPTION
**Pull request by totto82**
This will need some more testing before it can be considered for merging.

### CODE REVIEW

**Comment by totto82** [comment]
jenkins build this please

**Comment by totto82** [comment]
benchmark please

**Comment by ytelses** [comment]
Benchmark result overview: 




| Test    | Configuration                                     | Relative |
| ------- | ------------------------------------------------- | -------- |
| opm-git | OPM Benchmark: flow_mpi_extra - Threads: 1        | 1.007    |
| opm-git | OPM Benchmark: flow_mpi_extra - Threads: 8        | 1.004    |
| opm-git | OPM Benchmark: flow_mpi_norne - Threads: 1        | 1.004    |
| opm-git | OPM Benchmark: flow_mpi_norne - Threads: 8        | 1.022    |
| opm-git | OPM Benchmark: flow_mpi_norne_4c_msw - Threads: 1 | 0.993    |
| opm-git | OPM Benchmark: flow_mpi_norne_4c_msw - Threads: 8 | 0.997    |
* Speed-up = Total time master / Total time pull request. Above 1.0 is an improvement. *



View result details @ https://www.ytelses.com/opm/?page=result&id=1113

**Comment by totto82** [comment]
jenkins build this please

**Comment by totto82** [comment]
jenkins build this please

**Comment by totto82** [comment]
benchmark please

**Comment by totto82** [comment]
I have manually checked the results and they look fine. There are differences in the "eyeball norm" but they are minor.

**Comment by ytelses** [comment]
Benchmark result overview: 




| Test    | Configuration                                     | Relative |
| ------- | ------------------------------------------------- | -------- |
| opm-git | OPM Benchmark: flow_mpi_extra - Threads: 1        | 0.994    |
| opm-git | OPM Benchmark: flow_mpi_extra - Threads: 8        | 1.004    |
| opm-git | OPM Benchmark: flow_mpi_norne - Threads: 1        | 0.994    |
| opm-git | OPM Benchmark: flow_mpi_norne - Threads: 8        | 1.012    |
| opm-git | OPM Benchmark: flow_mpi_norne_4c_msw - Threads: 1 | 0.999    |
| opm-git | OPM Benchmark: flow_mpi_norne_4c_msw - Threads: 8 | 0.993    |
* Speed-up = Total time master / Total time pull request. Above 1.0 is an improvement. *



View result details @ https://www.ytelses.com/opm/?page=result&id=1119

**Comment by atgeirr** [comment]
The code looks good.

The testing seems to imply that the logic is also correct. However, I cannot really see how the following hypothetical situation would/should get resolved: Group G contains wells A and B. During iterations, well B shuts down. Is it then ok to keep the guide rate of G explicit, i.e. not changing it until the next step? If B's behaviour is continuous it does not matter. But if not (it shuts down from some nontrivial rate) G would seem to me to receive a too great share.

These are just theoretical worries, and if your testing shows better match then I am fine with merging it after a data update.

**Comment by totto82** [comment]
> However, I cannot really see how the following hypothetical situation would/should get resolved: Group G contains wells A and B. During iterations, well B shuts down. Is it then ok to keep the guide rate of G explicit, i.e. not changing it until the next step? 

Shutting/opening wells in the middle of timesteps is a tricky thing. A solution could be to re-compute the guiderate when that happens.

**Comment by totto82** [comment]
jenkins build this update_data please

**Comment by totto82** [comment]
jenkins build this opm-tests=507 please

**Pull request merged**
