### PR TITLE
Only print usage information on one processes.

### PR DESCRIPTION
**Pull request by blattms**
No matter whether requested via --help or printed due to a wrong command line parameter.

Closes #2012.

### CODE REVIEW

**Comment by blattms** [comment]
jenkins build this opm-models=577 please

**Comment by blattms** [comment]
For the record: This builds fine according to [jenkins](https://ci.opm-project.org/job/opm-simulators-PR-builder/310/). Failing build is due to a moron mixing up his own PRs :angry:

**Comment by blattms** [comment]
enkins build this serial please

**Comment by bska** [comment]
> enkins build this serial please

I'll rerun this with **j**enkins instead...

**Comment by bska** [comment]
jenkins build this serial please

**Comment by blattms** [comment]
Thanks @bska for chipping in and fixing my jenkins summoning.

**Pull request merged**
