### PR TITLE
LinearSolverVerbosity

### PR DESCRIPTION
**Pull request by OPMUSER**
This is one of several PRs that will rename some command line parameters for greater consistency, as agreed with Atgeirr in #4096

Here we rename FlowLinearSolverVerbosity to LinearSolverVerbosity.

### CODE REVIEW

**Comment by blattms** [comment]
jenkins build this please

**Comment by OPMUSER** [comment]
Yes the parameter is available with standard flow --help

2022-09-28 12_56_31-Kubuntu 22 04 LTS OPM Development  Running  - Oracle VM VirtualBox _ 1

I commented out the declaration that caused a compile error, would you like me to delete this instead, or fix the typo?

I have few more of these renaming of the command line parameters and I'll submit them individually, to ensure nothing breaks.

**Comment by blattms** [comment]
Yes please remove the commented code and fix spelling errors. Otherwise this is good to go in.

**Comment by atgeirr** [comment]
We could consider adding to the help string the hack for writing all the matrices to files (using verbosity > 10). However, this typically results in enormous amounts of output, so I guess that should remain a developer tool and therefore not be documented here.

**Comment by OPMUSER** [comment]
Done.

**Comment by blattms** [comment]
jenkins build this please

**Pull request merged**
