### PR TITLE
fix bug that sets global_time to 0

### LINKED ISSUE #3069: The time column in INFOSTEP file looks wrong
It uses the master branch from yesterday. 

```
  1   Time(day)  TStep(day)  Assembly    LSolve    LSetup    Update    Output WellIt Lins NewtIt LinIt Conv
  2           0           1    6.3893    1.5736   23.2751    2.4474    0.0000      0   11     10   260    1
  3           0         0.8    2.8261    0.6151    8.2614    1.0134    0.0000      0    5      4    91    1
  4           0        2.08    3.3543    0.7686   14.1873    1.2526    0.0000      0    6      5   160    1
  5           0       4.576    3.8841    0.9212   32.0168    1.4909    0.0000      0    7      6   372    1
  6           0      8.2368    3.3568    0.7683   32.7894    1.2565    0.0000      0    6      5   383    1
  7           0    18.12096    4.9376    1.3806   62.6628    1.9750    0.0000      0    9      9   731    0
  8           0   5.9799168    3.3608    0.7680   27.5671    1.2542    0.0000      0    6      5   321    1
  9           0  11.9598336    4.4137    1.0718   38.5869    1.7335    0.0000      0    8      7   449    1
 10           0 16.74376704    5.4712    1.3813   65.3111    2.2196    0.0000      0   10      9   763    1
 11           0 14.88334848    3.8868    0.9216   42.4813    1.4979    0.0000      0    7      6   497    1
 12           0 23.74033408    3.9055    1.0780   53.5896    1.4998    0.0000      0    7      7   626    0
 13           0 7.834310246    3.8985    0.9244   33.2069    1.4991    0.0000      0    7      6   384    1
 14           0 7.953011917    2.8454    0.6131   27.6529    1.0205    0.0000      0    5      4   323    1
 15           0 7.953011917    4.4304    1.0750   46.9540    1.7431    0.0000      0    8      7   548    1
 16           0 11.13421668    3.9003    0.9238   39.4786    1.5022    0.0000      0    7      6   458    1
 17           0 20.04159003    3.8849    0.9204   50.5944    1.5007    0.0000      0    7      6   591    1
 18           0 36.07486205    4.4125    1.2294   51.8721    1.7317    0.0000      0    8      8   602    0
 19           0 11.90470448    3.3632    0.7676   29.4785    1.2582    0.0000      0    6      5   341    1
 20           0 23.80940896    4.4141    1.0763   59.7445    1.7366    0.0000      0    8      7   697    1
 21           0 24.11007985    4.4187    1.2290   72.8638    1.7348    0.0000      0    8      8   851    0
 22           0 7.956326351    2.8375    0.6145   23.0087    1.0173    0.0000      0    5      4   266    1
 23           0  16.1537535    3.3732    0.7687   39.3361    1.2635    0.0000      0    6      5   459    1
 24           0  35.5382577    0.7244    0.1541   16.9811    0.0561    0.0000      0    1      1   200    0
 25           0 11.72762504    3.3675    0.7707   35.7140    1.2571    0.0000      0    6      5   415    1
 26           0 23.45525008    3.9059    0.9215   53.5992    1.4969    0.0000      0    7      6   626    1
```

### PR DESCRIPTION
**Pull request by fgfuchs**
fix bug that sets global_time to 0
fixes #3069

### CODE REVIEW

**Comment by fgfuchs** [comment]
jenkins build this please

**Comment by fgfuchs** [comment]
jenkins build this please

**Comment by atgeirr** [comment]
Ok to merge when green.

**Comment by bska** [comment]
Build check is green.  I'll merge into master.

**Pull request merged**
