### PR TITLE
added: ability to run norne using flow_ebos

### PR DESCRIPTION
**Pull request by akva2**
@andlaus asked for this

### CODE REVIEW

**Comment by akva2** [comment]
jenkins run norne_ebos please

**Comment by akva2** [comment]
note that the default should be changed to flow_legacy if we want it to continue running the old binary when frankenstein lands (since 'flow' links to flow_ebos  and not flow_legacy then i assume).

**Comment by atgeirr** [comment]
> since 'flow' links to flow_ebos and not flow_legacy then i assume

When we get to that point, flow_ebos will be the one that should be tested by default, so I think there is no change needed?

**Comment by akva2** [comment]
right, that was my educated guess which is why i left it as-is.

**Comment by andlaus** [comment]
that's cool, thanks a lot. until the `frankenstein` branches are merged, don't you need to instruct jenkins to use them? i.e.,

jenkins run norne_ebos opm-common=162 opm-simulators=800 please

**Comment by andlaus** [comment]
> When we get to that point, flow_ebos will be the one that should be tested by default, so I think there is no change needed?

I suppose that will happen automatically when the symlink changes? But we might want to have a `run Norne_legacy` then, right?

**Comment by akva2** [comment]
frankenstein is the base of this pr. i want to build the base with *this* pr, so the opm-simulators one is irrelevant and in any case you cannot specify the PR for the top module, that's always the pr you trigger on. the opm-common one however should have been there. but we'll survive due to shared directories though.

yes, we'd flip the triggers around then. just playing with open cards...

**Comment by andlaus** [comment]
ok, thanks for the clarification.

**Comment by akva2** [comment]
i guess i can state it in clear text: the PR builder builds some base branch with some branch pulled into it. the base can be any branch in the repo, master or frankenstein or whatever else is created. jenkins always simply pulls the branch into the base and builds (well, rather the pull stuff is performed by github and all we do is fetch the particular reference pulls/xx/merge but that's besides the point).

**Comment by akva2** [comment]
stupid pr builder bug.

**Comment by akva2** [comment]
jenkins run norne_ebos opm-common=162 please

**Comment by akva2** [comment]
there we go. note that i confirmed locally on the jenkins machine that it is indeed was flow_ebos that was running (not apparent from output, i'd consider changing that banner, even if only as a temporary measure).

**Comment by andlaus** [comment]
> there we go.

thanks. I guess we're ready to merge now?

> (not apparent from output, i'd consider changing that banner, even if only as a temporary measure)

#917!?

**Comment by akva2** [comment]
purfect and all is ready from my side yes.

**Comment by andlaus** [comment]
> purfect and all is ready from my side yes.

good. merging.

**Pull request merged**
