### PR TITLE
only check if wells has negative potentials if check_well_operability=true(default)

### PR DESCRIPTION
**Pull request by totto82**

### CODE REVIEW

**Comment by totto82** [comment]
jenkins build this please

**Comment by totto82** [comment]
I think this also should go into the release. It would make it possible to disallow shutting of wells with negative potentials using running a run-time parameter.

**Review by atgeirr — COMMENTED** [review]
I think this is good. Since you made the message more serious (info->warning): is it likely to trigger often and repeatedly for the same well? If so, consider adding a tag to silence repeats in the stdout, possibly including the well name in the tag.

**Comment by totto82** [comment]
jenkins build this please

**Comment by totto82** [comment]
TAG added. Will merge.

**Pull request merged**
