### PR TITLE
Add inner after well control switch

### PR DESCRIPTION
**Pull request by totto82**

### CODE REVIEW

**Comment by totto82** [comment]
jenkins build this please

**Comment by totto82** [comment]
benchmark please

**Comment by ytelses** [comment]
Benchmark result overview: 




| Test    | Configuration                                     | Relative |
| ------- | ------------------------------------------------- | -------- |
| opm-git | OPM Benchmark: flow_mpi_extra - Threads: 1        | 1.199    |
| opm-git | OPM Benchmark: flow_mpi_extra - Threads: 8        | 1.092    |
| opm-git | OPM Benchmark: flow_mpi_norne - Threads: 1        | 0.998    |
| opm-git | OPM Benchmark: flow_mpi_norne - Threads: 8        | 1.01     |
| opm-git | OPM Benchmark: flow_mpi_norne_4c_msw - Threads: 1 | 0.897    |
| opm-git | OPM Benchmark: flow_mpi_norne_4c_msw - Threads: 8 | 0.814    |
* Speed-up = Total time master / Total time pull request. Above 1.0 is an improvement. *



View result details @ https://www.ytelses.com/opm/?page=result&id=1342

**Comment by ytelses** [comment]
Benchmark result overview: 




| Test    | Configuration                                     | Relative |
| ------- | ------------------------------------------------- | -------- |
| opm-git | OPM Benchmark: flow_mpi_extra - Threads: 1        | 1.202    |
| opm-git | OPM Benchmark: flow_mpi_extra - Threads: 8        | 1.099    |
| opm-git | OPM Benchmark: flow_mpi_norne - Threads: 1        | 0.998    |
| opm-git | OPM Benchmark: flow_mpi_norne - Threads: 8        | 1.004    |
| opm-git | OPM Benchmark: flow_mpi_norne_4c_msw - Threads: 1 | 0.897    |
| opm-git | OPM Benchmark: flow_mpi_norne_4c_msw - Threads: 8 | 0.815    |
* Speed-up = Total time master / Total time pull request. Above 1.0 is an improvement. *



View result details @ https://www.ytelses.com/opm/?page=result&id=1342

**Comment by totto82** [comment]
Seemed promising for one case, but not for most others. Closing....

**Pull request closed without merging**
