### PR TITLE
RockCompressibility takes only EclipseState

### PR DESCRIPTION
**Pull request by jokva**
Requires https://github.com/OPM/opm-parser/pull/1013 and https://github.com/OPM/opm-core/pull/1124

### CODE REVIEW

**Comment by atgeirr** [comment]
jenkins build this opm-parser=1013 opm-core=1124 please

**Comment by atgeirr** [comment]
Both this and the opm-core PR looks ok, feel free to merge when green.

**Comment by jokva** [comment]
jenkins build this opm-core=1124 please

**Comment by atgeirr** [comment]
jenkins build this opm-core=1124 please

**Pull request merged**
