### PR TITLE
pick correct version of flow for gas-water-vapwat case

### PR DESCRIPTION
**Pull request by totto82**
See discussion in https://github.com/OPM/opm-simulators/pull/4537

### CODE REVIEW

**Comment by totto82** [comment]
jenkins build this please

**Review by bska — COMMENTED** [review]
Since this relaxes the requirements, you may want to mention `VAPWAT` in the associate [diagnostic message](https://github.com/OPM/opm-simulators/blob/ec80c0cab4858079ce0dfd79d4b65b058a3fb4e1/opm/simulators/flow/Main.hpp#L471-L476) too.

**Comment by totto82** [comment]
jenkins build this please

**Review by bska — APPROVED** [review]
Thanks for the updates.  I'll merge into master.

**Pull request merged**
