### PR TITLE
Fix/compdat nldd parallel

### PR DESCRIPTION
**Pull request by lisajulia**
This PR fixes the NLDD solver for parallel runs with the COMPDAT keyword inside an ACTIONX.
This PR is not relevant for the reference manual.

### CODE REVIEW

**Comment by lisajulia** [comment]
jenkins build this please

**Comment by lisajulia** [comment]
jenkins build this please

**Review by akva2 — APPROVED** [review]
There are a little too many deep details for me to investigate this right now but the usage of the serializer is certainly as intended.

Do we really need to add tests with 8 procs, what does that give that 4, the number of physical cores dedicated to a ci job, would not cover?

**Comment by lisajulia** [comment]
> There are a little too many deep details for me to investigate this right now but the usage of the serializer is certainly as intended.
> 
> Do we really need to add tests with 8 procs, what does that give that 4, the number of physical cores dedicated to a ci job, would not cover?

Thanks for having a look at this :)! I'll check if a test with less than 8 processes fails without and passes with this fix.

**Comment by lisajulia** [comment]
jenkins build this please

**Pull request merged**
