### PR TITLE
Janitoring

### PR DESCRIPTION
**Pull request by akva2**
- add virtual dtor to class with virtual members
- remove unused variable

### CODE REVIEW

**Comment by akva2** [comment]
jenkins build this please

**Comment by bska** [comment]
@multitalentloes : Would you mind having a look at this, please?  In particular whether or not the `size` variable is genuinely unused or if it is supposed to be used elsewhere.

**Comment by multitalentloes** [comment]
I dont see how this variable could have any effect. Looks like dead code which is safe to remove

**Comment by bska** [comment]
>  Looks like dead code which is safe to remove

Okay-cool.  Thanks for looking into this.  I'll merge into master.

**Pull request merged**
