### PR TITLE
[bugfix] Fix invalid read in WellDenseStandard when used with 2P Model.

### PR DESCRIPTION
**Pull request by dr-robertk**
This PR fixes the invalid read mentioned by @akva2 in #1192 .

### CODE REVIEW

**Comment by dr-robertk** [comment]
jenkins build this please

**Comment by akva2** [comment]
i would guess the fix only applies to to two phase case.

**Comment by akva2** [comment]
also i would expect a failure for the test now.

**Comment by akva2** [comment]
now libecl seems to suffer generic breakage in its 'ert' compatibility.

**Comment by dr-robertk** [comment]
@akva2 The fix applies to the 2p case. I did not discover any problems for the normal 3p cases.

**Comment by akva2** [comment]
then we have observed the same.

**Comment by andlaus** [comment]
The patch looks good to me after a cursory look. The jenkins failure is weird, but to me it seems to be unrelated and caused by some build system screw-up. does anyone have a glue what falls on Jenkins feet?

**Comment by dr-robertk** [comment]
Replaced  num_phases with numComponents after discussion with @totto82

**Comment by atgeirr** [comment]
jenkins build this please

**Comment by dr-robertk** [comment]
jenkins build this please

**Comment by dr-robertk** [comment]
I think this is good to be merged once the tests are finished.

**Comment by totto82** [comment]
Thanks for the fix.

**Pull request merged**
