### PR TITLE
Also print information about parallel run to PRT file.

### PR DESCRIPTION
**Pull request by blattms**
Up to now this information is only output to standard out. To help with debugging and replicating (e.g. in case of crashes) without saved standard putput, we now also print the imformation about MPI processes and OMP threads to the PRT file.

### CODE REVIEW

**Comment by blattms** [comment]
jenkins build this please

**Comment by blattms** [comment]
jenkins build this please

**Comment by blattms** [comment]
jenkins build this please

**Comment by blattms** [comment]
jenkins build this please

**Review by bska — APPROVED** [review]
Excellent.  This is indeed very useful information!  I'll merge into master.

**Pull request merged**
