### PR TITLE
fixing the LRAT control for StandardWellsDense

### PR DESCRIPTION
**Pull request by GitPaean**
The original StandardWellsDense does not provide correct strategy to enforce combined rate control like LRAT. 

With this fix, it can provide correct LRAT control. 

It is still WIP, and this part of code is pretty complicated. Please let me know if you find anything missing.

### CODE REVIEW

**Comment by totto82** [comment]
Thanks. I have read through the code and it looks correct and I don't immediately see anything missing.

**Comment by GitPaean** [comment]
Thanks. Then I will cleaning up a little bit then remove the WIP label soon.

**Comment by GitPaean** [comment]
This PR is ready for reviewing and merging from my side.

**Comment by atgeirr** [comment]
Looks fine, merging.

**Pull request merged**
