### PR TITLE
Use correct region temperature when calculating RS/RV

### LINKED ISSUE #2423: Parallel initstateequil.hh runs on a distributed grid but seems to assume a global one.
I was about to clean up initstateequil.hh as it seemed that getting the global field properties is superfluous. I have to admit that this code leaves me a bit clueless. Is this well tested in parallel?

What strikes me is this:
 [In the constructor of InitialStateComputer](OPM/opm-simulators/blob/a449b2e2e6a2f1bf420a20440f4b70b321d3e64d/ebos/equil/initstateequil.hh#L933) it's `temperature_` member is a vector of the number of elements of the local grid (called after loadbalance). Later in the constructor there is a call to [updateInitialTemperature](/OPM/opm-simulators/blob/a449b2e2e6a2f1bf420a20440f4b70b321d3e64d/ebos/equil/initstateequil.hh#L1086) which overwrites the vector by the global field property with key "TEMPI".  But the grid passed to the constructor is a loadbalanced parallel one (I see this in my gdb session, the backtrace shows that this is called during `problem_finishInit` in the Simulator of opm-models/opm/models/utils/simulator.hh). Later on this array is then used in `Opm::EQUIL::computeRs` and this function seems to assume that the temperature for the i-th cell its stored in `temperature_[i]`, but this array seems to be unchanged from before.

It also seems that all the region stuff cannot work on a distributed grid as it does see the cells of the region that belong to another processor.

I am lost, what am I missing?

### PR DESCRIPTION
**Pull request by blattms**
The `InitialStateComputer::temperature_` array, previously used, was of Cartesian size, but used as if it only contained the values of the cells of a region. With this commit `InitialStateComputer::temperature_` is a compressed local array and we explicitly copy out only the region values when computing RS/RV.

Closes #2423.

Needs  #2446 to be merged first! Won't work otherwise

### CODE REVIEW

**Comment by akva2** [comment]
can you tighten the parallel SPE1CASE2_THERMAL tolerances now?

**Comment by blattms** [comment]
Haven't tried. Whenever I try to use the jenkibs scripts locally as described in the [wiki](https://wiki.opm-project.org/index.php?title=Jenkins_triggers#Using_the_scripts_locally), I somehow get stuck. Could use some help.

How would I check that locally?

**Comment by akva2** [comment]
don't have to use jenkins scripts for that.

edit https://github.com/OPM/opm-simulators/blob/master/compareECLFiles.cmake#L530 to something more sane, then run the test using ctest -R Parallel.*THERMAL

**Comment by blattms** [comment]
I could have sworn that the test failed when I tried it on a debug build even for the default settings.

When retrying (release build) it works with tolerances "0.02" "1e-5".

This makes me a bit anxious (even more tighter tolerances seem possible)!

Also please note that my changes, might also change results for serial runs. Even for these we neglected the regions
when querying temperatures for RS/RV. Carefully examination by others is therefore advised.

**Comment by akva2** [comment]
jenkins build this please

**Comment by blattms** [comment]
Thanks for the approval.

I still think that somebody needs to manually verify the results as I am assuming
that for a case with several different equil regions the results of a serial
run should differ from the previous version.

**Comment by blattms** [comment]
Will anybody check this for a case with temperature and multiple regions?

**Comment by bska** [comment]
> Will anybody check this for a case with temperature and multiple regions?

I'll echo this request.  As it happens, I'm doing a bit of work in this area (simulation run initialization) at the moment and I would like to base that work on @blattms's fix here.  While even this PR may not be completely correct, it is my opinion that it is definitely more correct than the current master sources.

**Comment by blattms** [comment]
Cool. Then we should just merge.

**Comment by bska** [comment]
> Cool. Then we should just merge.

Agreed.  I'm merging now and take responsibility if something breaks since I'm working in this area anyway.  Thanks for the fix.

**Pull request merged**
