### PR TITLE
Packaging updates backport

### PR DESCRIPTION
**Pull request by akva2**
- Add ewoms as dependency
- Re-add usage of system eigen3 and remove orig source creation script (which bundled the eigen3 sources).

### CODE REVIEW

**Comment by atgeirr** [comment]
> Re-add usage of system eigen3

I assume that means it works well for Ubuntu 16.04 now? What has changed?

**Comment by akva2** [comment]
uhm, https://github.com/OPM/opm-simulators/pull/1070

**Comment by atgeirr** [comment]
> uhm, #1070

But I thought that the Eigen shipping with Ubuntu 16.04 was buggy, so even if we can compile with it will it work? (I guess we will find that out...)

**Comment by akva2** [comment]
it's 3.3. it builds and tests passed. on buildslave the opm-data derived tests do not execute, but i have been using system eigen3 on my laptop since that pr landed without any apparent issues.

anyways, that's why we do rc packages :)

**Comment by andlaus** [comment]
> But I thought that the Eigen shipping with Ubuntu 16.04 was buggy, so even if we can compile with it will it work? (I guess we will find that out...)

I just checked: with the 16.04 system package, flow_legacy seems to work fine for Norne.

The only annoying thing is that I get flooded by warnings, at least using GCC 7. that's the same as for the "buildsystem cloned" version, though.

**Comment by atgeirr** [comment]
> The only annoying thing is that I get flooded by warnings, at least using GCC 7. that's the same as for the "buildsystem cloned" version, though.

Consider using (and updating if necessary) our external warning suppression feature...!

**Comment by andlaus** [comment]
> Consider using (and updating if necessary) our external warning suppression feature...!

meh, it seems to be caused by many places, so I'm not sure if this is worth the effort -- in particular considering that Eigen is scheduled for retirement in the medium term future (?)

**Comment by atgeirr** [comment]
> considering that Eigen is scheduled for retirement in the medium term future (?)

While legacy flow will be retired as the main workhorse I am not sure we should abandon the framework completely, as it seems to be easier to understand than ewoms. For some at least! It could be moved to a separate module at some point, we have many options.

**Comment by andlaus** [comment]
okay, I'll add working around these warnings to my TODO list. but only at the very bottom ;)

**Comment by atgeirr** [comment]
Merging as there are no build system, test system or code changes here (Travis failure is the usual timeout).

**Pull request merged**
