### PR TITLE
Avoid global ecl state in setting up additional modules

### PR DESCRIPTION
**Pull request by akva2**
Avoid using deck directly on non-root processes when setting up the solvent, polymer and foam modules.

Downstream of https://github.com/OPM/opm-models/pull/584

### CODE REVIEW

**Comment by totto82** [comment]
We have tried to keep as much as possible of the model extension code "hidden" from the standard code and eclproblem.hh is already a very long file. Could you move the (un)pack code to the ...modules.hh files in opm-models if it is not too much work?

**Comment by akva2** [comment]
it depends on opm-simulators code so that is problematic.

**Comment by akva2** [comment]
hopefully you like this one better.

**Comment by totto82** [comment]
Thanks! Please merge when green.

**Comment by bska** [comment]
This appears to [break](https://ci.opm-project.org/job/opm-simulators/215/consoleFull) the sequential/serial build.  How much work will it be to restore that configuration?

**Comment by bska** [comment]
> This appears to break the sequential/serial build.

Just a quick follow-up.  Here are the (unique) diagnostic messages from a local build
```
${ROOT}/opm-simulators/ebos/eclproblem.hh:615:42: error: no matching function for call to ‘Opm::EclMpiSerializer::EclMpiSerializer(const Dune::CollectiveCommunication<Dune::No_Comm>&)’
${ROOT}/opm-simulators/ebos/eclproblem.hh:633:38: error: no matching function for call to ‘Opm::EclMpiSerializer::EclMpiSerializer(const Dune::CollectiveCommunication<Dune::No_Comm>&)’
```

**Comment by akva2** [comment]
Should be fixed by https://github.com/OPM/opm-simulators/pull/2265

**Comment by bska** [comment]
> Should be fixed by #2265

Cool.  Thanks a lot for the quick turn-around.  Merge #2265 when green.

**Pull request merged**
