### PR TITLE
New test class: init

### PR DESCRIPTION
**Pull request by akva2**
First commit enables adding tests for simulators besides 'flow'. I tried flow_ebos, and I have to increase the fuzz beyond reason to use the flow data as reference, so we will need multiple data sets for this I fearr

The second commit adds a new test class comparing an init file to a stored reference.
Right now only SPE1 is active; I wanted to reproduce the norne init tests from the python side, and it kept failing. Then I realized that the python test compared to an eclipse reference, and not the opm reference, and thus had very generous tolerances. So for the norne tests to be reinstated in a meaningful way we have to update that opm reference I guess.

- Do we want this test class ? The only case it can be useful for is in large cases like Norne, for spe1 etc init file is also checked as part of the normal regression tests.
- Should it compare to the eclipse reference ? To me, that is integration test land, not regression tests. As in, defining what is a regression is a bit hard since we do not have (nor expect) matching data in the first place.

### CODE REVIEW

**Comment by atgeirr** [comment]
I think that such a test is very important if we want to refactor the init code (and we do). I guess it should compare (regression test) to the opm reference (same as used for the Jenkins tests)?

**Comment by akva2** [comment]
yeah, that is what i think is the most reasonable. so if there are no protests i will update init reference data for norne in opm-data, and add such a test.

**Comment by akva2** [comment]
jenkins build this opm-data=143 please

**Comment by akva2** [comment]
test passed -> shameless self merge.

**Pull request merged**
