### PR TITLE
Single well state

### PR DESCRIPTION
**Pull request by joakim-hove**
Final PR in the mechanical refactor of wellState to single well state.

### CODE REVIEW

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by joakim-hove** [comment]
Comments to this?

**Comment by totto82** [comment]
Thanks for your effort. Looks good to me.

**Pull request merged**
