### PR TITLE
Use new linearizer for gaswater with thermal and diffusion

### PR DESCRIPTION
**Pull request by totto82**

### CODE REVIEW

**Comment by totto82** [comment]
jenkins build this please

**Comment by GitPaean** [comment]
Thanks for this. This is NOT something I am familiar with while if any case in the  opm-tests will use this PR?

**Comment by totto82** [comment]
I think it should have been part of https://github.com/OPM/opm-simulators/pull/4814 but somehow was forgotten. We really want the speed-up also for the gas-water case with diffusion and/or thermal.

**Comment by GitPaean** [comment]
> I think it should have been part of https://github.com/OPM/opm-simulators/pull/4814 but somehow was forgotten. We really want the speed-up also for the gas-water case with diffusion and/or thermal.

Sure. Have you tested with any cases with this PR?

**Comment by totto82** [comment]
Yes. The test shows the factor 2 speed-up on assembly as expected.

**Comment by GitPaean** [comment]
Thanks for the PR. I am merging this PR now as jenkins and testing approve.

**Pull request merged**
