### PR TITLE
Report Solution GOR and OGR at Segment Level

### PR DESCRIPTION
**Pull request by bska**
This enables calculating the `SOFRF` and `SGFRF` summary vectors.

### CODE REVIEW

**Comment by bska** [comment]
While nominally independent, I am nevertheless creating this as a continuation of #4180 to facilitate testing this together with the expanded set of RFT vectors.

**Comment by bska** [comment]
The prerequisite PR was merged into the master branch.  I'm declaring this as "ready for review".

**Comment by bska** [comment]
jenkins build this please

**Review by akva2 — APPROVED** [review]
Looks good

**Comment by bska** [comment]
jenkins build this please

**Comment by bska** [comment]
jenkins build this please

**Comment by bska** [comment]
jenkins build this please

**Comment by bska** [comment]
jenkins build this please

**Review by GitPaean — APPROVED** [review]
Sorry that I did not see the request earlier. The code looks good to me. If the result is verified, then the PR is good to go in.

**Comment by blattms** [comment]
Didn't know that we have veto rights. Merging as this is approved anyway.

**Comment by bska** [comment]
> The quantities calculated in the PR look more like vaporized oil rate and dissolved gas rate? Most likely the title of the PR is wrong?

Yes, the title is a little misleading.  We do indeed calculate the dissolved gas rate and vaporised oil rate here and that is the intention.

**Pull request merged**
