### PR TITLE
keywords co2store + gaswat

### PR DESCRIPTION
**Pull request by goncalvesmachadoc**
Preparation for https://github.com/OPM/opm-tests/pull/902

### CODE REVIEW

**Comment by goncalvesmachadoc** [comment]
jenkins build this please

**Comment by goncalvesmachadoc** [comment]
jenkins build this please

**Comment by totto82** [comment]
jenkins build this please

**Comment by totto82** [comment]
@goncalvesmachadoc Should we try to get this in? The regression test part is already added but the keyword part is not. It will need a rebase.

**Comment by goncalvesmachadoc** [comment]
jenkins build this please

**Pull request merged**
