### PR TITLE
Restore Groups' Active Constraints on Restart

### PR DESCRIPTION
**Pull request by bska**
This is a first step towards better restarts of models with group control. More work is needed, including actually retrieving the active constraint values from the `IGRP` table in the restart file, but this is at least a necessary step on the simulator side.

### CODE REVIEW

**Comment by bska** [comment]
jenkins build this please

**Comment by bska** [comment]
@akva2 : Would you mind having a look at the `ParallelRestart` parts of this PR?  It is trying to distribute the [`data::GuideRateValue`](https://github.com/OPM/opm-common/blob/746bb1568145d2a11e1bf868949d31dd8b4481db/opm/output/data/GuideRateValue.hpp#L31) and the [`data::GroupValues`](https://github.com/OPM/opm-common/blob/746bb1568145d2a11e1bf868949d31dd8b4481db/opm/output/data/Groups.hpp#L108) structures in OPM-Common.

**Comment by bska** [comment]
jenkins build this please

**Review by akva2 — APPROVED** [review]
The parallel restart stuff looks fine.

**Comment by bska** [comment]
Do any of you, @atgeirr or @GitPaean wish to review the changes to `BlackoilWellModel` and its `_impl` file?  If not, I'm going to merge this today.

**Comment by atgeirr** [comment]
I will review it now.

**Comment by atgeirr** [comment]
Looks fine, merging.

**Comment by bska** [comment]
> Looks fine, merging.

Thanks for the speedy review!

**Pull request merged**
