### PR TITLE
Change dp_max_rel default from 1.0 to 0.3

### PR DESCRIPTION
**Pull request by totto82**
This helps stabilizing the convergence for difficult cases. Tested on norne, Model 2-0 and Model 2-5.

### CODE REVIEW

**Comment by alfbr** [comment]
Cool! Any approximate numbers for the Model2 cases? (I am just very curious..)

**Comment by andlaus** [comment]
thumbs up: I've tested this on Norne and on my machine flow exhibited exactly the same performance.

**Comment by totto82** [comment]
> Cool! Any approximate numbers for the Model2 cases? (I am just very curious..)

Only a small improvement on Mode2 rel5. While testing #1368 I hit a case where the pressure became 0 in a small region due to convergence issues in the solver. Using dp_max_rel=1 seems like a unwise default since is allows the pressure to drop to zero. I have not attempt to tune this further, by keeping the default relatively large the effect of this change is minimal for most cases. 

```
< Total time (seconds):         4556.34
< Solver time (seconds):        4514.57
<  Assembly time (seconds):     2279.38 (Failed: 694.241; 30.4575%)
<  Linear solve time (seconds): 2068.28 (Failed: 506.655; 24.4964%)
<  Update time (seconds):       117.224 (Failed: 37.4017; 31.9063%)
<  Output write time (seconds): 63.6024
< Overall Well Iterations:      1979 (Failed: 481; 24.3052%)
< Overall Linearizations:       7456 (Failed: 2261; 30.3246%)
< Overall Newton Iterations:    6778 (Failed: 2261; 33.3579%)
< Overall Linear Iterations:    80225 (Failed: 17979; 22.4107%)
---
> Total time (seconds):         4401.48
> Solver time (seconds):        4359.67
>  Assembly time (seconds):     2227.48 (Failed: 665.803; 29.8905%)
>  Linear solve time (seconds): 1968 (Failed: 481.395; 24.4611%)
>  Update time (seconds):       115.624 (Failed: 36.1884; 31.2984%)
>  Output write time (seconds): 62.762
> Overall Well Iterations:      2007 (Failed: 513; 25.5605%)
> Overall Linearizations:       7355 (Failed: 2189; 29.7621%)
> Overall Newton Iterations:    6686 (Failed: 2189; 32.7401%)
> Overall Linear Iterations:    76296 (Failed: 17144; 22.4704%)
266853,266854c266559,266560
< Warnings          7416
< Info              2450
---
> Warnings          7308
> Info              2421
266858c266564
< Problems          207
---
> Problems          199

```

**Comment by totto82** [comment]
I will merge this later today if nobody objects.

**Comment by atgeirr** [comment]
The PR builder is available, so I'll start a run. I agree it can be merged when green.

**Comment by atgeirr** [comment]
jenkins build this please

**Pull request merged**
