### PR TITLE
Cleaningup well models

### PR DESCRIPTION
**Pull request by GitPaean**
some cleaning up in the well model related. Far from finished, will continue later. 

Stopping here to handle other higher-priority issue. 
1. removing the usage of Wells in resetWellControlFromState
2. removing the dumplicated numComponents in WellInterface
3. removing the "`current`" argment in updateWellStateWithTarget

And some other small cleaning up. 

It should not change any result in any way, while will run the several big models to report back.

### CODE REVIEW

**Comment by GitPaean** [comment]
jenkins build this please

**Comment by totto82** [comment]
Thanks for the cleaning. I didn't spot anything strange. Looking forward to next cleaning day.

**Comment by GitPaean** [comment]
running with model 2 with multisegment well did not show any difference in the residual history against master branch.

**Comment by atgeirr** [comment]
Thanks, merging.

**Pull request merged**
