### PR TITLE
[feature] Adds support for computing tracers in parallel runs.

### PR DESCRIPTION
**Pull request by blattms**
Needs OPM/opm-grid#552

Marking as WIP as it not perfect yet:

- There are deviations in a parallel run that seem to add up during the run (A few percent difference). I am a bit unsure whether this is to be expected or still a bug.
- Did not check restart output, but I am silently assuming that this wrong in parallel (albeit for the wells it magically worked out of the box)
- Distributed wells have not been checked yet. Might be broken, too.

Is there a tool to inspect the binary restart file?

### CODE REVIEW

**Comment by blattms** [comment]
@alfbr and I agreed that this should be merged to facilitate easier testing. Should not break anything as it just adds missing functionality (famous last words..., I know)

Will rebase and retest, today.

**Comment by blattms** [comment]
jenkins build this opm-grid=552 please

**Comment by bska** [comment]
> jenkins build this opm-grid=552 please

PR OPM/opm-grid#552 was already merged.

**Comment by blattms** [comment]
> PR OPM/opm-grid#552 was already merged.

Cool.

**Comment by blattms** [comment]
jenkins build this please

**Comment by blattms** [comment]
Shameless selfmerge.

**Pull request merged**
