### PR TITLE
Feature/metis support boost version

### PR DESCRIPTION
**Pull request by lisajulia**
I could not use a json file for the parameters without this change.

### CODE REVIEW

**Comment by lisajulia** [comment]
jenkins build this opm-grid=736 please

**Comment by lisajulia** [comment]
jenkins build this opm-grid=736 please

**Comment by lisajulia** [comment]
jenkins build this opm-grid=736 please

**Review by blattms — APPROVED** [review]
Approval for the last commit. I guess the other one is in #5477

**Comment by lisajulia** [comment]
> Approval for the last commit. I guess the other one is in #5477

ok, now everything is in #5477

**Pull request closed without merging**
