### PR TITLE
Remove members from WellSegment class

### PR DESCRIPTION
**Pull request by joakim-hove**
Downstream of: https://github.com/OPM/opm-common/pull/1460

### CODE REVIEW

**Comment by joakim-hove** [comment]
Temporary close to help GitHub

**Comment by GitPaean** [comment]
I might misread it and I have to go now. 

In the upstream, you removed the function `WellSegments::MultiPhaseModel WellSegments::multiPhaseModel() const {`, while I did not see the usage is removed here while it compiled. 

Excuse me if I got things wrong here.

**Comment by joakim-hove** [comment]
> while I did not see the usage is removed here while it compiled.

I think you got that one wrong - it is removed here.

**Comment by GitPaean** [comment]
I mean here.  The function `WellSegments::multiPhaseModel() const ` is removed from upstream.

https://github.com/OPM/opm-simulators/blob/0e45f0827ce06445ef1b4f40baaeb8dfcd763a9c/opm/simulators/wells/MultisegmentWell_impl.hpp#L1175

**Comment by joakim-hove** [comment]
> I mean here. The function WellSegments::multiPhaseModel() const is removed from upstream.

OK - removed. Why did it compile/link at all?

**Pull request merged**
