### PR TITLE
quell uninitialized usage warning without mpi

### PR DESCRIPTION
**Pull request by akva2**

### CODE REVIEW

**Comment by akva2** [comment]
jenkins build this serial please

**Comment by blattms** [comment]
I am too dense to see where the warning came from. `data` seems to have been used...

**Comment by akva2** [comment]
it's only used with MPI. without mpi it's not.

**Comment by blattms** [comment]
Ahh. thanks. That's quite tricky.

**Review by blattms — APPROVED** [review]

**Pull request merged**
