### PR TITLE
Sphinx gha

### PR DESCRIPTION
**Pull request by lisajulia**
This PR includes all commits from #5243 with further enhancements and hence is a replacement for #5243.
Further enhancements:

- Add documentation for the Python bindings from opm-common
- Add documentation for opm_embedded

### CODE REVIEW

**Comment by lisajulia** [comment]
jenkins build this opm-common=4018 please

**Comment by lisajulia** [comment]
jenkins build this opm-common=4018 please

**Comment by lisajulia** [comment]
jenkins build this opm-common=4018 please

**Comment by lisajulia** [comment]
jenkins build this opm-common=4018 please

**Comment by lisajulia** [comment]
jenkins build this opm-common=4018 please

**Comment by lisajulia** [comment]
jenkins build this opm-common=4018 please

**Comment by lisajulia** [comment]
jenkins build this opm-common=4018 please

**Comment by bska** [comment]
> jenkins build this opm-common=4018 please

Just a note for future reference: It is **generally** better to trigger builds that involve multiple repositories from the most upstream repository&ndash;in this case from OPM-Common.  The reason is that the CI runner ("jenikins") as a time-saving measure will bypass the unit tests in upstream repositories when the build is triggered from a downstream repository.

**Comment by lisajulia** [comment]
> This looks good but it is not clear if this is a relpacement for #5243 or if it builds on that PR.

Thanks! This will then be a replacement for #5243, I also updated the description just now.

Jenkins is passing now with this PR and https://github.com/OPM/opm-common/pull/4018), after I've resolved the issue with finding the generate_docstring_hpp.py file.

I have two more issues:

- The way of making the docstrings.json from opm-common available here:
https://github.com/OPM/opm-common/pull/4018/files#diff-1e7de1ae2d059d21e1dd75d5812d5a34b0222cef273b7c3a2af62eb747f9d20aR477
https://github.com/OPM/opm-simulators/pull/5336/files#diff-3764531759f1b50aee06cf2267f2ab7508c016a86d776664e4754694fd711bf9R28

- I'm still working on the documentation structure, since now all methods of all classes are listed under "common" but actually they should be grouped

**Comment by hakonhagland** [comment]
> This will then be a replacement for #5243

@lisajulia Ok :) but please clarify why it needs to be a replacement. Why not just build on #5243 ?

**Comment by lisajulia** [comment]
> > This will then be a replacement for #5243
> 
> @lisajulia Ok :) but please clarify why it needs to be a replacement. Why not just build on #5243 ?

Yes, we can also continue with #5243, closing this now

**Pull request closed without merging**
