### PR TITLE
remove template parameters for enableEnergy/Diffusion in transmissibility

### PR DESCRIPTION
**Pull request by akva2**
- the diffusion one is basically done on runtime anyways
- the energy one gives some small code elimination gains
  however, it complicates the writing of downstream templates.

### CODE REVIEW

**Comment by akva2** [comment]
jenkins build this please

**Comment by akva2** [comment]
jenkins build this please

**Comment by bska** [comment]
jenkins build this please

**Review by bska — APPROVED** [review]
Looks good to me.  I'll merge once green.

**Comment by bska** [comment]
Build is green.  Merging as advertised.

**Pull request merged**
