### PR TITLE
Apply gefac also on topmost VREP controlled group

### PR DESCRIPTION
**Pull request by blattms**
We have a model that has a tree of groups (three levels of groups below the topmost group F(topmost)->G1->G2->G3, wells only below G3). When we have a VREP constraint target on G1 and a group efficiency factor g1<1 results are wrong (We actually sometimes inject more than we should and there is a lot of switching in the group control modes). If on the other hand g1 is applied to G2 and G1 has group efficiency factor 1, the results are (nearly) correct.

~This is my rather naive attempt to always apply g1 to the topmost group G1. It does not really work and even worse injection drops to zero at some stage and has problems coming up again.~

~1ce5c598 is how I understood @atgeirr's private comment. (I also tested it standalone and it lead to injection dropping way below production and even production becoming 0 at some time).~

~I need to go back to my desk and rethink what might be happening here (maybe at some occasions applying the group efficiency factor of the VREP controlled group is actually wrong). But if anybody has some hints then they are highly welcome.~

I missed on spot. Fixed in d1f6545 and now reproducing results.

### CODE REVIEW

**Comment by blattms** [comment]
there is a German(?) saying: "you should praise the day before it's end", but the current run looks really promising... First bump is already gone. Let' wait patiently (faster computer faster)

**Comment by blattms** [comment]
jenkins build this please

**Comment by blattms** [comment]
I should have a party tonight! Even jenkins agrees with my code! :love_letter:

**Comment by joakim-hove** [comment]
Great news Markus!

**Comment by blattms** [comment]
Thanks. And it was about time (nearly went nuts).

**Comment by totto82** [comment]
Thanks. The code look good as well. Lets merge it!

> Even jenkins agrees with my code!

That means that the bug you fixed is not exposed in the tests. We should adapt one of the test case to make sure the topmost level is included in the GEFAC test coverage.

**Comment by blattms** [comment]
It also means that I didn't break anything else (which was from obvious to me).

What test covers GEFAC? I might try to add one that fails before this PR (but might need help).

**Pull request merged**
