### PR TITLE
Add gaswater energy simulator

### PR DESCRIPTION
**Pull request by totto82**
Needed in order to run https://github.com/OPM/opm-tests/pull/903

The plan is to add it to the flow executable after some more testing, but the stand alone simulator should be merged first.

### CODE REVIEW

**Comment by totto82** [comment]
jenkins build this please

**Comment by akva2** [comment]
looks like some git adds are missing.

**Comment by totto82** [comment]
jenkins build this please

**Comment by atgeirr** [comment]
Merging this, but the FLOW_SUPPORT_AMG define is weird, as it seems to be unused anywhere else in the system, other than here and the other gas-water simulator instance definitions. @plgbrts can you comment on this? It looks like you originally added it.

**Pull request merged**
