### PR TITLE
UDQ for the injection concentration for WINJFCNC

### PR DESCRIPTION
**Pull request by GitPaean**
downstream of https://github.com/OPM/opm-common/pull/3614 .

### CODE REVIEW

**Comment by GitPaean** [comment]
jenkins build this opm-common=3614 please

**Comment by GitPaean** [comment]
jenkins build this opm-common=3614 please

**Comment by GitPaean** [comment]
jenkins build this opm-common=3614 please

**Review by bska — APPROVED** [review]
This looks good to me now and I'll merge into master.

**Pull request merged**
