### PR TITLE
PerfData: add serialization support

### PR DESCRIPTION
**Pull request by akva2**
Sits on top of https://github.com/OPM/opm-simulators/pull/4433

### CODE REVIEW

**Comment by akva2** [comment]
jenkins build this opm-models=780 opm-common=3388 please

**Comment by bska** [comment]
> Sits on top of #4433

That PR was merged.  Please rebase this onto current master in order to fix the merge conflicts.

**Comment by akva2** [comment]
this one is likely not needed. i'm in the process of rebasing everything to confirm or not. i'll report back in a little.

**Comment by bska** [comment]
> this one is likely not needed. i'm in the process of rebasing everything to confirm or not. i'll report back in a little.

Understood.  I'll hold.

**Comment by akva2** [comment]
indeed. this is not necessary, PerfData is recreated on start of report steps.

**Pull request closed without merging**
