### PR TITLE
[bugfix][ISTLSolverEbos] fix compilation when dune-fem is used in

### PR DESCRIPTION
**Pull request by dr-robertk**
when dune-fem is used in conjunction with opm-simulators.

### CODE REVIEW

**Comment by dr-robertk** [comment]
jenkins build this please

**Comment by dr-robertk** [comment]
@totto82: Could you merge when the test succeeded?

**Comment by blattms** [comment]
I think this is the wrong fix. One should rather make the vanguards adhere to the same interface (i.e. add a correct gridView() method there).  Otherwise this bound to break again.

A test with another grid would be helpful, too.

**Comment by dr-robertk** [comment]
It's the right fix, trust me. When dune-fem is used then the GridView defined in vanguard is not the same as grid().leafGridView(), that is why the compilation fails. So when an ElementMapper with GridView from vanguard is defined, then gridView from vanguard  should be used and not grid().leafGridView(). It's quite simple. Otherwise Grid::LeafGridView should be used. But then the element numbering might differ. So long story short: It's the right fix!

**Comment by blattms** [comment]
Finally got it. Would probably have made sense to put that description in the commit message.

**Comment by totto82** [comment]
Thanks. Merging.

**Pull request merged**
