### PR TITLE
Remove duplicate EBOS based simulators and legacy simulators that has been replaced

### PR DESCRIPTION
**Pull request by akva2**
This
- removes flow_ebos application
- removes flow_ebos_2p application
- removes flow_ebos_polymer application
- removes flow_ebos_solvent application
- removes flow_multisegment_mpi applicaton
- removes flow_multisegment and associated files (i think i got them all)
- removes flow_solvent and associated files (i think i got them all)
- removes flow_mpi application

### CODE REVIEW

**Comment by akva2** [comment]
jenkins build this please

**Comment by andlaus** [comment]
I don't mind that these specialized binaries have been removed because they were redundant. That said, it would probably be a good idea to provide a binary which does somewhat exotic stuff that the standard `flow` binary cannot do; e.g. a two-phase simulator with polymer and solvent enabled?

**Comment by atgeirr** [comment]
> I don't mind that these specialized binaries have been removed because they were redundant. That said, it would probably be a good idea to provide a binary which does somewhat exotic stuff that the standard flow binary cannot do; e.g. a two-phase simulator with polymer and solvent enabled?

When we at some point have that capability, we should instantiate the combination and make it available through flow using the same mechanism as for the existing variants. Is there a reason this cannot or should not be done, other than the potential combinatorial explosion (which will require some judgement eventually)?

**Comment by joakim-hove** [comment]
> other than the potential combinatorial explosion

It is quite seldom I visit the code in opm-simulators, but from this exercise: #1315 I would say that the combinatorial explosion is already brewing.

**Comment by andlaus** [comment]
@atgeirr the combinatorial explosion mentioned by @joakim-hove is the reason; as I see it, the `flow` binary should only include the most common cases. If somebody is interested in something more exotic, he will have to compile his own simulator, but should not be prevented by the code in principle.

**Pull request merged**
