### PR TITLE
Revert PR 1070 to use auto instead of preprocessor statements.

### PR DESCRIPTION
**Pull request by dr-robertk**
I think this is a better approach to achieve what was done in #1070 . If the version numbers are not set correctly the code will fail to compile which is not the case with the approach proposed here.

### CODE REVIEW

**Comment by andlaus** [comment]
for the record: I'm equally fine with both approaches, but be aware that the amount of additional "future-proofness" which this PR provides over #1070 is probably quite limited because I don't think that the Eigen-devs will change this typedef again anytime time. (instead, I consider it likely that they will change something which we don't expect. ;))

**Comment by dr-robertk** [comment]
1070 needs the values of EIGEN_WORLD_VERSION, EIGEN_MAJOR_VERSION, and EIGEN_MINOR_VERSION set correctly. This can easily go wrong when the code is employed on different systems with different cmake version etc. The approach in this PR does not depend on these values that's why I consider it the better solution. But I'm also ok with the current solution. This code is sort of deprecated anyway.

**Comment by andlaus** [comment]
> This can easily go wrong when the code is employed on different systems with different cmake version etc.

as far as I can see, cmake is not involved here for once: these macros are defined by Eigen's `Core/util/Macros.h` header file. anyway, I still don't prefer #1070 over this one or vice versa...

**Comment by babrodtk** [comment]
I guess both approaches have a chance of breaking with future versions of Eigen. 

Looks good to me, and still solves the problem for me using Eigen 3.3!

**Comment by atgeirr** [comment]
I prefer this as it avoids macros. Thanks for the PR!

**Pull request merged**
