### PR TITLE
AdaptiveTimeSteppingEbos: add serialization support

### PR DESCRIPTION
**Pull request by akva2**
Sits on top of https://github.com/OPM/opm-simulators/pull/4416

Required for "perfect" restart.

### CODE REVIEW

**Comment by akva2** [comment]
jenkins build this opm-common=3383 please

**Comment by bska** [comment]
Would you mind rebasing this onto the current master sources to fix the merge conflicts, please?

**Comment by akva2** [comment]
Done.

**Comment by bska** [comment]
jenkins build this please

**Review by bska — APPROVED** [review]
Looks good to me and I'll merge into master.

**Pull request merged**
