### PR TITLE
Ask ebos to formulate the equation by surface volumes directly

### PR DESCRIPTION
**Pull request by totto82**
Avoids some unnecessary re-scaling of the residual and the jacobian. Gives a small speed up on the models I have tested. Depends on OPM/ewoms#205

### CODE REVIEW

**Comment by totto82** [comment]
jenkins build this ewoms=205 please

**Comment by totto82** [comment]
I forgot to remove convertResults()

**Comment by totto82** [comment]
jenkins build this ewoms=205 please

**Comment by totto82** [comment]
jenkins build this ewoms=205 please

**Comment by totto82** [comment]
I am a bit surprised that Jenkins complains about this patch. This just remove one multiplication and one division in ebos and one division and one multiplikasjon in flow.  I have tried it on Model2-rev0 and norne and I observe some noise in the convergence behavior but I didn't observe any changes in the results.

**Comment by bska** [comment]
jenkins run spe norne ewoms=205 please

**Comment by totto82** [comment]
jenkins run spe norne ewoms=205 please

**Comment by bska** [comment]
jenkins run spe norne ewoms=205 please

**Comment by totto82** [comment]
jenkins run spe norne ewoms=205 please

**Comment by totto82** [comment]
I have investigated the cases that fails for this PR (SPE1 and SPE3) manually and the difference in convergence and results is small and almost certainly caused by numerical noise. I will prepare an update off the reference solution.

**Comment by totto82** [comment]
jenkins build this ewoms=205 update_data please

**Comment by andlaus** [comment]
> I have investigated the cases that fails for this PR (SPE1 and SPE3)

it is probably because of different non-bijectivity of floating point arithmetics; in this case probably because, due to rounding errors, dividing y by x and then multiplying by x again is not y in FP arithmetics even if x != 0. cf. OPM/ewoms#205 and OPM/ewoms#208 for a similar discussion.

**Comment by totto82** [comment]
jenkins build this ewoms=205 opm-data=235 please

**Comment by atgeirr** [comment]
Merging!

**Pull request merged**
