### PR TITLE
set bhp control explicilty for well potential calculations

### PR DESCRIPTION
**Pull request by totto82**
This improves the results on the UDQ_WCONPROD case.

### CODE REVIEW

**Comment by totto82** [comment]
jenkins build this update_data please

**Comment by atgeirr** [comment]
Code is fine, assuming tests are only failing due to potential output changing, it is ok to mwefw when green.

**Comment by totto82** [comment]
Only SPE9GROUP and UDQ_WCONPROD have changes in the results. This is expected since the distribution of the group rates depends on well potentials. The SPE9GROUP is essentially unaffected, while UDQ_WCONPROD is improved due to this fix.

**Comment by totto82** [comment]
jenkins build this opm-tests=224

**Comment by totto82** [comment]
jenkins build this opm-tests=224 please

**Comment by totto82** [comment]
jenkins build this update_data please

**Comment by totto82** [comment]
jenkins build this opm-tests=223 please

**Pull request merged**
