### PR TITLE
Tag Unused Parameter as Maybe_Unused

### PR DESCRIPTION
**Pull request by bska**
Noted by [at]akva2

### CODE REVIEW

**Comment by bska** [comment]
jenkins build this please

**Comment by akva2** [comment]
it's not maybe_unused, it's unused, so my personal preference would be to anonymize but i dunno what the policies on that are.

**Comment by bska** [comment]
> my personal preference would be to anonymize [the parameter]

I prefer `[[maybe_unused]]` for the reason that it makes it easier to see what the value is in a debugger and, if we ever get there, to add Doxygen-style documentation for it.  The latter doesn't work if there's no parameter name.

**Comment by bska** [comment]
I'll merge this now to remove the warning.

**Pull request merged**
