### PR TITLE
Add comment about distribution

### PR DESCRIPTION
**Pull request by joakim-hove**
Just a comment which would have helped me when I was scratching my head over: https://github.com/OPM/opm-simulators/issues/3091

### CODE REVIEW

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by bska** [comment]
I'm tempted to say "comments are noise"...

**Comment by joakim-hove** [comment]
>I'm tempted to say "comments are noise"...

Hehe - I guess that was well deserved. Feel dere to close if you are som inclined.

**Comment by bska** [comment]
> > I'm tempted to say "comments are noise"...
> 
> Hehe - I guess that was well deserved.

I just couldn't help myself :wink: 

> Feel free to close if you are so inclined.

No, this is fine and I'll merge this into master.  Maybe we can recognize that comments explaining the **motivation** and/or **context** of something rather than the mere mechanics have a place in the source code.

**Comment by blattms** [comment]
:tada: Looks who is adding comments :+1:

**Pull request merged**
