### PR TITLE
Relaxed epsilon for restart test.

### PR DESCRIPTION
**Pull request by joakim-hove**
Relaxed test tolerances for restart tests.

### CODE REVIEW

**Comment by joakim-hove** [comment]
The current test framework works well as a safety harness, but it is quite time consuming to work with when the failures are nontrivial. Either because they are false positives, or in the case the failures signal a real problem in an incoming patch - the test framework in the current form is of limited value as debugging aid. I would like to propose a more agile approach to the testing framework in general, in particular I have these suggestions:

1. The call to driver routines in https://github.com/OPM/opm-simulators/blob/master/compareECLFiles.cmake is quite opaque, and it seems they all actually call the same test binaries - `${COMPARE_SUMMARY_COMMAND}` and `${COMPARE_ECL_COMMAND}`. I would like to have more small test binaries, and call them more selectively.

2. The test binaries halt the test at first failure, when working with this it would have been convenient to have the output from all the failing checks before the full test binary terminates.

Comments?

**Comment by atgeirr** [comment]
I leave final decisions on these things to @akva2 but here are my comments:
 - One of the tests were not relaxed but tightened, was that intended?
 - What are your suggested more specific test binaries?
 - The output is probably not too hard to get hold of, I seem to remember that there were some ctest options for that. @akva2 or @andlaus probably remembers?

**Comment by akva2** [comment]
1) they call test binaries passed as command line parameters (e.g. $7 and $8 for regressionTest). this is mostly about the fact that opm can build in many ways, so the full path to the binaries must be resolved by cmake, then passed to the script. i do not understand the need for more binaries, the available programs can be used keyword by keyword if you so desire.

2) this would require rewriting to not use exceptions  / throw for errors. i would not object if they were rewritten, this was mostly about sticking to opm code style.

as for the pr contents, i assume this is a correction for 07d90b5c8d58711d905da5ecb6b1896ec9a95272. please reset parallel to the previous values (0.02, 1e-5). or do you actually need the slacker tolerances for these tests as well?

**Comment by joakim-hove** [comment]
> i do not understand the need for more binaries, the available programs can be used keyword by keyword if you so desire.

Well - maybe the problem is in the organisation of `compareECLFiles.cmake`- or maybe I just don't understand. The file `compareECLFiles.cmake`contains sections:

```txt
# TEST: compareECLFiles
...
...
# TEST: compareECLRestartFiles
...
...
# TEST: compareECLInitFiles
...
...
# TEST: parallelECLFiles
```

but in the end of the day *all* call the same test binaries. Cleaning up that - and splitting the `${COMPARE_ECL_COMMAND}` into something like ${COMPARE_RESTART_COMMAND}` - ${COMPARE_INIT_COMMAND}` and ${COMPARE_RFT_COMMAND}$.

> this would require rewriting to not use exceptions / throw for errors

Yes.

> as for the pr contents, i assume this is a correction for 07d90b5. 

That is correct.

> please reset parallel to the previous values (0.02, 1e-5). or do you actually need the slacker tolerances for these tests as well?

I find it a bit difficult to interepret these test results; looking at the cmake setup I would assume that all tests should run even in the case of failure - but when working with this it seems to me that test execution stops when some tests fail? At least #1032 was an attempt to fix: 

https://ci.opm-project.org/job/opm-simulators-PR-builder/218/testReport/

But when looking at: https://ci.opm-project.org/job/opm-simulators-PR-builder/219/testReport/ it still seems to fail:

```txt
Comparing '/var/lib/jenkins/workspace/opm-simulators-PR-builder/mpi/build-opm-simulators/tests/results/restart/flow+spe9/SPE9_CP_SHORT' to '/var/lib/jenkins/workspace/opm-simulators-PR-builder/mpi/build-opm-simulators/tests/results/restart/flow+spe9/SPE9_CP_SHORT_RESTART'.
For keyword BPR:1
(days, reference value) and (days, check value) = (160, 3174.85) and (160, 3174.98)
The absolute deviation is 0.133789. The tolerance limit is 0.02
The relative deviation is 4.21386e-05. The tolerance limit is 1e-05
Program threw an exception: [/var/lib/jenkins/workspace/opm-simulators-PR-builder/deps/opm-output/opm/test_util/summaryRegressionTest.cpp:109] Deviation exceed the limit.
```

so now my hunch was that even though the test was named/prefixed with `mpi` - I was actually struggling with the restart family of test. I.e. - the fix in #1032 was targetting the wrong test - so now I try again. But the argument increased tolerance (*at least* the absolute one) should apply irrespective of MPI or not - so I think the (slightly corrected) changes from #1032 would still be necessary.

**Comment by akva2** [comment]
the test execution is administered by the configured driver script, either tests/run-regressionTest.sh (tests comparing against reference files), tests/run-restartRegressionTest.sh (tests comparing a restarted run vs a not restarted run), tests/run-InitRegressionTest.sh (comparing just the init files of a simulation against reference files) or tests/run-parallelRegressionTest.sh (tests comparing a serial run against a parallel run). the cmake functions sets the appropriate driver, then calls the script with all the necessary parameters.

the mpi in the path is the build configuration used. it is a mpi-enabled build. this has nothing to do with the test being executed, that's in the name of the ctest.

the listed error is in a restart test.

**Comment by joakim-hove** [comment]
> the test execution is administered by the configured driver script [....]

Well - I just reiterate; it is quite opaque and at the very least some more documentation would have helped. 

> the listed error is in a restart test.

Yes - I have understood now; so #1032 was actually fully targetting the wrong tests.

**Comment by akva2** [comment]
i guess more documentation would probably not hurt, though i don't think it would add much to the story that the code doesn't already describe. i have made an attempt in https://github.com/OPM/opm-simulators/pull/1036

**Comment by joakim-hove** [comment]
> i have made an attempt in #1036

Good - I have added some comments there.

**Comment by joakim-hove** [comment]
ping?

**Comment by joakim-hove** [comment]
Thank you for merging.

**Pull request merged**
