### PR TITLE
restrict maximum number of times a well can switch to the same control

### PR DESCRIPTION
**Pull request by totto82**
This can potentially stabilize the convergence in some special cases.

### CODE REVIEW

**Comment by totto82** [comment]
jenkins build this please

**Comment by totto82** [comment]
jenkins build this please

**Comment by totto82** [comment]
I have checked the test failure. With 1 day tuning this PR avoids one convergence problem and thus follow a slightly different convergence path. The results are qualitatively the same.

**Comment by totto82** [comment]
jenkins build this please

**Comment by totto82** [comment]
The feature kicks in for model4 and reduce the number of problems by one. As expected you get some differences in the results. 

image

**Comment by totto82** [comment]
benchmark please

**Comment by bska** [comment]
Please also fix the new [shadowing variable](https://ci.opm-project.org/job/opm-simulators-PR-builder/2889/gcc/fileName.-320325099/source.6a309066-4336-4384-ba3f-92f1a8e6f844/#215) warning before you merge this.

**Comment by totto82** [comment]
jenkins build this please

**Comment by OPMUSER** [comment]
At the moment we have this
```
Starting time step 0, stepsize 1 days, at day 2947/2948, date = 01-Dec-2005
    Switching control mode for well C-1H from RATE to GRUP
    Switching control mode for well C-2H from RATE to GRUP
    Switching control mode for well C-3H from RATE to GRUP
    Switching control mode for well F-1H from RATE to GRUP
    Switching control mode for well F-2H from RATE to GRUP
    Switching control mode for well F-3H from RATE to GRUP
    Switching control mode for well C-4AH from RATE to GRUP
    Switching control mode for well C-2H from GRUP to RATE
    Switching control mode for well C-3H from GRUP to RATE
    Switching control mode for well E-3CH from RESV to BHP
    Switching control mode for well C-1H from GRUP to BHP
    Switching control mode for well F-3H from GRUP to RATE
    Switching control mode for well C-1H from BHP to RATE
    Switching control mode for well C-1H from RATE to BHP
    Switching control mode for well C-4AH from GRUP to RATE
```
Is it possible to change to something like this instead:
```
Starting time step 0, stepsize 1 days, at day 2947/2948, date = 01-Dec-2005
    Well C-1H    control mode changed from RATE->GRUP->BHP ->RATE-> BHP
    Well C-2H    control mode changed from RATE->GRUP->RATE
    Well C-3H    control mode changed from RATE->GRUP->RATE  
    Well C-4AH   control mode changed from RATE->GRUP->RATE   
    Well E-3CH   control mode changed from RESV->BHP
    Well F-1H    control mode changed from RATE->GRUP 
    Well F-2H    control mode changed from RATE->GRUP
    Well F-3H    control mode changed from RATE->GRUP->RATE  
```
or something similar. So that the wells are in alphabetic order and all the changes for a well are on the same line. 

Just a suggestion to improve readability.

**Comment by totto82** [comment]
In https://github.com/OPM/opm-simulators/pull/3410
I suggest a change that will only write out if the well actually changed control during that timestep. i.e not the oscillatory behavior. So BHP-> ORAT-> BHP will  not show in the terminal at all but only in the .DBG file. 
But I liked your solution better. Should be too much work.

**Comment by ytelses** [comment]
Benchmark result overview: 




| Test    | Configuration                                     | Relative |
| ------- | ------------------------------------------------- | -------- |
| opm-git | OPM Benchmark: flow_mpi_norne - Threads: 1        | 1.003    |
| opm-git | OPM Benchmark: flow_mpi_norne - Threads: 8        | 1        |
| opm-git | OPM Benchmark: flow_mpi_norne_4c_msw - Threads: 1 | 0.842    |
| opm-git | OPM Benchmark: flow_mpi_norne_4c_msw - Threads: 8 | 1.054    |
* Speed-up = Total time master / Total time pull request. Above 1.0 is an improvement. *



View result details @ https://www.ytelses.com/opm/?page=result&id=1335

**Comment by ytelses** [comment]
Benchmark result overview: 




| Test    | Configuration                                     | Relative |
| ------- | ------------------------------------------------- | -------- |
| opm-git | OPM Benchmark: flow_mpi_norne - Threads: 1        | 1.003    |
| opm-git | OPM Benchmark: flow_mpi_norne - Threads: 8        | 1.002    |
| opm-git | OPM Benchmark: flow_mpi_norne_4c_msw - Threads: 1 | 0.861    |
| opm-git | OPM Benchmark: flow_mpi_norne_4c_msw - Threads: 8 | 1.046    |
* Speed-up = Total time master / Total time pull request. Above 1.0 is an improvement. *



View result details @ https://www.ytelses.com/opm/?page=result&id=1335

**Comment by totto82** [comment]
Locally 4C with the PR gives a speed up. 
I will re-run the benchmark tomorrow when I am sure a new ref time for model2 is installed on the system. 

diff master PR gives 

```
< Total time (seconds):         1975.70 
< Solver time (seconds):        1975.51 
<  Assembly time (seconds):      678.85 (Failed: 264.2; 38.9%)
<    Well assembly (seconds):    386.11 (Failed: 163.7; 42.4%)
<  Linear solve time (seconds):  852.68 (Failed: 174.4; 20.5%)
<    Linear setup (seconds):      71.09 (Failed: 31.8; 44.7%)
<  Update time (seconds):        128.46 (Failed: 54.5; 42.4%)
<  Pre/post step (seconds):      278.17 (Failed: 8.8; 3.2%)
<  Output write time (seconds):   33.33
< Overall Linearizations:       3376    (Failed: 1239; 36.7%)
< Overall Newton Iterations:    2767    (Failed: 1239; 44.8%)
< Overall Linear Iterations:   61314    (Failed: 10565; 17.2%)
---
> Total time (seconds):         1779.17 
> Solver time (seconds):        1778.99 
>  Assembly time (seconds):      584.96 (Failed: 203.6; 34.8%)
>    Well assembly (seconds):    344.52 (Failed: 131.2; 38.1%)
>  Linear solve time (seconds):  813.57 (Failed: 158.5; 19.5%)
>    Linear setup (seconds):      60.14 (Failed: 23.7; 39.5%)
>  Update time (seconds):        108.74 (Failed: 40.7; 37.4%)
>  Pre/post step (seconds):      239.24 (Failed: 6.7; 2.8%)
>  Output write time (seconds):   28.31
> Overall Linearizations:       2828    (Failed: 924; 32.7%)
> Overall Newton Iterations:    2329    (Failed: 924; 39.7%)
> Overall Linear Iterations:   59134    (Failed: 10222; 17.3%)

```

**Comment by totto82** [comment]
benchmark please

**Comment by ytelses** [comment]
Benchmark result overview: 




| Test    | Configuration                                     | Relative |
| ------- | ------------------------------------------------- | -------- |
| opm-git | OPM Benchmark: flow_mpi_extra - Threads: 1        | 1.001    |
| opm-git | OPM Benchmark: flow_mpi_extra - Threads: 8        | 0.999    |
| opm-git | OPM Benchmark: flow_mpi_norne - Threads: 1        | 1.002    |
| opm-git | OPM Benchmark: flow_mpi_norne - Threads: 8        | 0.994    |
| opm-git | OPM Benchmark: flow_mpi_norne_4c_msw - Threads: 1 | 0.862    |
| opm-git | OPM Benchmark: flow_mpi_norne_4c_msw - Threads: 8 | 1.058    |
* Speed-up = Total time master / Total time pull request. Above 1.0 is an improvement. *



View result details @ https://www.ytelses.com/opm/?page=result&id=1338

**Comment by ytelses** [comment]
Benchmark result overview: 




| Test    | Configuration                                     | Relative |
| ------- | ------------------------------------------------- | -------- |
| opm-git | OPM Benchmark: flow_mpi_extra - Threads: 1        | 0.998    |
| opm-git | OPM Benchmark: flow_mpi_extra - Threads: 8        | 0.996    |
| opm-git | OPM Benchmark: flow_mpi_norne - Threads: 1        | 0.998    |
| opm-git | OPM Benchmark: flow_mpi_norne - Threads: 8        | 0.995    |
| opm-git | OPM Benchmark: flow_mpi_norne_4c_msw - Threads: 1 | 0.862    |
| opm-git | OPM Benchmark: flow_mpi_norne_4c_msw - Threads: 8 | 1.064    |
* Speed-up = Total time master / Total time pull request. Above 1.0 is an improvement. *



View result details @ https://www.ytelses.com/opm/?page=result&id=1338

**Comment by totto82** [comment]
benchmark please

**Comment by totto82** [comment]
benchmark please

**Comment by ytelses** [comment]
Benchmark result overview: 




| Test    | Configuration                                     | Relative |
| ------- | ------------------------------------------------- | -------- |
| opm-git | OPM Benchmark: flow_mpi_extra - Threads: 1        | 0.999    |
| opm-git | OPM Benchmark: flow_mpi_extra - Threads: 8        | 1.006    |
| opm-git | OPM Benchmark: flow_mpi_norne - Threads: 1        | 0.997    |
| opm-git | OPM Benchmark: flow_mpi_norne - Threads: 8        | 1.012    |
| opm-git | OPM Benchmark: flow_mpi_norne_4c_msw - Threads: 1 | 0.989    |
* Speed-up = Total time master / Total time pull request. Above 1.0 is an improvement. *



View result details @ https://www.ytelses.com/opm/?page=result&id=1357

**Comment by ytelses** [comment]
Benchmark result overview: 




| Test    | Configuration                                     | Relative |
| ------- | ------------------------------------------------- | -------- |
| opm-git | OPM Benchmark: flow_mpi_extra - Threads: 1        | 0.994    |
| opm-git | OPM Benchmark: flow_mpi_extra - Threads: 8        | 1.008    |
| opm-git | OPM Benchmark: flow_mpi_norne - Threads: 1        | 0.999    |
| opm-git | OPM Benchmark: flow_mpi_norne - Threads: 8        | 1.012    |
| opm-git | OPM Benchmark: flow_mpi_norne_4c_msw - Threads: 1 | 0.989    |
* Speed-up = Total time master / Total time pull request. Above 1.0 is an improvement. *



View result details @ https://www.ytelses.com/opm/?page=result&id=1357

**Comment by ytelses** [comment]
Benchmark result overview: 




| Test    | Configuration                                     | Relative |
| ------- | ------------------------------------------------- | -------- |
| opm-git | OPM Benchmark: flow_mpi_extra - Threads: 1        | 0.999    |
| opm-git | OPM Benchmark: flow_mpi_extra - Threads: 8        | 1.005    |
| opm-git | OPM Benchmark: flow_mpi_norne - Threads: 1        | 0.996    |
| opm-git | OPM Benchmark: flow_mpi_norne - Threads: 8        | 0.982    |
| opm-git | OPM Benchmark: flow_mpi_norne_4c_msw - Threads: 1 | 0.957    |
| opm-git | OPM Benchmark: flow_mpi_norne_4c_msw - Threads: 8 | 1.141    |
* Speed-up = Total time master / Total time pull request. Above 1.0 is an improvement. *



View result details @ https://www.ytelses.com/opm/?page=result&id=1360

**Comment by ytelses** [comment]
Benchmark result overview: 




| Test    | Configuration                                     | Relative |
| ------- | ------------------------------------------------- | -------- |
| opm-git | OPM Benchmark: flow_mpi_extra - Threads: 1        | 0.995    |
| opm-git | OPM Benchmark: flow_mpi_extra - Threads: 8        | 1.004    |
| opm-git | OPM Benchmark: flow_mpi_norne - Threads: 1        | 0.996    |
| opm-git | OPM Benchmark: flow_mpi_norne - Threads: 8        | 0.988    |
| opm-git | OPM Benchmark: flow_mpi_norne_4c_msw - Threads: 1 | 0.956    |
| opm-git | OPM Benchmark: flow_mpi_norne_4c_msw - Threads: 8 | 1.134    |
* Speed-up = Total time master / Total time pull request. Above 1.0 is an improvement. *



View result details @ https://www.ytelses.com/opm/?page=result&id=1360

**Comment by totto82** [comment]
jenkins build this please

**Comment by totto82** [comment]
This has been an open PR since April. Time to get it merged. For some cases it reduce number of problems significantly. Like NORNE_ATW2013_3A_STDW where number of problems goes from 305 ->  13

**Comment by totto82** [comment]
The test failures is due to minor differences in results after the feature kicks in. I will start the update of reference solution and the merge process later today if no objections.

**Comment by totto82** [comment]
jenkins build this update_data please

**Comment by totto82** [comment]
jenkins build this opm-tests=623 please

**Pull request merged**
