### PR TITLE
changed: only add conditionally built files if they are to be built

### PR DESCRIPTION
**Pull request by akva2**
instead of unconditionally adding, and then conditionally removing
again. follow-up after @andlaus comment yesterday.

istl-conditionals removed since istl is a hard dependency for opm-simulators.

### CODE REVIEW

**Comment by akva2** [comment]
jenkins build this serial please

**Comment by atgeirr** [comment]
Needs a rebase.

**Comment by akva2** [comment]
rebased.

**Comment by atgeirr** [comment]
jenkins build this serial please

**Comment by atgeirr** [comment]
Merging now, sorry for taking so long...

**Pull request merged**
