### PR TITLE
Fixed output units RS and RV.

### PR DESCRIPTION
**Pull request by joakim-hove**
Followup to: https://github.com/OPM/opm-output/pull/153

### CODE REVIEW

**Comment by joakim-hove** [comment]
jenkins build this with opm-output=153 please

**Comment by atgeirr** [comment]
jenkins build this opm-output=153 please

**Comment by joakim-hove** [comment]
OK - just to clarify: The problem is that for decks with FIELD units `RS` and `RV` have been written to disk with the wrong unit conversion. The conversion between SI units and FIELD units has been internally consistent so flow has restarted correctly, but the on-disk values have been wrong. With this PR and https://github.com/OPM/opm-output/pull/153 the on-disk values will be correct, and this will require reference data update.

**Comment by akva2** [comment]
that explains 4 failures, but there is no reference data for the failed restart tests.

**Comment by joakim-hove** [comment]
> that explains 4 failures, but there is no reference data for the failed restart tests.

Hmmm - I agree; the restart failures show up in the summary comparison. Are we certain that master is green; I really do not understand how the current changes could give rise this (famous last words ...).

**Comment by akva2** [comment]
no idea. only have my phone until this afternoon so i'm not able to test right now.

**Comment by joakim-hove** [comment]
jenkins build this opm-output=153 please

**Comment by joakim-hove** [comment]
jenkins build this opm-output=153 please

**Comment by joakim-hove** [comment]
jenkins build this opm-output=153 please

**Comment by joakim-hove** [comment]
OK - now it is only the tests involving reference data which fail.

**Comment by akva2** [comment]
data update eta 30 min if i don't break the nsb wifi by then ;)

**Comment by akva2** [comment]
ran into some local issue (VM kept locking up, updating vbox wasn't a great idea..).

**Comment by akva2** [comment]
jenkins build this opm-output=153 opm-data=155 please

**Comment by alfbr** [comment]
KVM FTW :-)

**Comment by akva2** [comment]
if i was allowed to run a proper os on my laptop i wouldn't need a vm in the first place ;)

**Comment by alfbr** [comment]
That's why I got myself a Thinkpad. We need to ensure that you get proper tools :-)

**Comment by akva2** [comment]
all green.

**Comment by joakim-hove** [comment]
> all green.

Thank you for the data update - merging all over.

**Pull request merged**
