### PR TITLE
Split CO2 Store Handling Out to Helper Functions

### PR DESCRIPTION
**Pull request by bska**
This is mostly to aid readability by avoiding nested conditionals. While here, also remove redundant 'inline' and 'virtual' keywords.

### CODE REVIEW

**Comment by bska** [comment]
jenkins build this please

**Comment by bska** [comment]
jenkins build this please

**Comment by bska** [comment]
jenkins build this please

**Comment by blattms** [comment]
jenkins build this please

**Comment by bska** [comment]
jenkins build this please

**Comment by blattms** [comment]
thanks. looks good.

**Pull request merged**
