### PR TITLE
Split up different tests in include files

### PR DESCRIPTION
**Pull request by alfbr**
Updating compareECLFiles.cmake has become a bit complicated. This is one suggestion in making it easier. Just a suggestion, please shoot if there are ways to do this better. In the mean time I intend to abuse this PR to tidy a bit in opm-tests (a couple of PRs there needs a data update).

### CODE REVIEW

**Comment by alfbr** [comment]
jenkins build this please

**Comment by alfbr** [comment]
jenkins build this please

**Comment by alfbr** [comment]
jenkins build this opm-tests=571 update_data please

**Comment by bska** [comment]
> I think this is a good idea, but we should not change any of the tests in this refactoring

We don't.

> I assume the actual usage here is just as a "dummy" PR to generate the opm-tests PR for another purpose.

True.  The data update is to enable merging OPM/opm-tests#571.

> we should make sure it goes through with a clean jenkins run, without any opm-tests updates.

We will.

**Comment by bska** [comment]
jenkins build this please

**Comment by bska** [comment]
I am in favour of this change and would like to see it go in.  Further refactoring can be made in follow-up PRs.

**Comment by alfbr** [comment]
@blattms @akva2 great if one of you can have a quick look.

**Comment by akva2** [comment]
i'd suggest you put the if() around the include statements instead of inside the include files. that way we save an indent all over those files

**Comment by alfbr** [comment]
jenkins build this please

**Comment by alfbr** [comment]
Looks like everything went through correctly.

**Pull request merged**
