### PR TITLE
fixing the fraction calculation when initializing perf rates

### PR DESCRIPTION
**Pull request by GitPaean**
from the code, it should be the way in this PR for consistency.

### CODE REVIEW

**Comment by GitPaean** [comment]
jenkins build this please

**Comment by totto82** [comment]
benchmark please

**Comment by totto82** [comment]
Thanks. I agree that is make sense to scale with the b factor and not only the mobility. Please update the comment a few lines above your code change. 

>  for producers where all perforations have zero rate we
>     // approximate the perforation mixture using the mobility ratio
>     // and weight the perforations using the well transmissibility.

**Comment by GitPaean** [comment]
jenkins build this please

**Comment by GitPaean** [comment]
The jenkins failures are all checked. Looks okay. 

image

**Comment by GitPaean** [comment]
> Thanks. I agree that is make sense to scale with the b factor and not only the mobility. Please update the comment a few lines above your code change.
> 
> > for producers where all perforations have zero rate we
> > // approximate the perforation mixture using the mobility ratio
> > // and weight the perforations using the well transmissibility.

Thanks. the comments have been added before the for loop.

**Comment by ytelses** [comment]
Benchmark result overview: 




| Test    | Configuration                              | Relative |
| ------- | ------------------------------------------ | -------- |
| opm-git | OPM Benchmark: drogon - Threads: 1         | 1.054    |
| opm-git | OPM Benchmark: drogon - Threads: 8         | 1.134    |
| opm-git | OPM Benchmark: spe10_model_1 - Threads: 1  | 1.043    |
| opm-git | OPM Benchmark: spe10_model_1 - Threads: 8  | 0.995    |
| opm-git | OPM Benchmark: flow_mpi_extra - Threads: 1 | 0.99     |
| opm-git | OPM Benchmark: flow_mpi_extra - Threads: 8 | 0.829    |
| opm-git | OPM Benchmark: flow_mpi_norne - Threads: 1 | 0.991    |
| opm-git | OPM Benchmark: flow_mpi_norne - Threads: 8 | 0.984    |
* Speed-up = Total time master / Total time pull request. Above 1.0 is an improvement. *



View result details @ https://www.ytelses.com/opm/?page=result&id=2107

**Comment by GitPaean** [comment]
referring to 

opm-git | OPM Benchmark: flow_mpi_extra - Threads: 8 | 0.829
-- | -- | --


I used the origional model 2 OMEGA for the test, and the following is the simulation summary. The left is with this PR and the right is the master branch. 

With this PR, there are three time step chopping and four time step chopping with the master branch. But at the end, with this PR, there are about 9 time steps more than the run with the master branch (402 vs 393).  At then end, there are  about 4% more running time with PR for this specific run. Not like the benchmark reported about 18%. I will trigger the benchmark again to check. 

```
7776 ================    End of simulation     ===============                                                              |7752 ================    End of simulation     ===============
7777                                                                                                                        |7753 
7778 Number of MPI processes:         8                                                                                     |7754 Number of MPI processes:         8
7779 Threads per MPI process:         2                                                                                     |7755 Threads per MPI process:         2
7780 Total time (seconds):          619.14                                                                                  |7756 Total time (seconds):          590.23 
7781 Solver time (seconds):         619.00                                                                                  |7757 Solver time (seconds):         590.09 
7782  Assembly time (seconds):       90.44 (Failed: 2.1; 2.4%)                                                              |7758  Assembly time (seconds):       88.40 (Failed: 2.6; 3.0%)
7783    Well assembly (seconds):     15.45 (Failed: 0.3; 2.2%)                                                              |7759    Well assembly (seconds):     15.95 (Failed: 0.6; 3.4%)
7784  Linear solve time (seconds):  417.89 (Failed: 10.3; 2.5%)                                                             |7760  Linear solve time (seconds):  398.06 (Failed: 8.6; 2.2%)
7785    Linear setup (seconds):      29.10 (Failed: 0.8; 2.9%)                                                              |7761    Linear setup (seconds):      29.07 (Failed: 1.0; 3.4%)
7786  Update time (seconds):         47.93 (Failed: 1.3; 2.8%)                                                              |7762  Update time (seconds):         46.79 (Failed: 1.5; 3.2%)
7787  Pre/post step (seconds):       32.68 (Failed: 0.0; 0.0%)                                                              |7763  Pre/post step (seconds):       31.71 (Failed: 0.0; 0.1%)
7788  Output write time (seconds):   21.22                                                                                  |7764  Output write time (seconds):   16.53
7789 Overall Linearizations:       2474    (Failed:  60; 2.4%)                                                              |7765 Overall Linearizations:       2436    (Failed:  69; 2.8%)
7790 Overall Newton Iterations:    2072    (Failed:  60; 2.9%)                                                              |7766 Overall Newton Iterations:    2043    (Failed:  69; 3.4%)
7791 Overall Linear Iterations:   51091    (Failed: 1246; 2.4%)                                                             |7767 Overall Linear Iterations:   49913    (Failed: 996; 2.0%)
7792                                                                                                                        |7768 
```

**Comment by GitPaean** [comment]
benchmark please

**Comment by ytelses** [comment]
Benchmark result overview: 




| Test    | Configuration                              | Relative |
| ------- | ------------------------------------------ | -------- |
| opm-git | OPM Benchmark: drogon - Threads: 1         | 1.038    |
| opm-git | OPM Benchmark: drogon - Threads: 8         | 1.356    |
| opm-git | OPM Benchmark: smeaheia - Threads: 1       | 1        |
| opm-git | OPM Benchmark: smeaheia - Threads: 8       | 0.998    |
| opm-git | OPM Benchmark: spe10_model_1 - Threads: 1  | 1.045    |
| opm-git | OPM Benchmark: spe10_model_1 - Threads: 8  | 1.002    |
| opm-git | OPM Benchmark: flow_mpi_extra - Threads: 1 | 0.995    |
| opm-git | OPM Benchmark: flow_mpi_extra - Threads: 8 | 0.944    |
| opm-git | OPM Benchmark: flow_mpi_norne - Threads: 1 | 0.997    |
| opm-git | OPM Benchmark: flow_mpi_norne - Threads: 8 | 1.025    |
* Speed-up = Total time master / Total time pull request. Above 1.0 is an improvement. *



View result details @ https://www.ytelses.com/opm/?page=result&id=2108

**Comment by GitPaean** [comment]
jenkins build this update_data please

**Comment by GitPaean** [comment]
jenkins build this opm-tests=984 please

**Comment by GitPaean** [comment]
The new benchmark results reflect the local finding regarding 


opm-git | OPM Benchmark: flow_mpi_extra - Threads: 8 | 0.944
-- | -- | --

**Comment by GitPaean** [comment]
This PR is a pure bug fix from the coding level. I am getting this PR in to begin the testing and analysis of the PR #4682, which is the PR that fixes the reported issue.

**Pull request merged**
