### PR TITLE
add test case for rockcomp

### PR DESCRIPTION
**Pull request by akva2**

### CODE REVIEW

**Comment by akva2** [comment]
jenkins build this update_data please

**Comment by akva2** [comment]
jenkins build this update_data please

**Comment by totto82** [comment]
Thanks! This was the next item on my TODO list.

**Comment by akva2** [comment]
jenkins build this update_data please

**Comment by akva2** [comment]
@joakim-hove this fails to run with ENABLE_3DFIELDPROPS_TESTS

```
FieldPropsManager:   0
Eclipse3dProperties: 1
terminate called after throwing an instance of 'std::logic_error'
  what():  Exists error for: ROCKNUM
```

**Comment by joakim-hove** [comment]
Sorry - "fix" here: https://github.com/OPM/opm-common/pull/1274

**Comment by akva2** [comment]
no reason to apologize, WIP is WIP and there was no existing test.

**Comment by joakim-hove** [comment]
jenkins build this update_data please

**Comment by akva2** [comment]
jenkins build this update_data please

**Comment by akva2** [comment]
jenkins build this opm-tests=198 please

**Comment by akva2** [comment]
as this test proved useful even before it hit the repo i think i'll merge this now ;)

**Pull request merged**
