### PR TITLE
Frankenstein merge master

### PR DESCRIPTION
**Pull request by andlaus**
this fixes some serious screw-ups, almost all of them were caused by recent changes in the master
branch:

- there were methods added which depend on the types `V` and
`DataBlock`. these do not make much sense in the context of the
frankenstein simulator. Also, these types are defined globally for the
whole Opm namespace in `BlackoilModelBase_impl.hpp` (which should be
prosecuted as a fellony IMO)! Besides this, their names are useless;
'V' is the letter which comes after `U` in the alphabet and when it
comes to computers basically everything can be seen as a chunk of data
(i.e., a `DataBlock`).
- it seems like the new and shiny dense-AD based well model was never
compiled with assertations enabled, at least some asserts referenced
non-existing variables. Also in the new well code, some asserts within eigen
trigger  if debugging options are enabled. This is rarely a good thing because 
it seems like some out of bounds objects are accessed in arrays.
@totto82: did you already fix this in your recent cleanup branch?  if no, could you please have a look? To reproduce, you just need to compile everything with debug options and run Norne.
- the recent output-related API changes were pretty unfortunate
because they had the effect of tying the (sub-optimal, IMO) internal
structure of the model even closer to the output code: as far as I can
see, `rq` does only make sense if the model works *exactly* like
BlackoilModelBase and friends. (for flow_ebos, this could be
replicated, but first it would be another unnecessary conversion step
and second, most of the quantities in `rq` are of type `ADB` and much
of the "frankenstein" excercise is devoted to getting rid of these.) I
thus reverted back to an old version of the output code and created a
`frankenstein` branch in my personal `opm-output` github fork.

### CODE REVIEW

**Comment by joakim-hove** [comment]
This is waaasy outside my domain, but this PR is massive. If at all possible I would have preferred to merge it piecewise - even at the cost of temporary performance regressions.

**Output:** When it comes to output I don't really understand your comments, but it seems to be more related to the simulator code than the actual output code? In general we can of course change the output API, but it seems like all simulator developers wish for an API  of the type: "Then output appears" with zero impedance matching on the simulator side, that just isn't going to happen.

**Comment by andlaus** [comment]
> This is waaasy outside my domain, but this PR is massive.

well, only kind of: it only includes a few original modifications (the last patch). the remaining 5000 or so lines changes in the diff are caused by the merge of the master branch (this are *just* the changes which happened there during the last ~ 1.5 months!) 

> Output: When it comes to output I don't really understand your comments, but it seems to be more related to the simulator code than the actual output code?

the main problem is that the newish code expects the model to provide a `SimulatorData` object which in turn is expected to contain a `ReservoirResidualQuant` object called `rq`. this pretty much hand-cuffs the `SimulatorFullyImplicitBlackoilOutput` class to the internal structure of the current models. I'll have a look how much effort it takes to replace `SimulatorFullyImplicitBlackoilOutput` by `SimulatorFullyImplicitBlackoilOutputEbos`, though. (yes, `SimulatorFullyImplicitBlackoilOutput` is in `opm-simulators`, but the latest `opm-output` master did also not build with the old version of it,IIRC.)  I yesterday simply did wanted to get the branch build again as quickly as possible...

>  In general we can of course change the output API, but it seems like all simulator developers wish for an API of the type: "Then output appears" with zero impedance matching on the simulator side, that just isn't going to happen.

that's a noble goal, but isn't everything which the  `SimulatorFullyImplicitBlackoilOutput` class does impedance matching?

**Comment by totto82** [comment]
Trying to minimize the usage of Eigen dependent stuff in all new code would help the DenseAD development considerably. As one of the goal with the DenseAD development is to remove the Eigen dependency from the simulator.

**Comment by andlaus** [comment]
Ok, I misread your last statement: I just meant that `SimulatorFullyImplicitBlackoilOutput` currently feels a bit too "magical", but I'm not sure if there's a good solution.

**Comment by alfbr** [comment]
>  In general we can of course change the output API, but it seems like all simulator developers wish for an API of the type: "Then output appears" with zero impedance matching on the simulator side, that just isn't going to happen.

Please elaborate a bit, can you give some examples of impedance matching that probably should be done?

> the recent output-related API changes were pretty unfortunate because they had the effect of tying the (sub-optimal, IMO) internal structure of the model even closer to the output code

Please keep in mind that designing a good interface between opm-output and opm-simulators (and opm-parser for that matter) is a challenging task, and what you see is basically where we are at now. Ideally we would like to have opm-output reusable from different simulators, so your current effort is basically the first test run of that. Hence, I hope the fork can be rejoined with the necessary improvements to the interface(s).

**Comment by jokva** [comment]
What do you mean `SimulatorData` in output?

**Comment by andlaus** [comment]
> What do you mean SimulatorData in output?

I did not mean that it is in the `opm-output` module, but in the `SimulatorFullyImplicitBlackoilOutput` class. BTW: where do the e.g. saturations and pressures come from? It seems like they are not handled by `SimulatorFullyImplicitBlackoilOutput`...

**Comment by andlaus** [comment]
ok, I fixed this branch up enough so that the current master version of `opm-output` can be used again. It's not very efficient (it creates a separate array for each quantity which can be potentially outputted) and not very pretty, but it should get the job done.

**Comment by joakim-hove** [comment]
> Please elaborate a bit, can you give some examples of impedance matching that probably should be done?

I don't have concrete examples - right now I personally feel that the interaction between output and simulators is good in master, but that also means that part of completing this patch is to update it to work against current master of opm-output. In principle the opm-output api could be modified, but then we would break current master in anticipation of this patch. That is in my opinion a *very* special thing to do.

**Comment by atgeirr** [comment]
I believe no changes are needed in opm-output to support this branch, it is simply a question of how to best handle the situation of changes being applied to the master while still developing the branch.

The slight refactoring that was done to support output of derived quantities such as viscosity etc. should not be very hard to duplicate in this branch, in fact I think the underlying structure should support it better than the original master branch did.

**Comment by andlaus** [comment]
> I believe no changes are needed in opm-output to support this branch, it is simply a question of how to best handle the situation of changes being applied to the master while still developing the branch.

that's correct: the opm-output master is supported by the latest version of this PR. @joakim-hove: I just wish there was a more performant and convenient way to determine if a quantity is needed for output and the distinction between saturations and pressure (which are taken from the state and passed as the 4th argument of EclipseWriter::writeTimeStep()) and the remaining quantities (which is a vector of "CellData" and passed as the 5th argument) would be removed.

> The slight refactoring that was done to support output of derived quantities such as viscosity etc. should not be very hard to duplicate in this branch, in fact I think the underlying structure should support it better than the original master branch did.

in principle I agree that this was a change for the better. I'd just like to have "one way to rule them all" because one implementation's "derived" quantities, are another's primary ones ;)

**Comment by atgeirr** [comment]
> one implementation's "derived" quantities, are another's primary ones

I agree in principle (and it should be quite possible), although for the case of restart output we are in a context with a lot of baggage so I don't know if that would take a lot of extra work on the output side. (Extra work it is in any case, so let's do more pressing things first.)

**Comment by andlaus** [comment]
I also don't think that there is a need to hurry on that front. the main reason I propose it is that this would make it easier to abandon the "ReservoirState" class for simulators which do not need it (and if the same approach is used for well quantities, the "WellsState" could be eliminated, too).

**Comment by akva2** [comment]
was the branch 'frankenstein' pushed to origin on purpose ?

**Comment by andlaus** [comment]
> was the branch 'frankenstein' pushed to origin on purpose ?

yep: the idea is to increase its visibility and that people other than me can press green.

**Comment by atgeirr** [comment]
> the idea is to increase its visibility and that people other than me can press green

It was done with my explicit blessing at least. It is a departure and exception compared to our usual PR approach, but since it involves several different people it makes more sense to do it here than on @andlaus' github fork. A drawback is that in confuses people, it's easy to assume all PRs are for merging into the master. Do you have any good alternatives @akva2?

**Comment by akva2** [comment]
not really, and i see no problem with the branch being there. just wanted to check since these things are mishaps more often than not.

**Comment by andlaus** [comment]
ok, I've now also merged #812 into this branch and ran Norne with the result. for me everything worked fine.

**Comment by andlaus** [comment]
I just merged the latest master into this branch, so the monster simulator does not need the other repos (except opm-{common,simulators}) point to revisions other than their current master versions. since the 'frankenstein' branch starts to get long on its teeth, I think this PR here should be merged soon. @totto82: what do you think?

**Comment by joakim-hove** [comment]
Well - I'm not the one calling the shots in this part of town, but if I were, I would have asked kindly for a rebase .... Or is there a reason not to rebase?

**Comment by andlaus** [comment]
> Or is there a reason not to rebase?

yes, there are reasons: First, since the target branch (`frankenstein`) would need to be rebased on top of master, `git pull` would fail for this branch. (Also, I don't know if this can even be done without direct force pushes.) Second, and even more relevantly (at least as far as I'm concerned), rebaseing would be quite a bit more work since merge conflicts need to be solved for every single commit instead of only once which leads to a higher error potential.

A possibly helpful tool (If you don't know it already), to get a better overview of what's going on is `git log --graph`.

**Comment by totto82** [comment]
This only effects the Frankenstein branch. Is there any reason not to merge this asap.

**Comment by atgeirr** [comment]
I leave that up to you, @totto82 and @andlaus.

**Comment by andlaus** [comment]
thanks for your comments. since there is General enough Agreement that this should be merged, i'll show my bad manners once again and self-merge ;)

**Comment by totto82** [comment]
@andlaus Frankenstein does not compile after this merge. It seems like #833 is not included in this PR. (Even though I see it in the list above).

**Comment by andlaus** [comment]
weird: I just checked, it works for me. what does your compiler complain about? also: are you on the `frankenstein` branch of opm-common, (i.e., OPM/opm-common#162) ?

**Comment by andlaus** [comment]
I found the reason: the merge of the removal of the Compat.hpp header from opm-core (which seems to be done just now) has broken the build of the branch. fixed in #846.

**Comment by atgeirr** [comment]
> the merge of the removal of the Compat.hpp header from opm-core (which seems to be done just now) has broken the build of the branch. fixed

Note that we may need to reverse this since it broke opm-upscaling.

**Comment by andlaus** [comment]
> Note that we may need to reverse this since it broke opm-upscaling.

no problem from my perspective -- that will be just another sync with master :)

**Pull request merged**
