### PR TITLE
WIP: added keywords beginning w/B.

### PR DESCRIPTION
**Pull request by stefoss23**
Adding keywords beginning w/B.

### CODE REVIEW

**Comment by stefoss23** [comment]
jenkins build this please

**Comment by stefoss23** [comment]
jenkins build this please

**Comment by stefoss23** [comment]
jenkins build this please

**Comment by joakim-hove** [comment]
It looks like your editor has left some random binary bytes in the commit; maybe the simplest is to just redo the whole thing?!

**Pull request closed without merging**
