### PR TITLE
Make ebos compile with PolyhedralGrid again.

### PR DESCRIPTION
**Pull request by dr-robertk**
This PR fixes various issues when switching ebos from CpGrid to PolyhedralGrid.

### CODE REVIEW

**Comment by dr-robertk** [comment]
jenkins build this please

**Comment by dr-robertk** [comment]
jenkins build this dune2.4 please

**Comment by blattms** [comment]
Sorry, but this looks like a lot of renaming from Equil -> GlobalIO. Is that really necessary? It might pose a lot of additional rebasing work on people currently working on that code. Maybe that can prevented?

**Comment by dr-robertk** [comment]
Superseded  by #2222.

**Pull request closed without merging**
