### PR TITLE
Perforations well index

### PR DESCRIPTION
**Pull request by joakim-hove**
Make sure that all loops over the perforations of a well use an index spanning just over that wells perforations ... clear ehh?? Main point is to pull everything related to the offset of the per-well first perforation outside of the loops.

This is a preparation to be able to use a per-well vector for perforation rates.

### CODE REVIEW

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by joakim-hove** [comment]
Comments to this?

**Comment by totto82** [comment]
> This is a preparation to be able to use a per-well vector for perforation rates.

Cool. Thanks for the effort. I welcome these changes. The structure of the well_state has a long history. Maybe @atgeirr or @bska has some comments. Otherwise I think this can be merged.

**Comment by joakim-hove** [comment]
> I assume this is a confirmed bitwise-identical refactoring?

I will verify that further - but yes it should be bitwise identical.

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by joakim-hove** [comment]
> I assume this is a confirmed bitwise-identical refactoring?

OK - I have now verified bitwise identical results on norne. Will merge when the build check is green.

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by joakim-hove** [comment]
d..n that diff was hard work.

**Comment by bska** [comment]
This PR breaks debug builds.  There is now an [`assert()`](https://github.com/OPM/opm-simulators/blob/950247bf286e069a263828bd415e54bd1df83efa/opm/simulators/wells/WellStateFullyImplicitBlackoil.hpp#L686) which references the symbol `start_perf_next_well` that was removed here.

**Pull request merged**
