### PR TITLE
Revert "Communicate the ebos solution at the beginning of the run method

### PR DESCRIPTION
**Pull request by blattms**
This reverts commit 9adc4d5d3cab514d2707ee5b285ba61b0c441072.

### CODE REVIEW

**Comment by atgeirr** [comment]
I consider this a pure bugfix, restoring parallel performance, so it should be merged and part of the release. OK @andlaus?

**Comment by GitPaean** [comment]
I think it need a jenkins test?

**Comment by atgeirr** [comment]
jenkins build this please

**Comment by GitPaean** [comment]
It looks like with 8 processes, the master branch chops the time step too much after report step 134.  With this PR, convergence looks pretty good.

**Comment by blattms** [comment]
Total time Model 2 with 8 ranks is 2820 and 5932 for this PR and current master, respectively.

**Comment by atgeirr** [comment]
No reply, in any case I'll go ahead and merge this bugfix.

**Comment by andlaus** [comment]
> I consider this a pure bugfix, restoring parallel performance, so it should be merged and part of the release. OK @andlaus?

I guess I noticed this party too late to attend, but yes, the patch is quite simple and if it fixes the parallelization issues which we recently ran into, I surly agree. (it is a regression after all.)

**Pull request merged**
