### PR TITLE
tightenging tolerance for MS cases for regression test

### PR DESCRIPTION
**Pull request by GitPaean**

### CODE REVIEW

**Comment by GitPaean** [comment]
jenkins build this update_data please

**Comment by GitPaean** [comment]
With extra tightening of the tolerance, it does not bring anything further. 

```
The following tests FAILED:
	 43 - compareECLFiles_flow+MSW_MODEL_1 (Failed)
	 45 - compareECLFiles_flow+FAULTS_MODEL_1 (Failed)
	 57 - compareECLFiles_flow+TEST_WSEGSICD (Failed)
Errors while running CTest

```

Some more detailed analysis will be done.

**Comment by alfbr** [comment]
All three cases run with around thirty days time stepping. Limiting the maximum time tep (also available as command line option) seems worth while trying.

**Comment by GitPaean** [comment]
>  Limiting the maximum time tep (also available as command line option) seems worth while trying.

that is a good point. I have not checked about the detailed time stepping behavoir yet.

**Pull request closed without merging**
