### PR TITLE
Add support for MINPVV

### PR DESCRIPTION
**Pull request by totto82**
The test and code for pinchprocessor is removed since it is no
longer used.

Depends on OPM/opm-common#528

### CODE REVIEW

**Comment by bska** [comment]
Am I missing something or does this remove Flow's PINCH handling?  I fully appreciate that the existing process cuts a few corners, but removing it altogether seems presumptuous to me.  Are there are other pull requests coming in the **very** near future that  reimplements the feature?

**Comment by andlaus** [comment]
yes and (hopefully) no: yes because it removes the `DerivedGeology::pinchProcess_()`  code, but no because we are fairly certain that this code is only used by `flow_legacy`, i.e., it does not make much sense to spend time to this class because its only user currently is on the chopping block anyway.

**Comment by bska** [comment]
> yes and (hopefully) no:

I don't get it.  Are you saying that Flow&mdash;whichever version&mdash;is not going to support PINCH?  I don't particularly care about `DerivedGeology::pinchProcess_()`, but I do care about being able to process PINCH in a reasonably faithful manner.

**Comment by andlaus** [comment]
well, the removal at hand does almost certainly only affect `flow_legacy`. It is possible that PINCH is not implemented by non-legacy `flow`, but since this part of the code is quite beasty I will not even bet a beer on this...

**Comment by totto82** [comment]
Line 147 in GeoProps.hpp (legacy)
 // opmfil is hardcoded to be true. i.e the pinch processor is never used
The pinchProcess code was created by Liu Ming, but was never used by the simulator. (both legacy and master) The pinch processing is currently done in the gridding process in opm-grid.

**Comment by joakim-hove** [comment]
I don't know what is the "top-node" for this family of PR's, but I at least confirm that the opm-common PR can be merged when the rest is ready to be merged. I'll leave the actual merging to whoever merges the other PR's.

**Comment by andlaus** [comment]
Somewhat obviously I think that the eWoms part is also ready. i.e. whoever confirms the grid and simulators stuff, may merge the eWoms without having to expect pointy remarks from my side ;)

**Comment by alfbr** [comment]
This has been tested, and confirmed correct from our end.

**Pull request merged**
