### PR TITLE
Improve initialization of the well rates for trivial rates

### PR DESCRIPTION
**Pull request by totto82**
Note the first refactoring commit has its own PR #3183

### CODE REVIEW

**Comment by totto82** [comment]
jenkins build this please

**Comment by totto82** [comment]
benchmark please

**Comment by ytelses** [comment]
Benchmark result overview: 




| Test    | Configuration                                     | Relative |
| ------- | ------------------------------------------------- | -------- |
| opm-git | OPM Benchmark: flow_mpi_extra - Threads: 1        | 1.005    |
| opm-git | OPM Benchmark: flow_mpi_extra - Threads: 8        | 0.982    |
| opm-git | OPM Benchmark: flow_mpi_norne - Threads: 1        | 0.976    |
| opm-git | OPM Benchmark: flow_mpi_norne - Threads: 8        | 1.032    |
| opm-git | OPM Benchmark: flow_mpi_norne_4c_msw - Threads: 1 | 0.825    |
| opm-git | OPM Benchmark: flow_mpi_norne_4c_msw - Threads: 8 | 0.811    |
* Speed-up = Total time master / Total time pull request. Above 1.0 is an improvement. *



View result details @ https://www.ytelses.com/opm/?page=result&id=1172

**Comment by totto82** [comment]
jenkins build this please

**Comment by totto82** [comment]
benchmark please

**Comment by ytelses** [comment]
Benchmark result overview: 




| Test    | Configuration                                     | Relative |
| ------- | ------------------------------------------------- | -------- |
| opm-git | OPM Benchmark: flow_mpi_extra - Threads: 1        | 0.999    |
| opm-git | OPM Benchmark: flow_mpi_extra - Threads: 8        | 0.919    |
| opm-git | OPM Benchmark: flow_mpi_norne - Threads: 1        | 1.02     |
| opm-git | OPM Benchmark: flow_mpi_norne - Threads: 8        | 1.015    |
| opm-git | OPM Benchmark: flow_mpi_norne_4c_msw - Threads: 1 | 0.845    |
| opm-git | OPM Benchmark: flow_mpi_norne_4c_msw - Threads: 8 | 0.795    |
* Speed-up = Total time master / Total time pull request. Above 1.0 is an improvement. *



View result details @ https://www.ytelses.com/opm/?page=result&id=1179

**Comment by totto82** [comment]
jenkins build this please

**Comment by totto82** [comment]
benchmark please

**Comment by ytelses** [comment]
Benchmark result overview: 




| Test    | Configuration                                     | Relative |
| ------- | ------------------------------------------------- | -------- |
| opm-git | OPM Benchmark: flow_mpi_extra - Threads: 1        | 1.009    |
| opm-git | OPM Benchmark: flow_mpi_extra - Threads: 8        | 1.237    |
| opm-git | OPM Benchmark: flow_mpi_norne - Threads: 1        | 1.026    |
| opm-git | OPM Benchmark: flow_mpi_norne - Threads: 8        | 1.026    |
| opm-git | OPM Benchmark: flow_mpi_norne_4c_msw - Threads: 1 | 1.021    |
| opm-git | OPM Benchmark: flow_mpi_norne_4c_msw - Threads: 8 | 0.991    |
* Speed-up = Total time master / Total time pull request. Above 1.0 is an improvement. *



View result details @ https://www.ytelses.com/opm/?page=result&id=1188

**Comment by totto82** [comment]
I have manually checked the test failures. It is mostly the usual noise. 

```
    mpi.compareECLFiles_flow+BASE_MODEL_1 ok
    mpi.compareECLFiles_flow+3D_WECON (58 != 59)
    mpi.compareECLFiles_flow+0_BASE_MODEL2 (65 != 66)
    mpi.compareECLFiles_flow+ACTIONX_M1 ok
    mpi.compareECLFiles_flow+1_MULTREGT_MODEL2 (71 != 64)
    mpi.compareECLFiles_flow+2_MULTXYZ_MODEL2 (57 != 60)
    mpi.compareECLFiles_flow+4_MINPVV_MODEL2 (62 != 61)
    mpi.compareECLFiles_flow+3_MULTFLT_MODEL2 (62 != 61)
    mpi.compareECLFiles_flow+5_SWATINIT_MODEL2 ok
    mpi.compareECLFiles_flow+6_ENDSCALE_MODEL2 (62 != 63)
    mpi.compareECLFiles_flow+8_MULTIPLY_TRANXYZ_MODEL2 (65 != 64)
    mpi.compareECLFiles_flow+7_HYSTERESIS_MODEL2 (64 != 67)
    mpi.compareECLFiles_flow+9_EDITNNC_MODEL2 (63 != 65)
    mpi.compareECLFiles_flow+3D_TRAN_OPERATOR ok
```

**Comment by totto82** [comment]
These changes gives some speed-up according to Benchmark and also local testing. I will start the merging process.

**Comment by totto82** [comment]
jenkins build this update_data please

**Comment by totto82** [comment]
jenkins build this opm-tests=529 please

**Comment by totto82** [comment]
jenkins build this opm-tests=529 please

**Pull request merged**
