### PR TITLE
Two phase bugfixes

### PR DESCRIPTION
**Pull request by babrodtk**
This PR enables running a two phase test case with plausible results

This PR should have no side effects for running existing three phase simulations. See also the twin PR in opm-core which should be merged simultaneously with this one

### CODE REVIEW

**Comment by bska** [comment]
jenkins run norne spe polymer opm-core=1003 please

**Comment by atgeirr** [comment]
With the "EGG" case I get a segfault in step 14, so there are at least some problems still remaining. I'll investigate a little.

**Comment by atgeirr** [comment]
I have identified a bug and fixed it. With the fix the EGG case runs and seems to produce the expected results. The fix is in a PR to your branch @babrodtk.

**Comment by bska** [comment]
> The fix is in a PR to your branch @babrodtk.

Can you also rebase onto current master once you've merged that fix?  I'd prefer to drop the merge commit of this series.

**Comment by babrodtk** [comment]
@atgeirr Thanks for spotting and fixing the water/gas bug that I missed

@bska The rebase has been performed at your request

**Comment by bska** [comment]
> The rebase has been performed at your request

Much appreciated!  I'll launch a Jenkins run to verify that everything's okay.

**Comment by bska** [comment]
jenkins run norne polymer opm-core=1003 please

**Comment by atgeirr** [comment]
Even with some unresolved questions, ref. #665, this is still a marked improvement, I will merge this and the PR in opm-core.

**Pull request merged**
