### PR TITLE
reset the iteration count in the newtonSolver

### PR DESCRIPTION
**Pull request by totto82**
This hopefully fix seg-fault reported in #3000

### CODE REVIEW

**Comment by totto82** [comment]
jenkins build this please

**Comment by blattms** [comment]
I was a bit too fast for jenkins. At least I checked the diff and it seem very ok.. Anyway fingers crossed.

**Comment by bska** [comment]
> This hopefully fix seg-fault reported in #3000

Alas, it did not.  However if I switch the order around a bit then the simulation goes through:
```diff
diff --git a/opm/simulators/flow/BlackoilModelEbos.hpp b/opm/simulators/flow/BlackoilModelEbos.hpp
index f075e5988..33e37b8ca 100644
--- a/opm/simulators/flow/BlackoilModelEbos.hpp
+++ b/opm/simulators/flow/BlackoilModelEbos.hpp
@@ -244,10 +244,12 @@ namespace Opm {
             // episode does not matter, though.)
             ebosSimulator_.setTime(timer.simulationTimeElapsed());
             ebosSimulator_.setTimeStepSize(timer.currentStepLength());
-            ebosSimulator_.problem().beginTimeStep();
+
             // we also need to reset the iteration count
             ebosSimulator_.model().newtonMethod().setIterationIndex(0);
 
+            ebosSimulator_.problem().beginTimeStep();
+
             unsigned numDof = ebosSimulator_.model().numGridDof();
             wasSwitched_.resize(numDof);
             std::fill(wasSwitched_.begin(), wasSwitched_.end(), false);

```

**Comment by totto82** [comment]
@bska I suggest you just make a PR with your fix. Based on your diff you fix looks very obvious. I guess I was a bit too fast with my first fix.

**Comment by bska** [comment]
> I suggest you just make a PR with your fix

Cool.  I've created #3038.

**Pull request merged**
