### PR TITLE
Missing features

### PR DESCRIPTION
**Pull request by joakim-hove**
Added keywords to the list of unsupported keywords in flow.

This should in my opinion be inverted - i.e. `flow` should maintain a list of keywords which *are* completely supported, not the opposite - but that is a larger task. 

The first commit is purely linebreaking; the actualy new content is in the second commit.

### CODE REVIEW

**Comment by andlaus** [comment]
how about adding some usage tracking infrastructure to the parser? e.g. one can add a "bool markUsed" parameter to `deck.getKeyword()` and friends. If that was implemented, the results would automatically be comprehensive.

**Comment by alfbr** [comment]
> This should in my opinion be inverted

With the current handling, inverting would be a better solution. However, we need to add more handling of these unsupported keywords. For instance, we need to single out which of these keywords should trigger a halted simulation. Having one list to work on is then a natural step, so please keep the current set-up.

**Comment by atgeirr** [comment]
> how about adding some usage tracking infrastructure to the parser? e.g. one can add a "bool markUsed" parameter to deck.getKeyword() and friends. If that was implemented, the results would automatically be comprehensive.

I like this approach, I just don't remember why we did not do it already, perhaps there was a good reason not to? In any case, it is not a trivial job: it needs to be performed both on the Deck and EclipseState levels. So it has to provide enough usefulness to be worth it.

On a completely different topic: the author for the commits is not recognized by GitHub as you, @joakim-hove. I hope it is possible to amend the commits to have your usual author string?

**Comment by atgeirr** [comment]
Ping?

**Comment by joakim-hove** [comment]
Sorry - will ammend.

**Comment by joakim-hove** [comment]
OK - author ammended.

**Comment by atgeirr** [comment]
> OK - author ammended.

I recognize that guy...!

Thanks, merging.

**Pull request merged**
