### PR TITLE
 Include All Pertinent EFACs In Guiderate Potential Updates

### PR DESCRIPTION
**Pull request by bska**
This PR switches the helper function
```
WellGroupHelpers::updateGuideRateForGroups<>()
```
to include efficiency factors in the potential rates at grouptree levels below a particular group.  We furthermore switch the helper function
```
WellGroupHelpers::updateGuideRatesForWells<>()
```
to not include efficiency factors at all.

The motivation for this change is that efficiency factors always apply to the level we're accumulating rate values into rather than to the rate values themselves.

### CODE REVIEW

**Comment by bska** [comment]
Note: This PR depends on PR #2709 and must not be merged before that PR is already installed in master.

**Comment by bska** [comment]
jenkins build this please

**Comment by bska** [comment]
@atgeirr : Would you mind reviewing this?  It is part of the larger task to get guiderate summary output that more closely matches those of ECLIPSE&mdash;at least for a selection of models.

**Comment by atgeirr** [comment]
I think the code looks good. If it does the *right thing* I am not quite so certain of, but I believe it may be so. The difference appears to me to be this (please tell me if I misunderstood): when computing the guide rates of some object, we will no longer multiply its potentials by the efficiency factor of the object itself. Assuming that is the behaviour of eclipse (as tested by you) I am fine with this. I think that a priori it is not clear what is the "right" way, but we should be pragmatic enough to give the same behaviour so users get the experience they expect.

**Comment by bska** [comment]
> The difference appears to me to be this (please tell me if I misunderstood): when computing the guide rates of some object, we will no longer multiply its potentials by the efficiency factor of the object itself.

That is correct.  In this PR we apply efficiency factors only when accumulating an object's (well's or group's) potential rates upwards in the group tree.

> Assuming that is the behaviour of eclipse (as tested by you) I am fine with this.

ECLIPSE's rules for efficiency factors (in the range `[0, 1)`) are as follows:

1. An object (well or group) runs at its full rate (production, injection or potential) as implied by the reservoir and control states (and contributions from any levels below it)
2. The efficiency factor reduces the **time** available for the object to run; this impacts total volumes produced/injected attributable to the object
3. To the grouptree level **above** the object it appears as if the object runs for the full timestep, but with a reduced **rate**

The net outcome of this is that individual rate values are unaffected by the object's efficiency factor, but that the efficiency factor must be included when accumulating the object's contributions into the next level upwards in the group tree.

**Comment by bska** [comment]
Advance notice: Unless anyone objects I intend to generate new reference solutions at noon CEST tomorrow (Tuesday 15th September) and then merge this and the upstream PR (OPM/opm-common#1880) once those new reference solutions have been computed.

**Comment by bska** [comment]
Updated reference data and upstream PRs have been merged into master.  Merging this now per prior approval to complete the feature update.

**Pull request merged**
