### PR TITLE
fixed: conditionally build test_csrToCscOffsetMap

### PR DESCRIPTION
**Pull request by akva2**
Fixes build without opencl after #3750

### CODE REVIEW

**Comment by akva2** [comment]
jenkins build this serial please

**Comment by blattms** [comment]
Thanks. Should have tested that myself. Sorry.

**Comment by akva2** [comment]
no worries. that's why we have post builds ;)

**Comment by blattms** [comment]
somehow I did not get the jenkins breakage notification email this time.
Is that sent only to the one opening the merge request and you?

**Comment by akva2** [comment]
yes, commit'er email if registered plus me always.

**Pull request merged**
