### PR TITLE
add radial case to regression test

### PR DESCRIPTION
**Pull request by goncalvesmachadoc**
Radial case can run with https://github.com/OPM/opm-common/pull/2640

### CODE REVIEW

**Comment by alfbr** [comment]
Thank you! This looks good to me, let's see what jenkins says.

**Comment by alfbr** [comment]
jenkins build this please

**Comment by alfbr** [comment]
jenkins build this please

**Comment by bska** [comment]
jenkins build this please

**Comment by akva2** [comment]
jenkins build this update_data please

**Comment by akva2** [comment]
jenkins build this opm-tests=596 please

**Comment by bska** [comment]
The new reference results have been installed on the CI system.  I'll merge this into master now.  Thanks a lot!

**Pull request merged**
