### PR TITLE
Use VFPProdTable constructor

### PR DESCRIPTION
**Pull request by joakim-hove**
Avoid using the `VFPProdTables::init()` and default constructor. Only test code updated.

Can be merged alone, but must be merged before: https://github.com/OPM/opm-common/pull/380

### CODE REVIEW

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by atgeirr** [comment]
Check went through from here, I'll merge!

**Pull request merged**
