### PR TITLE
GasLiftStage2: some cleanups

### PR DESCRIPTION
**Pull request by akva2**
Sits on top of https://github.com/OPM/opm-simulators/pull/3304

### CODE REVIEW

**Comment by akva2** [comment]
jenkins build this please

**Comment by hakonhagland** [comment]
Thanks! This looks very good, though it contains cleanup in other parts of code that are unrelated to `GasLiftStage2`. These changed could have been presented in a separate PR to make review easier.

**Comment by akva2** [comment]
Everything that is not related to directly related to this GasLift had been split out in separate PR's prior. But this code in here did rely on those changes indirectly, so this PR sat on top of those others. They are mostly merged now, there's just one upstream for this one left. Never intended for anyone to start reviewing the final PR first...

**Comment by akva2** [comment]
jenkins build this please

**Comment by akva2** [comment]
jenkins build this please

**Comment by akva2** [comment]
Can this be merged?

**Comment by bska** [comment]
> Can this be merged?

I didn't want to be the one to merge this since gas-lift optimisation is not my area of expertise, but from a purely C++ point of view this looks good.  I'll merge this now.

**Pull request merged**
