### PR TITLE
refactoring the ration economic limit checking

### PR DESCRIPTION
**Pull request by GitPaean**
To reduce the code duplication further and make the extension to GOR, WGR more straightforward.  This PR can go before or after the PR https://github.com/OPM/opm-simulators/pull/1922 .

### CODE REVIEW

**Comment by GitPaean** [comment]
jenkins build this please

**Comment by GitPaean** [comment]
I will adapt PR#1922, so this PR should go in first then PR#1922.

**Comment by GitPaean** [comment]
jenkins build this please

**Review by atgeirr — APPROVED** [review]
Looks fine, can be merged.

**Pull request merged**
