### PR TITLE
EclMpiSerializer for Schedule

### LINKED ISSUE #2467: flow_blackoil_dunecpr broken for parallel runs.
```
Warning: Keyword 'ECHO' is not supported by flow.
In file /home/mblatt/src/dune/opm-2.7/opm-data/spe1/SPE1CASE2.DATA, line 105


Error: Parallel simulator setup is incorrect as it does not use ParallelEclipseState (std::bad_cast)

Error: Parallel simulator setup is incorrect as it does not use ParallelEclipseState (std::bad_cast)
Program threw an exception: Could not distribute the vanguard data: std::bad_cast (on rank 0)
--------------------------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code. Per user-direction, the job has been aborted.
--------------------------------------------------------------------------
--------------------------------------------------------------------------
mpirun detected that one or more processes exited with non-zero status, thus causing
the job to be terminated. The first process to do so was:
```

I guess the setup needs to be corrected, it does not seem to reflect the recent changes of reading the input file only on one process.

### PR DESCRIPTION
**Pull request by akva2**
Downstream of https://github.com/OPM/opm-common/pull/1565

Closes #2467

### CODE REVIEW

**Comment by akva2** [comment]
I included (a working version of) #2474 here.

**Comment by akva2** [comment]
jenkins build this opm-common=1565 please

**Comment by blattms** [comment]
> I included (a working version of) #2474 here.

Next time please make sure to give credit. I would have assumed that someone else would have appeared as author of 1ea535bca. Why didn't you just cherry-pick and amend?

**Comment by akva2** [comment]
sorry about that. i did actually do that but then i screwed up the amending. it's fixed now.

**Pull request merged**
