### PR TITLE
flow: remove the Newton-Raphson "update stabilization"

### PR DESCRIPTION
**Pull request by andlaus**
for the tests which I tested (Norne, Model 2 base case), the update "stabilization" only lead to worse performance while it did not improve convergence behavior. nevertheless, this PR requires thorough testing before merge as well as an update of the reference results.

### CODE REVIEW

**Comment by andlaus** [comment]
jenkins build this update_data please

**Comment by totto82** [comment]
@osae did some testing on this a while ago and concluded the same. He also tried to tune it differently and/or modify it slightly without any success. From theory this should by a good idea, but I guess the difficulty is to make it robust enough to work across several type of models. I am fine with removing this.

**Comment by alfbr** [comment]
I would like to see performance on full ensembles before removal. What was the impact on norne and model 2?

**Comment by GitPaean** [comment]
Why not just change the default parameter `use_update_stabilization` to be false and keep it as a option first in case there is some cases we need to it for testing purpose?

And also, if you want to remove it, you need to remove the member variable `use_update_stabilization_`.

**Comment by GitPaean** [comment]
And also, please share the testing output performance summary for discussion.

**Comment by andlaus** [comment]
I prefer to remove this code outright because keeping unused code around leads to confusion and and encourages unnecessary programming errors. (you do not keep your old shoes from ten years ago around, do you?) if this functionality ought to be brought back to life, it can always be salvaged from the annals of git.

about performance: for Norne, the situation on master is this on my machine:

```
Total time (seconds):         699.11
Solver time (seconds):        695.952
 Assembly time (seconds):     328.017 (Failed: 10.8504; 3.30787%)
 Linear solve time (seconds): 341.947 (Failed: 12.7523; 3.72932%)
 Update time (seconds):       16.1458 (Failed: 0.558969; 3.46201%)
 Output write time (seconds): 4.07963
Overall Well Iterations:      976 (Failed: 21; 2.15164%)
Overall Linearizations:       1937 (Failed: 66; 3.40733%)
Overall Newton Iterations:    1598 (Failed: 66; 4.13016%)
Overall Linear Iterations:    24133 (Failed: 935; 3.87436%)
```

while with this PR, I get:

```
Total time (seconds):         685.924
Solver time (seconds):        682.768
 Assembly time (seconds):     321.306 (Failed: 7.35365; 2.28867%)
 Linear solve time (seconds): 336.183 (Failed: 9.76216; 2.90383%)
 Update time (seconds):       15.4571 (Failed: 0.382625; 2.4754%)
 Output write time (seconds): 4.06257
Overall Well Iterations:      964 (Failed: 12; 1.24481%)
Overall Linearizations:       1912 (Failed: 44; 2.30126%)
Overall Newton Iterations:    1574 (Failed: 44; 2.79543%)
Overall Linear Iterations:    23686 (Failed: 689; 2.90889%)
```

the change here is less than what I experienced when I did casual testing, but I'm pretty sure that this is because I did not make an effort to reduce performance variability in the first attempt.

for the base case of model 2, the total sequential runtime as well as the number of newton and linear iterations is also down with this PR, but each less than 2% (none of these numbers was worse).

@alfbr: I cannot provide results for the whole Model 2 ensemble because I neither have the computational resources to run it nor do I currently have all datasets, i.e. running it probably needs to be done on your side.

**Comment by andlaus** [comment]
jenkins build this opm-tests=46 please

**Comment by totto82** [comment]
Note that #1542 may also have an impact on the convergence for some models. Since none of them are expected to cause any trouble, maybe they can be tested together?  Also I can do some pre-testing on this PR on a selection of models before going the full step of doing a complete ensemble run.

**Comment by alfbr** [comment]
Thanks for the performance numbers! Sure, ensemble testing can be done on my end. 2% is quite nice I would say.

**Comment by totto82** [comment]
I have tested this on the problematic model 2 realization 5: 
```

diff Model2-5/flowebos170818/Model2-5.PRT Model2-5/remove_update_stabilization/Model2-5.PRT

< Total time (seconds):         4678.07
< Solver time (seconds):        4667.47
<  Assembly time (seconds):     2261.42 (Failed: 672.557; 29.7405%)
<  Linear solve time (seconds): 2267.28 (Failed: 575.601; 25.3873%)
<  Update time (seconds):       113.25 (Failed: 35.323; 31.1903%)
<  Output write time (seconds): 16.0458
< Overall Well Iterations:      2027 (Failed: 475; 23.4336%)
< Overall Linearizations:       7306 (Failed: 2163; 29.6058%)
< Overall Newton Iterations:    6640 (Failed: 2163; 32.5753%)
< Overall Linear Iterations:    79181 (Failed: 18177; 22.9563%)
---
> Total time (seconds):         4719.82
> Solver time (seconds):        4709.2
>  Assembly time (seconds):     2393.54 (Failed: 723.682; 30.2348%)
>  Linear solve time (seconds): 2172.45 (Failed: 547.14; 25.1853%)
>  Update time (seconds):       117.175 (Failed: 37.1167; 31.6764%)
>  Output write time (seconds): 16.4728
> Overall Well Iterations:      2048 (Failed: 508; 24.8047%)
> Overall Linearizations:       7848 (Failed: 2365; 30.1351%)
> Overall Newton Iterations:    7158 (Failed: 2365; 33.04%)
> Overall Linear Iterations:    72772 (Failed: 16060; 22.0689%)

```

My conclusion last time we looked at the newton stabilization was
1) Stabilization is a good idea
2) The current implementation is not optimal 
3) It is hard to implement something that is robust. Works when it should and don't mess up the performance to much when it is not needed. 

I still conclude the same. Therefore I would suggest that we keep the current implementation until we come up with something better.

**Comment by andlaus** [comment]
okay, let's close this then.

**Pull request closed without merging**
