### PR TITLE
only enforcing production economic limit to producers.

### PR DESCRIPTION
**Pull request by GitPaean**
After consideration, decided not to enforce this through the parser level, since a well can switch back and forth between injector and producer.

At the end, it has to be confirmed through testing.

### CODE REVIEW

**Comment by GitPaean** [comment]
jenkins build this please

**Comment by GitPaean** [comment]
Although comparing with adding some logic to the parser, there might be some different consequence when a complicated `SCHEDULE` is used. But this PR itself should be good to go in since it is correct NOT to shut any injector due to economic limit, which is clear with the definition of `WECON`.

**Comment by GitPaean** [comment]
jenkins build this please

**Review by bska — APPROVED** [review]
Thanks a lot for the updates.  I'll merge into master.

**Comment by GitPaean** [comment]
> I guess the provided test case should also be added to the regression tests? Agreed @vkip?

Maybe let us modify an existing one to avoid increasing the numbers of the regression tests?

**Pull request merged**
