### PR TITLE
Create a CpGrid with LGRs from LgrCollection

### PR DESCRIPTION
**Pull request by aritorto**
Create a CpGrid with LGRs from LgrCollection

### CODE REVIEW

**Comment by aritorto** [comment]
jenkins build this please

**Comment by blattms** [comment]
Thanks. Should we put this into draft mode?

**Comment by aritorto** [comment]
Yes, it's a draft now!

**Comment by aritorto** [comment]
jenkins build this please

**Comment by aritorto** [comment]
jenkins build this please

**Comment by aritorto** [comment]
jenkins build this please

**Comment by aritorto** [comment]
jenkins build this please

**Comment by blattms** [comment]
A short heads up: Some of these files might be moved soon. See e.g. #5179 #5180

**Comment by aritorto** [comment]
jenkins build this please

**Comment by aritorto** [comment]
\Closing it since it got replaced/corrected by OPM/opm-simulators#5190

**Comment by aritorto** [comment]
Closing it since it got replaced/corrected by OPM/opm-simulators#5190

**Comment by aritorto** [comment]
jenkins build this please

**Pull request closed without merging**
