### PR TITLE
adapt to the EclMaterialLawManager's rename of the *Pointer methods

### PR DESCRIPTION
**Pull request by andlaus**

### CODE REVIEW

**Comment by atgeirr** [comment]
jenkins build this opm-material=156

**Comment by akva2** [comment]
jenkins build this opm-material=156 please

**Comment by andlaus** [comment]
be always friendly to jenkins ;)

**Comment by atgeirr** [comment]
Ah yes, thanks. Where is this documented btw? (If it is...)

**Comment by andlaus** [comment]
if you're happy (or rather not totally unhappy) with this PR, please feel free to also merge  OPM/opm-material#156

**Comment by akva2** [comment]
the documentation is nowhere to be found, apart from the instruction email i sent some time back.

**Comment by atgeirr** [comment]
> instruction email i sent some time back

Was this to the mailing list? I struggle to find it. I'd like to put it on the Wiki for easier reference.

**Comment by akva2** [comment]
On 06. juli 2016 14:52, Atgeirr Flø Rasmussen wrote:
>
>     instruction email i sent some time back
>
> Was this to the mailing list? I struggle to find it. I'd like to put 
> it on the Wiki for easier reference.
>
>
no, i only sent it to maintainers.

**Pull request merged**
