### PR TITLE
Added more cases/models to ctest

### PR DESCRIPTION
**Pull request by akva2**
- Adds two more test cases
- Refactoring
- Use a separate result directory for each tests (aids parallel execution, more tidy)

Replaces #771

### CODE REVIEW

**Comment by akva2** [comment]
jenkins build this opm-common=161 opm-output=90 opm-data=133 please

**Comment by akva2** [comment]
jenkins build this opm-common=161 opm-output=90 please

**Comment by akva2** [comment]
jenkins build this opm-common=174 opm-output=90 please

**Comment by akva2** [comment]
jenkins build this opm-common=174 opm-output=90 opm-data=134 please

**Comment by akva2** [comment]
everything works fine. i have checked 'run spe'  locally and on the jenkins machine. ready for merge.

**Comment by atgeirr** [comment]
I'm not sure how independent these changes are between repos, so I'm reluctant to press the button just for this PR.

In any case, you have license to merge this at will, @akva2.

**Pull request merged**
