### PR TITLE
reset target from wconprod and wconinje

### PR DESCRIPTION
**Pull request by totto82**
In eagerness to fix one issue I accidentally introduced another. Interesting that this did not surface during testing. Don't we have any test that start as history and move to prediction?

### CODE REVIEW

**Comment by totto82** [comment]
jenkins build this please

**Comment by GitPaean** [comment]
> Don't we have any test that start as history and move to prediction?

We had a field case a few years ago that moves from history to prediction.  We should get one in the regression test.

**Comment by GitPaean** [comment]
benchmark please

**Comment by totto82** [comment]
The `NORNE_ATW2013_B1H_RE-PERF ` failure is caused by a real fix, the other failures are noise. Lets wait for benchmark, but this fix a real bug and should be merge as soon as possible.

**Comment by GitPaean** [comment]
> The NORNE_ATW2013_B1H_RE-PERF failure is caused by a real fix, 

Can you give a little details about this? I looked at the schedule, did not get a immediate clue.

**Comment by GitPaean** [comment]
The code looks fine. When some schedule event happens, we use the control from the deck. I think this is reasonable to do.

**Comment by totto82** [comment]
```
WCONHIST 
     'B-1H'      'OPEN'      'ORAT'      0.000      0.000      0.000  5* /
/


-- 511.000000 days from start of simulation ( 6 'NOV' 1997 )
DATES
 1 'APR' 1999 /
/

WCONHIST 
     'B-1H'      'OPEN'      'RESV'   4334.313      0.000 832512.553  5* /
/
```
Current master sets the ORAT limit to 4334.313. Not the RESV limit given by converting ORAT, WRAT, GRAT to RESV.  


image

**Comment by GitPaean** [comment]
> Current master sets the ORAT limit to 4334.313. Not the RESV limit given by converting ORAT, WRAT, GRAT to RESV.

Thanks for the explanation. It looks right to me.

**Comment by GitPaean** [comment]
jenkins build this update_data please

**Comment by ytelses** [comment]
Benchmark result overview: 




| Test    | Configuration                                     | Relative |
| ------- | ------------------------------------------------- | -------- |
| opm-git | OPM Benchmark: flow_mpi_extra - Threads: 1        | 0.975    |
| opm-git | OPM Benchmark: flow_mpi_extra - Threads: 8        | 1.003    |
| opm-git | OPM Benchmark: flow_mpi_norne - Threads: 1        | 1        |
| opm-git | OPM Benchmark: flow_mpi_norne - Threads: 8        | 0.998    |
| opm-git | OPM Benchmark: flow_mpi_norne_4c_msw - Threads: 1 | 1.001    |
| opm-git | OPM Benchmark: flow_mpi_norne_4c_msw - Threads: 8 | 1.001    |
* Speed-up = Total time master / Total time pull request. Above 1.0 is an improvement. *



View result details @ https://www.ytelses.com/opm/?page=result&id=1126

**Comment by bska** [comment]
jenkins build this opm-tests=510 please

**Comment by GitPaean** [comment]
jenkins build this opm-tests=510 please

**Comment by bska** [comment]
New reference solutions have been installed on the CI system.  Merging this now to bring the overall system back to a consistent state.

**Pull request merged**
