### PR TITLE
WellGroupHelpers: make templates private

### PR DESCRIPTION
**Pull request by akva2**
use explicit template instantation. to avoid rebuilding
this code over and over (minor), and to avoid includes in headers.

### CODE REVIEW

**Comment by akva2** [comment]
jenkins build this serial please

**Comment by akva2** [comment]
jenkins build this serial please

**Comment by akva2** [comment]
jenkins build this serial please

**Review by bska — APPROVED** [review]
Thanks.  I'll merge this into master.

**Pull request merged**
