### PR TITLE
Clean opencl kernels rebased (rebased #3749)

### PR DESCRIPTION
**Pull request by blattms**
Moves all OpenCL kernels to *.cl files and uses Cmake to combine.
    
Kernel files are located in opm/simulators/linalg/bda/opencl/kernels. CMake will combine them for usage in     ${PROJECT_BINARY_DIR}/clSources.cpp that becomes part of the library.

I renamed the debug variable to indicate that it is for intel,

@ducbueno Still had your branch lying around and just cherry-picked the relevant commits on top of master.

### CODE REVIEW

**Comment by blattms** [comment]
jenkins build this serial please

**Comment by blattms** [comment]
maybe I have messed up things:
```
Error: [opm/simulators/linalg/bda/openclSolverBackend.cpp:204] OpenCL Error: clBuildProgram(-11)
CL_BUILD_PROGRAM_FAILURE, kernels in openclKernels.hpp cannot be compiled
Program threw an exception: [opm/simulators/linalg/bda/openclSolverBackend.cpp:204] OpenCL Error: clBuildProgram(-11)
CL_BUILD_PROGRAM_FAILURE, kernels in openclKernels.hpp cannot be compiled
```
Well, I am also getting this on your original branch.

**Comment by blattms** [comment]
Might be the mesa drivers on my system only supportint OpenCL 1.1

**Comment by ducbueno** [comment]
Hello Markus. Maybe it really is a problem related to your drivers only supporting OpenCL 1.1. I've cloned your branch to my system and I got no errors.

**Comment by blattms** [comment]
Indeed, on my other machine (NVIDIA) it works. Really need to get Rocm working on Debian stable ...

One more jenkins run and I'll merge.

**Comment by blattms** [comment]
Did you checks runs before this and after on some models?

**Comment by ducbueno** [comment]
Yes. I ran on Norne, SPE3 and SPE1. I can run some more if you like.

**Comment by blattms** [comment]
cool. in it goes.

**Comment by blattms** [comment]
Thanks again for this. Really appreciated.

**Comment by blattms** [comment]
:cold_face: Forgot to call jenkins. Lets see what happens.

**Pull request merged**
