### PR TITLE
Only compute the initial solution once. 

### PR DESCRIPTION
**Pull request by totto82**
1) Trust ebos to provide the correct initial solution also when SWATINIT is applied. 
2) Use the code in ebos for the explicit setting of the initial solution using (PRESSURE, SWAT etc. )
3) Output the initial solution from ebos. 

Tested on Model 2. 

Depends on OPM/ewoms#241

### CODE REVIEW

**Comment by totto82** [comment]
jenkins build this ewoms=241 please

**Comment by blattms** [comment]
> Tested on Model 2. 

In a parallel run?

**Comment by totto82** [comment]
Yes. Results and performance stays the same.

**Comment by totto82** [comment]
Har verifisert at resultatene på SPE5CASE1 og 2D_THREEPHASE_POLY_HETER ikke er endret signifikant. Hva med å endre max_iter på disse ustabile casene slikt at de ikke feiler? Det vil gjøre testene mer stabile for små pertubasjoner.

**Comment by atgeirr** [comment]
> How about changing max_ites on these unstable cases so they do not fail? This will make the tests more stable for small perturbations.

I would think that setting the first timestep to one day would improve this, does it fail and chop in a later timestep?

**Comment by totto82** [comment]
Yes. The polymer and solvent injections happens later. Increasing the max_iter on these cases to make sure they do not fail at all would be an improvement. I have tested it, but my network on my linux machine is down for the moment so no PRs from me in awhile....

**Comment by GitPaean** [comment]
> How about changing max_ites on these unstable cases so they do not fail? This will make the tests more stable for small perturbations.

I think we should stay with the default parameter when possible. Do we have any investigation how the default max_iter affect the performance? Maybe 10 is not optimal?

**Comment by totto82** [comment]
I just want to change the tests to make Jenkins less grumpy.

**Comment by GitPaean** [comment]
> I just want to change the tests to make Jenkins less grumpy.

Sure. I see.

**Comment by totto82** [comment]
jenkins build this ewoms=241 please

**Comment by atgeirr** [comment]
jenkins build this ewoms=241 please

**Comment by atgeirr** [comment]
jenkins build this ewoms=241 please

**Comment by totto82** [comment]
jenkins build this ewoms=241 please

**Comment by totto82** [comment]
I found the reason for the deviation. Due to changes in the number of iterations the suggested timestep differ slightly. By chance current master want to take an extra substep in February. I will update the ref-data.   
```

31: (days, reference value) and (days, check value) = (4, 0) and (4, 0)
31: The absolute deviation is 0. The tolerance limit is 0.02
31: The relative deviation is 0. The tolerance limit is 0.01
31: For keyword WBHP:INJG
31: (days, reference value) and (days, check value) = (12.8539, 0) and (12.9103, 0)
31: The absolute deviation is 0. The tolerance limit is 0.02
31: The relative deviation is 0. The tolerance limit is 0.01
31: For keyword WBHP:INJG
31: (days, reference value) and (days, check value) = (21.927, 0) and (21.9552, 0)
31: The absolute deviation is 0. The tolerance limit is 0.02
31: The relative deviation is 0. The tolerance limit is 0.01
31: For keyword WBHP:INJG
31: (days, reference value) and (days, check value) = (31, 0) and (31, 0)
31: The absolute deviation is 0. The tolerance limit is 0.02
31: The relative deviation is 0. The tolerance limit is 0.01
31: For keyword WBHP:INJG
31: (days, reference value) and (days, check value) = (47.4451, 0) and (59, 0)
31: The absolute deviation is 0. The tolerance limit is 0.02
31: The relative deviation is 0. The tolerance limit is 0.01
31: For keyword WBHP:INJG
31: (days, reference value) and (days, check value) = (59, 0) and (77.5424, 0)
31: The absolute deviation is 0. The tolerance limit is 0.02
31: The relative deviation is 0. The tolerance limit is 0.01
31: For keyword WBHP:INJG
31: (days, reference value) and (days, check value) = (77.5288, 0) and (90, 0)
31: The absolute deviation is 0. The tolerance limit is 0.02
31: The relative deviation is 0. The tolerance limit is 0.01
```

**Comment by totto82** [comment]
jenkins build this update_data please

**Comment by totto82** [comment]
jenkins build this  ewoms=241 update_data please

**Comment by totto82** [comment]
jenkins build this ewoms=241 opm-data=283 please

**Comment by totto82** [comment]
jenkins build this ewoms=241 opm-data=283 please

**Pull request merged**
