### PR TITLE
tightenging tolerance for MS cases for regression test

### PR DESCRIPTION
**Pull request by GitPaean**

### CODE REVIEW

**Comment by GitPaean** [comment]
jenkins build this update_data please

**Comment by alfbr** [comment]
Looks good. Please confirm if tests pass on your end. Once confirmed, and green, it goes in.

**Comment by akva2** [comment]
jenkins build this opm-tests=262 please

**Comment by GitPaean** [comment]
> Looks good. Please confirm if tests pass on your end. Once confirmed, and green, it goes in.

It is still in the WIP stage. I will notify when it works.

**Comment by GitPaean** [comment]
jenkins build this opm-tests=262 please

**Comment by GitPaean** [comment]
Okay. locally, it fixes the regression test failure except the `SICD` case. 

I guess we should merge this one if Jenkins gave green.

**Comment by alfbr** [comment]
Excellent, that leaves only one more test to fix. Thanks for your patience! Merging.

**Pull request merged**
