### PR TITLE
Fix parallel ebos

### PR DESCRIPTION
**Pull request by blattms**
Ebos was not running in parallel for  quite some will (due to only reading the deck on one process). This PR fixes this but might require more testing with the special ebos variants. I have test flow and ebos for some basic models.

Note that code for reading the ECL file and constructing the objects has been refactored and moved from Main.hpp to readDeck.[hc]pp and gets reused in EclBaseVanguard (and hence from ebos).

Based on and includes #2725.

### CODE REVIEW

**Comment by blattms** [comment]
jenkins build this serial parallel please

**Comment by blattms** [comment]
jenkins build this

**Comment by bska** [comment]
> jenkins build this

please?

**Comment by bska** [comment]
jenkins build this please

**Comment by blattms** [comment]
Yep, I forgot my manner. Thanks for chipping in.

Please be aware that there is one semantic change:
- Whenever EnableExperiments is true we do now check the array dimension. This does not happen in flow, but in ebos and in (some?) of the tests. That is why there is a change in one of the data files.

**Comment by blattms** [comment]
@totto82 Would be nice if you would check other ebos_* variants besides blackoil.

**Comment by totto82** [comment]
Thanks for the fix. I can test it for other versions.

**Comment by blattms** [comment]
Resolved the conflicts. would be nice if this would be merged soon.

**Comment by blattms** [comment]
jenkins build this please

**Comment by blattms** [comment]
:angry: Why do I merge other stuff and create conflicts in my own PRs?

**Comment by blattms** [comment]
Poor little jenkins.

**Comment by blattms** [comment]
jenkins build this please

**Comment by totto82** [comment]
I have tested the most relevant ebos extentions. And they works. Thanks for the fix. Please feel free to merge when green.

**Comment by blattms** [comment]
in it goes.

**Comment by blattms** [comment]
thanks a lot for testing.

**Pull request merged**
