### PR TITLE
move ebos/ecldummygradientcalculator.hh to opm/simulators/flow

### PR DESCRIPTION
**Pull request by akva2**

### CODE REVIEW

**Comment by akva2** [comment]
jenkins build this please

**Review by blattms — APPROVED** [review]
Nice. Was about to trigger merge, but maybe we should run jenkins again? I am a bit unsure.

**Comment by blattms** [comment]
jenkins build this please

**Comment by akva2** [comment]
as long as there are no conflicts it should be fine to merge.

**Comment by akva2** [comment]
jenkins build this please

**Comment by akva2** [comment]
merging per approval

**Pull request merged**
