### PR TITLE
support item 4 wvfpexp

### PR DESCRIPTION
**Pull request by totto82**
Since default is NO for WVFPEXP item 4 this fixes unexpected behavior in Flow that was introduced in https://github.com/OPM/opm-simulators/pull/3824

### CODE REVIEW

**Comment by totto82** [comment]
jenkins build this please

**Review by atgeirr — APPROVED** [review]

**Comment by totto82** [comment]
The test failures are the same cases that needed an update with #3824. I will ask for new reference data that will take the state of this cases back to before #3824. None of these cases have WVFPEXP.

**Comment by totto82** [comment]
jenkins build this update_data please

**Comment by totto82** [comment]
jenkins build this opm-tests=745 please

**Pull request merged**
