### PR TITLE
Remove legacy simulators

### PR DESCRIPTION
**Pull request by akva2**
Moved to a separate repo.

### CODE REVIEW

**Comment by atgeirr** [comment]
jenkins build this please

**Comment by akva2** [comment]
not yet.

**Comment by atgeirr** [comment]
I add a question mark to the please next time...

**Comment by akva2** [comment]
jenkins build this please

**Comment by akva2** [comment]
okay, merge at will.

**Comment by atgeirr** [comment]
> I'm pretty sure that a lot of code in opm-grid and opm-common is now also unused. (e.g. almost all the C code) Shouldn't this stuff also be moved to opm-simulators-legacy?

I think there might be less of it than you think, but if you identify such code, please make a proposal!

**Pull request merged**
