### PR TITLE
Fix opencl apply stdwells rebased (replaces #3746)

### PR DESCRIPTION
**Pull request by blattms**
Took @Tongdongq's PR #3746 and adjusted it to the new opencl kernels structure (see #3754 )

### CODE REVIEW

**Comment by blattms** [comment]
jenkins build this please

**Comment by blattms** [comment]
@Tongdongq Would you double that I replicated your fixes here, please. I think I did but running Norne without  adding the well contributions stil results in rather small timesteps. Just try `flow --accelerator-mode=opencl --linsolver=cpr_quasiimpes  NORNE_ATW2013` and compare without accelerator.

**Comment by Tongdongq** [comment]
I cannot reproduce the smaller than 1 days timesteps. With CPR, I get 379 timesteps for Dune, and 349 for opencl. With the masters of 2022-1-3.
I did not count the number of timesteps when using just iliu0, but the statistics at the end looked normal.

**Comment by blattms** [comment]
Man, how hard can it be. :flushed: must have used flow compiled with the wrong branch. Indeed this works as advertised.  Good work and sorry for the noise.

**Pull request merged**
