### PR TITLE
fix typo in test name

### PR DESCRIPTION
**Pull request by akva2**
I will use this PR to perform amgcl re-enablement so excuse the noise...

### CODE REVIEW

**Comment by akva2** [comment]
jenkins build this nompi mpi-amgcl please

**Comment by akva2** [comment]
jenkins build this please

**Comment by akva2** [comment]
amgcl is back. this can be merged if you deem it worthy.

**Review by bska — APPROVED** [review]
Doesn't hurt to have this.  I'll merge into master.

**Pull request merged**
