### PR TITLE
well iterations should start from 0.

### PR DESCRIPTION
**Pull request by qilicun**
Keep the same with flow.

### CODE REVIEW

**Comment by qilicun** [comment]
Since this is a tiny fix, if no one merged until today, I will do that. :smile:

**Comment by atgeirr** [comment]
Please let me have a look.

**Comment by atgeirr** [comment]
Had a look... (it was tiny as you said).

I just wonder: did we decide to return 0 for both "well solving is disabled" and "I did the well solve, but it was already converged" and not separate them (for example by returning -1 for the first case)? I'm thinking that there is *some* information in the difference (in the second case it tells us the wells are pretty much in a steady state).

**Comment by qilicun** [comment]
>did we decide to return 0 for both "well solving is disabled" and "I did the well solve, but it was already converged" and not separate them (for example by returning -1 for the first case)?


If the well is not solved, the well iteration will not report. While, there is one case that both return 0 that is well equation is solved but the iteration is 0.  But for this case, well iteration still will not be reported, since it stays 0. 

For any other cases, well iteration will be larger than 0, that shows well equation is solved.

**Comment by atgeirr** [comment]
Yes, just thinking we might want to separate those cases. It's not critical by any means, I'll merge this fix.

**Pull request merged**
