### PR TITLE
Adding explicit input specification of water-gas ratio (RVW) and RVW output plus simulator gas-water system with salt precipitation and water evaporation for 

### PR DESCRIPTION
**Pull request by plgbrts**
This PR depends on https://github.com/OPM/opm-material/pull/491 and https://github.com/OPM/opm-models/pull/684

### CODE REVIEW

**Comment by plgbrts** [comment]
@bska could you rerun jenkins? I fixed the failing of the one-phase test cases. The salt-precipitation test case (`SPE1CASE1_PRECSALT.DATA`) is expected  to fail since  PR [#684](https://github.com/OPM/opm-models/pull/684)  has a change  that impacts the salt-precipitation results.
Currently I am preparing PRs for salt precipitation in the context of simultaneous water and oil vaporization that builds further on this PR (#3830).

**Comment by akva2** [comment]
jenkins build this opm-material=491 opm-models=684 please

**Comment by akva2** [comment]
and i have added you to the whitelist, in the future you can trigger yourself.

**Comment by bska** [comment]
jenkins build this opm-material=491 opm-models=684 please

**Comment by plgbrts** [comment]
One test failed (`SPE1CASE1_PRECSALT.DATA`) as expected. Code can be reviewed.

**Comment by totto82** [comment]
Thanks for a very nice contribution. I have looked throw the PRs in opm-material, opm-models and opm-simulators and from my point of view this can be merged when green and the issue with unused "schedule" is fixed. See comment in opm-material.

**Comment by plgbrts** [comment]
jenkins build this opm-material=491 opm-models=684 please

**Comment by totto82** [comment]
jenkins build this  opm-models=684 update_data please

**Comment by totto82** [comment]
jenkins build this opm-models=684 update_data please

**Comment by plgbrts** [comment]
@totto82 it looks like the jenkins build is not triggered?!

**Comment by totto82** [comment]
jenkins build this opm-tests=744 please

**Comment by totto82** [comment]
jenkins build this  opm-models=684 opm-tests=744 please

**Pull request merged**
