### PR TITLE
use reservoir rates not reduction rate in target calculator for VREP

### PR DESCRIPTION
**Pull request by totto82**
We also want to remove the reservoir rates of other phases for wells under group control.

### CODE REVIEW

**Comment by totto82** [comment]
jenkins build this please

**Comment by totto82** [comment]
jenkins build this failure_report please

**Comment by totto82** [comment]
jenkins build this failure_report please

**Comment by totto82** [comment]
jenkins build this failure_report please

**Review by atgeirr — APPROVED** [review]
I think I get this now. Please insert a comment in the code explaining the crucial logic here: That we need to account for the possibility that the group in question has both a VREP control and another injection control for a different phase.

**Comment by totto82** [comment]
jenkins build this failure_report update_data please

**Comment by totto82** [comment]
jenkins build this failure_report update_data please

**Comment by totto82** [comment]
jenkins build this opm-tests=1269 please

**Pull request merged**
