### PR TITLE
Import adaptive time stepping and associated classes

### PR DESCRIPTION
**Pull request by akva2**
As requested, this imports the AdaptiveTimeStepping class from opm-core.
Do not merge this branch as-is, it's a bit interleaved with other fixes so I will have to rewrite it to reflect reality as seen in upstream before it is merged, but I open early so nobody else redo the same work (it's just a matter of rerunning my script).

### CODE REVIEW

**Comment by akva2** [comment]
please verify this is what was requested, and that i chose the appropriate path in the simulators repo.

**Comment by akva2** [comment]
should the timing class be moved as well ?

**Comment by dr-robertk** [comment]
The timing classes could be moved unless they are used in opm-core or other modules depending on opm-core. I'm not sure whether this is the case ore not.

**Comment by akva2** [comment]
right. it's only used in simulators, so will include.

**Comment by dr-robertk** [comment]
The TimeStepControl classes for sure. I'm not sure about SimulatorTimer etc.

**Comment by dr-robertk** [comment]
I saw you places the files in the opm/simulators subdirectory. If it is not to much effort one could choose a subdir of that, e.g. timestepping or similar.

**Comment by akva2** [comment]
that's why i ask, you can have whatever you want :)

**Comment by dr-robertk** [comment]
Ok, thanks.

**Comment by akva2** [comment]
file_list is http://pastebin.com/H9Nrs3rr 
tree filter filter is http://pastebin.com/nEW7YrMA
parent filter is http://pastebin.com/U5Hpk658 (needed to take care of the first sin of git - merges from upstream)

did i get everything right?

for reference, if you want to do it yourself, stick file_list and the filters in some folder (needs to be the same), then use through
```
git clone opm-core opm-core-filtered
cd opm-core-filtered
NEWDIR=opm/simulators/timestepping git filter-branch --prune-empty --tree-filter /path/to/filter --parent-filter /path/to/parent_filter.rb
```
then merge the resulting branch into opm-simulators. the merge, buildsystem and include path changes are not automated. the filter paths need to be absolute, as the operations run in some "random" subfolder. this assumes all processed files go into one folder, it's hard to automate anything more involved so i'd write a tailored tree filter then.

**Comment by dr-robertk** [comment]
Thanks for the work and explanation. I think this info should be conserved on the wiki.

**Comment by atgeirr** [comment]
The change looks ready to merge.

The only minor addition I could suggest would be to also move the SimulatorTimer* things (also examples/wells_example.cpp and tests/test_timer.cpp), if you think that it is better to do that as part of this PR I can wait. Otherwise, merge if you are done.

**Comment by akva2** [comment]
you want the SimulatorTimer in the timestepping folder or somewhere else ? to me it sounds a bit like a different beast (same with the adaptive one of course).

**Comment by atgeirr** [comment]
Same folder sounds good.

**Comment by akva2** [comment]
jenkins build this opm-core=1141 please

**Comment by akva2** [comment]
should be good to go.

**Comment by atgeirr** [comment]
I don't understand how the Jenkins test could have succeeded, because it looks like we failed to make some changes to include paths:
```
In file included from /Users/atgeirr/opm-build-debug/opm-simulators/opm/autodiff/SimulatorFullyImplicitBlackoilOutput.cpp:22:
/Users/atgeirr/opm-build-debug/opm-simulators/opm/autodiff/SimulatorFullyImplicitBlackoilOutput.hpp:23:10: fatal error: 
      'opm/core/simulator/SimulatorTimerInterface.hpp' file not found
```

I'll push a fix, but I'd really like to know how this could slip through Jenkins? Do we have some rogue installed files that were found?

**Comment by akva2** [comment]
Perfect storm :/
I have enabled ccache on jenkins to try to speed it up a bit. No files going into the compile unit was touched so object was copied straight out of cache. I should disable it again i guess, gains are substantial on repeated rebuilds but safety comes first

**Comment by atgeirr** [comment]
Should be fixed again in #1052.

**Pull request merged**
