### PR TITLE
Enable new test udq_actionx/ACTIONX_M1

### PR DESCRIPTION
**Pull request by joakim-hove**
Depends on:

~~https://github.com/OPM/opm-common/pull/2293~~
~~https://github.com/OPM/opm-simulators/pull/3050~~
~~https://github.com/OPM/opm-simulators/pull/3116~~

### CODE REVIEW

**Comment by joakim-hove** [comment]
jenkins build this update_data please

**Comment by joakim-hove** [comment]
OK - this test; along with the data update is ready to merge from my side - but an extra check from Equinor would be beneficial.

**Comment by joakim-hove** [comment]
jenkins build this opm-tests=518 please

**Comment by joakim-hove** [comment]
jenkins build this update_data please

**Comment by bska** [comment]
jenkins build this opm-tests=518 please

**Comment by joakim-hove** [comment]
OK - this has been verified at Equinor - will merge soon!

**Comment by joakim-hove** [comment]
jenkins build this update_data please

**Comment by joakim-hove** [comment]
jenkins build this opm-tests=518 please

**Comment by joakim-hove** [comment]
Merging this

**Pull request merged**
