### PR TITLE
Add missing features on U, V and T

### PR DESCRIPTION
**Pull request by joakim-hove**
Add unsupported keywords

### CODE REVIEW

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by bska** [comment]
PR OPM/opm-common#1050 was already merged.  Should this be merged too?

**Comment by joakim-hove** [comment]
Yed

**Comment by bska** [comment]
> Yed

I take it that 'd' should be an 's'?

**Comment by joakim-hove** [comment]
Yes - it should be merged. There is compile time dependencies here, so the `MissingFeatures` pull requests and the PR with new keywords can be merged independently.

**Comment by bska** [comment]
> the `MissingFeatures` pull requests and the PR with new keywords can be merged independently.

:+1:

I'll merge this into master.  Thanks a lot.

**Pull request merged**
