### PR TITLE
Support CPR when using DUNE 2.4 and no MPI

### PR DESCRIPTION
**Pull request by blattms**

### CODE REVIEW

**Comment by blattms** [comment]
jenkins build this please

**Comment by bska** [comment]
Thanks a lot Markus&mdash;you're really going beyond and above the call of duty!

Some minor build failures that are hopefully simple to correct.  By the way, I think you're supposed to be able to trigger a serial build on Jenkins by adding the keyword `serial` to the trigger command.  At least that's what the [Wiki suggests](https://wiki.opm-project.org/index.php?title=Jenkins_triggers).

**Comment by blattms** [comment]
Ok. Did not test the parallel case before posting. Finally this works serial and parallel on my machine.

**Comment by blattms** [comment]
Ok. Did not test the parallel case before posting. Finally this works serial and parallel on my machine.

**Comment by blattms** [comment]
Ok. Did not test the parallel case before posting. Finally this works serial and parallel on my machine.

**Comment by blattms** [comment]
Hugh? github web interface says to: "You can't comment at this time." WTF
Trying email:

Ok. Did not test the parallel case before posting PR. Did now and fixed stuff.
Finally this works in serial and parallel on my machine. Removed WIP

**Comment by blattms** [comment]
jenkins build this serial please

**Comment by blattms** [comment]
jenkins build this please

**Comment by bska** [comment]
jenkins build this serial please

**Comment by bska** [comment]
Jenkins declares that this restores the sequential build.  I'm away from the development box that has a Dune 2.4.1 configuration so I won't be able to test that before tomorrow, but I'm going to merge this into master regardless in order to recover nightly builds.

Thanks a lot for your efforts!

**Comment by blattms** [comment]
I am a bit jealous that it picked up your serial build request and not mine. :smirk:

**Comment by bska** [comment]
> I am a bit jealous that it picked up your serial build request and not mine.

Don't be.  To be honest, I've mostly given up trying to understand why any particular Jenkins trigger fails to launch a build.  I've had it happen to me on several occasions and then it **usually** helps to have someone else trigger the build.

And it just so happens that this does indeed fix my local build targeting Dune 2.4.1, so I'm doubly appreciative of your work.  It means I can put off upgrading the box for a little longer :smirk_cat:

**Pull request merged**
