### PR TITLE
Reorder variables and remove .reserve() calls

### PR DESCRIPTION
**Pull request by joakim-hove**
Veeery small trivial changes in MSW WellState code - just to start warming up there.

### CODE REVIEW

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by blattms** [comment]
What is the rational behind removing reserve calls? It seems to be good practice to prevent unnecessary reallocations and copies if possible.

I even fail to see any reason for this PR. Why is it needed?

**Comment by joakim-hove** [comment]
> I even fail to see any reason for this PR. Why is it needed?

It is certainly not needed - just a micro step in my process of getting aquainted with the code, and in my opinion a small *micro* improvement.

The code in itself already has a mix of different methods to set the size of vectors: `.resize(), .assign(), { }` and `push_back`, to me the code is slightly clearer without the use of `reserve()`. The code in question will be refactored further - so this will have essentially zero consequences in the not-so-long-term.

Reordering was just to be consistent with comment (I guess I would get more flack for removing the misleading comment :wink: ?)

**Comment by blattms** [comment]
IMHO, if you know the size you should always use reserve to prevent reallocating, copying and wasting memory. We are already hit by our memory consumption at other place, so let us not make the situation more worse.  https://www.geeksforgeeks.org/using-stdvectorreserve-whenever-possible/

**Pull request merged**
