### PR TITLE
Change method name -> IOConfig::restart()

### PR DESCRIPTION
**Pull request by joakim-hove**
This is a followup to: https://github.com/OPM/opm-parser/pull/777.

I started out with an intention of fixing: https://github.com/OPM/opm-parser/issues/773 - however as mentioned here: https://github.com/OPM/opm-parser/issues/773#issuecomment-214395099 I got cold feet and backed off from any substantial changes. 

The end result is that this PR is extremely trivial.

### CODE REVIEW

**Comment by joakim-hove** [comment]
jenkins build this opm-parser=777 please

**Comment by atgeirr** [comment]
The PR in itself is fine, but I think the new function name is less than ideal, to me it sounds like calling `restart()` is a command to restart something. I think `restartRequested()` would be a clearer name.

If you change the name or not, in any case you can merge this PR when ready.

**Comment by joakim-hove** [comment]
> to me it sounds like calling restart() is a command to restart something. I think restartRequested() would be a clearer name.

I agree - will update

**Comment by joakim-hove** [comment]
jenkins build this opm-parser=777 please

**Pull request merged**
