### PR TITLE
removing some repeated code in phaseUsageFromDeck

### PR DESCRIPTION
**Pull request by GitPaean**
found it when developing some new code. 

These two `phaseUsageFromDeck` functions  are almost identical. Please comment if I saw it wrongly . (like they are actually different).

### CODE REVIEW

**Comment by GitPaean** [comment]
jenkins build this please

**Comment by GitPaean** [comment]
jenkins build this please

**Comment by GitPaean** [comment]
jenkins build this please

**Comment by atgeirr** [comment]
Thanks, merging.

**Pull request merged**
