### PR TITLE
Enable async_output when pthreads are enabled.

### PR DESCRIPTION
**Pull request by dr-robertk**
This PR enables the async output when phtreads are enabled.

### CODE REVIEW

**Comment by atgeirr** [comment]
This was disabled by #690 recently as a workaround to fix problems with tests failing on Jenkins, Travis etc. I think we should not merge this until we are sure that the underlying problem has been fixed.

**Comment by atgeirr** [comment]
jenkins build this please

**Comment by dr-robertk** [comment]
Ok, let's wait then.

**Comment by andlaus** [comment]
To sum #690 up: The issue probably is that in some cases (relatively slow I/O and a fast CPU), the in-memory data gets modified by the simulator before the output writing is finished. If this is the culprit, this problem is very non-deterministic, so that it may work on Jenkins, but fail on other machines...

**Pull request closed without merging**
