### PR TITLE
remove test_ecl_output

### PR DESCRIPTION
**Pull request by akva2**
the tests done here is already done (better) elsewhere.

Rebased https://github.com/OPM/opm-simulators/pull/3696  - see there for some more rationale.

### CODE REVIEW

**Comment by akva2** [comment]
jenkins build this please

**Comment by bska** [comment]
> Rebased #3696

Right, but that PR also removed the input file [`tests/SUMMARY_DECK_NON_CONSTANT_POROSITY.DATA`](https://github.com/OPM/opm-simulators/blob/70027d541e35047bdffb205aa1c28e2570ccd406/tests/SUMMARY_DECK_NON_CONSTANT_POROSITY.DATA) which becomes unused following the removal of `test_ecl_output.cc`.  Maybe we could also remove that input file here?

**Comment by akva2** [comment]
jenkins build this please

**Review by bska — APPROVED** [review]
Thanks for the updates.  This looks good to me and I'll merge into master.

**Pull request merged**
