### PR TITLE
FOR TESTING. Enable Diffusion by default

### PR DESCRIPTION
**Pull request by totto82**
This PR is for testing the performance impact of enabling diffusion by default. You still need to add DIFFUSE to your deck to actually model diffusion.

### CODE REVIEW

**Comment by totto82** [comment]
benchmark please

**Comment by ytelses** [comment]
Benchmark result overview: 




| Test    | Configuration                              | Relative |
| ------- | ------------------------------------------ | -------- |
| opm-git | OPM Benchmark: flow_mpi_extra - Threads: 1 | 0.946    |
| opm-git | OPM Benchmark: flow_mpi_extra - Threads: 8 | 0.94     |
| opm-git | OPM Benchmark: flow_mpi_norne - Threads: 1 | 0.917    |
| opm-git | OPM Benchmark: flow_mpi_norne - Threads: 8 | 0.914    |
* Speed-up = Total time master / Total time pull request. Above 1.0 is an improvement. *



View result details @ https://www.ytelses.com/opm/?page=result&id=1083

**Comment by totto82** [comment]
This is why we want to enable features compile time. I will Jenkins it to make sure it doesn't break have any effect on any tests and close the PR. Why is the prediction case missing from the Benchmark?

**Comment by totto82** [comment]
jenkins build this please

**Comment by alfbr** [comment]
> Why is the prediction case missing from the Benchmark?

One of two. Either the prediction cases time out, or they are not run at all. We had another occurrence a couple of days ago, so it makes sense to track this down. I will find a PR to test if it is not run at all.

**Comment by totto82** [comment]
jenkins build this opm-models=642 please

**Comment by totto82** [comment]
Is it possible to run benchmark with upstream dependencies i.e. OPM/opm-models#642

**Comment by alfbr** [comment]
Sure, like this:

**Comment by alfbr** [comment]
benchmark please opm-models=642

**Comment by totto82** [comment]
jenkins build this opm-models=642 please

**Comment by ytelses** [comment]
Benchmark result overview: 




| Test    | Configuration                              | Relative |
| ------- | ------------------------------------------ | -------- |
| opm-git | OPM Benchmark: flow_mpi_extra - Threads: 1 | 1        |
| opm-git | OPM Benchmark: flow_mpi_extra - Threads: 8 | 1.007    |
| opm-git | OPM Benchmark: flow_mpi_norne - Threads: 1 | 1.003    |
| opm-git | OPM Benchmark: flow_mpi_norne - Threads: 8 | 0.992    |
* Speed-up = Total time master / Total time pull request. Above 1.0 is an improvement. *



View result details @ https://www.ytelses.com/opm/?page=result&id=1086

**Comment by alfbr** [comment]
benchmark please opm-models=642

**Comment by ytelses** [comment]
Benchmark result overview: 




| Test    | Configuration                                     | Relative |
| ------- | ------------------------------------------------- | -------- |
| opm-git | OPM Benchmark: flow_mpi_extra - Threads: 1        | 1.003    |
| opm-git | OPM Benchmark: flow_mpi_extra - Threads: 8        | 1.004    |
| opm-git | OPM Benchmark: flow_mpi_norne - Threads: 1        | 1.005    |
| opm-git | OPM Benchmark: flow_mpi_norne - Threads: 8        | 0.999    |
| opm-git | OPM Benchmark: flow_mpi_norne_4c_msw - Threads: 1 | 1.002    |
| opm-git | OPM Benchmark: flow_mpi_norne_4c_msw - Threads: 8 | 0.99     |
* Speed-up = Total time master / Total time pull request. Above 1.0 is an improvement. *



View result details @ https://www.ytelses.com/opm/?page=result&id=1087

**Comment by totto82** [comment]
With the changes in opm-models enabling diffusion seems to have no negative impact on the performance. I suggest we enable it by default and remove the specialized versions. Any objections?

**Comment by totto82** [comment]
jenkins build this opm-models=642 please

**Comment by bska** [comment]
> I suggest we enable [diffusion] by default and remove the specialized versions. Any objections?

No objections.  I'll merge this into master as a start.

**Pull request merged**
