### PR TITLE
make the default flow point to flow_ebos instead of flow_legacy

### PR DESCRIPTION
**Pull request by andlaus**
`flow_ebos` should be now capable of doing everything that `flow_legacy` can and recently all testing seems to have been centered on `flow_ebos`. note that `flow_ebos` does not yet support some more
advanced/exotic features like MPI, solvents, polymer, etc., but neither does the plain `flow_legacy` binary. until `flow_ebos` supports these features, the specialized simulators thus continue to use the legacy code paths.

### CODE REVIEW

**Comment by andlaus** [comment]
jenkins run norne please

**Comment by andlaus** [comment]
(I guess this should now use flow_ebos, probably the reference solutions need to be updated...)

**Comment by andlaus** [comment]
as expected, the tests fail because the reference solutions need to be updated. there also seems to be something wrong with the `analyze_summary_failure.sh` script? @akva2: who can fix this?

**Comment by akva2** [comment]
what's wrong with the script?

**Comment by andlaus** [comment]
> what's wrong with the script?

look at the travis log: it contains a gazillion messages like these:

```
/home/travis/build/OPM/opm-simulators/tests/analyze_summary_failure.sh: line 42: [: -eq: unary operator expected
/home/travis/build/OPM/opm-simulators/tests/analyze_summary_failure.sh: line 38: bc: command not found
```

**Comment by akva2** [comment]
travis. meh. i don't care about travis ;)

problem is this:
/home/travis/build/OPM/opm-simulators/tests/analyze_summary_failure.sh: line 38: bc: command not found

**Comment by andlaus** [comment]
ok, the `bc` command is not installed? can't you use python (or perl, ruby, ...) for these floating point calculations instead? I mean something like

```
echo "print (1.234*5.678)" | python
```

**Comment by akva2** [comment]
of course i can change command, but i find it easier to just install bc..

**Comment by andlaus** [comment]
```
python -c "print 1.234*5.678"
```

would actually also be possible.

> of course i can change command, but i find it easier to just install bc..

ok. to me, the only thing that matters with that regard is that it works...

**Comment by akva2** [comment]
anyways. if you are to do this, i do not think disabling the tests for the legacy solver is the way to go about it.

i suggest
1) restructuring opm-data such that you have case/opm-simulation-reference/simulator
2) making current tests use the old reference data and flow_legacy as binary
3) add the tests for flow_ebos with its own set of reference data

**Comment by andlaus** [comment]
I concur. looking at the Jenkins output, I'm no longer sure if the sequential test fail, though: the failing tests are all named `mpi.*`. alternatively the test names could wrong (or misleading)?

**Comment by akva2** [comment]
mpi is the build configuration - an mpi enabled build.

**Comment by andlaus** [comment]
ok, just slightly confusing test names then...

**Comment by akva2** [comment]
i guess. it's all very logical if you know how to read it. and it makes a lot of sense to label the tests when you do serial and parallel builds (or builds with clang, or whatever) in addition.

**Comment by akva2** [comment]
also. the tests most definitely fail. specifically the summary and restart comparisons, the init comparisons pass fine.

**Comment by andlaus** [comment]
ok, as a first step I tried to replace `flow` by `flow_legacy` in `compareECLFiles.cmake`. this produces some very strange errors on my machine:

```
and@heuristix:~/src/opm-simulators|make-flow_ebos-the-default > ctest -R "compareECLFiles_flow_legacy.*SPE1CASE" -V
UpdateCTestConfiguration  from :/home/and/src/opm-simulators/DartConfiguration.tcl
Parse Config file:/home/and/src/opm-simulators/DartConfiguration.tcl
UpdateCTestConfiguration  from :/home/and/src/opm-simulators/DartConfiguration.tcl
Parse Config file:/home/and/src/opm-simulators/DartConfiguration.tcl
Test project /home/and/src/opm-simulators
Constructing a list of tests
Done constructing a list of tests
Checking test dependency graph...
Checking test dependency graph end
test 18
    Start 18: compareECLFiles_flow_legacy+SPE1CASE2

18: Test command: /home/and/src/opm-simulators/tests/run-regressionTest.sh "/home/and/src/opm-simulators/../opm-data/spe1" "/home/and/src/opm-simulators/tests/results/flow_legacy+spe1" "/home/and/src/opm-simulators/bin" "SPE1CASE2" "2e-2" "1e-5" "flow_legacy" "/home/and/src/opm-simulators/../opm-data/spe1/SPE1CASE2.DATA"
18: Test timeout computed to be: 1500
18: /home/and/src/opm-simulators/tests/run-regressionTest.sh: line 21: /home/and/src/opm-simulators/bin/: Is a directory
18: /home/and/src/opm-simulators/tests/run-regressionTest.sh: line 25: flow_legacy: command not found
18: 1 summary keyword(s) exhibit failures
18: /home/and/src/opm-simulators/tests/run-regressionTest.sh: line 32: /home/and/src/opm-simulators/../opm-data/spe1/SPE1CASE2.DATA: Permission denied
18: /home/and/src/opm-simulators/tests/analyze_ecl_failure.sh: line 62: /home/and/src/opm-simulators/../opm-data/spe1/SPE1CASE2.DATA: Permission denied
18: 
18: Comparisons pass for all common keywords.
18: /home/and/src/opm-simulators/tests/run-regressionTest.sh: line 39: /home/and/src/opm-simulators/../opm-data/spe1/SPE1CASE2.DATA: Permission denied
18: /home/and/src/opm-simulators/tests/analyze_ecl_failure.sh: line 62: /home/and/src/opm-simulators/../opm-data/spe1/SPE1CASE2.DATA: Permission denied
18: 
18: Comparisons pass for all common keywords.
1/1 Test #18: compareECLFiles_flow_legacy+SPE1CASE2 ...***Failed    0.08 sec

0% tests passed, 1 tests failed out of 1

Total Test time (real) =   0.08 sec

The following tests FAILED:
         18 - compareECLFiles_flow_legacy+SPE1CASE2 (Failed)
Errors while running CTest
```

I tried to debug this, but so far I failed. any ideas?

**Comment by akva2** [comment]
no idea what you have done so i have no answer for you. it works just fine on my machine is all i can say.

**Comment by atgeirr** [comment]
> i suggest
> 
> restructuring opm-data such that you have case/opm-simulation-reference/simulator
> making current tests use the old reference data and flow_legacy as binary
> add the tests for flow_ebos with its own set of reference data

I agree with this approach, and I'll follow the progress here. I have no real suggestion for your "permission denied" problem @andlaus, sorry...

**Comment by andlaus** [comment]
I agree too. but let's do the reorganization of the unit tests as a separate step?! (i.e., at first, continue to use flow_legacy for the existing tests, but select it explicitly.)

**Comment by andlaus** [comment]
okay: on my machine I also get the same errors with the master branch. it seems like something goes wrong with passing the name of the binary, so the test driver tries to execute the target directory (hence the "permission denied" messages). I haven't been able to figure out what causes this, maybe it only happens with in-source builds and/or using dunecontrol. anyway, I'v changed the tests to explicitly request `flow_legacy` and pushed a new patch, so:

**Comment by andlaus** [comment]
jenkins build this please

**Comment by atgeirr** [comment]
This PR still changes the symlink (which should be the last step, after the other 3 steps are done), I think we should merge the change flow->flow_legacy (in the tests) separately. When all else is in order, we'll make a tiny final PR changing the symlink.

**Comment by andlaus** [comment]
as you like. patch changed so that it only touches the symlink. the rest has been factored out and can be merged separately as #1096. (that patch is also included here, so you can chose whether you prefer one or two PRs.)

**Comment by akva2** [comment]
sigh. rebase please @andlaus.

**Comment by akva2** [comment]
nm - wrong pr!

**Comment by andlaus** [comment]
jenkins build this please

**Comment by andlaus** [comment]
travis failed because #1096 was not yet merged when it started. jenkins was triggered after the merge, so there is a good chance that it succeeds...

**Comment by atgeirr** [comment]
I notice that some but not all tests in opm-simulators have flow_ebos variants. I believe that
 - the compareECLFiles tests "SPE1CASE2", "SPE3CASE1" and "SPE9_CP_SHORT"
 - the compareParallelSim tests
should be considered, although there is probably some overlap with the compareRestartedSim tests (perhaps some can be dropped) and of course the parallel tests must wait until we have a proper parallel flow_ebos.

I think the compareECLFiles tests at least should be in place before this PR is merged.

**Comment by akva2** [comment]
there are no reference files for ebos yet, hence no compareECLFiles test.
parallel and restart are two different test classes, and both should be executed for both simulators. however, i haven't been able to execute flow_ebos in parallel with any success yet, so the parallel tests have not been activated.

**Comment by andlaus** [comment]
is jenkins stuck? it seems like it did not do anything during the last two hours except stating "Build triggered. sha1 is merged."

**Comment by atgeirr** [comment]
> is jenkins stuck? it seems like it did not do anything during the last two hours except stating "Build triggered. sha1 is merged."

I don't think so, there is a long queue:

https://ci.opm-project.org

**Comment by andlaus** [comment]
ah, lot's of 'run norne_ebos' today. sorry for the noise.

**Comment by alfbr** [comment]
Seems like everything needed is done. Are we ready to merge this now?

**Comment by atgeirr** [comment]
> Seems like everything needed is done. Are we ready to merge this now?

Almost, #1133 should go in first.

**Comment by atgeirr** [comment]
> Almost, #1133 should go in first.

And since it is in, I'll do a final Jenkins sanity check before merging this.

**Comment by atgeirr** [comment]
jenkins run spe please

**Comment by atgeirr** [comment]
@andlaus please investigate the Jenkins failure

**Comment by akva2** [comment]
Shared opm data issue. Rerun.

**Comment by andlaus** [comment]
it also seems like the jenkins run did not include #1134. I rebased this PR, let's see if it helps...

**Comment by andlaus** [comment]
jenkins build this please

**Comment by andlaus** [comment]
alright, now all tests passed on jenkins.

**Comment by atgeirr** [comment]
And there we go! We have a new Flow in town...

**Pull request merged**
