### PR TITLE
fixed: include <cstring> for strlen

### PR DESCRIPTION
**Pull request by akva2**
Sorry, I did not see this before the nightly redhat build broke...

### CODE REVIEW

**Comment by akva2** [comment]
jenkins build this please

**Comment by totto82** [comment]
Is this relevant for the release?

**Comment by akva2** [comment]
not really. the lack of the include got triggered by the reorganization in opm-common, which is not in the release.

**Review by bska — APPROVED** [review]
Very good.  I'll merge this into master.

**Pull request merged**
