### PR TITLE
Redo existing tests

### PR DESCRIPTION
**Pull request by akva2**
- add ability to test simulators other than 'flow'
- remove old SPE1CASE2 test that only executed and did no comparison
- move the SPE1CASE1 flow_sequential test to an actual regression test

data update: https://github.com/OPM/opm-data/pull/142

please process ASAP to avoid duplicated work

### CODE REVIEW

**Comment by akva2** [comment]
@atgeirr this kills 2 of the 3 remaining tests that spit data directly to the build directory that you asked about at some point.

**Comment by akva2** [comment]
for the last test i need instructions. there is no reference data. is there are reason for that other than 'todo' ? also i would really like to reorganize the layout in opm-data, it's not compatible with my scripts which assumes the 'standard' layout /testname/file.DATA and /testname/opm-simulation-reference/file.UNRST

**Comment by akva2** [comment]
jenkins build this opm-data=142 please

**Comment by andlaus** [comment]
please proceed carefully: there is (used to be?) some kind of problem with SPE1CASE1? (IIRC it was that the DRSDT keyword is unsupported by OPM.)

**Comment by atgeirr** [comment]
> the DRSDT keyword is unsupported by OPM

I think that this keyword is the only difference between case 1 and 2, and since we do not support it and therefore cannot tell the difference we have probably been very sloppy about which case we have used for various purposes. So if you want to compare against Eclipse data you must use case 2 (which does not have the DRSDT).

**Comment by akva2** [comment]
This is a opm-opm regression test so it shouldnt matter. We are not checking for correctness, just changes. As long as the same 'garbage' is produced this test is happy

**Comment by alfbr** [comment]
> the DRSDT keyword is unsupported by OPM

Yes, this is the only difference.

> i would really like to reorganize the layout in opm-data

Me too, this has been long overdue. Please allow me to discuss it with you. The data sets serves as reference data sets as well as regression/integration tests, we should have an organization that caters to both needs. Right now it is a mess.

**Comment by andlaus** [comment]
> As long as the same 'garbage' is produced this test is happy

then I'm a happy camper :)

**Comment by akva2** [comment]
jenkins build this opm-data=142 please

**Comment by akva2** [comment]
tests pass, everybody happy -> shameless self-merge to avoid duplicated work.

**Pull request merged**
