### PR TITLE
Create all objects

### PR DESCRIPTION
**Pull request by joakim-hove**
The parsing process creates four top level objects: `Deck, EclipseState, Schedule` and `SummaryConfig`. With the advent of the `ErrorGuard` class it makes sense to create all four objects with the same `ErrorGuard` instance - to ensure that the maximum amount of error messages are presented to the user, before we jump ship.

With this PR ~~-and the accompanying in ewoms,~~ all four objects are created in flow.cpp and then all are set in the ewoms model using setExternalXXXX(). This also enables a new flag `--ecl-strict-parsing` which will give the *all strict* behavior.

~~Depends on: https://github.com/OPM/ewoms/pull/457~~

### CODE REVIEW

**Comment by joakim-hove** [comment]
jenkins build this ewoms=457 please

**Comment by GitPaean** [comment]
Can some tell me what `Vanguard::setExternalDeck` does here?

I did not find under what circumstance it will make a difference.  That is why I did not include it in `flow_ebos_oilwater_polymer_injectivity.cpp`

**Comment by joakim-hove** [comment]
> Can some tell me what Vanguard::setExternalDeck does here?

```
It ain't me babe,
it ain't me you are looking for
```

**Comment by joakim-hove** [comment]
jenkins build this ewoms=457 please

**Comment by joakim-hove** [comment]
jenkins build this ewoms=457 please

**Comment by andlaus** [comment]
> I did not find under what circumstance it will make a difference. That is why I did not include it in flow_ebos_oilwater_polymer_injectivity.cpp

It avoid having to parse the same deck twice. for small decks it does not matter, but people tend to get annoyed if they have to unnecessarily wait for a minute or two ;)

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by joakim-hove** [comment]
Thank you @andlaus - it works now! I might have been messing up `--ecl-strict-parse=true` and `--ecl-strict-parsing=true`- the latter is correct.

**Pull request merged**
