### PR TITLE
BUGFIX Pass solution from flowEbos to ebos initially

### PR DESCRIPTION
**Pull request by totto82**
The initial solution in ebos and  in flowEbos are different in cases where
SWATINIT is present. Pass the initial solution and recalculate the
intensive quantities to make sure that the flowEbos initial solution is
used.

### CODE REVIEW

**Comment by andlaus** [comment]
hm, this seems to serve the same purpose as https://github.com/OPM/opm-simulators/pull/1026/commits/ae38de70ef689bee2cb99be706b32b8b21e54652 (which has been merged as part of #1025). I like your patch better though, could you please revert ae38de70ef689bee2cb99be706b32b8b21e54652 in this PR?

**Comment by atgeirr** [comment]
All fine by me.

@andlaus you have the button on this one.

**Comment by andlaus** [comment]
> @andlaus you have the button on this one.

Thanks. I prefer #1029. The thing is that with merging it, ae38de7 should be reverted in order to avoid doing more work than necessary.

**Comment by totto82** [comment]
I have reverted ae38de7.

**Comment by andlaus** [comment]
cool. since travis does not complain, I'll merge this now. Thanks!

**Pull request merged**
