### PR TITLE
Use rst_deck capability to interpret commandline argument as file for restart testing

### PR DESCRIPTION
**Pull request by joakim-hove**
Small simplification using the rst_deck application possibility to treat argument as proper filename

### CODE REVIEW

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by joakim-hove** [comment]
Comments to this?

**Comment by bska** [comment]
I'm closing this now.  If we need this kind of functionality in the future we'll revive it in some form.

**Pull request closed without merging**
