### PR TITLE
tightening the tolerance for polymer cases for testing purpose.

### PR DESCRIPTION
**Pull request by GitPaean**

### CODE REVIEW

**Comment by GitPaean** [comment]
jenkins build this please

**Comment by GitPaean** [comment]
jenkins build this update_data please

**Comment by GitPaean** [comment]
```
	 37 - compareECLFiles_flow+3D_MSW (Failed)
	 39 - compareECLFiles_flow+2D_POLYMER_INJECTIVITY (Failed)
	 43 - compareECLFiles_flow+MSW_MODEL_1 (Failed)
	 45 - compareECLFiles_flow+FAULTS_MODEL_1 (Failed)
	 57 - compareECLFiles_flow+TEST_WSEGSICD (Failed)
```

**Comment by alfbr** [comment]
This is to be expected. Differences in time stepping will give failure. We will need to investigate differences at report steps to see the real deviations.

**Pull request closed without merging**
