### PR TITLE
Allow usage of system fmtlib and always use imported library.

### PR DESCRIPTION
**Pull request by blattms**
Needs OPM/opm-common#2291

### CODE REVIEW

**Comment by alfbr** [comment]
benchmark please

**Comment by alfbr** [comment]
just testing the benchmarking functionality, please ignore the noise

**Comment by ytelses** [comment]
Benchmark result overview: 




| Test    | Configuration                              | Relative |
| ------- | ------------------------------------------ | -------- |
| opm-git | OPM Benchmark: flow_mpi_extra - Threads: 1 | 1.003    |
| opm-git | OPM Benchmark: flow_mpi_extra - Threads: 8 | 1.008    |
| opm-git | OPM Benchmark: flow_mpi_norne - Threads: 1 | 0.999    |
| opm-git | OPM Benchmark: flow_mpi_norne - Threads: 8 | 0.998    |
* Speed-up = Total time master / Total time pull request. Above 1.0 is an improvement. *



View result details @ https://www.ytelses.com/opm/?page=result&id=1085

**Comment by blattms** [comment]
enkins build this opm-simulators=3058 please

**Comment by bska** [comment]
> enkins build this opm-simulators=3058 please

Did you mean to run this from opm-common instead?

**Comment by blattms** [comment]
Indeed, thankfully I misspelled the command.

**Pull request closed without merging**
