### PR TITLE
remove unused variable

### PR DESCRIPTION
**Pull request by akva2**
quell warning.

### CODE REVIEW

**Comment by akva2** [comment]
jenkins build this opm-common=2116 opm-grid=501 please

**Comment by akva2** [comment]
jenkins build this opm-common=2116 opm-grid=501 please

**Comment by akva2** [comment]
jenkins build this opm-grid=501 please

**Comment by akva2** [comment]
jenkins build this please

**Review by blattms — APPROVED** [review]
Approved if jenkins agrees.

**Pull request merged**
