### PR TITLE
make sure getTHPConstratint() consistent between the WellInterfaceGeneric and WellBhpThpCalculator

### PR DESCRIPTION
**Pull request by GitPaean**
potentially a fallout introduced from the PR https://github.com/OPM/opm-simulators/pull/4188 , thanks @akva2 for spotting the potential problem. 

There is still some testing needs to clear out for now. So mark the PR as draft for now.

### CODE REVIEW

**Comment by GitPaean** [comment]
jenkins build this please

**Comment by akva2** [comment]
This does not address the regression. The regression is that https://github.com/OPM/opm-simulators/blob/master/opm/simulators/wells/WellBhpThpCalculator.cpp#L171 calls the implementation in the WellBhpThpCalculator,
while it should call the one in the WellInterface, https://github.com/OPM/opm-simulators/blob/master/opm/simulators/wells/WellInterfaceGeneric.cpp#L208

It thus misses the check for the dynamic THP limit. I think the proper fix is to pass thp_limit as a parameter to WellBhpThpCalculator::computeBhpAtThpLimitProd, and give the parameter the value from WellInterface::getTHPConstraint.

**Comment by GitPaean** [comment]
Thanks for the comment while I am not totally following.  If you can draft a PR, it will be much appreciated. @akva2

**Comment by GitPaean** [comment]
Because there is my confusion from my side during testing.  So it is good if you can draft it since you understand what is happening here better.

**Comment by akva2** [comment]
https://github.com/OPM/opm-simulators/pull/4289

**Comment by GitPaean** [comment]
closing this in favor of #4289.

**Pull request closed without merging**
