### PR TITLE
fixed: build with g++ 5.3

### PR DESCRIPTION
**Pull request by akva2**
this partially fixes the build on ubuntu xenial.
it also breaks due to an updated eigen, but with this
you can build with the old eigen instead of the distro
supplied eigen.

### CODE REVIEW

**Comment by bska** [comment]
Would you mind trying to put
```C++
using std::isnan;
```
at the beginning of `Selector<>::Selector()` instead?  That would trigger ADL which is probably what's needed here.

**Comment by akva2** [comment]
sure thing. that does the job just as well (branch is updated).

**Comment by bska** [comment]
> that does the job just as well (branch is updated).

Thanks--I'll merge into master.  Incidentally, what do the errors look like when targeting a more recent version of Eigen?

**Comment by akva2** [comment]
uhm, i don't have it at hand but;

there are two  problems;

1) an index type changed from size_t to unsigned int (or the other way around). those can be fixed with an 'auto'.
2) there's a bug in the eigen 3.3-beta packages in xenial which triggers deep inside eigen headers (it's trying to call an operator += that is protected). this is non-trivial to fix and can probably only be cured by patience. whoever decided to push beta packages to a LTS OS should be .. asked to defend themself.

**Comment by bska** [comment]
> whoever decided to push beta packages to an LTS OS should be .. asked to defend themselves.
Sounds about right.  Thank goodness we have our [fall-back option](https://github.com/OPM/eigen3).

**Comment by atgeirr** [comment]
The Eigen package issue is annoying, but I guess the main effect on us is that we'll stay on 14.04 as default a bit longer?

**Comment by alfbr** [comment]
I support staying with 14.04 as default.

**Pull request merged**
