### PR TITLE
Rename option FlowNewtonMaxIterations to NewtonMaxIterations.

### PR DESCRIPTION
**Pull request by blattms**
Now it is consistent with other options (e.g. NewtonMinIterations.

Needs OPM/opm-models#741

### CODE REVIEW

**Comment by bska** [comment]
There are three regression test cases which explicitly explicitly set `FlowNewtonMaxIterations` in their `TEST_ARGS`.  You probably need to update those settings too

1. [`compareECLFiles_flow+SPE3CASE1`](https://github.com/OPM/opm-simulators/blob/3e680e41f56d39974403ec029be123589e10b138/compareECLFiles.cmake#L436)
2. [`compareECLFiles_flow+SPE5CASE1`](https://github.com/OPM/opm-simulators/blob/3e680e41f56d39974403ec029be123589e10b138/compareECLFiles.cmake#L497)
3. [`compareECLFiles_flow+SPE5CASE1_DYN`](https://github.com/OPM/opm-simulators/blob/3e680e41f56d39974403ec029be123589e10b138/compareECLFiles.cmake#L504)

**Review by bska — APPROVED** [review]
Thanks.  I'll merge this into the master branch now.

**Comment by OPMUSER** [comment]
The option is currently hidden, that is it only printed with the CLI option `--help-all`, previously the old version was listed when` --help `was used. 

Can we revert to the same behavior for the release.

**Comment by atgeirr** [comment]
> Can we revert to the same behavior for the release.

Yes we should unhide it.

**Pull request merged**
