### PR TITLE
Add regression test for model with GEFAC

### PR DESCRIPTION
**Pull request by joakim-hove**
I need this safety belt for: #3480  

@totto82

### CODE REVIEW

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by totto82** [comment]
Thanks!

**Comment by bska** [comment]
Do you need to hook this up to the "`update_data`" machinery too?

**Comment by joakim-hove** [comment]
> Do you need to hook this up to the "update_data" machinery too?

Yes - thank you

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by joakim-hove** [comment]
jenkins build this update_data please

**Comment by joakim-hove** [comment]
jenkins build this opm-tests=585 please

**Comment by joakim-hove** [comment]
This has supposedly been verified in Equinor - I'll merge!

**Pull request merged**
