### PR TITLE
Add class for well group controls

### PR DESCRIPTION
**Pull request by akva2**
More splitting of well code.

### CODE REVIEW

**Comment by akva2** [comment]
jenkins build this please

**Comment by bska** [comment]
I haven't looked at this at all, but I notice that the PR includes the files

* `WellGroupControls.cpp~658c6e8c7`
* `WellGroupControls.hpp~658c6e8c7`

Are these git/GitHub artifacts that just happen to show up in the "files changed" view or did you accidentally include some conflict resolution files into the history?

**Comment by akva2** [comment]
fixed.

**Comment by akva2** [comment]
jenkins build this please

**Review by bska — APPROVED** [review]
Looks good to me.  I'll run a build check and merge if green.

**Comment by bska** [comment]
jenkins build this please

**Comment by atgeirr** [comment]
I assume this is a pure refactoring, not changing the solutions by a microepsilon?

Also, please give @GitPaean or @totto82 a little time to look at it before merging.

**Comment by GitPaean** [comment]
Although did not check each single line of the code, it looks like to me the PR just moves code around. I do not have objections to merge it.

**Comment by bska** [comment]
> I do not have objections to merge it.

Cool.  I'll merge this into the master branch then.

**Pull request merged**
