### PR TITLE
For discussion: Relaxed tolerances

### PR DESCRIPTION
**Pull request by alfbr**
This pull request is controversial. It is sent in as a pull request since this maybe the defaults we end up using internally. We do not expect it to be merged, but send it as a pull request to avoid in-house patches (invisible to the community), enabling community discussion.

### CODE REVIEW

**Comment by andlaus** [comment]
I don't object to this at all, nor do I really have an opinion about this. I just want to point out that the original number of strict iterations was also 4 or 5 and that 1e-5 was the default tolerance until a few months ago. IIRC, both settings were changed to reduce differences w.r.t. the commercial simulator, so you're probably well advised to be careful when looking at the results.

**Comment by alfbr** [comment]
benchmark

**Comment by ytelses** [comment]
Benchmark result overview: 




| Test | Configuration | Relative |
| ---- | ------------- | -------- |
* Speed-up = Total time master / Total time pull request. Above 1.0 is an improvement. *



View result details @ https://www.ytelses.com/opm/?page=result&id=212

**Comment by alfbr** [comment]
benchmark

**Comment by ytelses** [comment]
Benchmark result overview: 




| Test    | Configuration                              | Relative |
| ------- | ------------------------------------------ | -------- |
| opm-git | OPM Benchmark: flow_mpi_extra - Threads: 1 | 1.027    |
| opm-git | OPM Benchmark: flow_mpi_extra - Threads: 8 | 0.99     |
| opm-git | OPM Benchmark: flow_mpi_norne - Threads: 1 | 0.992    |
| opm-git | OPM Benchmark: flow_mpi_norne - Threads: 8 | 1.033    |
* Speed-up = Total time master / Total time pull request. Above 1.0 is an improvement. *



View result details @ https://www.ytelses.com/opm/?page=result&id=217

**Comment by GitPaean** [comment]
This PR does make the running faster and possible further, while it is claimed to be converged for something like follows, with some relatively big CNV tolerances. It doses not seem to cause deviations in the results in an obviously way either, while it is not easy to say what is the best way to handle the tolerances. 

```
 72665 Time step 0, stepsize 16 days.                                                                       
 72670 Well equation solution gets converged with 2 iterations                                                                          
 72671 Iter    MB(O)      MB(W)      MB(G)      CNV(O)     CNV(W)     CNV(G)                                                            
 72672    0  3.438e-04  1.992e-04  1.825e-04  3.375e-01  3.713e+00  1.735e+00                                                           
 72673    1  3.777e-06  9.747e-06  9.034e-07  1.919e+02  3.681e+00  4.464e+03
 72674    2  2.452e-07  3.256e-06  1.612e-06  2.136e+01  8.995e+00  5.012e+02 
 72675    3  1.046e-06  9.516e-06  1.016e-06  4.796e+00  5.576e+00  1.072e+02
 72676    4  1.258e-06  9.958e-06  1.189e-06  1.556e+01  8.580e-01  3.437e+02
```

**Comment by GitPaean** [comment]
I have been testing these days, the below is some findings from my side.

The relaxation of `ToleranceMb` is helpful for both getting through a deck and also for better performance. 

The relaxation of `MaxStrictIter` is helpful for better performance, while not that essential for getting through a deck.

**Comment by alfbr** [comment]
Thanks for testing! I have made the same observations. For historic period, the results are typically good enough. We are a bit more uncertain when it comes to prediction though, as the setting is more unstable.

**Comment by akva2** [comment]
Can one of the admins verify this patch?

**Comment by andlaus** [comment]
last time I checked -- which is admittedly a longish time ago -- this PR resulted in significantly better performance for Norne but the results also changed significantly...

**Comment by alfbr** [comment]
> Can one of the admins verify this patch?

Verify what?

> last time I checked -- which is admittedly a longish time ago -- this PR resulted in significantly better performance for Norne

It still does, but just as importantly the patch provide better numerical robustness across ensembles.

> but the results also changed significantly...

No, but there are a few cases where the results change significantly. Hence, these tolerances are controversial.

**Comment by joakim-hove** [comment]
Guys - I am willing to bet significant amount of beers that the request to verify the patch is automatically sent from Jenkins - no humans have been involved.

**Comment by akva2** [comment]
Yes, currently jenkins install is very broken and as i cannot find the reason, i am setting up a new instance (almost done, will deploy tmrw after final sanity checks). Noise such as that post and the localhost links are artifacts of that process. Just ignore.

**Comment by alfbr** [comment]
Had to move these into a separate branch, and the PR was subsequently automatically closed. Will send in a new one to make the change available for testing.

**Pull request closed without merging**
