### PR TITLE
honour group available for higher controll

### PR DESCRIPTION
**Pull request by totto82**

### CODE REVIEW

**Comment by totto82** [comment]
jenkins build this please

**Comment by atgeirr** [comment]
Thanks, merging.

**Comment by akva2** [comment]
this seems to have broken the ParallelRestart test, https://ci.opm-project.org/job/opm-simulators/779/

**Comment by totto82** [comment]
Strange it was green. I will investigate...

**Comment by totto82** [comment]
I works locally. And https://ci.opm-project.org/job/opm-simulators/780/ seems fine. Could it be a false negative.

**Comment by akva2** [comment]
it's not a false negative, but it is also not related to this. running valgrind on test_ParallelRestart discloses quite some issues..

**Comment by atgeirr** [comment]
> it's not a false negative, but it is also not related to this. running valgrind on test_ParallelRestart discloses quite some issues..

That is a bit concerning! If it is more than you can fix easily, you can post the results and we could try to split the work? Risking arbitrary brokenness is not much fun.

**Comment by akva2** [comment]
i'm on top of most of them, this one i have not decoded yet;

```
==207456== Conditional jump or move depends on uninitialised value(s)
==207456==    at 0x6C52FB: Opm::VFPProdTable::operator==(Opm::VFPProdTable const&) const (VFPProdTable.cpp:565)
==207456==    by 0x22A27B: void Opm::Schedule::pack_map<int, Opm::VFPProdTable>(std::vector<Opm::VFPProdTable, std::allocator<Opm::VFPProdTable> >&, std::vector<unsigned long, std::allocator<unsigned long> >&) (Schedule.hpp:422)
==207456==    by 0x1FD77A: void Opm::Schedule::pack_unpack_map<int, Opm::VFPProdTable, Opm::EclMpiSerializer>(Opm::EclMpiSerializer&) (Schedule.hpp:398)
==207456==    by 0x1DC659: void Opm::Schedule::serializeOp<Opm::EclMpiSerializer>(Opm::EclMpiSerializer&) (Schedule.hpp:328)
==207456==    by 0x1C5C5F: void Opm::EclMpiSerializer::pack<Opm::Schedule>(Opm::Schedule&) (eclmpiserializer.hh:302)
==207456==    by 0x1AA1BC: std::tuple<Opm::Schedule, int, int> PackUnpack2<Opm::Schedule>(Opm::Schedule&) (test_ParallelRestart.cpp:286)
==207456==    by 0x16083E: Schedule::test_method() (test_ParallelRestart.cpp:533)
==207456==    by 0x16053F: Schedule_invoker() (test_ParallelRestart.cpp:533)
==207456==    by 0x1E870F: boost::detail::function::void_function_invoker0<void (*)(), void>::invoke(boost::detail::function::function_buffer&) (function_template.hpp:117)
==207456==    by 0x48DC3F1: ??? (in /usr/lib/x86_64-linux-gnu/libboost_unit_test_framework.so.1.71.0)
==207456==    by 0x48D9C74: boost::execution_monitor::catch_signals(boost::function<int ()> const&) (in /usr/lib/x86_64-linux-gnu/libboost_unit_test_framework.so.1.71.0)
==207456==    by 0x48D9CF7: boost::execution_monitor::execute(boost::function<int ()> const&) (in /usr/lib/x86_64-linux-gnu/libboost_unit_test_framework.so.1.71.0)
==207456==  Uninitialised value was created by a heap allocation
==207456==    at 0x483BE63: operator new(unsigned long) (in /usr/lib/x86_64-linux-gnu/valgrind/vgpreload_memcheck-amd64-linux.so)
==207456==    by 0x2F06BD: __gnu_cxx::new_allocator<std::__detail::_Hash_node<std::pair<int const, Opm::VFPProdTable>, false> >::allocate(unsigned long, void const*) (new_allocator.h:114)
==207456==    by 0x2D5DD3: std::allocator_traits<std::allocator<std::__detail::_Hash_node<std::pair<int const, Opm::VFPProdTable>, false> > >::allocate(std::allocator<std::__detail::_Hash_node<std::pair<int const, Opm::VFPProdTable>, false> >&, unsigned long) (alloc_traits.h:444)
==207456==    by 0x2B44A5: std::__detail::_Hash_node<std::pair<int const, Opm::VFPProdTable>, false>* std::__detail::_Hashtable_alloc<std::allocator<std::__detail::_Hash_node<std::pair<int const, Opm::VFPProdTable>, false> > >::_M_allocate_node<std::piecewise_construct_t const&, std::tuple<int const&>, std::tuple<> >(std::piecewise_construct_t const&, std::tuple<int const&>&&, std::tuple<>&&) (hashtable_policy.h:2081)
==207456==    by 0x28BE99: std::__detail::_Map_base<int, std::pair<int const, Opm::VFPProdTable>, std::allocator<std::pair<int const, Opm::VFPProdTable> >, std::__detail::_Select1st, std::equal_to<int>, std::hash<int>, std::__detail::_Mod_range_hashing, std::__detail::_Default_ranged_hash, std::__detail::_Prime_rehash_policy, std::__detail::_Hashtable_traits<false, false, true>, true>::operator[](int const&) (hashtable_policy.h:701)
==207456==    by 0x25B15E: std::unordered_map<int, Opm::VFPProdTable, std::hash<int>, std::equal_to<int>, std::allocator<std::pair<int const, Opm::VFPProdTable> > >::operator[](int const&) (unordered_map.h:985)
==207456==    by 0x22A25E: void Opm::Schedule::pack_map<int, Opm::VFPProdTable>(std::vector<Opm::VFPProdTable, std::allocator<Opm::VFPProdTable> >&, std::vector<unsigned long, std::allocator<unsigned long> >&) (Schedule.hpp:422)
==207456==    by 0x1FD77A: void Opm::Schedule::pack_unpack_map<int, Opm::VFPProdTable, Opm::EclMpiSerializer>(Opm::EclMpiSerializer&) (Schedule.hpp:398)
==207456==    by 0x1DC659: void Opm::Schedule::serializeOp<Opm::EclMpiSerializer>(Opm::EclMpiSerializer&) (Schedule.hpp:328)
==207456==    by 0x1C5C5F: void Opm::EclMpiSerializer::pack<Opm::Schedule>(Opm::Schedule&) (eclmpiserializer.hh:302)
==207456==    by 0x1AA1BC: std::tuple<Opm::Schedule, int, int> PackUnpack2<Opm::Schedule>(Opm::Schedule&) (test_ParallelRestart.cpp:286)
==207456==    by 0x16083E: Schedule::test_method() (test_ParallelRestart.cpp:533)
```

**Comment by atgeirr** [comment]
Looked at the pack_map() function for a while but could not see any bugs there.

**Comment by bska** [comment]
> this one i have not decoded yet;

This is possibly caused by `ScheduleDeck`'s [default constructor](https://github.com/OPM/opm-common/blob/ca03815efea1835ab1a9828f4fb094e8a6fc4a38/src/opm/parser/eclipse/EclipseState/Schedule/ScheduleDeck.cpp#L290-L293) not initialising [`m_restart_offset`](https://github.com/OPM/opm-common/blob/ca03815efea1835ab1a9828f4fb094e8a6fc4a38/opm/parser/eclipse/EclipseState/Schedule/ScheduleDeck.hpp#L123).  The data members [`m_restart_time`](https://github.com/OPM/opm-common/blob/ca03815efea1835ab1a9828f4fb094e8a6fc4a38/opm/parser/eclipse/EclipseState/Schedule/ScheduleDeck.hpp#L122) and [`m_restart_offset`](https://github.com/OPM/opm-common/blob/ca03815efea1835ab1a9828f4fb094e8a6fc4a38/opm/parser/eclipse/EclipseState/Schedule/ScheduleDeck.hpp#L124) are of class type with default constructors but should probably be fully initialised too.

**Comment by akva2** [comment]
i found it. it's not really a biggie.
on l422 https://github.com/OPM/opm-common/blob/master/opm/parser/eclipse/EclipseState/Schedule/Schedule.hpp#L422 it uses [] to deref the map. This is mutable, so it will insert a default created object. Since default created objects have uninitialized members, it causes the valgrind error. Fixed it by using find and checking the iterator.

What @bska points to is another issue but I have already fixed that too. I'm just cleaning up now, then I will PR.

**Comment by akva2** [comment]
https://github.com/OPM/opm-common/pull/2434

**Comment by atgeirr** [comment]
I see, thanks! I do not understand why we need the current_value map, could we not do
```
if (!value_list.empty() && !(*value == value_list.back())) {
...
}
```

**Comment by akva2** [comment]
i must admit i did not really read the code that close. @joakim-hove will have to answer that one.

**Comment by joakim-hove** [comment]
> I do not understand why we need the current_value map, could we not do

Quite frankly I can not answer right away - but the core of the complexity here is to make sure that only one unique value is passed for objects managed by `std::shared_ptr<>`.

**Pull request merged**
