### PR TITLE
Trinemykk smartwater

### PR DESCRIPTION
**Pull request by totto82**
Rebased version of #2184

### CODE REVIEW

**Comment by totto82** [comment]
jenkins build this opm-common=1391 opm-material=367 opm-models=583 please

**Comment by totto82** [comment]
jenkins build this opm-common=1391 opm-material=367 opm-models=583 please

**Comment by totto82** [comment]
jenkins build this opm-common=1391 opm-material=381 opm-models=584 please

**Comment by totto82** [comment]
jenkins build this opm-common=1391 opm-material=381 opm-models=585 please

**Comment by totto82** [comment]
jenkins build this opm-common=1391 opm-material=381 opm-models=585 please

**Comment by totto82** [comment]
jenkins build this opm-common=1391 opm-material=381 opm-models=585 please

**Comment by totto82** [comment]
@akva2 Any hint on the ParallelRestart failure?

**Comment by totto82** [comment]
jenkins build this opm-common=1391 opm-material=381 opm-models=585 please

**Comment by akva2** [comment]
I told you pvt was nasty ;) 

I can't tell off hand what is up. Use your debugger, some type is missing serialization support, likely the new pvt stuff added ?

**Comment by totto82** [comment]
@akva2 I have made a fix. I am a bit afraid it is band-aid solution for something else, so I would appreciate if you could take a look at the last commit.

**Comment by totto82** [comment]
jenkins build this opm-common=1391 opm-material=381 opm-models=585 opm-tests=227 please

**Comment by totto82** [comment]
@akva2 Do I need to merge opm-tests first for Jenkins to pick-up the new test case.

**Comment by akva2** [comment]
not to pick up the test case, but if you want to add reference data you have to merge the test case first, as you cannot have two opm-tests PR in one build.

it could not run cause it's SPE1CASE*1*_BRINE.DATA, not SPE1CASE*2*_BRINE.DATA

**Comment by akva2** [comment]
it's fine with the bandaid for now. i still have some ways to go before i attack the fluid system setup so as long as it builds and the test works, it's okay for now.

**Comment by akva2** [comment]
please address the warnings. change OPM_OPTIM_UNUSED to OPM_UNUSED for those vars, they are not used with debugging either.

**Comment by totto82** [comment]
jenkins build this opm-common=1391 opm-material=381 opm-models=585 opm-tests=227 please

**Comment by totto82** [comment]
Finally green!

**Pull request merged**
