### PR TITLE
Write the initial OIP values if requested.

### PR DESCRIPTION
**Pull request by blattms**
This is when writing the first time step as is this is the first step when OIP is available.
With this change FOE will be calculated by opm-output if FOE and FOIP is requested.

Needs OPM/opm-output#198

### CODE REVIEW

**Comment by blattms** [comment]
jenkins build this opm-output=198 please

**Comment by joakim-hove** [comment]
As I see it this will not be 100% correct, the call to `Summary::overWriteInitialOIP( )` will come *after* the first timestep has been completed, and in general that will not be the *initial* OIP, but rather the OIP after the first timestep. Probably not a big difference - but in general not entirely correct either.

**Comment by blattms** [comment]
I admit that this is hard to see, but I am sure you are wrong. The initial write is at [SimulatorFullyImplicitBlackoilEbos.hpp#L293](/OPM/opm-simulators/blob/1939453adb10b0e5a01a25933ea30becba88a6a0/opm/autodiff/SimulatorFullyImplicitBlackoilEbos.hpp#L293). These are really the initial values being written. Only the grid and the transmissibilities have been written before. Afterwards the computation starts in [SimulatorFullyImplicitBlackoilEbos.hpp#L311-349](/OPM/opm-simulators/blob/1939453adb10b0e5a01a25933ea30becba88a6a0/opm/autodiff/SimulatorFullyImplicitBlackoilEbos.hpp#L311-L349).

**Comment by joakim-hove** [comment]
OK - then I am sorry for the noise.

**Comment by blattms** [comment]
Don't be sorry. It was a nice check.

**Comment by joakim-hove** [comment]
Ok -last comment:Maybe instead of maintaining the `writeInitial` flag the write timestep routine in output could check the report step value and take correct action if report step equals zero?

**Comment by blattms** [comment]
Seems like a good idea.

**Comment by blattms** [comment]
BTW it made me thinking what happens when restarting a simulation. Looking at the code which calls writeTimestepWithoutCellProperties for all previous report steps, I assume that the initial OIP values will be missing and FOE will not be calculated.

**Comment by joakim-hove** [comment]
Restarted simulations will not handle FOE correctly - that is a bigger task though.

**Comment by blattms** [comment]
jenkins build this opm-output=198 please

**Comment by blattms** [comment]
Updated with @joakim-hove's idea, no extra boolean parameter anymore.

**Comment by blattms** [comment]
jenkins build this opm-output=198 please

**Comment by atgeirr** [comment]
I have verified that this compiles and works, will merge.

There is a caveat however: to get FOE numbers different from zero I must specify *both* FOE and FOIP in the SUMMARY section. That seems like a minor bug to me, somewhere in opm-output. I'll investigate it.

**Comment by atgeirr** [comment]
> That seems like a minor bug to me, somewhere in opm-output. I'll investigate it.

I was wrong, it is the simulator's responsibility to pass the data if needed. Making a patch.

**Pull request merged**
