### PR TITLE
Make SummaryState Objects Aware of Undefined UDQ Value

### PR DESCRIPTION
**Pull request by bska**
This PR switches to calling the `SummaryState` constructor which is aware of the value of undefined UDQs (OPM/opm-common#4052) directly.

While here, also sort headers, split some long lines, and prefer initialisation lists to constructor body assignments.

### CODE REVIEW

**Comment by bska** [comment]
I'm creating this PR in draft mode for two reasons

1. It depends on the new `SummaryState` constructor introduced in upstream PR OPM/opm-common#4052
2. It is, technically, built on top of the earlier PR #5330 

The latter is mostly to simplify testing and not strictly necessary for this work in isolation.  I will probably decouple this PR from #5330 once the upstream PR is merged.  I will nevertheless keep the PR in a draft state until such time as that happens.

**Comment by bska** [comment]
jenkins build this please

**Comment by bska** [comment]
jenkins build this please

**Comment by bska** [comment]
jenkins build this please

**Comment by bska** [comment]
I'm setting this PR back to draft state pending #5379.

**Comment by tskille** [comment]
This PR has now been tested locally in Equinor and results are excellent. Looking forward to see this code getting in to master.

**Comment by bska** [comment]
The prerequisite PR #5379 was merged into the master branch.  I'm marking this as "ready for review" now and I'm running a build check.

**Comment by bska** [comment]
jenkins build this please

**Review by akva2 — APPROVED** [review]
Looks fine

**Comment by bska** [comment]
PR approved and build check is green.  I'll merge into the master branch.

**Pull request merged**
