### PR TITLE
rename "local AD" to "dense AD"

### PR DESCRIPTION
**Pull request by andlaus**
this is the opm-simulators part of OPM/opm-material#147. the PR must be merged in lockstep lest there be breakage...

### CODE REVIEW

**Comment by atgeirr** [comment]
jenkins build this opm-material=147 opm-core=1022 please

**Comment by atgeirr** [comment]
This looks completely innocent, and you can merge if Jenkins succeeds. There is one tiny fly in the ointment though: the use of "Lad" in typedefs and variable names can now be a little confusing. I'll not require a type/variable renaming now though, since that can happen later in an independent PR only for this module.

**Comment by andlaus** [comment]
> There is one tiny fly in the ointment though: the use of "Lad" in typedefs and variable names can now be a little confusing. I'll not require a type/variable renaming now though, since that can happen later in an independent PR only for this module.

good point, I just forgot about the *Lad variable names. I will rename it to `*Dad` (or whatever you prefer) ASAP.

**Comment by andlaus** [comment]
alternatively, they could be renamed to `*Mom` ;)

**Comment by jokva** [comment]
"I deref'd your mum", let's make this a trending insult people.

**Comment by andlaus** [comment]
*g*. I guess dads are more likely to be able cope with these kinds of insults ;)

**Pull request merged**
