### PR TITLE
Switch to dune buildsystem

### PR DESCRIPTION
**Pull request by andlaus**
this is the opm-simulators part of OPM/opm-common#277. please do the generic discussion about it there, i.e., only discuss the opm-simulators specific issues here.

### CODE REVIEW

**Comment by andlaus** [comment]
jenkins build this opm-common=277 opm-core=1181 opm-grid=287 ewoms=228 opm-material=250 opm-output=210 please

**Comment by andlaus** [comment]
the jenkins failure is weird: it builds all dependencies just fine but then it fails complains about not finding opm-common when configuring the final module (i.e., opm-simulators). any idea @akva2?

**Comment by andlaus** [comment]
jenkins build this opm-common=277 opm-core=1181 opm-grid=287 ewoms=228 opm-material=250 opm-output=210 please

**Comment by andlaus** [comment]
jenkins seems not to start even though its queue is currently empty. This may be caused by the fact that the exact same commit ID was already tested. While this is reasonable behavior, it ignores the fact that the upstream PRs have some changes. is this theory correct @akva2?

**Comment by andlaus** [comment]
jenkins build this opm-common=277 opm-core=1181 opm-grid=287 ewoms=228 opm-material=250 opm-output=210 please

**Comment by andlaus** [comment]
jenkins build this opm-common=277 opm-core=1181 opm-grid=287 ewoms=228 opm-material=250 opm-output=210 please

**Comment by andlaus** [comment]
jenkins build this opm-common=277 opm-core=1181 opm-grid=287 ewoms=228 opm-material=250 opm-output=210 please

**Comment by andlaus** [comment]
jenkins build this opm-data=270 opm-common=277 opm-core=1181 opm-grid=287 ewoms=228 opm-material=250 opm-output=210 please

**Comment by andlaus** [comment]
jenkins build this opm-data=270 opm-common=277 opm-core=1181 opm-grid=287 ewoms=228 opm-material=250 opm-output=210 please

**Comment by andlaus** [comment]
jenkins build this opm-data=270 opm-common=277 opm-core=1181 opm-grid=287 ewoms=228 opm-material=250 opm-output=210 please

**Comment by andlaus** [comment]
jenkins build this opm-data=270 opm-common=277 opm-core=1181 opm-grid=287 ewoms=228 opm-material=250 opm-output=210 please

**Comment by andlaus** [comment]
jenkins build this opm-data=270 opm-common=277 opm-core=1181 opm-grid=287 ewoms=228 opm-material=250 opm-output=210 please

**Comment by akva2** [comment]
i promised to stay out of this, but when you interfer with systems i maintain, i have to put down the foot.. revert the opm data pull on every build immediately or i WILL revoke your jenkins trigger rights. network traffic is a direct cost. you have exactly 0 builds to comply.

**Comment by andlaus** [comment]
alright, no problem. will you fix this then, please?

**Comment by akva2** [comment]
no.

**Comment by andlaus** [comment]
I was not aware that this broke the jenkins rig. 

> no.

well, the only problem is to point the compareEcl cmake stuff to the correct location of opm-data. since it works fine for me locally, I'm pretty sure that this is some jenkins issue and the errors must thus be ignored.

**Comment by andlaus** [comment]
jenkins build this opm-data=270 opm-common=277 opm-core=1181 opm-grid=287 ewoms=228 opm-material=250 opm-output=210 please

**Comment by andlaus** [comment]
jenkins build this opm-common=277 opm-core=1181 opm-grid=287 ewoms=228 opm-material=250 opm-output=210 please

**Comment by andlaus** [comment]
jenkins build this opm-common=277 opm-core=1181 opm-grid=287 ewoms=228 opm-material=250 opm-output=210 please

**Comment by andlaus** [comment]
jenkins build this opm-common=277 opm-core=1181 opm-grid=287 ewoms=228 opm-material=250 opm-output=210 please

**Comment by andlaus** [comment]
jenkins build this opm-common=277 opm-core=1181 opm-grid=287 ewoms=228 opm-material=250 opm-output=210 please

**Comment by andlaus** [comment]
finally! jenkins is now happy and tests everything which it tested before. IMO, fixing stuff like this is way too much fun without SSH access to the CI system.

**Comment by andlaus** [comment]
jenkins build this opm-common=277 opm-core=1181 opm-grid=287 ewoms=228 opm-material=250 opm-output=210 please

**Comment by andlaus** [comment]
jenkins build this opm-common=277 opm-core=1181 opm-grid=287 ewoms=228 opm-material=250 opm-output=210 please

**Comment by andlaus** [comment]
jenkins build this opm-common=277 opm-core=1181 opm-grid=287 ewoms=228 opm-material=250 opm-output=210 please

**Comment by andlaus** [comment]
jenkins build this opm-common=277 opm-core=1181 opm-grid=287 ewoms=228 opm-material=250 opm-output=210 please

**Comment by andlaus** [comment]
jenkins build this opm-common=277 opm-core=1181 opm-grid=287 ewoms=228 opm-material=250 opm-output=210 please

**Comment by andlaus** [comment]
jenkins build this opm-common=277 opm-core=1181 opm-grid=287 ewoms=228 opm-material=250 opm-output=210 please

**Comment by andlaus** [comment]
jenkins build this opm-common=277 opm-core=1181 opm-grid=287 ewoms=228 opm-material=250 opm-output=210 please

**Comment by andlaus** [comment]
jenkins build this opm-common=277 opm-core=1181 opm-grid=287 ewoms=228 opm-material=250 opm-output=210 please

**Comment by andlaus** [comment]
jenkins build this opm-common=277 opm-core=1181 opm-grid=287 ewoms=228 opm-material=250 opm-output=210 please

**Comment by andlaus** [comment]
jenkins build this opm-common=277 opm-core=1181 opm-grid=287 ewoms=228 opm-material=250 opm-output=210 please

**Comment by andlaus** [comment]
jenkins build this opm-common=277 opm-core=1181 opm-grid=287 ewoms=228 opm-material=250 opm-output=210 please

**Comment by andlaus** [comment]
jenkins build this opm-common=277 opm-core=1181 opm-grid=287 ewoms=228 opm-material=250 opm-output=210 please

**Comment by andlaus** [comment]
jenkins build this opm-common=277 opm-core=1181 opm-grid=287 ewoms=228 opm-material=250 opm-output=210 please

**Comment by andlaus** [comment]
jenkins build this opm-common=277 opm-core=1181 opm-grid=287 ewoms=228 opm-material=250 opm-output=210 please

**Comment by andlaus** [comment]
jenkins build this opm-common=277 opm-core=1181 opm-grid=287 ewoms=228 opm-material=250 opm-output=210 please

**Comment by andlaus** [comment]
jenkins build this opm-common=277 opm-core=1181 opm-grid=287 ewoms=228 opm-material=250 opm-output=210 please

**Comment by andlaus** [comment]
jenkins build this opm-common=277 opm-core=1181 opm-grid=287 ewoms=228 opm-material=250 opm-output=210 please

**Comment by andlaus** [comment]
jenkins build this opm-common=277 opm-core=1181 opm-grid=287 ewoms=228 opm-material=250 opm-output=210 please

**Comment by andlaus** [comment]
jenkins build this opm-common=277 opm-core=1181 opm-grid=287 ewoms=228 opm-material=250 opm-output=210 please

**Comment by andlaus** [comment]
this PR will soon be replaced by a "more additive" one. closing.

**Pull request closed without merging**
