### PR TITLE
Add cases to regression tests

### PR DESCRIPTION
**Pull request by goncalvesmachadoc**

### CODE REVIEW

**Comment by bska** [comment]
jenkins build this please

**Comment by bska** [comment]
Hi,

There were, as expected, two failed regression tests as a result of this PR.  One of those failures,

* [compareECLFiles_flow_SPIDER_CAKESLICE](https://ci.opm-project.org/job/opm-simulators-PR-builder/1921/testReport/(root)/mpi/compareECLFiles_flow_SPIDER_CAKESLICE/)

was expected (no existing reference solution with which to compare the results), but the other failure

* [compareParallelSim_flow_onephase_energy_SPE1CASE2_THERMAL_ONEPHASE](https://ci.opm-project.org/job/opm-simulators-PR-builder/1921/testReport/(root)/mpi/compareParallelSim_flow_onephase_energy_SPE1CASE2_THERMAL_ONEPHASE/)

appears to be different (input not found).  @akva2: Would you mind taking a look at the [specification](https://github.com/OPM/opm-simulators/pull/2972/files) here to help identify what's missing?

**Comment by goncalvesmachadoc** [comment]
> * [compareParallelSim_flow_onephase_energy_SPE1CASE2_THERMAL_ONEPHASE](https://ci.opm-project.org/job/opm-simulators-PR-builder/1921/testReport/(root)/mpi/compareParallelSim_flow_onephase_energy_SPE1CASE2_THERMAL_ONEPHASE/)
> 
> appears to be different (input not found). @akva2: Would you mind taking a look at the [specification](https://github.com/OPM/opm-simulators/pull/2972/files) here to help identify what's missing?

The PR with this case has not being merged yet in OPM-tests.

**Comment by bska** [comment]
> > Would you mind taking a look at the [specification](https://github.com/OPM/opm-simulators/pull/2972/files) here to help identify what's missing?
> 
> The PR with this case has not being merged yet in OPM-tests.

Ah, I see.  Which PR is that, please?

**Comment by goncalvesmachadoc** [comment]
PR #500

**Comment by bska** [comment]
jenkins build this opm-tests=500 please

**Comment by bska** [comment]
jenkins build this please

**Comment by bska** [comment]
jenkins build this update_data please

**Comment by bska** [comment]
jenkins build this opm-tests=506 please

**Comment by bska** [comment]
New reference solutions installed on the CI system.  Merging this to bring the overall system back to a consistent state.

**Pull request merged**
