### PR TITLE
[feature][WellModelMatrixAdapter] use OpenMP parallel for matrix-vector multiply.

### PR DESCRIPTION
**Pull request by dr-robertk**
Since flow already uses 2 threads per default we might as well just uses those for the matrix-vector multiply during the linear solve. This PR reduces the run time of flow for NORNE.

Current master:
================    End of simulation     ===============

Total time (seconds):         495.621
Solver time (seconds):        492.412
 Assembly time (seconds):     166.356 (Failed: 3.5837; 2.15423%)
 Linear solve time (seconds): 308.897 (Failed: 5.65008; 1.82911%)
 Update time (seconds):       8.28161 (Failed: 0.188576; 2.27705%)
 Output write time (seconds): 4.08117
Overall Well Iterations:      952 (Failed: 5; 0.52521%)
Overall Linearizations:       1950 (Failed: 42; 2.15385%)
Overall Newton Iterations:    1615 (Failed: 42; 2.60062%)
Overall Linear Iterations:    24928 (Failed: 420; 1.68485%)

Wiht this PR (reduction in the linear solve time):
================    End of simulation     ===============

Total time (seconds):         471.362
Solver time (seconds):        468.153
 Assembly time (seconds):     166.267 (Failed: 3.56121; 2.14186%)
 Linear solve time (seconds): 284.579 (Failed: 5.22471; 1.83594%)
 Update time (seconds):       8.34116 (Failed: 0.187728; 2.25062%)
 Output write time (seconds): 4.08875
Overall Well Iterations:      952 (Failed: 5; 0.52521%)
Overall Linearizations:       1950 (Failed: 42; 2.15385%)
Overall Newton Iterations:    1615 (Failed: 42; 2.60062%)
Overall Linear Iterations:    24928 (Failed: 420; 1.68485%)

### CODE REVIEW

**Comment by alfbr** [comment]
Very interesting results! From a user who do not want to deal with MPI, this is a clear win. I am a bit more uncertain how this will play out in combination with MPI. The linear solver is memory bandwidth limited, and with MPI we explicitely distribute load on the numa nodes to ensure performance. The idea with enabling OpenMP by default on two threads is that all x86 CPUs today have hyperthreading, and the extra thread actually gives a bit of extra juice for the assembly. If we include the linear solve in it, I am afraid it will be a negative effect in this case (i.e., the case with all physical cores in use with MPI, the extra thread on the hyperthreading extension of the CPU). I can do some testing over here.

**Comment by andlaus** [comment]
can you actually test if your assumption applies, @alfbr? modern CPUs are awfully complicated beasts...

**Comment by alfbr** [comment]
Yes, as I said, I can do some testing over here. The timing is a bit bad though. However, it is dead easy for you to test the hyperthreading thingy. If you have a 4core/8thread laptop, simply test mpriun -np4 with and without this patch, and see if performance degrades. In addition comes the Numa-aware aspect, which a typical desktop or laptop CPU will not exhibit. On the positive side, the multithreading do not influence convergence. I am afraid this ends up a bit less clear cut than threading the assembly, in the sense that turning it on by default will have a negative impact in a couple of cases.

**Comment by dr-robertk** [comment]
Shouldn't be to hard to only enable this when the size of system is large enough so that it actually makes sense.

**Comment by alfbr** [comment]
Good point. I should be able to do a bit of benchmarking next week though, so that we can have a better picture of possible cases with negative impact.

**Comment by dr-robertk** [comment]
Does not seem to be of interest, closing.

**Pull request closed without merging**
