### PR TITLE
Perf wellcontainer

### PR DESCRIPTION
**Pull request by joakim-hove**
Use `WellContainer<std::vector<double>>` for various perforation properties.

### CODE REVIEW

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by joakim-hove** [comment]
https://ci.opm-project.org/job/opm-simulators-PR-builder/2482/testReport/

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by joakim-hove** [comment]
One last kick on this - and then I will merge it.

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by bska** [comment]
> One last kick on this - and then I will merge it.

Please address the [new warning concerning unused variables](https://ci.opm-project.org/job/opm-simulators-PR-builder/2494/gcc/new/) before this gets merged.

**Comment by joakim-hove** [comment]
jenkins build this please

**Pull request merged**
