### PR TITLE
Cleanup SparseMatrixAdapter.

### PR DESCRIPTION
**Pull request by dr-robertk**
This PR cleans the use of matrices over SparseMatrixAdapter in the various well models to make the code compile, when other linear solver frameworks are used. In addition it contains to minor fixes.

### CODE REVIEW

**Comment by blattms** [comment]
benchmark

**Comment by alfbr** [comment]
benchmark please

**Comment by ytelses** [comment]
Benchmark result overview: 




| Test    | Configuration                              | Relative |
| ------- | ------------------------------------------ | -------- |
| opm-git | OPM Benchmark: flow_mpi_extra - Threads: 1 | 0.977    |
| opm-git | OPM Benchmark: flow_mpi_extra - Threads: 8 | 1.039    |
| opm-git | OPM Benchmark: flow_mpi_norne - Threads: 1 | 1.035    |
| opm-git | OPM Benchmark: flow_mpi_norne - Threads: 8 | 0.956    |
* Speed-up = Total time master / Total time pull request. Above 1.0 is an improvement. *



View result details @ https://www.ytelses.com/opm/?page=result&id=389

**Comment by dr-robertk** [comment]
@blattms: This one should go into the 2019.10 release.

**Comment by blattms** [comment]
Seems like the well code evolved quite a lot. Someone needs to resolve the merge conflict,

**Comment by dr-robertk** [comment]
jenkins build this please

**Comment by dr-robertk** [comment]
@blattms: I have rebased my commits on the current master.

**Comment by dr-robertk** [comment]
@blattms: Any objections of this being merged?

**Comment by dr-robertk** [comment]
jenkins build this please

**Comment by dr-robertk** [comment]
@totto82: I have now remove the duplicate multTransposed method.

**Comment by dr-robertk** [comment]
benchmark please

**Comment by ytelses** [comment]
Benchmark result overview: 




| Test    | Configuration                              | Relative |
| ------- | ------------------------------------------ | -------- |
| opm-git | OPM Benchmark: flow_mpi_extra - Threads: 1 | 1.023    |
| opm-git | OPM Benchmark: flow_mpi_extra - Threads: 8 | 0.942    |
| opm-git | OPM Benchmark: flow_mpi_norne - Threads: 1 | 0.981    |
| opm-git | OPM Benchmark: flow_mpi_norne - Threads: 8 | 0.99     |
* Speed-up = Total time master / Total time pull request. Above 1.0 is an improvement. *



View result details @ https://www.ytelses.com/opm/?page=result&id=541

**Comment by totto82** [comment]
jenkins build this please

**Comment by dr-robertk** [comment]
jenkins build this please

**Comment by dr-robertk** [comment]
@totto82: I removed the unused variable.

**Pull request merged**
