### PR TITLE
added: allow running the norne test in parallel

### PR DESCRIPTION
**Pull request by akva2**
This enables triggering a parallel norne run using 'run norne_parallel'. trigger runs with 4 procs right now.

### CODE REVIEW

**Comment by akva2** [comment]
jenkins run norne_parallel please

**Comment by akva2** [comment]
this worked, but as observed locally, the new opm-grid code deadlocks for norne with 4 processes. @blattms

**Comment by blattms** [comment]
Not sure I can easily fix this in a fast manner and awfully sorry for my premature merge. I guess I will have to propose reverting that merge.

**Comment by blattms** [comment]
I have a merge request reverting the premature merge in OPM/opm-grid#404

**Comment by atgeirr** [comment]
The parallel tests in opm-simulators work, and locally I assumes this works @blattms? Is the error only showing up on Jenkins?

**Comment by akva2** [comment]
the error shows up with norne using e.g. 4 and 8 processes. it passes with 2 and 6. i'll take the liberty of quoting myself;
[quote]
this worked, but as observed *locally*, the new opm-grid code deadlocks for norne with 4 processes.
[/quote]

**Comment by akva2** [comment]
this pr has value in itself, please consider merging it.

**Comment by atgeirr** [comment]
jenkins run norne_parallel please

**Comment by atgeirr** [comment]
This ran through, but the artifacts (well plots) were not generated properly:

```
./plotwells.sh: line 22: /var/lib/jenkins/workspace/opm-simulators-PR-builder@2/mpi/install/bin/summary.x: No such file or directory
```

I guess that is a separate problem not caused by this PR, so this should be merged in any case?

**Comment by akva2** [comment]
yeah, that's a libecl binary we have not yet replaced. not related to this pr.

**Comment by atgeirr** [comment]
> yeah, that's a libecl binary we have not yet replaced

No need to replace the binary for that purpose? It's not like it needs to be updated all the time, if at all?

**Comment by akva2** [comment]
not as such, but it was built as part of the libecl dependency. @tskille said he'd look at implementing a replacement.

**Comment by atgeirr** [comment]
> @tskille said he'd look at implementing a replacement.

Ok, I suggest we keep using the utilities though until such a replacement exists.

**Comment by akva2** [comment]
okay, i'll put int the work to use a system hosted installed version and build one up then.

**Pull request merged**
