### PR TITLE
changed: use compressed field properties for blackoil extension init conds

### PR DESCRIPTION
**Pull request by akva2**
Extracted from https://github.com/OPM/opm-simulators/pull/2374

### CODE REVIEW

**Comment by akva2** [comment]
jenkins run norne_parallel please

**Comment by blattms** [comment]
On a side note: In the plots we compare the parallel run with 4 procs with flow_legacy and the commercial simulator. Of course there will be slight discrepancies which hard to judge without an acompanying serial run.

**Comment by akva2** [comment]
okay, i'll make sure to run serial and parallel in future prs.

**Comment by blattms** [comment]
ah, if there has been a serial run then it will be taken into account. Cool.

**Pull request merged**
