### PR TITLE
Add  test for cases with Carlson’s hysteresis model

### PR DESCRIPTION
**Pull request by totto82**
0: Drainage curve is used or the wetting phase
1: Imbibition curve is used for the wetting phase

The second test also test the combination solvent + hysteresis.

Depends on OPM/opm-material#300 and OPM/opm-tests#32

### CODE REVIEW

**Comment by andlaus** [comment]
as far as I can tell, all is good here.

**Comment by andlaus** [comment]
if nobody objects, I'll merge this in the afternoon.

**Comment by totto82** [comment]
@andlaus I think you where a bit fast on this. Now we have added one more test, but not updated the reference solution.

**Comment by totto82** [comment]
I will revert it, and ask Jenkins for the ref solution.

**Comment by andlaus** [comment]
yes, that was too fast. apologies for that. with OPM/opm-tests#34 Jenkins seems to be happy again, though.

**Pull request merged**
