### PR TITLE
Get rid off temporary copies of depth and pore volume.

### PR DESCRIPTION
**Pull request by blattms**
We can pass the Eigen array directly to WellModel::init where they
will either be copied anyway or the important data will be extracted.

### CODE REVIEW

**Comment by atgeirr** [comment]
I think a reason these interfaces take `std::vector` is to avoid the Eigen dependency. So perhaps a better way would be to change the `Eigen::Array`s to `std::vector`s in the DerivedGeology? That would also require some changes to the legacy sims, but would get rid of these temporaries for flow_ebos while preserving the Eigen-independence.

**Comment by andlaus** [comment]
a better fix for this is #1019, IMO. The argument outlined there still applies: removing `geo_` might lead to slightly better performance, the `geo_` object is unused except for a bit of output and keeping a non-trivial object like this around is very confusing to the uninitiated.

I've rebased #1019 on top of the current master and verified that it produces exactly the same error with MPI for SPE1CASE2 as the present PR.

**Comment by atgeirr** [comment]
While I do not think #1019 is the answer (as discussed a little in that PR) I think this PR should not be merged either, due to the increased Eigen usage (it does not fix any bugs and is only a simplification/performance thing, correct?). I therefore intend to close this, unless there are points I have not considered, @blattms?

**Comment by blattms** [comment]
Honestly, I do not care about closing. But I also do not see how this
patch strengthens the EIGEN dependency.

**Comment by atgeirr** [comment]
> Honestly, I do not care about closing.

Ok, will close this then!

> But I also do not see how this
> patch strengthens the EIGEN dependency.

By making StandardWellsDense include and use Eigen.

**Pull request closed without merging**
