### PR TITLE
Log debug messages about wells only on master.

### PR DESCRIPTION
**Pull request by blattms**
Previously all ranks logged the message and did clutter the
output files quite a bit.

### CODE REVIEW

**Comment by GitPaean** [comment]
jenkins build this please

**Comment by GitPaean** [comment]
A small question, `terminal_output_` is only true for the master process, right?

**Comment by akva2** [comment]
gotta love the if spaghetti :>
just for reference, this can be compared to the equivalent things in IFEM;
[code]
IFEM::cout << "only logged to terminal on a specified process, and optionally routed to a separate file per process" << std::endl;
[/code]
which is a better approach imho. deal with it once and be done with it. not necessarily the use of a stream but the idea.

**Comment by blattms** [comment]
> A small question, `terminal_output_` is only true for the master process, right?

that is what I assumed. I should have checked by
changes. Embarassingly, I did not. Will do right away.

**Comment by blattms** [comment]
Arrgh, there is one message for every well here. That is quite some
logging. Do we really want that?

In any case my patch is wrong as it will neglect all messages for
wells not on rank 0.

**Comment by blattms** [comment]
Closing because of this.

IMHO we are using too much logging...

**Comment by GitPaean** [comment]
> Arrgh, there is one message for every well here. That is quite some
logging. Do we really want that?

For sure, we do not want that. But really? the `OPM_THROW` from `StandardWellsDense` should not happen to every well.

**Comment by blattms** [comment]
Reopening.
I remove my changes to the logging before throwing. Theses messages should be logged on non-root ranks.
@akva2 You are right. Maybe such a function is even there. I did not check.

**Comment by GitPaean** [comment]
I understand your point now. We need to report all the wells having bad residuals, which was designed that way.

**Comment by GitPaean** [comment]
jenkins build this please

**Comment by GitPaean** [comment]
This PR removes the repeated logging message from non-master processes. It looks good to me.

**Comment by atgeirr** [comment]
I see this could have been merged long ago, I'll run Jenkins again to be safe and then merge.

**Comment by atgeirr** [comment]
jenkins build this please

**Pull request merged**
