### PR TITLE
fixReportPRT

### PR DESCRIPTION
**Pull request by goncalvesmachadoc**

### CODE REVIEW

**Comment by goncalvesmachadoc** [comment]
I am trying to get the field information from the summary state, but it is returning zero:

                        const auto& st = simulator_.vanguard().summaryState();
                        const auto& schedule = simulator_.vanguard().schedule();
                        for (const auto& gname: schedule.groupNames()) {
                
                                auto gName = static_cast<std::string>(gname);                
                                auto get = [&st, &gName](const std::string& vector)
                                {
                                        const auto key = vector + ':' + gName;

                                        return st.has(key) ? st.get(key) : 0.0;
                                };      
                
                                tmp_names[0] = gname; 
               
                                tmp_values[2] = get("GOIR");//WellInjDataType::OilRate                          
                                tmp_values[3] = get("GWIR"); //WellInjDataType::WaterRate
                                tmp_values[4] = get("GGIR"); //WellInjDataType::GasRate 
                                tmp_values[5] = get("GVIR");//WellInjDataType::FluidResVol       
                
                                outputInjectionReport_(tmp_values, tmp_names, forceDisableInjOutput); 
                        }
Anyone know how can I fix this?

**Comment by joakim-hove** [comment]
> Anyone know how can I fix this?

Well - `st.get("FOPR")` should get you the field oil production - *if it is there* - if you are getting 0 that probably means that it is not in there; has it been configured in the `SUMMARY`section of the deck?

**Comment by goncalvesmachadoc** [comment]
David reported that the commercial simulator givers values but OPM does gives zeros (Issue [#2559](https://github.com/OPM/opm-simulators/issues/2559)). I am not sure which deck he is testing.  @OPMUSER comments?

**Comment by bska** [comment]
> Well - `st.get("FOPR")` should get you the field oil production - _if it is there_

The field-scale oil production rate is already among the list of [`requiredRestartVectors`](https://github.com/OPM/opm-common/blob/94defc8a087f48de803093dab0d9c48df1bac422/src/opm/output/eclipse/Summary.cpp#L107).  Unless there's a mistake somewhere the value should already be available.

**Comment by OPMUSER** [comment]
@goncalvesmachadoc Sorry for the delay in getting back to you - different time zones.

I used the Norne model with 2020-04 RC2. The FOPR vector should be available as it is in the SUMMARY files and can be plotted in ResInsight.

**Comment by alfbr** [comment]
What is the status here?

**Comment by OPMUSER** [comment]
To be clear, the problem is not with the summary vectors in the SUMMARY file or the RSM file but in the reports in the PRINT file. The issue is still there in 2021-10, as you can see below taken from the Norne model.:

```
=================================================== CUMULATIVE PRODUCTION/INJECTION REPORT =========================================
:  WELL  :  LOCATION :  WELL  :CTRL:    OIL    :   WATER   :    GAS    :   Prod    :    OIL    :   WATER   :    GAS    :   INJ     :
:  NAME  :  (I,J,K)  :  TYPE  :MODE:    PROD   :   PROD    :    PROD   :  RES.VOL. :    INJ    :   INJ     :    INJ    :  RES.VOL. :
:        :           :        :    :    MSCM   :   MSCM    :    MMSCM  :   MRCM    :    MSCM   :   MSCM    :    MMSCM  :   MRCM    :
====================================================================================================================================

:   FIELD:           :        :    :        0.0:        0.0:        0.0:        0.0:        0.0:        0.0:        0.0:        0.0: 
:--------:-----------:--------:----:------------:----------:-----------:-----------:------------:----------:-----------:-----------: 

:  MANI-C:           :        :    :        0.0:        0.0:        0.0:        0.0:        0.0:    48473.0:  8681622.5:    94223.6: 
:--------:-----------:--------:----:------------:----------:-----------:-----------:------------:----------:-----------:-----------: 

:B1-DUMMY:           :        :    :    14152.0:     2918.8:  2579059.4:    26773.2:        0.0:        0.0:        0.0:        0.0: 
:--------:-----------:--------:----:------------:----------:-----------:-----------:------------:----------:-----------:-----------: 

: MANI-D1:           :        :    :    11232.2:     3680.6:  2637147.1:    25614.3:        0.0:        0.0:        0.0:        0.0: 
:--------:-----------:--------:----:------------:----------:-----------:-----------:------------:----------:-----------:-----------: 

:    INJE:           :        :    :        0.0:        0.0:        0.0:        0.0:        0.0:   101835.5:  8681622.5:   149655.1: 
:--------:-----------:--------:----:------------:----------:-----------:-----------:------------:----------:-----------:-----------: 

:    PROD:           :        :    :    67133.3:    23110.0: 14608980.2:   148444.8:        0.0:        0.0:      159.4:        0.8: 
:--------:-----------:--------:----:------------:----------:-----------:-----------:------------:----------:-----------:-----------: 

: MANI-B2:           :        :    :    11069.7:     3922.4:  2870519.8:    26940.9:        0.0:        0.0:        0.0:        0.0: 
:--------:-----------:--------:----:------------:----------:-----------:-----------:------------:----------:-----------:-----------: 

: MANI-B1:           :        :    :    14152.0:     2918.8:  2579059.4:    26773.2:        0.0:        0.0:        0.0:        0.0: 
:--------:-----------:--------:----:------------:----------:-----------:-----------:------------:----------:-----------:-----------: 

: MANI-D2:           :        :    :    11222.3:     1311.0:  3960965.3:    29360.0:        0.0:        0.0:        0.0:        0.0: 
:--------:-----------:--------:----:------------:----------:-----------:-----------:------------:----------:-----------:-----------: 

: MANI-E1:           :        :    :    10346.3:     7953.4:  1442657.3:    23509.0:        0.0:        0.0:      159.4:        0.8: 
:--------:-----------:--------:----:------------:----------:-----------:-----------:------------:----------:-----------:-----------: 

: MANI-E2:           :        :    :     9110.7:     3323.7:  1118631.3:    16247.4:        0.0:        0.0:        0.0:        0.0: 
:--------:-----------:--------:----:------------:----------:-----------:-----------:------------:----------:-----------:-----------: 

: MANI-K1:           :        :    :        0.0:        0.0:        0.0:        0.0:        0.0:        0.0:        0.0:        0.0: 
:--------:-----------:--------:----:------------:----------:-----------:-----------:------------:----------:-----------:-----------: 

: MANI-K2:           :        :    :        1.1:        0.0:    28688.1:      134.5:        0.0:        0.0:        0.0:        0.0: 
:--------:-----------:--------:----:------------:----------:-----------:-----------:------------:----------:-----------:-----------: 


```

**Comment by alfbr** [comment]
> To be clear, the problem is not with the summary vectors in the SUMMARY file or the RSM file but in the reports in the PRINT file. The issue is still there in 2021-10, as you can see below taken from the Norne model.:

Thanks for the clarification! Next, I am wondering if this PR solves the issue? If so, a rebase and merge would be great.

**Comment by goncalvesmachadoc** [comment]
This PR switch outputting Nan to zero and report values for FIELD in the PRT file. 
In order to not break any simulations in case they are not added in SUMMARY section, FVIR, FOIR and FOIT need to be added as required vectors in opm-common. Will send another PR for that.

**Comment by bska** [comment]
jenkins build this please

**Comment by bska** [comment]
Hi @goncalvesmachadoc. I was a little surprised by the [regression failures](https://ci.opm-project.org/job/opm-simulators-PR-builder/3345/testReport/) because your change looks correct and necessary at first glance. However, on second thought I think I understand what's happening and we'll need to add just a little bit of a safety net here.  The direct cause, I think, is that the `output*Log()` functions are all called [before](https://github.com/OPM/opm-simulators/blob/44faf036c954363916cbdcc0c6c81f82121c324c/ebos/eclwriter.hh#L206-L208) we evaluate/update the `EclWriter`'s `summaryState_` data member in [`EclWriter<>::evalSummaryState()`](https://github.com/OPM/opm-simulators/blob/44faf036c954363916cbdcc0c6c81f82121c324c/ebos/eclwriter.hh#L215).  In general, this ordering probably means that we report slightly stale data in the `.PRT` file but for the very first call to `EclWriter<>::evalSummaryState()` it means that we're trying to extract summary vector values before those values have been assigned.

I think we have two options
1. Move the `output*Log()` calls **after** the call to `evalSummary()`.
2. Protect the direct, FIELD-level, [`SummaryState::get()`](https://github.com/OPM/opm-simulators/blob/52d096c46ac1831d99e057632e8d9f9d63ca3d6c/ebos/eclgenericoutputblackoilmodule.cc#L295-L300) calls with a [default/fallback value](https://github.com/OPM/opm-common/blob/6e6b4384051eb7b5e8bb57a3e25fa1bd3b4b6778/opm/parser/eclipse/EclipseState/Schedule/SummaryState.hpp#L103) as in
    ```C++
    tmp_values[2] = st.get("FOPR", 0.0);
    ```
    Similarly for [`outputCumLog()`](https://github.com/OPM/opm-simulators/blob/52d096c46ac1831d99e057632e8d9f9d63ca3d6c/ebos/eclgenericoutputblackoilmodule.cc#L131-L138) and [`outputInjLog()`](https://github.com/OPM/opm-simulators/blob/52d096c46ac1831d99e057632e8d9f9d63ca3d6c/ebos/eclgenericoutputblackoilmodule.cc#L412-L415).

My **personal** preference might actually to do both of these options.

**Review by bska — COMMENTED** [review]
Thank you so much for the updates.  I **expect** that this will do the right thing, but I'll run a build check to be sure.

**Comment by bska** [comment]
jenkins build this please

**Comment by bska** [comment]
> I'll run a build check to be sure [that the current version does not break anything]

Build check successful.  I'll merge this now.  Thanks a lot for your persistence in seeing this feature through.

**Pull request merged**
