### PR TITLE
added: generate a plot without ecl reference for norne runs

### PR DESCRIPTION
**Pull request by akva2**
sometimes it is easier to compare without the extra data in the graphs

@atgeirr as requested

### CODE REVIEW

**Comment by akva2** [comment]
jenkins run norne_ebos please

**Comment by akva2** [comment]
there we go. works fine now (i pushed a fix directly to opm-data since you were so trigger happy ;))

**Comment by atgeirr** [comment]
Very nice, makes it easier to spot changes. Thanks!

**Comment by atgeirr** [comment]
Next question is of course: should we have separate flow_legacy and flow_ebos reference solutions (since they are sufficiently different to notice)?

**Comment by akva2** [comment]
i'd reckon so. it would be interleaved in the general reorganization needed for reference data to move ebos to default i guess.

**Comment by atgeirr** [comment]
> i'd reckon so. it would be interleaved in the general reorganization needed for reference data to move ebos to default i guess.

I agree, it should happen as part of that. I guess first we should merge #1096, right?

**Comment by akva2** [comment]
yes. do note that #1096 is somewhat incomplete. it needs changes in the norne plotting scripts as well as the run-norne script and some small stuff on jenkins setup. i can focus on this tmrw bit busy today.

**Pull request merged**
