### PR TITLE
fix reduction rate for injection groups

### PR DESCRIPTION
**Pull request by totto82**
This is a first attempt to fix the computation of reduction rate. This needs further testing.

### CODE REVIEW

**Comment by totto82** [comment]
jenkins build this please

**Comment by totto82** [comment]
This is an important fix for a proprietary model.  The test failures are noise. I have also verified the changes on the norne prediction family. From the testing point of view this can be merged.

**Review by atgeirr — APPROVED** [review]
Looks good!

**Comment by totto82** [comment]
jenkins build this update_data please

**Comment by bska** [comment]
jenkins build this opm-tests=544 please

**Comment by bska** [comment]
The updated reference solutions have been installed on the CI system.  Merging this now to bring the overall system back to a consistent state.

**Pull request merged**
