### PR TITLE
added: update norne integration test from jenkins trigger

### PR DESCRIPTION
**Pull request by akva2**
The data is used for plotting

### CODE REVIEW

**Comment by atgeirr** [comment]
I am not exactly sure what this PR does? Does it give new auto-update capabilities?

**Comment by akva2** [comment]
yes. it adds the ability to update the 'opm reference'  data used for the plots generated in the norne integration tests if  'run norne / run norne_ebos'  is combined with the 'update_data' trigger.

**Comment by atgeirr** [comment]
Good! I'll merge unless you have further changes coming here?

**Comment by akva2** [comment]
nothing more coming, as long as you do not think it's a bad idea to make this 'too accessible'.

**Comment by atgeirr** [comment]
> as long as you do not think it's a bad idea to make this 'too accessible'.

Not at all, it's not as if it forces us to merge the created PRs...

**Comment by joakim-hove** [comment]
> if 'run norne / run norne_ebos' is combined with the 'update_data' trigger.

Personally I would love if the `update_data` was more of a top-level object in this system, so that I could write:

```
jenkins update_data opm-parser=xxx opm-output=yyyy please
```

and get a opm-data PR with **all** the required updates. 

If we have a PR set which affects both the SPE tests in the normal opm-simulators and the norne tests (I think ??) it is impossible to ensure an "atomic" update where *everything* works. The set: https://github.com/OPM/opm-output/pull/167 + https://github.com/OPM/opm-parser/pull/1043/ is an example.

**Comment by akva2** [comment]
the only problem as far as i see it is that run triggers cannot be triggered upstream, which is on my list of things to remedy. what you suggest would require much more regexp'ery and if's than i would want to have in there (ie more logic needs to be put in the jenkins setup scripts, and i want to keep as little there as possible).

**Comment by joakim-hove** [comment]
> the only problem as far as i see it is that run triggers [.....]

I did not really understand the answer; but anyway my situation (which is quite common!) is that the two PRS:  OPM/opm-output#167 + OPM/opm-parser#1043 will induce changes both in the SPE data and the norne data. Will this work:

1. Create a PR in opm-simulators (white space if necessary).
2. Run `jenkins build this opm-output=167 opm-parser=1043 update_data please`
3. Run `jenkins run norne opm-output=167 opm-parser=1043 update_data please`

Merge the tree source PR's along with the two generated opm-data PR's in one go?

**Comment by akva2** [comment]
you'd just do 3 and it will update regression and integration test data in one go (apart from what i said - you can only use run triggers from opm-simulators currently).

**Comment by joakim-hove** [comment]
> you'd just do 3 and it will update regression and integration test data in one go

OK good!

> you can only use run triggers from opm-simulators currently

Yes - that was why I suggested to create a white-space PR in opm-simulators?

**Comment by akva2** [comment]
see my edit.

**Pull request merged**
