### PR TITLE
Regression testing for PINCH and MULTZ- barrier

### PR DESCRIPTION
**Pull request by tskille**
Both test cases are using PINCH + ALL in item 5. One case have a MULTZ barrier the other not.

Simulation results for both test cases has been verified with simulations using flow build from master this morning (2023/02/21). Simulation results shows excellent agreement with the commercial simulator.

### CODE REVIEW

**Comment by OPMUSER** [comment]
I'm just about to submit a PR with the pinch directory re-factored. I don't think this will affect your PR as the test cases have the same names. Let me create the PR and you can perhaps have a quick check.

**Comment by bska** [comment]
jenkins build this please

**Comment by blattms** [comment]
> Simulation results shows excellent agreement with the commercial simulator.

I always enjoy hearing this phrase. :laughing:

**Comment by blattms** [comment]
This has been hanging for quite a while and as I am working on PINCH I feel more comfortable with more tests. Let's get this in. Just need to find out the update data drill works again. Let's just do a normal jenkins build which should fail and then update data.

**Comment by blattms** [comment]
jenkins build this please

**Comment by blattms** [comment]
Seems like the mentioned refactoring is merged already, anyway.

**Comment by bska** [comment]
jenkins build this update_data please

**Comment by bska** [comment]
jenkins build this opm-tests=936 please

**Pull request merged**
