### PR TITLE
fixed: run proper executable in SPE jenkins script

### PR DESCRIPTION
**Pull request by akva2**

### CODE REVIEW

**Comment by akva2** [comment]
jenkins run spe please

**Comment by akva2** [comment]
failure is unrelated as such, just outdated reference data -> this fixes a real issue. the trigger gets very little usage, i do not know why the grid comparison now fails against eclipse data - and it's hard to know when this regressed.

**Comment by atgeirr** [comment]
> i do not know why the grid comparison now fails against eclipse data - and it's hard to know when this regressed.

I thought this meant that master is broken on Jenkins, but opm-simulators seems to be ok there. So then I do not understand what you mean?

**Comment by akva2** [comment]
the run spe trigger is broken. this is not normally run by the pr or post builder.

**Comment by atgeirr** [comment]
jenkins run spe please

**Comment by blattms** [comment]
Test failed with
```
Grid1 and grid2 have different X, Y and/or Z coordinates .  First difference found for cell i=1 j=1 k=1
```

**Comment by atgeirr** [comment]
jenkins run spe please

**Comment by bska** [comment]
@akva2 : Is this PR still relevant?

**Comment by bska** [comment]
I'm closing this now.  Please open a new PR if you still want to do something along these lines.

**Pull request closed without merging**
