### PR TITLE
add spe5 flow_solvent regression test

### PR DESCRIPTION
**Pull request by akva2**
Same procedure as last time: Merge the upstreams, then run update_data on this to generate jenkins data.

### CODE REVIEW

**Comment by atgeirr** [comment]
jenkins build this please

**Comment by atgeirr** [comment]
Actually it was intentional to take the slightly slower, "do not update data the first time to verify that it fails" step, but I guess that is a bit over-cautious...

**Comment by akva2** [comment]
slipped in-between commit in opm-data and update of shared opm-data copy on jenkins :/

**Comment by akva2** [comment]
jenkins build this update_data please

**Comment by akva2** [comment]
right, in that case i'm sorry. only meant to help.

**Comment by atgeirr** [comment]
No problem!

**Comment by akva2** [comment]
jenkins build this opm-data=225 please

**Comment by atgeirr** [comment]
Thanks! Now we have a solvent test!

**Pull request merged**
