### PR TITLE
Add dedicated class for output of logs

### PR DESCRIPTION
**Pull request by akva2**
More separation of concerns.

### CODE REVIEW

**Comment by akva2** [comment]
jenkins build this please

**Comment by atgeirr** [comment]
A bit tricky to review large code moves, especially for inadvertent changes. I guess the tests is what we rely on to make it work, but I do not think we have a lot of tests on the log output. Any ideas for how to go about checking in a rational way?

**Comment by akva2** [comment]
i guess running old binary and new binary and diffing the output files is the only way to go about it. is what i did while developing it.

**Comment by akva2** [comment]
jenkins build this please

**Comment by atgeirr** [comment]
I have not yet reviewed this throroughly, but I think we should avoid the ebos/ directory as well as `EclXYZ` class names for things that do not take a TypeTag parameter or in another way directly deals with the opm-models interface or approach.

Maybe `LogOutputHelper`?

**Comment by akva2** [comment]
changed to LogOutputHelper.

**Comment by akva2** [comment]
jenkins build this please

**Comment by akva2** [comment]
I have added tests. The reference data was created before the refactoring.

**Comment by akva2** [comment]
i put it in utils, but okay, i can move it to flow..

**Comment by akva2** [comment]
jenkins build this please

**Comment by akva2** [comment]
jenkins build this please

**Comment by atgeirr** [comment]
jenkins build this please

**Review by atgeirr — APPROVED** [review]
Tested and got identical output (up to the usual differences from one run to another).

**Pull request merged**
