### PR TITLE
WIP implement rsrv item 10 WCONINJE

### PR DESCRIPTION
**Pull request by totto82**
See issue https://github.com/OPM/opm-simulators/issues/3850

Depends on https://github.com/OPM/opm-common/pull/2999

Needs more testing and the MSW part is missing.

### CODE REVIEW

**Comment by totto82** [comment]
jenkins build this opm-common=2999 please

**Comment by totto82** [comment]
jenkins build this opm-common=2999 please

**Comment by totto82** [comment]
jenkins build this opm-common=2999 please

**Comment by totto82** [comment]
jenkins build this opm-common=2999 please

**Comment by totto82** [comment]
jenkins build this opm-common=2999 please

**Comment by blattms** [comment]
Volunteer is my second name, today :wink:

**Pull request merged**
