### PR TITLE
change default reg factor for MSW to 100

### PR DESCRIPTION
**Pull request by totto82**
See discussion in  #3859

### CODE REVIEW

**Comment by totto82** [comment]
jenkins build this please

**Comment by totto82** [comment]
benchmark please

**Comment by alfbr** [comment]
We have done quite extensive testing of this pull request, and have so far seen no negative consequences. Moreover, this PR solves real problems at our end. Great it we can get this in.

**Comment by totto82** [comment]
With relaxed tolerenaces and only checking report steps only 

	114 - compareECLFiles_flow+9_4A_WINJ_MAXWRATES_MAXBHP_GCONPROD_1L_MSW (Failed)
	122 - compareECLFiles_flow+MOD4_UDQ_ACTIONX (Failed)

fails locally. Some snap-shots from these cases follows 

image


image

**Comment by totto82** [comment]
> We have done quite extensive testing of this pull request, and have so far seen no negative consequences. Moreover, this PR solves real problems at our end. Great it we can get this in.

I have seen some unexpected results while testing this PR with current master that I would like to double-check before it gets in to the master code.

**Comment by ytelses** [comment]
Benchmark result overview: 




| Test    | Configuration                                     | Relative |
| ------- | ------------------------------------------------- | -------- |
| opm-git | OPM Benchmark: flow_mpi_extra - Threads: 1        | 0.994    |
| opm-git | OPM Benchmark: flow_mpi_extra - Threads: 8        | 1.007    |
| opm-git | OPM Benchmark: flow_mpi_norne - Threads: 1        | 1.011    |
| opm-git | OPM Benchmark: flow_mpi_norne - Threads: 8        | 1.009    |
| opm-git | OPM Benchmark: flow_mpi_norne_4c_msw - Threads: 1 | 1.297    |
| opm-git | OPM Benchmark: flow_mpi_norne_4c_msw - Threads: 8 | 0.986    |
* Speed-up = Total time master / Total time pull request. Above 1.0 is an improvement. *



View result details @ https://www.ytelses.com/opm/?page=result&id=1619

**Comment by totto82** [comment]
jenkins build this please

**Comment by totto82** [comment]
The LET merge introduced some new issues. I will fix asap. 

https://ci.opm-project.org/job/opm-simulators-PR-builder/3675/gcc/new/

**Comment by totto82** [comment]
benchmark please

**Comment by totto82** [comment]
jenkins build this please

**Comment by ytelses** [comment]
Benchmark result overview: 




| Test    | Configuration                                     | Relative |
| ------- | ------------------------------------------------- | -------- |
| opm-git | OPM Benchmark: flow_mpi_extra - Threads: 1        | 0.965    |
| opm-git | OPM Benchmark: flow_mpi_extra - Threads: 8        | 0.988    |
| opm-git | OPM Benchmark: flow_mpi_norne - Threads: 1        | 0.993    |
| opm-git | OPM Benchmark: flow_mpi_norne - Threads: 8        | 0.978    |
| opm-git | OPM Benchmark: flow_mpi_norne_4c_msw - Threads: 1 | 1.193    |
| opm-git | OPM Benchmark: flow_mpi_norne_4c_msw - Threads: 8 | 0.943    |
* Speed-up = Total time master / Total time pull request. Above 1.0 is an improvement. *



View result details @ https://www.ytelses.com/opm/?page=result&id=1625

**Comment by totto82** [comment]
jenkins build this please

**Comment by totto82** [comment]
With relaxed tolerances and only checking report steps, the only case that both fails locally on Jenkins is  `MOD4_UDQ_ACTIONX`

image

**Comment by atgeirr** [comment]
The deviations I see, at around 2019-10 and 2020-6, are they due to timestep changes? The latter period at least seems significant enough to worry about.

**Comment by alfbr** [comment]
Any update on this?

**Comment by totto82** [comment]
jenkins build this please

**Comment by totto82** [comment]
> The deviations I see, at around 2019-10 and 2020-6, are they due to timestep changes? The latter period at least seems significant enough to worry about.

Seems so. Change in newton -> change in time-step. I added results from OPU3 instead, there the difference caused by the timestepping is more clear) 

### PR
Starting time step 0, stepsize 16 days, at day 246/276, date = 01-Apr-2020
    Well OPL5 control mode changed from GRUP->LRAT
    Well OPU5 control mode changed from GRUP->LRAT
The action: ACT01 evaluated to false at 2020/04/17  report:48
The action: ACT01A evaluated to false at 2020/04/17  report:48
 **Newton its=10**, linearizations=11 (0.1sec), linear its= 56 (0.0sec)

**Starting time step 1, stepsize 7 days, at day 262/276, date = 17-Apr-2020**

### Master
Starting time step 0, stepsize 16 days, at day 246/276, date = 01-Apr-2020
    Well OPL5 control mode changed from GRUP->LRAT
    Well OPU5 control mode changed from GRUP->LRAT
The action: ACT01 evaluated to false at 2020/04/17  report:48
The action: ACT01A evaluated to false at 2020/04/17  report:48
 **Newton its= 9,** linearizations=10 (0.1sec), linear its= 56 (0.0sec)

**Starting time step 1, stepsize 14 days, at day 262/276, date = 17-Apr-2020**


image

**Comment by totto82** [comment]
jenkins build this opm-tests=768 please

**Comment by bska** [comment]
New reference solutions have been installed on the CI system.  Merging this now to bring the overall system back to a consistent state.

**Pull request merged**
