### PR TITLE
Using getInputGrid API from Parser

### PR DESCRIPTION
**Pull request by pgdr**
Using new EclipseState.getInputGrid API in Parser

See OPM/opm-parser#769

### CODE REVIEW

**Comment by joakim-hove** [comment]
jenkins build this opm-output=18 opm-parser=769 opm-core=1002 please

**Comment by joakim-hove** [comment]
jenkins build this opm-output=18 opm-parser=769 opm-core=1002 opm-material=141 please

**Comment by joakim-hove** [comment]
The main changes are  in parser and core. 

Parser is really to be merged

**Comment by joakim-hove** [comment]
OK - build test is green here, and the comments in core (the only non-trivial changes) have been addressed. Unless someone screams and shout I will merge this afternoon.

**Comment by atgeirr** [comment]
> Unless someone screams and shout I will merge this afternoon.

Sounds good, just have one lingering worry: the grid we get from getInputGrid() does take ACTNUM into account, right?

**Comment by joakim-hove** [comment]
>  just have one lingering worry: the grid we get from getInputGrid() does take ACTNUM into account, right?

Short story: Yes

Longer story: This fix came about to be able to do property modifications on the `ACTNUM` keyword; however the property modifiers require a grid - so this is a sort of catch 22. The way it is solved currently is that inside the `EclipseState`constructor:

1. A grid is created with the the `EclipseGrid(Deck , nullptr)` constructor - this grid will initially not heed the `ACTNUM` keyword from the deck.
2. The properties, including `ACTNUM` are read and modified in `Eclipse3DProperties` constructor.
3. If `ACTNUM`is present the `EclipseGrid::resetActnum()` method is called with the fully processed `ACTNUM` data.

So - when querying the `EclipseState` for a grid you will get a grid where ACTNUM has been taken correctly into account, but if you use the `EclipseGrid(Deck , const int* actnum)` constructor you must yourself make sure that correct `ACTNUM` information is passed.

**Comment by atgeirr** [comment]
Thanks for the explanation, it makes sense. So the direct construction of an EclipseGrid from user code is now discouraged, and the code in opm-core is changed to avoid that. I have a small question in opm-core, other than that it is ready to be merged.

**Comment by atgeirr** [comment]
As discussed in opm-core, we work around an issue by changing the initialization of CpGrid used by Flow. That change I have made in a branch in my fork named 'simplify-gridinit'. Please include that patch in this PR (it must also be changed to use the new API, I used the old to verify it worked with the existing master branch).

**Comment by pgdr** [comment]
@atgeirr done, and _all tests pass here_™

**Comment by joakim-hove** [comment]
> we work around an issue by changing the initialization of CpGrid used by Flow

OK - but the functions in `opm-grid` taking `Deck` input will remain? On *quite-short-term* I think we should remove those completely - only exposing functions which take `EclipseGrid` as input.

**Comment by atgeirr** [comment]
> OK - but the functions in opm-grid taking Deck input will remain

Yes for now. They can be removed later, I agree. Before we require EclipseGrid input we should make it a little simpler to create the chain of objects though.

Feel free to merge this and the other PRs!

**Pull request merged**
