### PR TITLE
Store the number of connections in separate vector

### PR DESCRIPTION
**Pull request by joakim-hove**
To prepare for refactor

### CODE REVIEW

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by blattms** [comment]
Please don't.
This is a very common and long established pattern in scientific computing to get performant code (due to less cache misses).

**Comment by joakim-hove** [comment]
>Please don't.

OK - this is a multistep plan:

0. Store number of connections and connection offset in separate vectors (i.e. this PR)
1. Store the number of connections and connection offset in a `std::pair<int,int>`
2. Store the well state in a per well datastructure.

Don't know how far this will get; but the transition 0 &rightarrow; 1 should be quite simple in a followup PR. A WIP is here: https://github.com/OPM/opm-simulators/pull/3214

> This is a very common and long established pattern in scientific computing to get performant code (due to less cache misses).

I see that point; hopefully the step 1 described above will reduce the problem. That said I can not see that the code in question is exactly inner loop, and I think the current design has some sign of premature optimization. The WellState class is challenging to work with - and simplifications here are in my opinion valuable.

**Comment by bska** [comment]
I hear the concern about cache misses, but I also think that this particular code could benefit from being organised as a structure of arrays and into an array of structures.  If measurements/profiling highlight this as a bottleneck I think we should investigate hybrid structures that store the actual data in larger arrays and loop over indices into those.  In the end, it all comes down to what we expect to be the primary access patterns.  Do we expect to access most/all quantities associated to a single well before moving on to the next well or do we expect to access a few quantities for all wells at a time?

In the meantime I'm going to merge this to enable the refactoring that @joakim-hove outlines.  My own biggest performance concern is moving to a data model that primarily does lookup in terms of names/strings rather than linear indices.

**Pull request merged**
