### PR TITLE
[bugfix] Fixes deadlocks with agressively distributed wells

### PR DESCRIPTION
**Pull request by blattms**
We should always keep in mind that the number local perforations is no sign/hint for the number of perforations the well would have in a sequential run. Hence returning in a function because `perf_data` is empty might lead to deadlocks and checking whether all perforations are empty needs communication. Both is fixed with this PR and now Norne runs with distributed wells even for @andrthu patch of opm-grid.

Such a small fix that needed lots of debugging time... Amazing.

### CODE REVIEW

**Comment by blattms** [comment]
jenkins build this please.

**Comment by blattms** [comment]
jenkins build this please

**Comment by blattms** [comment]
benchmark please

**Comment by akva2** [comment]
do note the new warning.

**Comment by blattms** [comment]
Mmh, accidentally stashed that one.

**Comment by blattms** [comment]
jenkins build this please

**Comment by ytelses** [comment]
Benchmark result overview: 




| Test    | Configuration                                     | Relative |
| ------- | ------------------------------------------------- | -------- |
| opm-git | OPM Benchmark: flow_mpi_extra - Threads: 1        | 1.008    |
| opm-git | OPM Benchmark: flow_mpi_extra - Threads: 8        | 1.011    |
| opm-git | OPM Benchmark: flow_mpi_norne - Threads: 1        | 1        |
| opm-git | OPM Benchmark: flow_mpi_norne - Threads: 8        | 0.994    |
| opm-git | OPM Benchmark: flow_mpi_norne_4c_msw - Threads: 1 | 0.996    |
| opm-git | OPM Benchmark: flow_mpi_norne_4c_msw - Threads: 8 | 0.993    |
* Speed-up = Total time master / Total time pull request. Above 1.0 is an improvement. *



View result details @ https://www.ytelses.com/opm/?page=result&id=1724

**Comment by blattms** [comment]
Shameless self-merge :grin:

**Pull request merged**
