### PR TITLE
adding some comments about getSegmentRateUpwinding()

### PR DESCRIPTION
**Pull request by GitPaean**
Some comments are added as requested and a variable renaming for better readability. This should not change any result in any sense.

### CODE REVIEW

**Comment by GitPaean** [comment]
jenkins build this please

**Comment by GitPaean** [comment]
Added an assertion to make sure the pressure derivative in getSegmentRateUpwinding() is zero.  Otherwise, the assumption fails.

**Comment by GitPaean** [comment]
jenkins build this please

**Comment by bska** [comment]
Looks okay, just one question: Does "derivative against" mean "derivative with respect to"?

**Comment by GitPaean** [comment]
> Does "derivative against" mean "derivative with respect to"?

Yes. I will change it since it is possibly easier to people to understand.

**Comment by GitPaean** [comment]
jenkins build this please

**Comment by atgeirr** [comment]
Thanks, this makes that code a lot easier to understand (and to avoid making mistakes). Merging.

**Pull request merged**
