### PR TITLE
fixed: build with dune 2.6 without MPI

### PR DESCRIPTION
**Pull request by akva2**

### CODE REVIEW

**Comment by akva2** [comment]
jenkins build this dune2.6 serial please

**Comment by akva2** [comment]
jenkins build this dune2.6 serial please

**Comment by atgeirr** [comment]
Thanks, will merge. I do not think the configuration this is supposed to fix is actually tested by jenkins, correct? (But the jenkins test ensure other configurations were not broken of course.)

**Comment by akva2** [comment]
i actually changed it now. if you include both dune2.6 and serial it will test a serial dune 2.6 as well.

**Pull request merged**
