### PR TITLE
Removed OPERATER and OPERNUM since they are supported.

### PR DESCRIPTION
**Pull request by alfbr**
Updating the missing features list.

### CODE REVIEW

**Comment by alfbr** [comment]
jenkins build this please

**Review by bska — APPROVED** [review]
Cool.  Would you mind removing one of the duplicated [`OPTIONS`](https://github.com/OPM/opm-simulators/blob/09412bea6267cde17d684c41b8ffeef1d8e559ff/opm/simulators/flow/MissingFeatures.cpp#L517-L518) entries just below those too?

**Comment by alfbr** [comment]
Sure, done.

**Comment by bska** [comment]
> Sure, done.

Thanks.  I'll merge once the build check is complete

**Comment by alfbr** [comment]
jenkins build this please

**Comment by bska** [comment]
Build check successful.  Merging now.  Thanks a lot for updating this list.

**Pull request merged**
