### PR TITLE
Allow Hysteresis option 4

### PR DESCRIPTION
**Pull request by totto82**
See https://github.com/OPM/opm-common/pull/4003

### CODE REVIEW

**Comment by totto82** [comment]
Non-wetting hysteresis needs some more testing before allowed in the simulator.

**Comment by totto82** [comment]
jenkins build this please

**Comment by totto82** [comment]
Now the relevant hysteresis option 4 PRs are merged. It is time to merge this.

**Comment by atgeirr** [comment]
> Now the relevant hysteresis option 4 PRs are merged. It is time to merge this.

Great, merging!

**Pull request merged**
