### PR TITLE
removing the including of FlowProblem in BlackoilWellModel

### PR DESCRIPTION
**Pull request by GitPaean**

### CODE REVIEW

**Comment by GitPaean** [comment]
jenkins build this please

**Comment by GitPaean** [comment]
jenkins build this please

**Comment by GitPaean** [comment]
jenkins build this please

**Review by blattms — APPROVED** [review]
Looks like a good and innocent cleanup to me,

**Comment by akva2** [comment]
sorry, was on vacation. this is not entirely correct, we do not need flowproblem but we need some of the properties to be defined for happy clangd. will submit a follow-up PR.

**Comment by GitPaean** [comment]
> sorry, was on vacation. this is not entirely correct, we do not need flowproblem but we need some of the properties to be defined for happy clangd. will submit a follow-up PR.

Can you elaborate so that we can discuss a solution?

**Comment by akva2** [comment]
we need stuff which are , indirectly defined in FlowProblem.hpp, e.g. ```Properties::EquilGrid```,  ```Properties::GlobalEqVector``` is undefined. It's correct we don't need FlowProblem, but we need stuff that was pulled in through that header. Let me just create the PR.

**Pull request merged**
