### PR TITLE
Serialize density-temparture class DenT

### PR DESCRIPTION
**Pull request by joakim-hove**
Downstream of: 
https://github.com/OPM/opm-common/pull/1507
https://github.com/OPM/opm-material/pull/404

### CODE REVIEW

**Comment by bska** [comment]
jenkins build this opm-common=1507 opm-material=404 please

**Comment by joakim-hove** [comment]
jenkins build this opm-common=1507 opm-material=404 please

**Comment by joakim-hove** [comment]
This is green from opm-common.

**Comment by joakim-hove** [comment]
jenkins build this opm-common=1507 opm-material=404 please

**Pull request merged**
