### PR TITLE
trying to fix a problematic situation when updateWellState

### PR DESCRIPTION
**Pull request by GitPaean**
for example, distr = 0 1 0, for rate control, F = 1 0 0, we will get a
zero F_target, then it is wrong to do the division with F_target.

It is okay when target = 0. When target != 0, the result is already very
wrong. Non-linear iteration can send us anywhere, not sure the best
solution for this kind of strange situation.

It was reported by @odd, while I am not sure it is something should go in. 

For the current StandardWell we are trying to have the control target in implicitly through kind of manual way, it is possible that having a control equation explicitly will solve this kind of situation better.

### CODE REVIEW

**Comment by GitPaean** [comment]
jenkins build this please

**Comment by GitPaean** [comment]
Basically, for the situation `distr = 0 1 0, for rate control, F = 1 0 0`, it means the well is under oil rate control, but in the wellbore only filled with water.  When the rate target is zero, water is crossflowing through the well-bore.  If the rate target is non-zero, it means the well has a non-zero oil rate target. Either the well will change to BHP control without producing any oil or the simulation will fail, since there is no way the well can produce the oil target.

**Comment by GitPaean** [comment]
I added the warning for the situation when `F_target==0.`. However, we saw these warning in the places we did not have problem in obtaining  the solution. Not sure whey we were not bitten earlier without this PR. Anyway, please review the code carefully in case there are some logical mistakes involved.

**Comment by GitPaean** [comment]
jenkins build this please

**Comment by GitPaean** [comment]
jenkins  run norne please

**Comment by atgeirr** [comment]
Looks like the jenkins command did not take, I'll repeat it.

**Comment by atgeirr** [comment]
jenkins run norne please

**Comment by atgeirr** [comment]
Thanks for the patch, merging!

**Pull request merged**
