### PR TITLE
only when both oil and gas exist, we handle drsdt and drvdt

### PR DESCRIPTION
**Pull request by GitPaean**

### CODE REVIEW

**Comment by GitPaean** [comment]
jenkins build this please

**Comment by GitPaean** [comment]
jenkins build this please

**Comment by GitPaean** [comment]
With this approach, we ignore the DRSDT, DRVDT, when not both oil and gas phase exist from the simulator side. 

Maybe we should check `DISGAS` and `VAPOIL`, but so far we have not used that way.

**Review by totto82 — APPROVED** [review]

**Comment by bska** [comment]
Approved and build check green.  I'll merge into master.

**Pull request merged**
