### PR TITLE
only log changes of group controls on rank 0

### PR DESCRIPTION
**Pull request by totto82**
No need to spam the log with multiple messages with the same content.

### CODE REVIEW

**Comment by totto82** [comment]
jenkins build this please

**Comment by bska** [comment]
Do control changes get communicated back to the I/O rank?  In other words, do we guarantee that if process 123 changes the control model of PROD-X from ORAT to GRUP then process 0 knows about that change?  If not, I think this PR is actually wrong.

**Comment by totto82** [comment]
> Do control changes get communicated back to the I/O rank?

No, but all groups lives on all ranks and the group rates get communicated. I. E they should be violated at the same time.

**Comment by bska** [comment]
> > Do control changes get communicated back to the I/O rank?
> 
> No, but all groups lives on all ranks and the group rates get communicated. I. E they should be violated at the same time.

Ah, yes&mdash;you're right.  I missed the key phrase "group control changes" and thought this was about wells too.  In that case we're safe and I'll merge this into master.  Sorry about the confusion.

**Pull request merged**
