### PR TITLE
add gas condensate case to regression test

### PR DESCRIPTION
**Pull request by goncalvesmachadoc**
Case https://github.com/OPM/opm-tests/pull/988

### CODE REVIEW

**Comment by bska** [comment]
jenkins build this update_data please

**Comment by bska** [comment]
jenkins build this opm-tests=995 please

**Comment by bska** [comment]
Hi @goncalvesmachadoc.  I don't think we can activate the test case in its current form.  It takes too long&mdash;nearly 11 minutes&mdash;to run on our CI system.  Is there a way to reduce the runtime down to something more manageable?

---

For reference, here's the timing output from the [earlier test run](https://github.com/OPM/opm-simulators/pull/4702#issuecomment-1594766374)
```
238/271 Test  #66: compareECLFiles_flow+GASCONDENSATE_VAPWAT_PRECSALT ................   Passed  642.40 sec
```

**Comment by bska** [comment]
jenkins build this please

**Comment by bska** [comment]
Ignore the "Failed" status&ndash;that's expected since [we haven't installed the reference solutions](https://ci.opm-project.org/job/opm-simulators-PR-builder/5098/testReport/junit/(root)/mpi/compareECLFiles_flow_GASCONDENSATE_VAPWAT_PRECSALT_REGRESSION/).  The fact that this runs in a few seconds is very attractive.  If you think the numerical solution is sufficiently good, @goncalvesmachadoc, then we should activate this regression test.

---

> ```
> 55/287 Test  #71: compareECLFiles_flow+GASCONDENSATE_VAPWAT_PRECSALT_REGRESSION .....***Failed    5.43 sec
> ```

**Comment by goncalvesmachadoc** [comment]
On my side, this is ready to get in the regression testing.

**Comment by bska** [comment]
jenkins build this update_data please

**Comment by bska** [comment]
jenkins build this opm-tests=1007 please

**Pull request merged**
