### PR TITLE
Put WellState in separate compile unit

### PR DESCRIPTION
**Pull request by akva2**
Smaller rebuilds, more fun.

### CODE REVIEW

**Comment by akva2** [comment]
jenkins build this please

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by akva2** [comment]
missing a.config.h include, will add later.

**Comment by joakim-hove** [comment]
> missing a.config.h include, will add later.

OK - I was keen on a little rebasing ... ;-)

**Comment by akva2** [comment]
jenkins build this please

**Comment by joakim-hove** [comment]
Yeah!

**Pull request merged**
