### PR TITLE
use rates for potentials for pressure controlled controled wells

### PR DESCRIPTION
**Pull request by totto82**

### CODE REVIEW

**Comment by totto82** [comment]
I have checked the test failures. Most of them only have small changes in the potentials. For some group oriented cases changes in potentials may cause changes in the results. Some of the cases like 9_2B and MOD_GRP shows visible changes in the summary plots in ResInsight but mostly due to slight changes in the timestepping I also tested this on some of the norne based prediction cases. With this PR some strange oscillation in the potentials for wells with small rates disappears.

**Review by atgeirr — APPROVED** [review]

**Comment by totto82** [comment]
@bska This also needs an update of the reference solution. Do you want OPM/opm-common#2485 in first?

**Comment by bska** [comment]
> This also needs an update of the reference solution. Do you want [OPM/opm-common#2485](https://github.com/OPM/opm-common/pull/2485) in first?

PR OPM/opm-common#2485 isn't ready for merging yet as there is still ongoing testing.  On the other hand, PR OPM/opm-common#2475 is in the process of updating the reference solutions to account for new output vectors related to well lists so please don't start updating reference solutions until that one is fully merged.

**Comment by totto82** [comment]
OPM/opm-common#2475 is in. I will start the update process.

**Comment by totto82** [comment]
jenkins build this update_data please

**Comment by totto82** [comment]
Last time I run Jenkins there were no issue with the parallel run. Any idea why SPE9_CP_GROUP suddenly show up. 

[here](https://ci.opm-project.org/job/opm-simulators-PR-builder/2395/testReport/junit/(root)/mpi/compareParallelSim_flow_SPE9_CP_GROUP/)

**Comment by totto82** [comment]
jenkins build this opm-tests=541 please

**Pull request merged**
