### PR TITLE
[WIP] Introduce more proper error handling to asynchronous output writing.

### PR DESCRIPTION
**Pull request by blattms**
The dispatch method now checks whether there was any error, previously.
In this case it clears the queue. In any case a tuple with the error
indicator and the messages is returned which is used outside for error
handling. For error handling for the last output write step will be done
in the ThreadHandleQueue destructor that is run by the main thread.

The reason for the [WIP] is that terminating the thread like it is done now is really giving me headaches as I cannot see how  to catch error in the last writing thread and not throw twice. This would need to be done in the destructor, but that means that `err_` might be one even if it stems from a previous unsucessful write that we already detected and have thrown an exception for already. Here I assume that the destructor is called during stack unwinding after an exception was thrown. Maybe joining the thread in FlowMain would prevent the second throw?

### CODE REVIEW

**Comment by atgeirr** [comment]
jenkins build this please

**Comment by dr-robertk** [comment]
I think the error handling should be moved to writeTimeStepSerial, to avoid code duplication. This way 
the error handling stays outside of ThreadHandle which I think is the better option.

**Comment by blattms** [comment]
I am not really sure what you mean by error handling and therefore what you want to have in writeTimeStepSerial.

Please be aware that writeTimeStepSerial is only run on one rank in a thread separate from main. If we throw there a parallel program will surely deadlock.

**Comment by blattms** [comment]
stale and not needed any more.

**Pull request closed without merging**
