### PR TITLE
removing more legacy Multisegment Wells related.

### PR DESCRIPTION
**Pull request by GitPaean**
I think this is the leftover from #1330.

### CODE REVIEW

**Comment by akva2** [comment]
yes, probably.i left it as the code was tested and i didn't quite know what was in use and not

**Comment by GitPaean** [comment]
jenkins build this opm-data=278 please

**Comment by GitPaean** [comment]
It is good to remove them though, otherwise the filenames related to well models are a little messy.

**Comment by akva2** [comment]
sure. just gave the reason i left the code.

**Comment by atgeirr** [comment]
jenkins build this please

**Comment by GitPaean** [comment]
> jenkins build this please

It will fail on Jenkins without OPM/opm-data#278.

**Comment by atgeirr** [comment]
jenkins build this please

**Comment by atgeirr** [comment]
Thanks, merging!

**Pull request merged**
