### PR TITLE
fixing the scaling of segment rates

### PR DESCRIPTION
**Pull request by GitPaean**
when initial segment rate is zero.

This PR closes https://github.com/OPM/opm-simulators/issues/3829 . 

With the original code, the oil and water rate will be zeros after scaled because the `perforation_rates` entering `calculateSegmentRates` only have the gas rate and zero water and oil rates. 

With this PR, it will make sure the top segment rates will be same (approximately) with the well rates after scaled from zero rates.

### CODE REVIEW

**Comment by GitPaean** [comment]
jenkins build this please

**Comment by GitPaean** [comment]
jenkins build this please

**Comment by GitPaean** [comment]
benchmark please

**Comment by ytelses** [comment]
Benchmark result overview: 




| Test    | Configuration                                     | Relative |
| ------- | ------------------------------------------------- | -------- |
| opm-git | OPM Benchmark: flow_mpi_extra - Threads: 1        | 1.003    |
| opm-git | OPM Benchmark: flow_mpi_extra - Threads: 8        | 1.004    |
| opm-git | OPM Benchmark: flow_mpi_norne - Threads: 1        | 1.011    |
| opm-git | OPM Benchmark: flow_mpi_norne - Threads: 8        | 0.999    |
| opm-git | OPM Benchmark: flow_mpi_norne_4c_msw - Threads: 1 | 0.718    |
| opm-git | OPM Benchmark: flow_mpi_norne_4c_msw - Threads: 8 | 1.123    |
* Speed-up = Total time master / Total time pull request. Above 1.0 is an improvement. *



View result details @ https://www.ytelses.com/opm/?page=result&id=1556

**Comment by totto82** [comment]
Thanks. Good catch! This is clearly fixing a bug in the code and should be merged. Did you check the test failures for unexpected fails? If so, please update and merge. I would not worry to much about the performance impact on `norne_4c_msw`

.

**Comment by GitPaean** [comment]
Without this PR, the top segment rates might not be the same with the well rates. And the primary variables are built based on segment rates, it means the primary variables will not reflect the well rates. Something like the following,

master branch
```
11077  well F well rates 
11078   -0.0967982  -0.00579416  -0.831324
11079  segment rates 
11080  seg 0  0  0  -0.831324
11081  seg 1  0  0  -0.831324
11082  seg 2  0  0  -0.123552
```

Wit this PR
```
11077  well F well rates 
11078   -0.0967982  -0.00579416  -0.831324
11079  segment rates 
11080  seg 0  -0.0967982  -0.00579416  -0.831324
11081  seg 1  -0.0967982  -0.00579416  -0.831324
11082  seg 2  -0.0143863  -0.000861136  -0.123552
```

The jenkins results are checked. I am updating the reference result now.

**Comment by GitPaean** [comment]
jenkins build this update_data please

**Comment by GitPaean** [comment]
https://github.com/OPM/opm-tests/pull/737 is merged. This PR is going in now.

**Pull request merged**
