### PR TITLE
Remove bda naming from project

### PR DESCRIPTION
**Pull request by razvnane**
The word is replaced by gpu, e.g, gpuBridge will be used instead of bdaBridge , bda/ subfolder is replaced by gpubridge/

### CODE REVIEW

**Comment by akva2** [comment]
jenkins build this serial rocm hipify please

**Comment by razvnane** [comment]
please run jenkins again

**Comment by akva2** [comment]
jenkins build this serial rocm hipify please

**Comment by akva2** [comment]
this looks fine, but due to the already existing confusion with two different gpu codes can you please rename ISTLSolverGpu to ISTLSolverGpuBridge to atleast try to make it a little more apparent which classes are used with which codepaths? the GpuISTL solvers can be used with the regular ISTLSolver class...

**Comment by razvnane** [comment]
> this looks fine, but due to the already existing confusion with two different gpu codes can you please rename ISTLSolverGpu to ISTLSolverGpuBridge to atleast try to make it a little more apparent which classes are used with which codepaths? the GpuISTL solvers can be used with the regular ISTLSolver class...

Done. Thanks for the suggestion.

**Comment by akva2** [comment]
jenkins build this serial rocm hipify please

**Comment by akva2** [comment]
Thankd, merging.

**Pull request merged**
