### PR TITLE
  Added WTEST models

### PR DESCRIPTION
**Pull request by jilocode**
Added wtest models to test regime

### CODE REVIEW

**Comment by jilocode** [comment]
Added WTEST files to flow test regime

**Comment by alfbr** [comment]
jenkins build this update_data please

**Comment by bska** [comment]
> update_data

This PR is sadly not ready for merging.  There are syntax errors in the `compareECLFiles.cmake` file&mdash;the `add_test_compareECLFiles` macro calls aren't properly closed with a `)` character&mdash;and no records in the [`update_reference_data.sh`](https://github.com/OPM/opm-simulators/blob/9ef547edca4c79b8e401a3a20e382a1dea104e3b/tests/update_reference_data.sh#L53-L60) script to account for the new test cases.

**Comment by bska** [comment]
Thank you for the updates, this looks a lot better than the initial version.

Before we merge this we'll still need to add records for the new regression tests in the shell script that updates the reference solutions in case of new development (i.e., in [`tests/update_reference_data.sh`](https://github.com/OPM/opm-simulators/blob/eb6265b1486f771cb824c05b503f3cfe3aab0053/tests/update_reference_data.sh#L52-L60)), but that should be fairly easy to do.  Please reach out to me if you need any assistance in that task.

**Comment by bska** [comment]
Thanks for the updates.  I'll try a test build now.

**Comment by bska** [comment]
jenkins build this please

**Comment by bska** [comment]
All regression tests fail in the expected way&mdash;due to missing reference solutions.  I'll try to update the reference data now, with the possible caveat that the issue which prevented generating new reference solutions in #3788 (OPM/opm-tests#715) might still be present.

**Comment by bska** [comment]
jenkins build this update_data please

**Comment by bska** [comment]
jenkins build this opm-tests=716 please

**Comment by bska** [comment]
jenkins build this update_data please

**Comment by bska** [comment]
jenkins build this opm-tests=722 please

**Comment by bska** [comment]
Thank you for the updates and the new regression test cases.  The new reference solutions have been installed on the CI system and I'll merge this into master now.

**Pull request merged**
