### PR TITLE
fixing some typos in MultisegmentWell_impl.hpp

### PR DESCRIPTION
**Pull request by GitPaean**
there should be no change in the results at all.

### CODE REVIEW

**Comment by GitPaean** [comment]
jenkins build this opm-tests=847 update_data please

**Comment by GitPaean** [comment]
jenkins build this please

**Comment by GitPaean** [comment]
This PR was created to create reference result for PR https://github.com/OPM/opm-tests/pull/847 . Itself is also mergeable.

**Review by bska — APPROVED** [review]
Thanks.  I'll merge this into the master branch.

**Pull request merged**
