### PR TITLE
WECON RATE limit should not be applied if the well is under zero group rate target

### PR DESCRIPTION
**Pull request by GitPaean**

### CODE REVIEW

**Comment by GitPaean** [comment]
jenkins build this please

**Comment by GitPaean** [comment]
jenkins build this please

**Comment by GitPaean** [comment]
jenkins build this please

**Comment by GitPaean** [comment]
The PR is ready for review, while let us wait for the reporting back from the testing of the field case, which might potentially brings in more adjustment.

**Comment by tskille** [comment]
This PR has now been tested on a full field model in Equinor and results are good. Looking forward to see this going in to master repo.

**Comment by GitPaean** [comment]
> This PR has now been tested on a full field model in Equinor and results are good. Looking forward to see this going in to master repo.

Thanks for the testing. I am marking the PR as ready for review now.

**Comment by GitPaean** [comment]
jenkins build this please

**Comment by steink** [comment]
I think this looks fine. I was a little bit confused about the naming of the new function `wellUnderZeroGroupRateTarget` which calls `wellUnderZeroRateTargetGroup` because of the name similarities. Maybe not a big thing, but I would suggest giving it a less similar name.

**Comment by GitPaean** [comment]
> I think this looks fine. I was a little bit confused about the naming of the new function `wellUnderZeroGroupRateTarget` which calls `wellUnderZeroRateTargetGroup` because of the name similarities. Maybe not a big thing, but I would suggest giving it a less similar name.

Thanks. Changing `wellUnderZeroGroupRateTarget` to `zeroRateTargetGroup` in hope of less naming confusion.  The later basically only check the group rate target without checking whether the well is actually under the group control.

**Comment by GitPaean** [comment]
jenkins build this please

**Comment by GitPaean** [comment]
Thanks for @steink reviewing the PR. The PR has been updated accordingly.  Jenkins approves. I am getting the PR in now.

**Pull request merged**
