### PR TITLE
[cleanup] Remove the commented out code from WellGroupHelpers.hpp

### PR DESCRIPTION
**Pull request by blattms**
The real code is in the *.cpp and trying to maintain the commented out code is just not working. Hence it is only distraction for the developers.

Not sure whether this will produce conflicts with #3112

### CODE REVIEW

**Comment by blattms** [comment]
jenkins build this please

**Comment by totto82** [comment]
@blattms I suggest to close this PR and include it in #3112 to avoid possible conflicts.

**Comment by blattms** [comment]
Sure, be my guest.

**Comment by totto82** [comment]
This is now included in #3112. Thanks @blattms for noticing.

**Pull request closed without merging**
