### PR TITLE
war

### PR DESCRIPTION
**Pull request by atgeirr**

### CODE REVIEW

**Comment by akva2** [comment]
this is sparta!

**Comment by bska** [comment]
"What is it good for?"

**Comment by blattms** [comment]
I have quite a few branches lying around on my disk from working on
the DUNE release. Just waiting to push until the release is out or I
find time to cleanup.

There is a great chance that the work will overlap...

**Comment by atgeirr** [comment]
I had open the diff and acidentally created a PR when I thought I was somewhere else...

**Pull request closed without merging**
