### PR TITLE
Cmakify sibling search

### PR DESCRIPTION
**Pull request by blattms**
Same procedure as in OPM/opm-material#247

### CODE REVIEW

**Comment by akva2** [comment]
jenkins build this opm-grid=282 opm-material=246 opm-core=1175 ewoms=224 please

**Comment by akva2** [comment]
@blattms ignore error but please look at opm-output output in the jenkins build log.

**Comment by akva2** [comment]
i have tested the sibling based builds locally. all announced functionality is sound, great work. once we get rid of the scary scary with installation builds, i'm ready to merge.

**Comment by blattms** [comment]
Sorry, I seem to be a bit blind. Where and what is the error in jenkins for opm-output? I only see problems finding the correct PR for opm-material:
```
Building upstream opm-material=pull/246/merge configuration=mpi
~/workspace/opm-simulators-PR-builder ~/workspace/opm-simulators-PR-builder
Initialized empty Git repository in /var/lib/jenkins/workspace/opm-simulators-PR-builder/deps/opm-material/.git/
fatal: Couldn't find remote ref pull/246/merge
error: pathspec 'branch_to_build' did not match any file(s) known to git.
```

**Comment by akva2** [comment]
it is built just before opm-material, which is why i gave a faulty pr to halt the process there to try to highlight it
```
CMake Warning at CMakeLists.txt:47 (message):
  Value passed to variable opm-common_DIR is not a directory
```

**Comment by blattms** [comment]
Thanks. Will look into it.

**Comment by blattms** [comment]
In that case opm-commoon_DIR was empty and an empty path is not a directory. Ergo the bogus warning. I fixed this in all modules. Thanks for noticing.

**Comment by akva2** [comment]
jenkins build this opm-grid=282 opm-material=247 opm-core=1175 ewoms=224 please

**Comment by akva2** [comment]
merge fest 2017 coming up.

**Pull request merged**
