### PR TITLE
This is the faster ilu pull request but with the traversal of the columns of upper in the original ordering

### PR DESCRIPTION
**Pull request by blattms**
DO NOT MERGE THIS.

I just want to see whether the regressions of #1186 vanish with these changes.

### CODE REVIEW

**Comment by blattms** [comment]
jenkins run norne please

**Comment by blattms** [comment]
Jenkins run will have to wait until ewoms is fixed.

**Comment by blattms** [comment]
With this PR I get the exact same iteration numbers as with master.
It is a bit slower than #1186 though as needs 1117.22 seconds instead of 1082.18 seconds as for #1186 (current master takes 1188.5 seconds).

Looking forward to run the regression tests.

**Comment by blattms** [comment]
jenkins run norne please

**Comment by dr-robertk** [comment]
Good. I thought about this and when I looked at the code I thought it was implemented this way but obviously not. Thanks. I hope that fixes the convergence issues. Otherwise I would be surprised.

**Comment by blattms** [comment]
Well jenkins is happy with this one!

The to the other PR is that when solving Ux=y for x we do the sum in x_i = D_{ii}^{-1}(y-sum_{j=i+1}^N U_{ij} y_j) from j=N to j=i+1 and not the other way around. This is the same order is in dune-istl.
Any differences are due to this change and the use of floating point numbers.

I will leave the decision which one to merger to somebody else. Both versions are fine by me.

**Comment by akva2** [comment]
if the test failures have been explained and the other code is faster, my vote is on the faster code. but it was a parallel test that failed right? that's a bit more icky to handle as in it's not just updating references.

**Comment by andlaus** [comment]
I concur with @akva2: semantically both changes should be identical, the fact that one approach is sometimes faster than the other due to floating point arithmetics is random noise which IMO should be ignored.

> but it was a parallel test that failed right?

I don't know about test failures with MPI, but I run #1186 on four processes with norne and the performance did not seem to improve compared to the current master (sequentially it did, as expected). I suppose the explanation is that 4 parallel processes probably keep the memory channels busy even if the access pattern is sub-optimal. Anyway, I'm strongly in favour of merging #1186.

**Comment by akva2** [comment]
have investigated the parallel test a bit but now it's time to call it a night. i still find the fact that the reorder cause such a huge difference a bit suspicious. if this was purely round-off i would not expect the difference between the two implementation to be so pointwise. e.g. comparing for the first process, the one point has a deviation of 1e-4, while the mean of the others are 1e-8. by no means dismissing it yet but did you look at this aspect @blattms ?

**Comment by atgeirr** [comment]
Can't we merge this first and have a better ILU, and leave the difference to #1186 to be decided later? Seems we can have our cake and eat it too, that way.

**Comment by dr-robertk** [comment]
From my point of view this can be merged. We have discussed enough and also tested enough. Both PRs are fine. This one is closer to the current implementation of ILU and that might be an argument for merging this one. If nobody objects I'll push green around noon tomorrow (later today)

**Comment by atgeirr** [comment]
Re-running jenkins after recent merging of other performance-related stuff just to be sure. If successful I (still) think we should merge.

**Comment by atgeirr** [comment]
jenkins run norne please

**Comment by blattms** [comment]
Concerning performance: These PRs definitely decrease the time per iteration but the setup time gets higher. Luckily we need to do enough iterations to still see a performance increase. If we take the linear solve time and divide it by the number of linear iterations we get:

This PR: 448.247/26526 = .0169
#1186 : 439.29/25597  =  .0172
Master: 521.053/26526 = .020

**Comment by blattms** [comment]
The number are from yesterday. The merge of #1211 which might change them.

**Comment by atgeirr** [comment]
All green, @blattms do you agree we should merge this?

**Comment by blattms** [comment]
Sure. Go ahead.

**Pull request merged**
