### PR TITLE
Adjust packaging for pybind bump

### PR DESCRIPTION
**Pull request by akva2**
not supported by newer pybind11 and long out of support in any case

Companion to https://github.com/OPM/opm-common/pull/4247

### CODE REVIEW

**Comment by alfbr** [comment]
I am afraid we are still using 3.6 on Red Hat 7. I do believe we will phase out Red Hat 7 very soon, and then be on 3.8. Any chance we can postpone this a month or so?

**Comment by akva2** [comment]
I asked @vkip and he said you were on 3.8.

It's really unfortunate if we do not get this into the release and that will mean broken python bindings for everyone on python > 3.8 for at least another 6 months.

**Comment by alfbr** [comment]
He is ahead of the curve, on Red Hat 7 we are still on 3.6.

**Comment by akva2** [comment]
i have increased the complexity of this to keep you afloat. while in theory some trouble maker may have built numpy2 for python < 3.8 i think the chance of finding this animal in the wild is small.

**Pull request merged**
