### PR TITLE
Fix shut-in logic for wells with shut-instructions (revised)

### PR DESCRIPTION
**Pull request by bska**
This is a rebased version of #4902 which additionally limits the timestep size of certain sensitive regression tests for improved determinism and stability.

Supersedes and closes #4902.

### CODE REVIEW

**Comment by bska** [comment]
jenkins build this please

**Review by atgeirr — APPROVED** [review]

**Comment by atgeirr** [comment]
jenkins build this update_data please

**Comment by bska** [comment]
jenkins build this opm-tests=1094 please

**Comment by bska** [comment]
jenkins build this update_data please

**Comment by bska** [comment]
jenkins build this opm-tests=1095 please

**Comment by bska** [comment]
The new reference solutions have been installed on the CI system.  I'm merging this now per prior approval to activate the new shut-in logic.

**Pull request merged**
