### PR TITLE
Make CPR preconditioner honor linear_solver_ignoreconvergencefailure

### PR DESCRIPTION
**Pull request by blattms**
This is a follow up to PR #700 which only covered ILU as a preconditioner

### CODE REVIEW

**Comment by atgeirr** [comment]
Fine apart from nitpicks (inconsistent indentation or perhaps tabs, member naming not consistent with existing members). Will merge when fixed and tested.

**Comment by blattms** [comment]
Seems like I even use an uninitialized value. One should not use copy & paste.

**Comment by atgeirr** [comment]
> Seems like I even use an uninitialized value.

You do, I should have noticed! One more reason I like the "default init in the class definition" C++11 thing (it would have made it stand out).

**Comment by atgeirr** [comment]
Uninitialized value still present. Fix?

**Comment by blattms** [comment]
On Tue, Jun 07, 2016 at 02:39:55AM -0700, Atgeirr Flø Rasmussen wrote:
> Uninitialized value still present. Fix?
>

I will fix it, but it has low priority currently. Might take some
time.

**Comment by atgeirr** [comment]
We're not in a hurry, no problem.

**Comment by blattms** [comment]
Everything should be fixed now.

**Pull request merged**
