### PR TITLE
Fix polymer rates bug

### PR DESCRIPTION
**Pull request by qilicun**
The previous implementation will set the polymer rates to the wrong wells. This PR fix the bug.

### CODE REVIEW

**Comment by qilicun** [comment]
This is a real bug, I think the reason why polymer simulators never suffer this trouble dues to **Lucky**, I'm willing to see this goes in ASAP.

**Comment by atgeirr** [comment]
I agree this is a real bug, will merge. Do you have a case exposing it?

**Comment by qilicun** [comment]
>Do you have a case exposing it?

Yes, any case if you have injectors more than one. Like

```
WELSPECS
    'INJE01' 'I'    26  44 1* 'WATER'     /   
    'INJE02' 'I'    12  85 1* 'WATER'    / 

WPOLYMER
'INJE02' 1.0 0.0 /
```

Whatever you set in the ``WPOLYMER`` keyword, the polymer injectio rate will be set to 0, because of  the bug, since it will always use the value from ``INJE01``.

**Comment by atgeirr** [comment]
Perhaps you could modify one of the existing tests to be like this, to expose the bug? If you have time of course.

**Comment by qilicun** [comment]
>Perhaps you could modify one of the existing tests to be like this, to expose the bug? If you have time of course.

Will try to make a test.

**Pull request merged**
