### PR TITLE
make scalar version of computePerfRate for MSW

### PR DESCRIPTION
**Pull request by totto82**
Avoid unnecessary operations on evals. Follows the same pattern as for stw.

### CODE REVIEW

**Comment by totto82** [comment]
jenkins build this please

**Comment by totto82** [comment]
What is `SACT`?

**Comment by akva2** [comment]
bad timing, try again, ref https://github.com/OPM/opm-common/pull/2669

**Comment by totto82** [comment]
jenkins build this please

**Comment by totto82** [comment]
@akva2 Any comments?

**Comment by akva2** [comment]
it looks fine as far as i can see. there seems to be some opportunity for refactoring and sharing code with stdw but that can be done later.

**Pull request merged**
