### PR TITLE
changed: simplify buildsystem a little

### PR DESCRIPTION
**Pull request by akva2**
- use loops instead of copy-paste
- use object libraries to avoid some unnecessary archives
- tab scrubbing

### CODE REVIEW

**Comment by akva2** [comment]
jenkins build this please

**Comment by atgeirr** [comment]
Looks good to me, though I am an amateur at cmake.

**Comment by akva2** [comment]
ping @blattms

**Comment by blattms** [comment]
Sorry, my main compute system is currently broken and thus this took longer.

Looks good and tested locally. Merging.

**Comment by blattms** [comment]
The only thing that I do not get, but that was already there before this PR. Why are we using opm_add_test to build something that we are actually installing? Seems like this could be break
Indeed installation fails withcmake  -DBUILD_EBOS_EXTENSION=ON -DBUILD_TESTING:BOOL=OFF

**Pull request merged**
