### PR TITLE
Import some files from opm core (with history)

### PR DESCRIPTION
**Pull request by akva2**
This was requested by @atgeirr 

Do note that the test is disabled, like it was in opm-core.

### CODE REVIEW

**Comment by andlaus** [comment]
wow. that are a lot of (mostly empty?) merge commits. I think they will vanish if you rebase the PR on master.

**Comment by akva2** [comment]
Yes but then all rebases go and meta history is lost. If that is preferred...

**Comment by akva2** [comment]
Ehrr all merge commits.

**Comment by akva2** [comment]
And a brief explanation why all those unrelated merge commits show up; it is caused by violations of the first rule of git: you pull from a downstream and you rebase on an upstream.

This offense has been done in pull requests which touch the imported files. This means those merge commits have ancestry as if they were part of the offending pull. So the tools will include them. Fixing this up properly would be hours of work with lots of manual commit grafting. I am not willing to put in that time.

**Comment by andlaus** [comment]
yeah, I also think that manually going through all of them is too much hassle. on the other hand: can empty merge commits be removed of automatically? (that would be about 90% of them, I guess.)

**Comment by akva2** [comment]
internet to the rescue. found a way to filter parent commits. and learned something new in the process. branch is redone.

**Comment by andlaus** [comment]
cool. now it looks much better :)

**Comment by atgeirr** [comment]
Thanks a lot, will merge!

**Pull request merged**
