### PR TITLE
Output Well Flow Sheets for All Wells

### PR DESCRIPTION
**Pull request by bska**
There is no need to restrict PRT file flow reports to those wells which are active on the current rank since the `SummaryState` object holds information for all wells active at the current report step.

---

As an example of the impact of this change, here's the difference between abridged cumulative flow reports from the last report step of [`NORNE_ATW2013`](https://github.com/OPM/opm-tests/blob/4d1ef6e376f16f8a792056e13873e529f799c2ec/norne/NORNE_ATW2013.DATA) when run as
```sh
OMP_NUM_THREADS=1 mpirun -np 6  ${flow} --ecl-deck-file-name=${cse}
```
with different output directories (`np/6/dev` for this PR and `np/6/master` for the current master sources).  Flow values omitted here to avoid cluttering the display.

```diff
--- np/6/master/cumulative.rpt.last	2024-01-04 14:00:32.737251300 +0100
+++ np/6/dev/cumulative.rpt.last	2024-01-04 13:59:18.869309148 +0100
@@ -11,15 +11,40 @@
 :   FIELD:           :        :    :
 [...]
 :D2-DUMMY:           :        :    :
+:    C-4H:   11,   35:     INJ:WRAT:
+:    B-2H:   15,   31:    PROD:RESV:
+:    D-1H:   22,   22:    PROD:ORAT:
+:    D-2H:   14,   28:    PROD:RESV:
+:    B-4H:   10,   32:    PROD:ORAT:
+:    D-4H:   19,   38:    PROD:ORAT:
+:    C-1H:   26,   44:     INJ:GRAT:
 :    E-3H:   12,   72:    PROD:ORAT:
+:    C-2H:   23,   15:     INJ:WRAT:
+:    B-1H:   14,   34:    PROD:ORAT:
+:    C-3H:    9,   13:     INJ:GRAT:
+:    F-1H:   12,   85:     INJ:WRAT:
 :    B-3H:    9,   37:    PROD:RESV:
 :    E-1H:   18,   68:    PROD:RESV:
 :    F-2H:   18,   83:     INJ:WRAT:
 :    E-2H:   13,   67:    PROD:ORAT:
+:    E-4H:   36,   96:    PROD:ORAT:
+:   E-4AH:   38,   98:    PROD:ORAT:
+:    D-3H:   19,   54:    PROD:ORAT:
+:   D-3AH:   19,   54:    PROD:ORAT:
 :    F-3H:    6,   57:     INJ:WRAT:
+:   E-3AH:    7,   64:    PROD:ORAT:
 :   B-4AH:    9,   46:    PROD:ORAT:
+:    F-4H:   36,   68:     INJ:WRAT:
 :   B-4BH:    9,   46:    PROD:ORAT:
+:   D-4AH:   16,   66:    PROD:ORAT:
+:   D-1CH:   25,   37:    PROD:RESV:
+:   C-4AH:   29,   51:     INJ:GRAT:
+:   B-4DH:   10,   29:    PROD:RESV:
 :   E-3BH:   15,   74:    PROD:ORAT:
 :   E-3CH:   15,   74:    PROD:RESV:
 :   E-2AH:   13,   67:    PROD:RESV:
+:   D-3BH:   19,   54:    PROD:RESV:
+:   B-1AH:   10,   24:    PROD:ORAT:
+:   B-1BH:   10,   24:    PROD:RESV:
+:    K-3H:   11,   28:    PROD:RESV:
 :--------:-----------:--------:----:
```

### CODE REVIEW

**Comment by bska** [comment]
jenkins build this please

**Comment by bska** [comment]
jenkins build this please

**Review by akva2 — APPROVED** [review]
Makes sense.

**Comment by bska** [comment]
Merging per approval.

**Pull request merged**
