### PR TITLE
Add some more parallel tests

### PR DESCRIPTION
**Pull request by akva2**
This adds some more parallel tests. Will be useful when working on changing parallelism.

### CODE REVIEW

**Comment by akva2** [comment]
jenkins build this please

**Comment by akva2** [comment]
ROCKCOMP is broken in parallel. removing that test for now.

**Comment by akva2** [comment]
jenkins build this please

**Comment by atgeirr** [comment]
Good, merging!

**Comment by blattms** [comment]
> ROCKCOMP is broken in parallel. 

in what sense was/is it broken?

**Comment by akva2** [comment]
Did not really look into details but BGAS vectors had different size in parallel run vs serial run.

**Pull request merged**
