### PR TITLE
Use lists in buildsystem and rename some ebos models to be consistent with flow

### PR DESCRIPTION
**Pull request by akva2**
This simplifies the buildsystem a little by reusing lists instead of repeating them.
It also includes some changes to ebos models to use names consistent with the flow models to further simplify things.

No problem for me to rebase this after https://github.com/OPM/opm-simulators/pull/2851

### CODE REVIEW

**Comment by akva2** [comment]
jenkins build this please

**Comment by akva2** [comment]
jenkins build this please

**Review by blattms — APPROVED** [review]
Looks good. (Header is a bit misleading as there are renames in the source code, too)
There seems to be no rebase needed.

**Comment by akva2** [comment]
jenkins build this please

**Comment by akva2** [comment]
@totto82 since you are the closest to an ebos caretaker, any objections to the renames?

**Comment by totto82** [comment]
Looks good. Thanks for the cleanup!

**Comment by akva2** [comment]
jenkins build this please

**Pull request merged**
