### PR TITLE
removing GEFAC from MissingFeatures.cpp

### LINKED ISSUE #1272: Remove GEFAC from list in MissingFeatures.cpp
Has been supported for some time.

### PR DESCRIPTION
**Pull request by GitPaean**
this closes #1272. 

By the way, what is the status of `SSOL`?. I got the impression it should be supported, while I am not 100% positive.  If it is supported, I can remove `SSOL` too in this PR.

### CODE REVIEW

**Comment by GitPaean** [comment]
jenkins build this please

**Comment by totto82** [comment]
Yes, SSOL is supported. FlowMainEbos.hpp#550

**Comment by GitPaean** [comment]
> Yes, SSOL is supported. FlowMainEbos.hpp#550

SSOL is also removed.

**Comment by atgeirr** [comment]
Thanks, merging!

**Pull request merged**
