### PR TITLE
add missing include and damaris reference file update support

### PR DESCRIPTION
**Pull request by akva2**
hopefully this is enough to bring back damaris support.

### CODE REVIEW

**Comment by akva2** [comment]
jenkins build this mpi-damaris please

**Comment by akva2** [comment]
jenkins build this nompi mpi-damaris update_data please

**Comment by akva2** [comment]
jenkins build this nompi mpi-damaris update_data please

**Comment by akva2** [comment]
jenkins build this nompi mpi-damaris update_data please

**Comment by akva2** [comment]
jenkins build this nompi mpi-damaris update_data please

**Comment by akva2** [comment]
jenkins build this nompi mpi-damaris opm-tests=1197 please

**Comment by akva2** [comment]
jenkins build this mpi-damaris opm-tests=1197 please

**Comment by akva2** [comment]
this is ready for merge. when this is in we can activate damaris in the default mpi build configuration.

**Review by bska — APPROVED** [review]
Very good.  The new reference solutions have been installed on the CI system so I'll merge this now.

**Pull request merged**
