### PR TITLE
making the single phase RESV injection work.

### PR DESCRIPTION
**Pull request by GitPaean**
@atgeirr , please help to confirm it works for your case.

### CODE REVIEW

**Comment by GitPaean** [comment]
jenkins build this opm-data=278 please

**Comment by atgeirr** [comment]
Unfortunately, in my case it still does not match. I'll investigate.

**Comment by atgeirr** [comment]
jenkins build this please

**Comment by GitPaean** [comment]
I think this PR can go in without breaking anything, and the results show correct behavior. Do you agree @atgeirr ?

**Comment by atgeirr** [comment]
jenkins build this please

**Comment by atgeirr** [comment]
I think perhaps this run was ruined by merges performed in between, will rerun.

**Comment by atgeirr** [comment]
jenkins build this please

**Comment by atgeirr** [comment]
All green, merging!

**Pull request merged**
