### PR TITLE
changed: use EclMpiSerializer to distribute transmissibilities

### PR DESCRIPTION
**Pull request by akva2**
Downstream of https://github.com/OPM/opm-common/pull/3143

### CODE REVIEW

**Comment by blattms** [comment]
Thanks, looked good.

**Comment by akva2** [comment]
untested on jenkins. let's hope it was good ;)

**Comment by blattms** [comment]
:flushed: Shoot. Was so happy to not fall in "Hey, this guy is changing my holy code, how dare he"-trap, that I might have overlooked this.
Thought upstream was green though. But maybe I am hallucinating,

**Comment by akva2** [comment]
i didn't have time to trigger jenkins as i was waiting for other merges. but i'm fairly certain it's okay, all parallel tests passed locally..

**Pull request merged**
