### PR TITLE
Simplify and fix check for violation of GRUP for multiple level of guiderates

### PR DESCRIPTION
**Pull request by totto82**
This needs more testing so I will make it a draft.

### CODE REVIEW

**Comment by totto82** [comment]
jenkins build this please

**Comment by totto82** [comment]
Tested and approved by @tskille. The test failures are either minor or for the MOD4_GR cases manually verified that the results is not changed in the "eyeball norm".

**Review by atgeirr — APPROVED** [review]
I have looked at this quite carefully, and also discussed it at length with @totto82, and believe this should be merged.

**Comment by totto82** [comment]
jenkins build this update_data please

**Comment by totto82** [comment]
jenkins build this opm-tests=800 please

**Pull request merged**
