### PR TITLE
[for testing] tighening tolerance for testing purpose

### PR DESCRIPTION
**Pull request by GitPaean**
brine model is disabled because it can not finish running.

Please do not merge it.

### CODE REVIEW

**Comment by GitPaean** [comment]
jenkins build this update_data please

**Comment by bska** [comment]
> Please do not merge it.

This situation is perfect for a "draft" pull request.  Those cannot be merged, but you can still run Jenkins on them.

**Comment by GitPaean** [comment]
>  but you can still run Jenkins on them.

Thanks for letting me know. I did not know I can run Jenkins for a draft PR.

**Comment by GitPaean** [comment]
This PR tightens the tolerance very much, very likely not suitable for practical purpose. Just creating it to look for some clues.

**Comment by GitPaean** [comment]
With this PR, it is the following tests failed. 
```
	 36 - compareECLFiles_flow+3D_MSW (Failed)
	 42 - compareECLFiles_flow+MSW_MODEL_1 (Failed)
	 44 - compareECLFiles_flow+FAULTS_MODEL_1 (Failed)
	 56 - compareECLFiles_flow+TEST_WSEGSICD (Failed)
```

They are all related to MSW model. 

Compared to the master branch on my machine
```
	 39 - compareECLFiles_flow+2D_POLYMER_INJECTIVITY (Failed)
	 40 - compareECLFiles_flow+2D_THREEPHASE_POLY_HETER (Failed)
```

are recovered. 

It means, tightening the convergence criteria might be able to recover the test failure related to the polymer cases.

**Pull request closed without merging**
