### PR TITLE
Remove the mpi calls from the business logic

### PR DESCRIPTION
**Pull request by lisajulia**
Implement mmv and mv functions that do the communication and are called from the business layer.

### CODE REVIEW

**Comment by lisajulia** [comment]
jenkins build this please

**Comment by lisajulia** [comment]
jenkins build this please

**Comment by lisajulia** [comment]
jenkins build this please

**Comment by akva2** [comment]
jenkins build this please

**Review by akva2 — APPROVED** [review]
Looks good to me

**Comment by atgeirr** [comment]
All green and reviewed, merging.

**Pull request merged**
