### PR TITLE
checking LIFTOPT active before gliftBeginTimeStepWellTestUpdateALQ and before attempting to optimize alq in gliftBeginTimeStepWellTestIterateWellEquations

### PR DESCRIPTION
**Pull request by GitPaean**
to avoid meaningless message output related to GLIFT and WTEST.

When LIFTOPT is not active, it is confusing to see screen messages as the following

GLIFT WTEST: Well xxx : Gas Lift not activated: WLIFTOPT is probably missing. Skipping.

and 

GLIFT WTEST: Well {} does not have THP constraints"

### CODE REVIEW

**Comment by GitPaean** [comment]
jenkins build this please

**Comment by GitPaean** [comment]
I added a second commit which is related while different context.

**Comment by GitPaean** [comment]
jenkins build this please

**Review by bska — APPROVED** [review]
Excellent!  These stray messages have bothered me for a long time.  I'll merge into master.

**Comment by akva2** [comment]
ripe for backport?

**Comment by bska** [comment]
> ripe for backport?

Yes, I think so.  I'll tag this with the release milestone.

**Pull request merged**
