### PR TITLE
changed: unify getMobility(Eval|Scalar)

### PR DESCRIPTION
**Pull request by akva2**
To avoid manual duplication of code.

### CODE REVIEW

**Comment by akva2** [comment]
jenkins build this please

**Comment by akva2** [comment]
jenkins build this please

**Comment by akva2** [comment]
@totto82 @GitPaean  why the difference in msw for relperms, ref the relpermArray() lambda ? is the complication there for a reason and if so should we do the same for stw?

**Comment by GitPaean** [comment]
>  @totto82 @GitPaean why the difference in msw for relperms, ref the relpermArray() lambda ? is the complication there for a reason and if so should we do the same for stw?

I think the same can be used for stw, it might be able to slightly faster to use Scalar when we only need the Scalar values.

**Comment by totto82** [comment]
Cant getMobility be further unified between MSW and STW? The difference is related to missing solvent ++ in MSW, but shouldn't that be taken care of by `if constexpr (has_solvent)` Or did I miss something?

**Comment by totto82** [comment]
> that was my plan yes, in a follow-up. but if you want it here, i'll go for it now.

Do what you think best. Thanks for the cleanup! From my point of view this can be merged.

**Comment by akva2** [comment]
jenkins build this please

**Comment by akva2** [comment]
any objections @bska @atgeirr @GitPaean  ?

**Comment by GitPaean** [comment]
I did not check all the details, but I understand this PR is an effort to refactor and cleaning up of the code and does not change running results.  

I think it is good and have no objections to get it in.

**Comment by GitPaean** [comment]
jenkins build this please

**Comment by GitPaean** [comment]
jenkins build this opm-tets=963 please

**Comment by akva2** [comment]
jenkins build this opm-tests=963 please

**Comment by akva2** [comment]
jenkins build this opm-tests=963 please

**Comment by akva2** [comment]
jenkins build this opm-tests=963 please

**Comment by GitPaean** [comment]
I think my purpose was to update_data, but somehow I forgot it. But I saw it is triggered in opm-tests now.

**Comment by GitPaean** [comment]
jenkins build this opm-tests=963 update_data please

**Comment by akva2** [comment]
it's not a good idea to use this PR as it changes code that might affect those values.

**Comment by akva2** [comment]
jenkins build this please

**Comment by GitPaean** [comment]
with the merging of https://github.com/OPM/opm-simulators/pull/4655 , there is a conflicts now. Please help to fix and update it.

**Comment by akva2** [comment]
jenkins build this please

**Pull request merged**
