### PR TITLE
update primary variables in prepareTimeStep after updating the well target

### PR DESCRIPTION
**Pull request by GitPaean**
In `BlackoilWellModel<TypeTag>::prepareTimeStep(DeferredLogger& deferred_logger)`, when some well event happen, we update the well state to match the new control type. 

Before we use the well for well solving, we need to update the primary variables and Evaluation related to wells.

### CODE REVIEW

**Comment by GitPaean** [comment]
benchmark please

**Comment by GitPaean** [comment]
jenkins build this please

**Comment by totto82** [comment]
Good catch. `iterateWellEqWithControl(...) `expects updated primaryvariables when it starts.

**Comment by GitPaean** [comment]
Local tests does not see the big changes for 
https://ci.opm-project.org/job/opm-simulators-PR-builder/3665/testReport/junit/(root)/mpi/compareECLFiles_flow_9_2B_DEPL_GCONPROD_2L_STW/

```
	WWPT:PROD1: Summary file
		Fails for 19 entries
		Largest absolute error: 6.7358723e+00
		Largest relative error: 2.1900330e-01
	WWPT:PROD2: Summary file
		Fails for 19 entries
		Largest absolute error: 2.2339706e+01
		Largest relative error: 1.2316350e-01
	WWPT:PROD3: Summary file
		Fails for 19 entries
		Largest absolute error: 1.7494299e+02
		Largest relative error: 8.2455539e-02
	WWPT:PROD4: Summary file
		Fails for 19 entries
		Largest absolute error: 2.1072556e+01
		Largest relative error: 6.7911430e-01
```

using update_data to help to check.

**Comment by GitPaean** [comment]
jenkins build this update_data please

**Comment by GitPaean** [comment]
benchmark please

**Comment by ytelses** [comment]
Benchmark result overview: 




| Test    | Configuration                                     | Relative |
| ------- | ------------------------------------------------- | -------- |
| opm-git | OPM Benchmark: flow_mpi_extra - Threads: 1        | 1.01     |
| opm-git | OPM Benchmark: flow_mpi_extra - Threads: 8        | 0.989    |
| opm-git | OPM Benchmark: flow_mpi_norne - Threads: 1        | 1.031    |
| opm-git | OPM Benchmark: flow_mpi_norne - Threads: 8        | 1.01     |
| opm-git | OPM Benchmark: flow_mpi_norne_4c_msw - Threads: 1 | 1.343    |
| opm-git | OPM Benchmark: flow_mpi_norne_4c_msw - Threads: 8 | 1.196    |
* Speed-up = Total time master / Total time pull request. Above 1.0 is an improvement. *



View result details @ https://www.ytelses.com/opm/?page=result&id=1621

**Comment by ytelses** [comment]
Benchmark result overview: 




| Test    | Configuration                                     | Relative |
| ------- | ------------------------------------------------- | -------- |
| opm-git | OPM Benchmark: flow_mpi_extra - Threads: 1        | 0.991    |
| opm-git | OPM Benchmark: flow_mpi_extra - Threads: 8        | 0.991    |
| opm-git | OPM Benchmark: flow_mpi_norne - Threads: 1        | 1.028    |
| opm-git | OPM Benchmark: flow_mpi_norne - Threads: 8        | 1.007    |
| opm-git | OPM Benchmark: flow_mpi_norne_4c_msw - Threads: 1 | 1.343    |
| opm-git | OPM Benchmark: flow_mpi_norne_4c_msw - Threads: 8 | 1.195    |
* Speed-up = Total time master / Total time pull request. Above 1.0 is an improvement. *



View result details @ https://www.ytelses.com/opm/?page=result&id=1622

**Comment by totto82** [comment]
jenkins build this opm-tests=756 please

**Pull request merged**
