### PR TITLE
Ignore linear solver convergence failure.

### PR DESCRIPTION
**Pull request by dr-robertk**
This PR adds a user flag to allow to ignore the convergence failure of the linear solver. 
For Model 2 this gives a speedup according to totto82.

The default behavior remains unchanged.

### CODE REVIEW

**Comment by atgeirr** [comment]
Looks fine, but would it not be better to test this at the call site? Then it would apply to all current and future solver variants.

**Comment by dr-robertk** [comment]
You mean catch the exception and then don't do anything if no convergence?

**Comment by atgeirr** [comment]
I managed to confuse myself, sorry! I thought for a moment that this class returned a report-type class with a converged flag, but it does not. Please ignore my previous comment, I'll merge!

**Comment by blattms** [comment]
@dr-robertk You becoming an engineer ;)

So basically this means that we want to achieve a specific reduction in a maximum number of steps of the iterative solver, but if we cannot do that then we are happy with the reduction that we have achieved. And we leave it to the nonlinear solver to detect problems and the time stepper to repair things.
I am wondering whether using this keyword without adaptive timestepping makes sense.
I guess somebody should compute the minimum reduction needed and try running the model with that reduction threshold and this keyword set to false. I would be interested in the runtime.

**Comment by atgeirr** [comment]
Without adaptive timestepping this PR allows the process to continue instead of immediately terminating. As you say, if the nonlinear solver cannot go on (too many iterations or exploding residuals) it will terminate then. With adaptive timestepping these events will lead to timestep chopping because it will catch the exception.

At some point I'd like to replace the throw-catch with a more explicit communication protocol for this, but since we may encounter occasional dune-istl exceptions it's probably not worth the effort, since we still need to do the catching.

**Pull request merged**
