### PR TITLE
Remove Eigen from BlackoilModelEbos.

### PR DESCRIPTION
**Pull request by dr-robertk**
This PR removes last traces of Eigen classes from BlackoilModelEbos. This needs testing Model 2 and 3 and 4.

### CODE REVIEW

**Comment by dr-robertk** [comment]
jenkins build this please and then fix any bugs and then merge

**Comment by andlaus** [comment]
you went into the AI business recently? cool! ;)

**Comment by dr-robertk** [comment]
jenkins build this please

**Comment by dr-robertk** [comment]
jenkins bring beer please ;-)

**Comment by andlaus** [comment]
jenkins build this opm-common=162 please

**Comment by andlaus** [comment]
(it may not work since jenkins may not be able to pick up new dependencies automatically. @akva2?)

**Comment by totto82** [comment]
Tested on Model 2 and Model 2.2. 
Has Travis succeeded before with the Frankenstein PRs? Is seems that it is not able to find ewoms and that couldn't be this PRs fault.

**Comment by notspiff** [comment]
@andlaus dependency can mean a lot of different things. but looking at the jenkins failure, i assume the answer to your question is 'no'. you have to update the list at https://github.com/OPM/opm-simulators/blob/master/jenkins/build.sh#L3 to include ewoms as an upstream of opm-simulators.

**Comment by akva2** [comment]
argh, wrong login. ^^ @akva2

**Comment by andlaus** [comment]
@totto82: no, travis never succeeded for frankenstein because of the dependency issue. I guess this PR should be merged and @akva2's fix for travis/jenkins should also be applied to frankenstein soon.

**Pull request merged**
