### PR TITLE
[refactor] Remove unnecessary copy in axisCentroid and simply code.

### PR DESCRIPTION
**Pull request by blattms**
We stored 3 copies of each cell centroid in axisCentroid. This seemed to be a waste of memory and also made the function distanceVector_ hard to understand.

With this change we omit this copy of information and simplify distanceVector_

### CODE REVIEW

**Comment by blattms** [comment]
jenkins build this please

**Comment by GitPaean** [comment]
Thanks. I will also test how the this reflect in the memory profiling.

**Comment by blattms** [comment]
If it does then it must have been one of the short peaks.

**Comment by blattms** [comment]
benchmark please

**Comment by ytelses** [comment]
Benchmark result overview: 




| Test    | Configuration                                     | Relative |
| ------- | ------------------------------------------------- | -------- |
| opm-git | OPM Benchmark: drogon - Threads: 1                | 0.999    |
| opm-git | OPM Benchmark: drogon - Threads: 8                | 1.005    |
| opm-git | OPM Benchmark: punqs3 - Threads: 1                | 0.978    |
| opm-git | OPM Benchmark: punqs3 - Threads: 8                | 1.014    |
| opm-git | OPM Benchmark: smeaheia - Threads: 1              | 0.983    |
| opm-git | OPM Benchmark: smeaheia - Threads: 8              | 1.003    |
| opm-git | OPM Benchmark: spe10_model_1 - Threads: 1         | 0.998    |
| opm-git | OPM Benchmark: spe10_model_1 - Threads: 8         | 1.002    |
| opm-git | OPM Benchmark: flow_mpi_extra - Threads: 1        | 1.009    |
| opm-git | OPM Benchmark: flow_mpi_extra - Threads: 8        | 0.998    |
| opm-git | OPM Benchmark: flow_mpi_norne - Threads: 1        | 0.979    |
| opm-git | OPM Benchmark: flow_mpi_norne - Threads: 8        | 0.993    |
| opm-git | OPM Benchmark: flow_mpi_norne_4c_msw - Threads: 1 | 1.001    |
| opm-git | OPM Benchmark: flow_mpi_norne_4c_msw - Threads: 8 | 1.007    |
* Speed-up = Total time master / Total time pull request. Above 1.0 is an improvement. *



View result details @ https://www.ytelses.com/opm/?page=result&id=2529

**Review by bska — APPROVED** [review]
This is very welcome and does indeed get rid of some memory we don't need.  I have just one question for your consideration here.  Since every call to `distanceVector_()` now is of the form
```C++
distanceVector_(faceCentroid, centroids_(i))
```
for some element index `i`, might it make sense to change the interface to
```C++
DimVector distanceVector_(const DimVector&, const unsigned elmIdx) const;
```
and to push the call to the `centroids_()` call-back into `distanceVector_()` itself?

**Comment by GitPaean** [comment]
> If it does then it must have been one of the short peaks.

You are correct. For the case with 1 million cells and 14 process, the change in this PR does not make obvious changes in the memory profiling for the rank 0 (possibly flattening a little bit to a small local peak (far from the global peak)). But it is always something positive to reduce unnecessary memory usage.

**Comment by blattms** [comment]
Interface changed.

**Comment by blattms** [comment]
jenkins build this please.

**Comment by blattms** [comment]
Shameless self-merge because of prior approval.

**Comment by blattms** [comment]
jenkins build this please

**Review by bska — APPROVED** [review]
Thanks a lot for the updates. This looks good to me and I'll merge into master.

**Pull request merged**
