### PR TITLE
Avoid cache

### PR DESCRIPTION
**Pull request by hnil**
Added explicit call to intensive quantities to make it possible to run the code with calculation the property on the fly.
It also add better checking and error messages, if wrong options or logical errors in the code.

### CODE REVIEW

**Comment by bska** [comment]
jenkins build this please

**Review by bska — APPROVED** [review]
Very good.  I'll merge into master.

**Comment by akva2** [comment]
this merged warnings.

**Comment by bska** [comment]
> this merged warnings.

Thanks for the heads up.  I'll fix.

**Comment by akva2** [comment]
Will you add the missing headers and such while at it ?

**Comment by bska** [comment]
@akva2 : PR #4557 fixes those issues.

**Pull request merged**
