### PR TITLE
[cleanup] Removes unnecessary if clauses for unsupported DUNE versions.

### PR DESCRIPTION
**Pull request by blattms**
We are targetting DUNE 2.4.* and 2.5.* currently. Therefore this commit removes
the if checks for lower versions to cleanup the code.

### CODE REVIEW

**Comment by blattms** [comment]
jenkins build this with dune2.4 please

**Comment by atgeirr** [comment]
I do not understand why Jenkins has not at least been triggered (if not finished, there is a long queue), will retry triggering (I find the Dune 2.4 check very prudent).

**Comment by blattms** [comment]
Because I triggered it, and while it was running added a new
commit. That stopped jenkins.

Plan was to post similar PRs for the other modules and then run
jenkings once with all of them. Not sure whether that would work,
though.

**Comment by blattms** [comment]
jenkins run triggered on OPM/opm-grid#286

**Pull request merged**
