### PR TITLE
added: StandardWellEquations

### PR DESCRIPTION
**Pull request by akva2**
This is a container class for the equation system, as well as methods for applying to vectors.

- better code organization
- less instances. instead of one instance per index instance there is now one instance per block size (1..6).

This is part of a process to refactor the equation system and assembly of this from in standard well, as drafted in https://github.com/OPM/opm-simulators/pull/4238. All data members are still public, but this will be remedied later.

Sits on top of https://github.com/OPM/opm-simulators/pull/4237

### CODE REVIEW

**Comment by akva2** [comment]
jenkins build this please

**Comment by akva2** [comment]
jenkins build this please

**Comment by akva2** [comment]
jenkins build this please

**Review by bska — APPROVED** [review]
Very good.  I like this a lot and I appreciate the direction in which we're going.  I'm going to merge this into the master branch now.

**Pull request merged**
