### PR TITLE
flow_ebos: do not use (smart) pointers for opm-parser objects anymore

### PR DESCRIPTION
**Pull request by andlaus**
this patch also includes code to make FlowMainEbos more autonomous (i.e. it does not derive from FlowMainBase anymore). this allows more flexibility how and what stuff gets created. Note that this implies that parts of #947 are included here (in particular the grid initialization).

this is the companion PR for OPM/ewoms#102.

### CODE REVIEW

**Comment by andlaus** [comment]
I've verified that the performance of `flow_ebos` did not regress for the Norne deck.

**Comment by dr-robertk** [comment]
I think it should include all parts of #947 because all of them are bug fixes.

**Comment by andlaus** [comment]
> I think it should include all parts of #947 because all of them are bug fixes.

ok, after 947 is merged, I'll rebase #947 on master.

**Comment by andlaus** [comment]
jenkins run norne_ebos ewoms=102 please

**Comment by dr-robertk** [comment]
I'll merge #947 into this tomorrow. Then it's easier  to fix the remaining bugs.

**Comment by andlaus** [comment]
jenkins run norne_ebos ewoms=103 please

**Comment by andlaus** [comment]
jenkins run norne_ebos ewoms=103 please

**Comment by andlaus** [comment]
since jenkins is happy, I'll merge this and OPM/ewoms#103 some time tomorrow. (if nobody objects. if you want it sooner you have my blessings to merge these two yourself.)

**Comment by andlaus** [comment]
silence means merging ;)

**Pull request merged**
