### PR TITLE
Hide vtk

### PR DESCRIPTION
**Pull request by hnil**
This hide all the vtk output options from flow.  Currently it was not possible to do this dependent on if the enable-vtk option was used.

### CODE REVIEW

**Comment by atgeirr** [comment]
I support this, as it will make the "flow --help" experience a lot better. Maybe we need to provide a mechanism to expose all available parameters if requested (unless it already exists), but I think this can be merged. We should wait until after the big de-macro-ing (new word...) of the property system has been merged though.

**Comment by atgeirr** [comment]
jenkins build this please

**Comment by alfbr** [comment]
Hiding less used options is a very good idea. This is exactly what users expect from command line options. A help text only gives a brief description, while the man-page tells the whole story.

**Comment by hnil** [comment]
One could have change the help text for the enable-vtk-output to point to the documentation.

**Comment by totto82** [comment]
What about adding an option that also shows the hidden parameters? Something like --help-all

**Comment by atgeirr** [comment]
After merging the PR changing the property system I think I'll rerun Jenkins to be sure before merging this.

**Comment by atgeirr** [comment]
jenkins build this please

**Pull request merged**
