### PR TITLE
Add a common executable for all flow variants.

### PR DESCRIPTION
**Pull request by dr-robertk**
This PR creates one executable for all variants of flow_ebos, i.e. flow_ebos, flow_ebos_polymer, flow_ebos_solvent, flow_ebos_2p.

The old executables still exist and are unchanged. This PR requires https://github.com/OPM/ewoms/pull/217 .

### CODE REVIEW

**Comment by dr-robertk** [comment]
jenkins build this please

**Comment by atgeirr** [comment]
This is good! I am happy to see this resolved.

My only worry is this: what happens if something goes wrong in reading the deck. I think the current version here will print a misleading error message referring to a log file but giving no file name. There will be no log file either, unless the main function has been run (I think). So perhaps we must extract the logging setup (and things it depend on) from the FlowMainEbos class, after all these things do not really use the template parameter. Alternatively, the class can be made a non-template, and the final run() method (only) made into a template, do you think this is feasible?

I will not veto merging this as-is though, since it does not change existing programs, but I would prefer to resolve this now instead of later. It must be resolved before we consider removing the individual programs though.

**Comment by dr-robertk** [comment]
@atgeirr: Additionally the tests have to be assigned to the flow executable. I wanted this to be resolved in a separate PR as I don't know what the consequences on the reference files are.

**Comment by akva2** [comment]
in opm-data, the reference data is stored as opm-simulation-reference/simulatorname and right now it's the same parameter to the macros. so either you have to extend the macros to allow passing another parameter, or you have to do renames in opm-data.

**Comment by dr-robertk** [comment]
That's what I thought, so I would suggest to do this in a separate PR.

**Comment by dr-robertk** [comment]
Or should it be done in one shot?

**Comment by akva2** [comment]
i'm sorry but i have to disagree. merging such a huge refactor without testing seems like a very very bad idea.

**Comment by dr-robertk** [comment]
Ok, then I'll copy the data files in opm-data and add all the tests. It is by the way no huge refactor. All of the simulation code etc stays unchanged.

**Comment by dr-robertk** [comment]
@atgeirr : A quick glance a the setupLogging in FlowMainEbos.hpp reveals that setupLogging is setup after the deck is created. So if something goes wrong in checkDeck and MissingFeatures::checkKeywords then the printed logFile_ string is empty.

**Comment by dr-robertk** [comment]
jenkins build this with opm-data=242 ewoms=217 please

**Comment by dr-robertk** [comment]
Looks good to me. I think this can be merged once the corresponding PRs in opm-data and ewoms have been merged.

**Comment by atgeirr** [comment]
> Looks good to me. I think this can be merged once the corresponding PRs in opm-data and ewoms have been merged.

I agree, feel free to merge this PR.

We should discuss what we want to have in the end, though:
 - Only the flow executable?
 - Flow and the specialized (smaller) executables?
 - Links or scripts from the specialized names to flow, used by flow to decide which variant to run (overriding anything in the deck)?

I think one of the last two would be necessary for sanity-checking such as making sure the solvent sim can run a straight black-oil case etc.

**Comment by GitPaean** [comment]
I did not look into the change.  A simple question, with this PR, when we solve two phase problem with `flow_ebos`, is there still a dummy phase?

**Comment by dr-robertk** [comment]
This executable selects the code that corresponds to flow_ebos_2p in case a two-phase system is detected.

**Comment by dr-robertk** [comment]
jenkins build this opm-data=242 please

**Comment by dr-robertk** [comment]
If there are not further objections then I'll merge this.

**Pull request merged**
