### PR TITLE
Support Calculating Phase Pressures for Water/Gas at Block Level

### PR DESCRIPTION
**Pull request by bska**
This PR adds support for calculating/extracting the block-level phase pressures for water (`BWPR`) and gas (`BGPR`) for summary output purposes.

### CODE REVIEW

**Comment by bska** [comment]
jenkins build this please

**Comment by bska** [comment]
When combined with OPM/opm-common#2967 we get the following curves for
```
BWPR
 12 1 7 /
/
BGPR
 1 1 1 /
/
```
added to [`SPE9_CP.DATA`](https://github.com/OPM/opm-tests/blob/94820d1a26562261131b80be63716d14950a22eb/spe9/SPE9_CP.DATA#L347-L349)

---

### Oil and Water Phase Pressures (BPR &amp; BWPR) ###
SPE9_CP_Block_12_1_7

### Oil and Gas Phase Pressures (BPR &amp; BGPR) ###
SPE9_CP_Block_1_1_1

**Comment by akva2** [comment]
reason for failure is a bug in jenkins (saw your last comment, not the trigger).

**Comment by akva2** [comment]
jenkins build this please

**Comment by bska** [comment]
> reason for failure is a bug in jenkins (saw your last comment, not the trigger).

Right.  I didn't mean to submit the follow-up comment until the build started but I hit the "Comment" button too soon.  Thanks for retriggering!

**Pull request merged**
