### PR TITLE
solve linear system more accuratly (factor 1/10) when newton iter > 8

### PR DESCRIPTION
**Pull request by totto82**
Motivation avoid stagnation when forcing small time-steps by `TUNING` or `--solver-max-time-step-in-days=XXX`.

The 8 and 1/10 in the PR is hard-coded and based on intuition and inspired a bit on "CHOOSING THE FORCING TERMS IN AN INEXACT NEWTON METHOD*" EISENSTAT et al 2016. and seems to work fine on the models I have tested. May need to be adjusted further and should potentially be input parameters rather than hard-coded numbers.

### CODE REVIEW

**Comment by atgeirr** [comment]
I guess this shows there should be a dynamic call for FlexibleSolver to set the tolerance.

This code does not look like it resets the tolerance, but keeps the new one for the rest of the simulation. Maybe not intentional?

**Comment by totto82** [comment]
> This code does not look like it resets the tolerance, but keeps the new one for the rest of the simulation. Maybe not intentional?

Not at all I tried to be smart and avoiding some recreation of solvers when cleaning up the PR. I will update imidiatly.

**Comment by totto82** [comment]
jenkins build this please

**Comment by bska** [comment]
Since we're solving systems more accurately, what's the performance impact of this change?

**Comment by totto82** [comment]
jenkins build this please

**Comment by totto82** [comment]
benchmark please

**Comment by totto82** [comment]
> Since we're solving systems more accurately, what's the performance impact of this change?

Lets see what benchmark thinks. For the test I have don't it actually gives a decent speed-up due to less newton iterations. But more testing is indeed needed in order to say something in general.

**Comment by ytelses** [comment]
Benchmark result overview: 




| Test    | Configuration                                     | Relative |
| ------- | ------------------------------------------------- | -------- |
| opm-git | OPM Benchmark: flow_mpi_extra - Threads: 1        | 0.948    |
| opm-git | OPM Benchmark: flow_mpi_extra - Threads: 8        | 1.003    |
| opm-git | OPM Benchmark: flow_mpi_norne - Threads: 1        | 1.007    |
| opm-git | OPM Benchmark: flow_mpi_norne - Threads: 8        | 0.991    |
| opm-git | OPM Benchmark: flow_mpi_norne_4c_msw - Threads: 1 | 0.791    |
| opm-git | OPM Benchmark: flow_mpi_norne_4c_msw - Threads: 8 | 1.217    |
* Speed-up = Total time master / Total time pull request. Above 1.0 is an improvement. *



View result details @ https://www.ytelses.com/opm/?page=result&id=1682

**Comment by atgeirr** [comment]
> Lets see what benchmark thinks. For the test I have don't it actually gives a decent speed-up due to less newton iterations. But more testing is indeed needed in order to say something in general.

We have seen this on many cases before, that using tighter linear solver tolerances can pay off. It pays off more with stronger preconditioners usually. It is very case-dependent though, so adding some adaptivity as here is a good direction.

**Comment by totto82** [comment]
jenkins build this please

**Comment by totto82** [comment]
benchmark please

**Comment by ytelses** [comment]
Benchmark result overview: 




| Test    | Configuration                                     | Relative |
| ------- | ------------------------------------------------- | -------- |
| opm-git | OPM Benchmark: flow_mpi_extra - Threads: 1        | 0.962    |
| opm-git | OPM Benchmark: flow_mpi_extra - Threads: 8        | 0.936    |
| opm-git | OPM Benchmark: flow_mpi_norne - Threads: 1        | 0.976    |
| opm-git | OPM Benchmark: flow_mpi_norne - Threads: 8        | 0.985    |
| opm-git | OPM Benchmark: flow_mpi_norne_4c_msw - Threads: 1 | 0.884    |
| opm-git | OPM Benchmark: flow_mpi_norne_4c_msw - Threads: 8 | 1.342    |
* Speed-up = Total time master / Total time pull request. Above 1.0 is an improvement. *



View result details @ https://www.ytelses.com/opm/?page=result&id=1686

**Comment by OPMUSER** [comment]
Can this be closed?

**Pull request closed without merging**
