### PR TITLE
add option for relaxed convergence for stw

### PR DESCRIPTION
**Pull request by totto82**
The logic is the same as what's already there for msw

### CODE REVIEW

**Comment by totto82** [comment]
jenkins build this please

**Comment by totto82** [comment]
benchmark please

**Comment by totto82** [comment]
I have checked the test failure. This PR uses less number of newton iterations 1 May 2019 and thus alter the time-stepping and convergence history after that. Qualitatively the results are the same.

**Comment by ytelses** [comment]
Benchmark result overview: 




| Test    | Configuration                                     | Relative |
| ------- | ------------------------------------------------- | -------- |
| opm-git | OPM Benchmark: flow_mpi_norne - Threads: 1        | 1.018    |
| opm-git | OPM Benchmark: flow_mpi_norne - Threads: 8        | 1.002    |
| opm-git | OPM Benchmark: flow_mpi_norne_4c_msw - Threads: 1 | 0.998    |
| opm-git | OPM Benchmark: flow_mpi_norne_4c_msw - Threads: 8 | 0.997    |
* Speed-up = Total time master / Total time pull request. Above 1.0 is an improvement. *



View result details @ https://www.ytelses.com/opm/?page=result&id=1334

**Comment by ytelses** [comment]
Benchmark result overview: 




| Test    | Configuration                                     | Relative |
| ------- | ------------------------------------------------- | -------- |
| opm-git | OPM Benchmark: flow_mpi_norne - Threads: 1        | 1.017    |
| opm-git | OPM Benchmark: flow_mpi_norne - Threads: 8        | 0.999    |
| opm-git | OPM Benchmark: flow_mpi_norne_4c_msw - Threads: 1 | 0.997    |
| opm-git | OPM Benchmark: flow_mpi_norne_4c_msw - Threads: 8 | 0.997    |
* Speed-up = Total time master / Total time pull request. Above 1.0 is an improvement. *



View result details @ https://www.ytelses.com/opm/?page=result&id=1334

**Comment by totto82** [comment]
jenkins build this please

**Comment by totto82** [comment]
jenkins build this please

**Comment by totto82** [comment]
benchmark please

**Comment by ytelses** [comment]
Benchmark result overview: 




| Test    | Configuration                                     | Relative |
| ------- | ------------------------------------------------- | -------- |
| opm-git | OPM Benchmark: flow_mpi_extra - Threads: 1        | 0.999    |
| opm-git | OPM Benchmark: flow_mpi_extra - Threads: 8        | 1        |
| opm-git | OPM Benchmark: flow_mpi_norne - Threads: 1        | 0.997    |
| opm-git | OPM Benchmark: flow_mpi_norne - Threads: 8        | 0.998    |
| opm-git | OPM Benchmark: flow_mpi_norne_4c_msw - Threads: 1 | 1.001    |
| opm-git | OPM Benchmark: flow_mpi_norne_4c_msw - Threads: 8 | 1.001    |
* Speed-up = Total time master / Total time pull request. Above 1.0 is an improvement. *



View result details @ https://www.ytelses.com/opm/?page=result&id=1345

**Comment by totto82** [comment]
I will merge this now. Shouldn't change much with the current default values, but gives yet another option for tuning and at the same time it makes the stw code more similar to msw.

**Comment by ytelses** [comment]
Benchmark result overview: 




| Test    | Configuration                                     | Relative |
| ------- | ------------------------------------------------- | -------- |
| opm-git | OPM Benchmark: flow_mpi_extra - Threads: 1        | 0.997    |
| opm-git | OPM Benchmark: flow_mpi_extra - Threads: 8        | 1.003    |
| opm-git | OPM Benchmark: flow_mpi_norne - Threads: 1        | 0.994    |
| opm-git | OPM Benchmark: flow_mpi_norne - Threads: 8        | 1.006    |
| opm-git | OPM Benchmark: flow_mpi_norne_4c_msw - Threads: 1 | 1        |
| opm-git | OPM Benchmark: flow_mpi_norne_4c_msw - Threads: 8 | 0.997    |
* Speed-up = Total time master / Total time pull request. Above 1.0 is an improvement. *



View result details @ https://www.ytelses.com/opm/?page=result&id=1345

**Pull request merged**
