### PR TITLE
using 1.e-7 as default convergence tolerance for standard well

### PR DESCRIPTION
**Pull request by GitPaean**
some tests show it improves the results.  creating the pr for testing purpose.

### CODE REVIEW

**Comment by GitPaean** [comment]
benchmark please

**Comment by GitPaean** [comment]
jenkins build this please

**Comment by ytelses** [comment]
Benchmark result overview: 




| Test    | Configuration                              | Relative |
| ------- | ------------------------------------------ | -------- |
| opm-git | OPM Benchmark: drogon - Threads: 1         | 1.001    |
| opm-git | OPM Benchmark: drogon - Threads: 8         | 0.826    |
| opm-git | OPM Benchmark: smeaheia - Threads: 1       | 0.962    |
| opm-git | OPM Benchmark: smeaheia - Threads: 8       | 0.863    |
| opm-git | OPM Benchmark: spe10_model_1 - Threads: 1  | 1.123    |
| opm-git | OPM Benchmark: spe10_model_1 - Threads: 8  | 1.027    |
| opm-git | OPM Benchmark: flow_mpi_extra - Threads: 1 | 0.988    |
| opm-git | OPM Benchmark: flow_mpi_extra - Threads: 8 | 0.976    |
| opm-git | OPM Benchmark: flow_mpi_norne - Threads: 1 | 1.003    |
| opm-git | OPM Benchmark: flow_mpi_norne - Threads: 8 | 0.916    |
* Speed-up = Total time master / Total time pull request. Above 1.0 is an improvement. *



View result details @ https://www.ytelses.com/opm/?page=result&id=2014

**Comment by GitPaean** [comment]
benchmark please

**Comment by ytelses** [comment]
Benchmark result overview: 




| Test    | Configuration                              | Relative |
| ------- | ------------------------------------------ | -------- |
| opm-git | OPM Benchmark: drogon - Threads: 1         | 0.988    |
| opm-git | OPM Benchmark: drogon - Threads: 8         | 0.976    |
| opm-git | OPM Benchmark: smeaheia - Threads: 1       | 0.948    |
| opm-git | OPM Benchmark: smeaheia - Threads: 8       | 1.002    |
| opm-git | OPM Benchmark: spe10_model_1 - Threads: 1  | 1.119    |
| opm-git | OPM Benchmark: spe10_model_1 - Threads: 8  | 1.063    |
| opm-git | OPM Benchmark: flow_mpi_extra - Threads: 1 | 0.987    |
| opm-git | OPM Benchmark: flow_mpi_extra - Threads: 8 | 0.998    |
| opm-git | OPM Benchmark: flow_mpi_norne - Threads: 1 | 1        |
| opm-git | OPM Benchmark: flow_mpi_norne - Threads: 8 | 1.032    |
* Speed-up = Total time master / Total time pull request. Above 1.0 is an improvement. *



View result details @ https://www.ytelses.com/opm/?page=result&id=2016

**Pull request closed without merging**
