### PR TITLE
Use CpGrid::loadBalance to distribute the field properties.

### PR DESCRIPTION
**Pull request by blattms**
The created data handle for the communication could in theory be used with other DUNE grids, too. In reality we will need to merge with the handle that ALUGrid already uses to communicate the cartesian indices.

This PR gets rid of using the get_global_(double|int) method in ParallelEclipseState and reduces the amount of boilerplate code there.

Depends on OPM/opm-grid#452

### CODE REVIEW

**Comment by blattms** [comment]
jenkins build this opm-grid=452

**Comment by akva2** [comment]
This looks great. A related, but separate task, is to handle the distribution of the eclipse grid centroids used in ecltransmissibilities.hh. If you want to tackle that while at it.

**Comment by blattms** [comment]
Sounds reasonable, will do.

**Comment by blattms** [comment]
jenkins run norne norne_parallel please

**Comment by blattms** [comment]
Interesting: all test pass, but for norne parallel well curves are definitely off, now.

**Comment by blattms** [comment]
I did check this on my machine by comparing the well curves for a parallel run with 16 processes with this PR and without it. They match perfectly, which is quite a relief.

But it means that a regression must have been introduced somewhen. Yesterday as of PR [2386](https://ci.opm-project.org/job/opm-simulators-PR-builder/690/) it was still fine

**Comment by akva2** [comment]
latest post build https://ci.opm-project.org/job/opm-simulators/297/ show no discrepancies, so it has to be some change in another module.

**Comment by blattms** [comment]
My rebase should have fixed stuff.

**Comment by blattms** [comment]
jenkins run norne norne_parallel please

**Comment by blattms** [comment]
I don't get it. For jenkins the plots are still off. Can I somehow see which commits were used to build?

**Comment by joakim-hove** [comment]
> I don't get it.

I am sorry to say - but sometimes when Jenkins/GitHub together conspire to use stale references (most problematic with multi repo PR's) it does help to close and reopen the PR - for all it is worth.

> Can I somehow see which commits were used to build?

Don't know

**Comment by blattms** [comment]
Of course the computer/jenkins was right and the problem was sitting in front of the screen.

I always tested with 16 processors and there the curves looked decent. With 4 processors I saw the same deviations.

I think i found a fix and jenkins has some mercy for a mere mortal

**Comment by blattms** [comment]
jenkins run norne norne_parallel please

**Comment by blattms** [comment]
Thanks jenkins, now the curves match. Merging

**Comment by akva2** [comment]
this broke the post-build (serial/no-mpi) build https://ci.opm-project.org/job/opm-simulators/301/

**Pull request merged**
