### PR TITLE
Fix bug in the well efficiency factor

### PR DESCRIPTION
**Pull request by totto82**
The well efficiency factor should not be in the well control equation.

### CODE REVIEW

**Comment by totto82** [comment]
jenkins build this please

**Comment by atgeirr** [comment]
I assumed we had a test for this, but apparently not! Do you have a small testcase we can use (that shows this fix to be correct)?

**Comment by totto82** [comment]
I suggest modifying the SPE9_CP case. I have made a PR OPM/opm-tests#214

**Comment by atgeirr** [comment]
jenkins build this opm-tests=214

**Comment by totto82** [comment]
Why is this Green! Shouldn't adding WEFAC need an update of the reference solution?

**Comment by joakim-hove** [comment]
> Why is this Green!

Never satisfied are you?

**Comment by atgeirr** [comment]
> Shouldn't adding WEFAC need an update of the reference solution?

I agree, this smells a little strange. Did you see changes locally from the case modification?

**Comment by totto82** [comment]
Yes. There are significant changes locally based on WEFAC. WELTARG should not change anything.

**Comment by totto82** [comment]
jenkins build this opm-tests=214 update_data please

**Comment by akva2** [comment]
i posted the explanation in the opm-tests PR.

**Comment by totto82** [comment]
jenkins build this opm-tests=215 please

**Comment by akva2** [comment]
notice the failure for the restart test - that is probably not expected.

**Comment by totto82** [comment]
jenkins build this opm-tests=215 please

**Comment by totto82** [comment]
I have update OPM/opm-tests#215 as you suggested

**Comment by totto82** [comment]
jenkins build this opm-tests=215 update_data please

**Comment by totto82** [comment]
jenkins build this please opm-tests=215 opm-tests=218 please

**Comment by totto82** [comment]
jenkins build this opm-tests=215 opm-tests=218 please

**Comment by akva2** [comment]
that's not going to work :) you have to merge your PR manually.

**Comment by totto82** [comment]
> that's not going to work :)

Jenkins is happy!

**Comment by akva2** [comment]
now that is rather confusing. you cannot specify two pr's for the same repo...

**Comment by totto82** [comment]
Maybe both are ignored

**Comment by akva2** [comment]
haha yes i commented too soon so it saw my comment and ran with master of opm-tests. sigh.

**Comment by atgeirr** [comment]
If it is green with both ignored, we can merge here now and add the case afterwards? Not perfect but workable?

**Comment by akva2** [comment]
jenkins build this opm-tests=219 please

**Comment by akva2** [comment]
let's end this saga.

**Pull request merged**
