### PR TITLE
Reduced maximum time step on four MSW tests.

### PR DESCRIPTION
**Pull request by alfbr**
First attempt in fixing MSW tests that fail locally. Need jenkins to provide new solutions to check.

### CODE REVIEW

**Comment by alfbr** [comment]
jenkins build this update_data please

**Comment by akva2** [comment]
white-list updated.

**Comment by akva2** [comment]
jenkins build this update_data please

**Comment by bska** [comment]
jenkins build this opm-tests=294 please

**Comment by bska** [comment]
Updated reference solutions installed in master.  I'll merge this now to bring the source up-to-date too.

**Pull request merged**
