### PR TITLE
update scripts to use new paths for reference data

### PR DESCRIPTION
**Pull request by akva2**
reference data paths have been updated to reflect simulator data is for.

### CODE REVIEW

**Comment by akva2** [comment]
jenkins build this opm-data=198 please

**Comment by atgeirr** [comment]
I assume this is ready to be merged straightaway when/if green?

**Comment by akva2** [comment]
yes. but jenkins is busy today so will be a while before we know.

**Comment by joakim-hove** [comment]
> I assume this is ready to be merged straightaway when/if green?

Need to update opm-parser: https://github.com/OPM/opm-parser/blob/master/opm/parser/eclipse/IntegrationTests/CMakeLists.txt#L17

**Comment by akva2** [comment]
i don't see any usage of the reference files there, and i cannot even find the term 'opm-simulation-reference' in the opm-parser repo. please be more specific.

**Comment by joakim-hove** [comment]
> i don't see any usage of the reference files there, and i cannot even find the term 'opm-simulation-reference' in the opm-parser repo. please be more specific.

Sorry - multiple mistakes on my side.

**Comment by akva2** [comment]
nw

**Comment by akva2** [comment]
jenkins build this opm-data=198 please

**Comment by akva2** [comment]
all green.

**Pull request merged**
