### PR TITLE
Separate eclctransmissibility.hh into typetag dependent/independent code

### PR DESCRIPTION
**Pull request by akva2**
This allows using explicit template instantation to only compile this code (a few times) per grid instead of in each simulator object.

This sits on top of https://github.com/OPM/opm-simulators/pull/3219 which must be processed first.

### CODE REVIEW

**Comment by akva2** [comment]
jenkins build this please

**Comment by akva2** [comment]
rebased.

**Comment by akva2** [comment]
jenkins build this please

**Comment by blattms** [comment]
I have one question:
Why exactly do we need two classes `EclTransmissibility<TypeTag>` and EclGenericTransmissibility<GridType1,...>`?
Couldn't we do the same with one class by getting rid of the TypeTag and instead using either the list of types needed or the Type of the vanguard? As it is now `EclTransmissibility<TypeTag>` just has a constructor which might indicate that it is not needed. Where am I wrong?

**Comment by akva2** [comment]
You are not really wrong. I did not know up front that there would be nothing left after I was done splitting. I can definitely change that.

**Comment by akva2** [comment]
there u go.

**Comment by akva2** [comment]
jenkins build this please

**Comment by blattms** [comment]
Cool, thanks.

**Pull request merged**
