### PR TITLE
Simplify template params

### PR DESCRIPTION
**Pull request by akva2**
In the interest of DRY, we can use the Scalar from the FluidSystem.

### CODE REVIEW

**Comment by akva2** [comment]
jenkins build this please

**Comment by akva2** [comment]
jenkins build this please

**Comment by akva2** [comment]
jenkins build this please

**Comment by akva2** [comment]
jenkins build this please

**Review by blattms — APPROVED** [review]
Nice

**Comment by blattms** [comment]
jenkins build this please

**Comment by akva2** [comment]
green and approved. merging.

**Pull request merged**
