### PR TITLE
Removed python tests [WIP]

### PR DESCRIPTION
**Pull request by kristfho**
This PR removes the python tests. The tests are covered by [PR](https://github.com/OPM/opm-output/pull/70) in opm-output. 

The SPE1 test case have been changed from CASE1 to CASE2. #771 

 In addition a shell script running a regression test on Norne is to be uploaded.

### CODE REVIEW

**Comment by joakim-hove** [comment]
I just can not understand why it is so important to eridacate these Python based tests, they work - in my opinion the Python approach is a very simple and convenient way to create tests, and as far as I know they have created any trouble?

If they absolutely have to go for some reason, the correct way would anyway be to merge the alternative solution first, so that there is a short period of duplicated tests, and then remove the Python based approach. The current approach will temporary set us in a situation without tests at all - for no appearent reason.

**Comment by jokva** [comment]
I'm still not clear what new functionality we've got here, i.e. what cases can we now detect that we couldn't before? What do the new programs accomplish? Anyone care to write a short summary?

**Comment by atgeirr** [comment]
I'm with @joakim-hove here: this will not be merged at least until an alternative is merged and stable.

**Comment by alfbr** [comment]
Please make a separate pull request for removal of python tests.

**Comment by pgdr** [comment]
@kristfho Please prefix your PR titles with "WIP" (work in progress) if they are not yet ready to merge.

This is not yet ready to merge, since the PR you're depending on --- OPM/opm-output#70 --- isn't merged yet, and there is something to which "is to be uploaded".

**Comment by kristfho** [comment]
Firstly, to be clear, I meant this for to be merged when opm/opm-output#70 was merged. My mistake. 

> I just can not understand why it is so important to eradicate these Python based tests 

 Why was these Python tests made/modified a couple of weeks ago under the knowledge that there were already efforts to create c++ tests for this?

**Comment by joakim-hove** [comment]
Well - at the time the Python tests were the only alternative,  and that is indeed still the case. When       the  PR in opm-output is merged we might have a foundation to replace these tests - but the actual tests are still not in place in any PR?

I have no doubt that the C++ based solution can eventually be used to replace these Python tests, but my point is that I personally think an approach based on small custom Python scripts is better than the monolithic application based approach used in the C++ code - at least when a new feature is developed.

This is all about *testing* and not the final opm product, I therefor fail to understand why there is such a strong will to force all developers to write integration tests the same way - I mean some developers even like `vi`!

**Comment by jokva** [comment]
>  I mean some developers even like vi!

soul

**Comment by jokva** [comment]
It's still not clear to me what these new tests bring to the table that we weren't already able to test. Anyone care to enlighten me?

**Comment by joakim-hove** [comment]
Ok - I retract part of my statement, I now saw the restart test based on the SPE9 case, the INIT tests are still not reprodused though.

**Comment by alfbr** [comment]
I believe INIT testing is already included, you should find it in compareEcl binary. The only thing missing is RFT, which will need a test case first.

**Comment by joakim-hove** [comment]
Well a binary for testing INIT files is already in place OK, but as far as I am aware that has only been used for flow-flow comparisons, a flow-eclipse comparison is slightly more complex with respect to keywords to compare and precision - maybe it will work out of the box, maybe not.

**Comment by alfbr** [comment]
Not sure INIT testing makes much sense for flow-eclipse comparisons.

**Comment by joakim-hove** [comment]
> Not sure INIT testing makes much sense for flow-eclipse comparisons.

The INIT file is where the net effect of various modifiers - and in particular calculated quantities like `PORV` and `TRANX` is reported. So INIT testing makes sense to verify the initialization code - and since that code is distributed among several modules an integration test actually running flow is essential.

**Comment by alfbr** [comment]
Of course, and that is well catered for. Comparing flow to Eclipse does not necessarily make sense for those quantities. Comparing them to quality assured flow simulations may be the better approach. This was what I tried to say. Now I really need a vacation.

**Comment by akva2** [comment]
the tests have been removed.

**Pull request closed without merging**
