### PR TITLE
Group tests3

### PR DESCRIPTION
**Pull request by alfbr**
The 9_2B tests under model2 is hereby confirmed to give correct results. Let us put them under continuous testing.

### CODE REVIEW

**Comment by alfbr** [comment]
jenkins build this update_data please

**Comment by bska** [comment]
> jenkins build this update_data please

@akva2 : That didn't seem to take.  Is @alfbr still not on the whitelist?

**Comment by bska** [comment]
jenkins build this update_data please

**Comment by bska** [comment]
jenkins build this opm-tests=311 please

**Comment by bska** [comment]
Build check okay.  I'm merging this now to get this new set of regression tests into our portfolio.

**Pull request merged**
