### PR TITLE
Wellstate iget

### PR DESCRIPTION
**Pull request by joakim-hove**
Extracted part of #3255. Access the bhp / thp / temperature members through a C like api. I am not saying this is how it should eventually be, but need to encapsulate things a bit to be able to refactor reasonably safe.

### CODE REVIEW

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by joakim-hove** [comment]
benchmark please

**Comment by ytelses** [comment]
Benchmark result overview: 




| Test    | Configuration                                     | Relative |
| ------- | ------------------------------------------------- | -------- |
| opm-git | OPM Benchmark: flow_mpi_extra - Threads: 1        | 0.999    |
| opm-git | OPM Benchmark: flow_mpi_extra - Threads: 8        | 0.998    |
| opm-git | OPM Benchmark: flow_mpi_norne - Threads: 1        | 1.005    |
| opm-git | OPM Benchmark: flow_mpi_norne - Threads: 8        | 0.994    |
| opm-git | OPM Benchmark: flow_mpi_norne_4c_msw - Threads: 1 | 1.001    |
| opm-git | OPM Benchmark: flow_mpi_norne_4c_msw - Threads: 8 | 1.001    |
* Speed-up = Total time master / Total time pull request. Above 1.0 is an improvement. *



View result details @ https://www.ytelses.com/opm/?page=result&id=1202

**Comment by joakim-hove** [comment]
See: https://github.com/OPM/opm-simulators/pull/3277#issuecomment-843965916

The `WellState::update_bhp()` api is temporary, it is introduced to avoid giving out mutable references to the internals of the `WellState` class. My intention is that this will end up as a container of structs like:
```
struct SingleWellState {
     double bhp;
     double thp;
     ....
};
```
but that will not be tomorrow. Right now I am just buying room to refactor.

**Comment by joakim-hove** [comment]
I'll merge this later today - unless .....

**Pull request merged**
