### PR TITLE
Some more cleaning in the output code in opm-output, ewoms and opm-simulator

### PR DESCRIPTION
**Pull request by totto82**
1) Don't depend on legacy code for communicating the data::wells
2) Bugfix. Store globalIdx instead localIdx in data::wells::complitions
3) Move ThreadHandle to ebos

Depends on OPM/opm-output#250 and OPM/ewoms#284

Tested on norne and model2. Also in parallel.

### CODE REVIEW

**Comment by totto82** [comment]
jenkins build this ewoms=284 opm-output=250 please

**Comment by totto82** [comment]
jenkins build this ewoms=284 opm-output=250 please

**Comment by totto82** [comment]
jenkins build this ewoms=284 opm-output=250 please

**Comment by atgeirr** [comment]
Will test and eventually merge (when ewoms PR is mergeable).

**Comment by totto82** [comment]
jenkins build this ewoms=284 opm-output=250 please

**Comment by atgeirr** [comment]
Thanks, merging!

**Pull request merged**
