### PR TITLE
Testing only: PR4307 with current master and network in history

### PR DESCRIPTION
**Pull request by vkip**

### CODE REVIEW

**Comment by GitPaean** [comment]
hei, I am also refactoring most of the content from #4307 to https://github.com/OPM/opm-simulators/pull/4598 . 

https://github.com/OPM/opm-simulators/pull/4598 is ready for review. Not sure https://github.com/OPM/opm-simulators/pull/4598 can fulfill the purpose of this PR?

**Comment by vkip** [comment]
Hi, I noticed, and that is exactly what I'm going to check :) (The PR is just for convenience... this will never make it out of draft)

**Comment by GitPaean** [comment]
>  Hi, I noticed, and that is exactly what I'm going to check :) (The PR is just for convenience... this will never make it out of draft)

Sure. Let me know if you see something needs to be fixed.

**Comment by vkip** [comment]
All good, closing this.

**Pull request closed without merging**
