### PR TITLE
Add serializer support for set - closely modelled after map

### PR DESCRIPTION
**Pull request by joakim-hove**
Upstream: https://github.com/OPM/opm-common/pull/2712

### CODE REVIEW

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by joakim-hove** [comment]
jenkins build this opm-common=2712 please

**Comment by joakim-hove** [comment]
jenkins build this opm-common=2712 please

**Comment by joakim-hove** [comment]
jenkins build this opm-common=2712 please

**Comment by joakim-hove** [comment]
This is green from upstream: https://ci.opm-project.org/job/opm-common-PR-builder/4228/

**Comment by joakim-hove** [comment]
Comments to this?

**Comment by akva2** [comment]
seems fine. strictly speaking i think we could generalize vector to also handle sets but the slight duplication is probably worth the added code clarity.

**Pull request merged**
