### PR TITLE
split mpi function from newtoniterationutilities

### PR DESCRIPTION
**Pull request by akva2**
One more small attempt at doing my assigned task.......

### CODE REVIEW

**Comment by atgeirr** [comment]
jenkins build this please

**Comment by atgeirr** [comment]
Thanks, merging.

**Comment by bska** [comment]
How did this pass pre-commit build check when the post-commit check [failed](https://ci.opm-project.org/job/opm-simulators/611/consoleText) on Jenkins?

**Comment by akva2** [comment]
because post commit builds a configuration without mpi in addition.

**Comment by atgeirr** [comment]
Hopefully addressed in #1627.

**Pull request merged**
