### PR TITLE
Use GuideRate value instead of std::unique_ptr<GuideRate>

### PR DESCRIPTION
**Pull request by joakim-hove**
Small drive-by change while fighting with restart

### CODE REVIEW

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by bska** [comment]
Not all models have guide rates.

**Comment by joakim-hove** [comment]
> Not all models have guide rates.

That is obviously true, but current master did not utilize pointer semantics to differentiate between models with and without guide rates - so unless there is a plan to actually allow empty guide rate pointers in the well model I would say the the current PR is a (quite minor) simplification by removing the uneccessary pointer semantics.

**Comment by joakim-hove** [comment]
jenkins build this please

**Pull request merged**
