### PR TITLE
Added the remaining group tests that are correct.

### PR DESCRIPTION
**Pull request by alfbr**
I have now gone through all remaining data sets for model2. The remaining ones that are confirmed to run correctly are added as regression tests in this PR.

### CODE REVIEW

**Comment by alfbr** [comment]
jenkins build this update_data opm-tests=295 please

**Comment by alfbr** [comment]
Just occurred to me that I forgot to update the update script. Commit on its way!

**Comment by alfbr** [comment]
@akva2 or @bska , it would be great to get this in quickly. The group control code is in motion, so getting tests in place that prevents fall-outs is very valuable.

**Comment by akva2** [comment]
jenkins build this update_data opm-tests=295 please

**Comment by atgeirr** [comment]
jenkins build this opm-tests=296 please

**Comment by alfbr** [comment]
jenkins build this update_data please

**Comment by alfbr** [comment]
Now this one can finally be merged?

**Comment by bska** [comment]
> Now this one can finally be merged?

Yes.  Going in now along with OPM/opm-tests#303.  Thanks for your patience.

**Pull request merged**
