### PR TITLE
removing unused updateImbnum_ function

### PR DESCRIPTION
**Pull request by GitPaean**
found the function unused when looking at HYSTER related code.

### CODE REVIEW

**Comment by GitPaean** [comment]
jenkins build this please

**Review by bska — COMMENTED** [review]
For what it's worth, the function was introduced in #4384 and looks intentional.  Maybe @hakonhagland would like to have a word before we remove this.

**Comment by hakonhagland** [comment]
@bska I will have a look at this later today. I do not remember exactly, but I think the intention was that there should be a call to  `this->updateImbnum_()`  in `readMaterialParameters_()` in `FlowProblem.hpp` see: 

https://github.com/OPM/opm-simulators/blob/66aacb5042b0de5b9af96cef17cf93abcec36663/opm/simulators/flow/FlowProblem.hpp#L2045

**Comment by hakonhagland** [comment]
I checked this again, and it seems we can also remove the `updateKrnum_()` ? Instead of storing the vectors `KRNUM` and `IMBNUM` in class `FlowGenericProblem`, we are storing them in class `EclMaterialManager`, see

https://github.com/OPM/opm-common/blob/9e942d2d2c1c5056da3aaec30e2f699c17c67fb1/opm/material/fluidmatrixinteractions/EclMaterialLawManager.hpp#L456

**Comment by GitPaean** [comment]
> I checked this again, and it seems we can also remove the `updateKrnum_()` ? Instead of storing the vectors `KRNUM` and `IMBNUM` in class `FlowGenericProblem`, we are storing them in class `EclMaterialManager`, see
> 
> https://github.com/OPM/opm-common/blob/9e942d2d2c1c5056da3aaec30e2f699c17c67fb1/opm/material/fluidmatrixinteractions/EclMaterialLawManager.hpp#L456
> 
> so the vectors in class `FlowGenericProblem` seems to be unused.

Thanks @hakonhagland . Let me update the PR and let it run through the tests.

**Comment by GitPaean** [comment]
jenkins build this please

**Comment by GitPaean** [comment]
jenkins build this please

**Comment by GitPaean** [comment]
It looks like mostly fine. @bska can you have a look?

**Review by bska — APPROVED** [review]
Yep, this is good.  I'll merge into master.

**Pull request merged**
