### PR TITLE
Intended to update WSEGSICD test

### PR DESCRIPTION
**Pull request by alfbr**
Just a trivial code change intended to make the WSEGSICD test updated.

### CODE REVIEW

**Comment by alfbr** [comment]
@bska just created this one with the sole purpose of getting https://github.com/OPM/opm-tests/pull/293 in.

**Comment by alfbr** [comment]
jenkins build this update_data opm-tests=293 please

**Comment by alfbr** [comment]
I assume merging opm-tests=293 and opm-tests=304 will keep jenkins green.

**Comment by bska** [comment]
> just created this one with the sole purpose of getting OPM/opm-tests#293 in.

Very good.  I'll merge this, OPM/opm-tests#293, and the associate data update in OPM/opm-tests#304 to finally settle the long-running issue.  Thanks a lot for your persistence!

> I assume merging opm-tests=293 and opm-tests=304 will keep jenkins green.

I agree.

**Comment by alfbr** [comment]
Thank you!

**Pull request merged**
