### PR TITLE
Use 1 day as default initial time step

### PR DESCRIPTION
**Pull request by totto82**
This PR effects results and convergence on most of the cases. I have verified that it doesn't introduce any big problems on any of the big models. Since the timestepping is changed most test should fail.

### CODE REVIEW

**Comment by alfbr** [comment]
How does it affect performance?

**Comment by atgeirr** [comment]
jenkins build this please

**Comment by atgeirr** [comment]
As expected, it failed all the regression tests but no others. I think we should do this unless it is too much of a performance pessimization.

**Comment by atgeirr** [comment]
jenkins build this update_data please

**Comment by totto82** [comment]
> How does it affect performance?

Little on most cases I have tested. (SPEs, norne and model2 rel0) 
For some strange reasons both performance and results are affected on model 2 rel5. Luckily it is in the positive direction. My experience with rel 5 is that it is very unstable to small changes.

**Comment by atgeirr** [comment]
jenkins build this opm-data=280 please

**Comment by atgeirr** [comment]
@totto82 this is ready to be merged. Just tell me if you want to check the regression test changes first.

**Comment by totto82** [comment]
@atgeirr Did you forget to merge opm-data=280?

**Comment by atgeirr** [comment]
Yes I did, and then I went to a meeting...

**Pull request merged**
