### PR TITLE
Add float blackoil simulator

### PR DESCRIPTION
**Pull request by akva2**
Sits on top of https://github.com/OPM/opm-simulators/pull/5556

### CODE REVIEW

**Comment by akva2** [comment]
jenkins build this opm-models=896 please

**Comment by akva2** [comment]
jenkins build this update_data please

**Comment by akva2** [comment]
jenkins build this opm-tests=1222 serial please

**Comment by akva2** [comment]
can this be merged?

**Review by bska — APPROVED** [review]
Okay, let's enable this to make sure that we have regression test support for the `float` variant going forward.

**Comment by akva2** [comment]
There is a data update

**Comment by bska** [comment]
> There is a data update

:angry:

**Pull request merged**
