### PR TITLE
eclwriter: split in typetag dependent and typetag-independent parts

### PR DESCRIPTION
**Pull request by akva2**
Sits on top of https://github.com/OPM/opm-simulators/pull/3263
Sits on top of https://github.com/OPM/opm-simulators/pull/3262

### CODE REVIEW

**Comment by akva2** [comment]
jenkins build this please

**Comment by akva2** [comment]
jenkins build this please

**Comment by akva2** [comment]
jenkins build this please

**Comment by akva2** [comment]
jenkins build this please

**Review by bska — APPROVED** [review]
Thanks. I'll merge this into master.

**Pull request merged**
