### PR TITLE
[bugfix] Always broadcast NNCs from input.

### PR DESCRIPTION
**Pull request by blattms**
This was only done if there were NNCs from aquifers, but it should always be done whenever there are NNCs.

Those NNCs also hold information of (additional) transmissibilities for a grid intersection. While the intersection is already represented by the grid, the transmissibility is not. This PR fixes this and makes the NNcs available on all processes.

If I missed where we broadcast NNCs, then please tell me.

### CODE REVIEW

**Comment by blattms** [comment]
jenkins build this please

**Comment by blattms** [comment]
We must be doing this somewhere else already. Just need to find it.

**Comment by akva2** [comment]
These are already broadcast during the EclipseState broadcast, ie, https://github.com/OPM/opm-common/blob/master/opm/input/eclipse/EclipseState/EclipseState.hpp#L151

**Comment by blattms** [comment]
And that seems to happen in readDeck.cpp, which is really early. Why might just want to move that to a later stage. It seem that we don't need it before we have a distributed grid.

**Comment by atgeirr** [comment]
A somewhat common way to do arbitrary non-cornerpoint grids in OPM Flow is to make a disjointed grid with all cells in a row, then adding every connection as an explicit NNC. Will this work make that scale worse in parallel than before?

**Pull request closed without merging**
