### PR TITLE
Remove fpgaSolver

### PR DESCRIPTION
**Pull request by Tongdongq**
The `fpgaSolver` was already broken since May 2022. This PR removes the support completely.
Also some cleanup with other unused code, add `cusparseSolver` with jacobi-ilu test.
And combines the variables `HAVE_CUDA`, `HAVE_OPENCL`, `HAVE_AMGCL` and `HAVE_ROCALUTION` into `COMPILE_BDA_BRIDGE` for easier addition of future libraries like rocsparse.

More info on fpgaSolver:
https://wiki.opm-project.org/index.php?title=FPGA_setup_and_building

### CODE REVIEW

**Comment by atgeirr** [comment]
> And combines the variables `HAVE_CUDA`, `HAVE_OPENCL`, `HAVE_AMGCL` and `HAVE_ROCALUTION` into `COMPILE_BDA_BRIDGE` for easier addition of future libraries like rocsparse

Would this not make it harder to add other code using Cuda or OpenCL etc.?

**Comment by Tongdongq** [comment]
My initial reason for this change was that there were a lot of `HAVE_CUDA | HAVE_OPENCL | ...` macros, adding the `rocalutionSolver` or removing `fpgaSolver` meant all of these needed to be updated. Some code is required if any of these are true, like `BdaBridge.cpp`.

The `HAVE_XXX` variables are still used in various cuda-specific or opencl-specific places. New backend-dependant code could still use these.

**Comment by atgeirr** [comment]
> The `HAVE_XXX` variables are still used in various cuda-specific or opencl-specific places. New backend-dependant code could still use these.

Thanks for the clarification, then I am not against the change.

**Comment by blattms** [comment]
jenkins build this serial please

**Comment by blattms** [comment]
Needs a rebase now. :flushed: I am awfully sorry, @Tongdongq for merging the other PR first and producing the conflicts.

**Review by blattms — APPROVED** [review]
I have tested this locally and after a successful jenkins rerun this can go in.

**Comment by akva2** [comment]
jenkins build this please

**Pull request merged**
