### PR TITLE
Move parameters to typetag free parameter system: Last batch

### PR DESCRIPTION
**Pull request by akva2**
This is the final batch completing moving parameters to the typetag free system.

I'm marking this draft as it will create havoc for #5157, I'll handle the rebasing after that one has been merged.

### CODE REVIEW

**Comment by akva2** [comment]
jenkins build this please

**Comment by bska** [comment]
> This is the final batch completing moving parameters to the typetag free system.

Is there no companion PR in any upstream repositories?

**Comment by bska** [comment]
> indeed, no companion.

Okay understood.

> there will be a cleanup PR afterwards removing the old system as well as one moving some more code to cpp files.

Very good.  I look forward to seeing this work becoming fully finalised.

**Comment by akva2** [comment]
jenkins build this please

**Review by bska — APPROVED** [review]
I didn't verify that every single parameter default value was fully transferred to the new system, but the successful regression test suggests that it was.  This looks good to me and I'll merge into master.

**Pull request merged**
