### PR TITLE
Sphinx gha

### PR DESCRIPTION
**Pull request by lisajulia**

### CODE REVIEW

**Comment by lisajulia** [comment]
jenkins build this pleasae

**Review by atgeirr — APPROVED** [review]

**Comment by lisajulia** [comment]
Same as https://github.com/OPM/opm-simulators/pull/5349, just from this repository and not from my fork, because from my fork, the action "Build Python Sphinx Docs and push to gh-pages / build (pull_request) " does not pass.
Also, I added the commit:
https://github.com/OPM/opm-simulators/pull/5470/commits/61958cb137ae683174641663777c298351fb4db9
This commit force selects the master branch to build the documentation.

Before anyone merges this, we have to make sure tough that the action "Build Python Sphinx Docs and push to gh-pages / build (pull_request) " which is now green here, will not interfere with other, future PRs from other forks.

**Comment by lisajulia** [comment]
jenkins build this please

**Comment by lisajulia** [comment]
This was a test, closing since we have #5349.

**Pull request closed without merging**
