### PR TITLE
fixed: make python simulator object depend on copy_python

### PR DESCRIPTION
**Pull request by akva2**
if not, building just the python binding won't end up in a complete build

### CODE REVIEW

**Comment by akva2** [comment]
jenkins build this please

**Comment by bska** [comment]
> if not building just the python binding won't end up in a complete build

Sorry, I'm having a little bit of difficulty parsing that sentence.  Would you mind expanding a little on what situation you're addressing.

**Comment by akva2** [comment]
while packaging the python bindings i only want to build the python objects. so i do ```ninja simulators```. problem is this does not copy the necessary python files into the build directory. now it does.

**Review by bska — COMMENTED** [review]
> when packaging the python bindings i only want to build the python object. so i do `ninja simulators`. problem is this does not copy the necessary python files (in particular the `__init__.py` file) into the build directory. now it does.

Ah, okay&ndash;thanks.  Then I understand what you're trying to do.  Very good.  I'll merge into master.

**Pull request merged**
