### PR TITLE
changed: use ilu0 for alugrid test

### PR DESCRIPTION
**Pull request by akva2**
Trying to see if this resolves the serial-differ-from-parallel fallout from the new defaults.

### CODE REVIEW

**Comment by akva2** [comment]
jenkins build this update_data please

**Comment by akva2** [comment]
jenkins build this.opm-tests=1210 serial please

**Comment by akva2** [comment]
so no, this did not help.

**Comment by bska** [comment]
> so no, this did not help.

Yeah, that's a pity.  One other potential test would be to restore **all** of the default parameters from #5157 to their original states, i.e.,
```sh
--linear-solver=ilu0 --tolerance-mb=1.0e-6 --min-strict-cnv-iter=0 \
--local-well-solve-control-switching=false --use-implicit-ipr=false \
--enable-drift-compensation=true
```
If that does not help, then we may have to disable the ALUGrid test.

**Pull request closed without merging**
