### PR TITLE
Fix/actionx compdat show error

### PR DESCRIPTION
**Pull request by lisajulia**

### CODE REVIEW

**Comment by lisajulia** [comment]
jenkins build this opm-tests=1199 please

**Comment by blattms** [comment]
Nice, thanks.

On of the few occasions where a failing test is something good :sweat_smile:

**Comment by blattms** [comment]
Last jenkins build used master and fails with
```
Exception received: Cannot find input case '/var/lib/jenkins/post-builder/workspace/opm-simulators-PR-builder/deps/opm-tests/actionx/COMPDAT_SHORT'. Try '--help' for a usage description.
```

Let's try with the OPM/opm-tests#1199

**Comment by lisajulia** [comment]
> jenkins build this opm-tests=1199 please

ah yes, thanks!

**Comment by lisajulia** [comment]
jenkins build this opm-tests=1199 please

**Comment by lisajulia** [comment]
jenkins build this please

**Comment by lisajulia** [comment]
jenkins build this opm-tests=1200 please

**Comment by blattms** [comment]
It seems like it fails correctly now.

**Comment by lisajulia** [comment]
> It seems like it fails correctly now.

Yes, I don't really know where this timeout came from .. I ran the previous test file with a bit older version of flow (possibly from last week) and it was also failing because of the correct reason, yet today I ran that with a freshly compiled version and the program was also frozen at the same reportstep as on Jenkins.
I have opened an issue for this: https://github.com/OPM/opm-simulators/issues/5494

**Comment by lisajulia** [comment]
Closing this since https://github.com/OPM/opm-simulators/pull/5488 has been merged

**Pull request closed without merging**
