### PR TITLE
Remove dead code.

### PR DESCRIPTION
**Pull request by blattms**
the second commit fixes a bug that has been there for some time and only surfaced if there was no UMFPack found. The rest removes dead code that appeared due the ISTLSolver.hpp for ebos (command line parameter system

Superseeds #1579 and #1580.

### CODE REVIEW

**Comment by blattms** [comment]
Closes #1574

**Comment by blattms** [comment]
Because most of the dead code is due to 976ab03

**Comment by andlaus** [comment]
that patch did not change any of the code, though; It just happens that all users of this defected to `ISTLSolverEbos`? if so, `ISTLSolverEbos` should also have a few dead methods, i.e., most of those which are not dead in `ISTLSolver`? It would IMO be beneficial to remove them as well.

**Comment by blattms** [comment]
Well, some of the methods in ISTLSolver.hpp were only used by flow_legacy and some only by flow_ebos. At that time there was at least less dead code. But with ISTLSolverEbos.hpp being nearly an identical copy of ISTLSolver.hpp we suddenly had dead code in both (unused ebos/legacy functionality).

If you look closely you will see that this PR removes dead code in both.

**Comment by andlaus** [comment]
ah, okay. Thanks.

@atgeirr: can this PR be merged please? the build error is really annoying for me.

**Comment by atgeirr** [comment]
> @atgeirr: can this PR be merged please? the build error is really annoying for me.

OK. There are some typos in the exception string, but since it should never be triggered I won't hold it back.

**Pull request merged**
