### PR TITLE
Use consisten pvt region index for groups in parallel.

### LINKED ISSUE #2921: pvt region index in BlackoilWellModel::checkGroupHigherConstraints inconsistent in parallel run.
In parallel this is much worse. Not only might the pvt region computed have no association to the wells of the group, but may also be different from process to process as there might be no local wells and if there are the first one might not be the same well
[BlackoilWellModel_impl.hpp#L2390](https://github.com/OPM/opm-simulators/blob/0dcfc6036339f1b9fa10100db21666acea4d37d4/opm/simulators/wells/BlackoilWellModel_impl.hpp#L2390) 

~There is a very problematic data access at [BlackoilWellModel_impl.hpp#L2390](https://github.com/OPM/opm-simulators/blob/0dcfc6036339f1b9fa10100db21666acea4d37d4/opm/simulators/wells/BlackoilWellModel_impl.hpp#L2390) where we do
`pvt_region_idx_[well_perf_data_[0][0].cell_index]`. The problem is that well_perf_data has an entry for each global well, but if the
well at index 0 is not in this process's then `well_perf_data_[0]` is an empty vector.~

I would fix this, but it is very misty what the original code is trying to do. At least it is not clear to me, why anyone would query a well without even testing if that well belongs to the group we are computing for.

This really stalls me and I need help.

### PR DESCRIPTION
**Pull request by blattms**
In serial we use the first cell of the first well to determine the pvt region index for a group. Previously, we used the first cell of
the first local well in a parallel run. Unfortunately that may lead to different pvt region indices being used for the same goup on
different processes.

We fix this by using the same approach in parallel as we already use in serial. For this we usedWell::seqIndex() to determine the needed ordering.

Closes #2921 (at least the reported parallel inconsistency, not whether the index used makes sense).

### CODE REVIEW

**Comment by blattms** [comment]
jenkins build this please

**Comment by blattms** [comment]
Would be cool if this was merged soon.

**Comment by blattms** [comment]
jenkins build this please

**Review by atgeirr — APPROVED** [review]
Looks fine, can be merged when green.

**Comment by blattms** [comment]
In it goes.

**Pull request merged**
