### PR TITLE
Move action handling from eclproblem to separate class

### PR DESCRIPTION
**Pull request by akva2**
Continuing https://github.com/OPM/opm-simulators/pull/3996 as github got confused by me accidentially pushing the wrong branch into the PR branch.

### CODE REVIEW

**Comment by akva2** [comment]
jenkins build this please

**Comment by akva2** [comment]
jenkins build this please

**Review by bska — APPROVED** [review]
Thanks for the updates.  I'll merge into master.

**Comment by atgeirr** [comment]
We should celebrate every 1000'th issue...!

**Pull request merged**
