### PR TITLE
1: Pack and unpack WellTestState in CollectIO class

### PR DESCRIPTION
**Pull request by joakim-hove**
Collect WellTestState on IO rank for restart output.

Upstream: https://github.com/OPM/opm-common/pull/2724

### CODE REVIEW

**Comment by joakim-hove** [comment]
OK - I need some typetag first aid here: Deep down the test `test_ecl_output` calls `CollectToIORank::collect()` - that function calls `WellManager<TypeTag>::wellTestState()`. The `test_ecl_output` is configured (by magic ...???) to use the ebos class `EclWellManager` - and there the `wellTestState()`methods look like:
```
WellTestState& wellTestState() {
        throw std::logic_error("wellTestState() method not implemented for class eclwellmanager");
}
```
and all in all the `test_ecl_output` test fails hard. I guess the good/correct solution would be to use the `BlackoilWellModel` instead of `EclWellManager` in the offending test?

**Comment by bska** [comment]
> I need some typetag first aid here

I take it you've already run the test in a debugger locally with something along the lines of `catch throw` to identify the call site?

**Comment by joakim-hove** [comment]
> I take it you've already run the test in a debugger locally with something along the lines of catch throw to identify the call site?

Ehhh - I had not thought of that; and I will try it - but my understanding of the problem is more how to control which wellmodel is instantiated. When it is run with the wrong wellmodel - i.e. `EclWellManager` in this case - the call to `CollectToIORank::collect()` in `eclwriter`*will fail*. Anyway - backtrace goes like this:
```
#0  0x00007ffff2aa5afd in __cxa_throw () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#1  0x00005555558cd2bc in Opm::EclWellManager<Opm::Properties::TTag::TestEclOutputTypeTag>::wellTestState (this=0x555556c64e50)
    at /home/hove/work/OPM/opm-simulators/ebos/eclwellmanager.hh:650
#2  0x00005555558c0418 in Opm::EclWriter<Opm::Properties::TTag::TestEclOutputTypeTag>::evalSummaryState (this=0x555556bc0ef0, isSubStep=false)
    at /home/hove/work/OPM/opm-simulators/ebos/eclwriter.hh:185
#3  0x000055555587d26c in Summary::test_method (this=0x7fffffffc30f) at /home/hove/work/OPM/opm-simulators/tests/test_ecl_output.cc:179
#4  0x000055555587cd72 in Summary_invoker () at /home/hove/work/OPM/opm-simulators/tests/test_ecl_output.cc:151

```

**Comment by bska** [comment]
> When it is run with the wrong wellmodel - i.e. `EclWellManager` in this case - the call to `CollectToIORank::collect()` in `eclwriter` _will fail_.

Okay&mdash;just one more question.  Do you need to meet a semantic requirement that `EclWellManager::wellTestState()` return a reference to an existing object or is it merely syntactical?  In other words, would defining the function as below meet the call-site requirements?
```C++
WellTestState EclWellManager::wellTestState()
{
    return {};
}
```

**Comment by joakim-hove** [comment]
>  In other words, would defining the function as below meet the call-site requirements?

```
WellTestState EclWellManager::wellTestState()
{
    return {};
}
```
That would solve my immediate problem - and I might end up there - but it would introduce a silent failure in `EclWellManager`

**Comment by joakim-hove** [comment]
jenkins build this opm-common=2724 please

**Comment by joakim-hove** [comment]
jenkins build this opm-common=2724 please

**Comment by joakim-hove** [comment]
jenkins build this opm-common=2724 please

**Comment by joakim-hove** [comment]
I am working on restart support for the WTEST functionality - surprisingly it seems the greatest challenge has been to hook the `WellTestState` instance up to the IO framework. This PR is the first of two series with that target.

The second commit in this PR disables parts of the test `test_ecl_output`. To summarize the problem with the `test_ecl_output` test goes as follows:

1. With this PR a `WellTestState`member is added to the `CollectToIORank` class - and as part of the `::collect()` method the method `<WellModel>::wellTestState()` is called.
2. The method `<WellModel>::wellTestState()` is only implemented for `WellModel == BlackOilModel` which is the well model used by `flow` (and all other simulators?). For the model `EclWellModel` the method `wellTestSate()` is only a shim which throws an exception. 
3. The test in `test_ecl_output` instantiates a `EclWellModel` instance and during the test execution the shim which throws is invoked and the whole test fails.

I have made some half hearted attempts getting the test to instantiate and use `BlackoilWellModel` instead of `EclWellModel, but it fails with error messages from the language Ebos++ - quite frankly I am not all that interested in learning Ebos++ and would prefer to stick with C++. I am all for unit tests, but this particular test mainly tests our ability to create correct summary output - we have quite good test coverage on that already; both explicitly in opm-common and in the form of regression tests in opm-simulators.

I will let this linger for a not-very-long time and then I'll merge it.

**Comment by blattms** [comment]
I am probably missing something, but can't you catch the exception and send a dummy pack a dummy test state in that case? And throw at the unpacking site to?

As the well manager type is known at compile time one could omit the methods for the ecl manger and check for their existence at compile time.

Seems like pure C++ to me, but I could be wrong of course.

**Comment by joakim-hove** [comment]
> but can't you catch the exception and send a dummy pack a dummy test state in that case? 

Yes - that is correct; I can remove the exception entirely and return a dummy `WellTestState` from the `EclWellManager` class, but then the `EclWellmanager` returns invalid data - akin to a silent failure in my opinion. But for me that is of course the simplest way out of this - although I am reluctant to give the `EclWellManager` class "a scent of maintained" this way.

**Pull request merged**
