### PR TITLE
add changes to fix the order

### PR DESCRIPTION
**Pull request by ElyesAhmed**
This PR enables SFC (Space-Filling Curve) reordering in AluGrid as the default choice. The changes has been tested both with and without MPI across multiple cases from the opm-tests and opm-data!

### CODE REVIEW

**Comment by akva2** [comment]
Note that flipping these defines in opm code does nothing. You are entirely at the mercy of however dune-alugrid itself was built as the defines are not in headers but in compile units.

**Comment by akva2** [comment]
No there is no indication of this. It's just an #ifdef in its gridfactory.cc that exits early. What makes it even more fun is that gridfactory.cc *can* be built inline (ie the .cc file is included in the .hh file) if you build dune-alugrid with COMPILE_ALUGRID_INLINE define. But you can't just set this for a library that was built without it as you'd get duplicate symbols. So as I said, at the mercy of how the library is built.

**Comment by atgeirr** [comment]
jenkins build this serial please

**Comment by atgeirr** [comment]
jenkins build this serial failure_report please

**Comment by ElyesAhmed** [comment]
can we try again!

**Comment by akva2** [comment]
jenkins build this serial failure_report please

**Comment by akva2** [comment]
jenkins build this serial opm-tests=1234 please

**Comment by atgeirr** [comment]
jenkins build this serial failure_report update_data please

**Comment by atgeirr** [comment]
jenkins build this serial opm-tests=1234 please

**Comment by atgeirr** [comment]
Data update merged, will merge this once the data update Jenkins job has started.

**Comment by bska** [comment]
> will merge this once the data update Jenkins job has started.

The new reference solutions were installed 30 minutes ago.  Did you accidentally forget to merge this?

**Comment by atgeirr** [comment]
> Did you accidentally forget to merge this?

Yes, had to go to a meeting, sorry!

**Comment by blattms** [comment]
Just a note. According to my failed tests (because of missing rebase). The changes to the well solutions are quite large: https://ci.opm-project.org/job/opm-common-PR-builder/7522/testReport/(root)/mpi/compareECLFiles_flow_blackoil_alugrid_SPE1CASE2/

**Comment by atgeirr** [comment]
> The changes to the well solutions are quite large:

We are aware of this, it is because the previous solution was wrong. The bugfixes in this PR apparently had a big influence.

**Comment by blattms** [comment]
Well, our code should not rely on internal ordering. If it does then we are doomed (not only for ALUGrid...).

Maybe somebody could describe what this is supposed to fix.

**Pull request merged**
