### PR TITLE
Rename SpiralICD -> ICD

### PR DESCRIPTION
**Pull request by joakim-hove**
Downstream of: https://github.com/OPM/opm-common/pull/1798

### CODE REVIEW

**Comment by GitPaean** [comment]
Hi, how about at least SICD, because there are other ICDs.

**Comment by GitPaean** [comment]
At `ICD.hpp` might have problems with `icd.hpp` in some operating systems, although we do not support them yet.

**Comment by joakim-hove** [comment]
> Hi, how about at least SICD, because there are other ICDs.

Well - the point was that the current `SpiralICD` class seems to be a suitable "base class" for ICD's; see:  OPM/opm-common#1798 - I might be wrong though.

**Comment by joakim-hove** [comment]
> At ICD.hpp might have problems with icd.hpp in some operating systems, although we do not support them yet.

I agree - I will fix that.

**Comment by atgeirr** [comment]
If the "ICD" class is to be (sort of or actually) a base class for ICDs, we could consider giving it the full name "InflowControlDevice", using the ICD abbreviation in the names of subclasses.

**Comment by joakim-hove** [comment]
> we could consider giving it the full name "InflowControlDevice", using the ICD abbreviation in the names of subclasses.

Ohhh man - that is long; I'll start with ICD; and then we will see.

**Comment by joakim-hove** [comment]
Closing to tickle jenkins

**Pull request merged**
