### PR TITLE
fixed: do not try to hide parameters that are not registered without MPI

### PR DESCRIPTION
**Pull request by akva2**
Whoopsie..

### CODE REVIEW

**Comment by akva2** [comment]
jenkins build this serial please

**Review by bska — APPROVED** [review]
Very good&ndash;I was about to submit something similar.  Please merge when green.

**Comment by bska** [comment]
> the test failure is caused by the new defaults PR, not the parameter stuff

Agreed.  We noticed this in [post-commit build](https://ci.opm-project.org/job/opm-simulators/2305/testReport/) of #5157.  For whatever reason, the [ALUGrid regression test](https://github.com/OPM/opm-simulators/blob/bee91d2fdd5586505eceb54f525ec8f905b1c483/regressionTests.cmake#L1493-L1498) appears to give different results when configured as a sequential build compared to a parallel build.

**Comment by bska** [comment]
> For whatever reason, the [ALUGrid regression test](https://github.com/OPM/opm-simulators/blob/bee91d2fdd5586505eceb54f525ec8f905b1c483/regressionTests.cmake#L1493-L1498) appears to give different results when configured as a sequential build compared to a parallel build.

One potential fix might be to go back to using `--linear-solver=ilu0` for this particular test.

**Comment by akva2** [comment]
have you confirmed that fixes it? if so that seems like a acceptable solution.

**Comment by bska** [comment]
> have you confirmed that fixes it?

I have not because I don't currently have a build which includes ALUGrid...

**Comment by akva2** [comment]
there is an approval so i'll merge this to simplify further investigation.

**Pull request merged**
