### PR TITLE
Fix network convergence issues

### PR DESCRIPTION
**Pull request by steink**
During testing, two culprits for network convergence problems were identified:

1. The current lower bound on network pressure update may lead to convergence issues, so it's suggested simply to remove this.
2. The default (standard) well convergence tolerance is in some cases not sufficiently strict to get network convergence. This PR suggest a rather _ad-hoc_  solution by simply tightening the tolerance by a factor 10 for wells that are controlled under dynamic thp-limit.

### CODE REVIEW

**Comment by GitPaean** [comment]
jenkins build this please

**Comment by GitPaean** [comment]
jenkins build this please

**Comment by steink** [comment]
The four failures here seem fine (on the order of tolerances).

**Comment by GitPaean** [comment]
> The four failures here seem fine (on the order of tolerances).

okay. I think it is a github refreshing issue. I thought there was no testing triggered, so I make another one.

**Comment by GitPaean** [comment]
> The default (standard) well convergence tolerance is in some cases not sufficiently strict to get network convergence. This PR suggest a rather ad-hoc solution by simply tightening the tolerance by a factor 10 for wells that are controlled under dynamic thp-limit.

We probably will revisit this later.  Tightening the default well tolerance will probably have some performance impact. The current solution fixes a practical issue and also provides insight for the future development along this line.

**Review by GitPaean — APPROVED** [review]
It looks fine to me. I am preparing to get it in now.

**Comment by akva2** [comment]
jenkins build this update_data please

**Comment by GitPaean** [comment]
jenkins build this opm-tests=1124 please

**Comment by GitPaean** [comment]
The reference is updated. This PR is going in now.

**Pull request merged**
