### PR TITLE
Avoid some dead stores

### PR DESCRIPTION
**Pull request by akva2**
As flagged by static analyzers.

### CODE REVIEW

**Comment by akva2** [comment]
jenkins build this please

**Comment by blattms** [comment]
About the dead stores in ddd0c5629dd50a69b2230f86943246be8b21c7ee : To me it seems like all stores in result in that function are dead, not only those two. Actually the local variable result could even be removed. It does not seem to be read anywhere.

What am I missing?

**Comment by akva2** [comment]
It is returned from the function below.

**Comment by blattms** [comment]
I see. Sorry missed that.

**Pull request merged**
