### PR TITLE
GasLiftSingleWell: split typetag independent code to separate class 

### PR DESCRIPTION
**Pull request by akva2**
Sits on top of https://github.com/OPM/opm-simulators/pull/3284

### CODE REVIEW

**Comment by totto82** [comment]
@akva2 The gaslift code is still under development. I would appreciate if we can hold merging this until we finish the development.

**Comment by akva2** [comment]
i can wait but that is rather backwards. It is precisely during development you want to avoid all the full rebuilds..

**Comment by totto82** [comment]
Good point. I thought the PR was in its making, and wanted to avoid yet another rebase. But we found some remaining  issues that needs to be addressed first so maybe it make sense to merge this first.  What do you think @hakonhagland?

**Comment by hakonhagland** [comment]
> It is precisely during development you want to avoid all the full rebuilds..

@akva2 I am not sure exactly what this means? What is the problem with the current code using the type tag? Is this PR making the compilation faster or is it something else? Thanks.

**Comment by akva2** [comment]
by putting the code in a separate compile unit, when you change the code, only that cpp file is rebuilt, not the entire simulator.

**Comment by hakonhagland** [comment]
> What do you think hakonhagland?

@totto82 and @akva2 Maybe we can merge this into master, and after that I rebase our current work on this?

**Comment by totto82** [comment]
jenkins build this please

**Comment by totto82** [comment]
Lets merge this when its green.

**Comment by bska** [comment]
> Let's merge this when its green.

It's green now.  I'll merge into master.

**Pull request merged**
