### PR TITLE
Unsupported Keywords BCAD

### PR DESCRIPTION
**Pull request by goncalvesmachadoc**

### CODE REVIEW

**Comment by OPMUSER** [comment]
Cinta,

BCAD is not an E100/E300 keyword, if this is an OPM Flow keyword then 
may it should be in the 900 OPM directory instead.

OPM User

**Comment by goncalvesmachadoc** [comment]
Hi David, that's an Eclipse 100 keyword to output the polymer adsorption block concentration.

**Comment by OPMUSER** [comment]
Cinta,
Then it does not go in the UnsupportedKeyword list, SUMMARY variables are treated differently. I think if they are not defined in 

`../opm-common/src/opm/parser/eclipse/EclipseState/SummaryConfig/SummaryConfig.cpp` 

then they are automatically ignored - but @joakim-hove is Dr Parser on these topics.

**Comment by goncalvesmachadoc** [comment]
This keyword is not currently ignored:
image
Will add to the parser list then. Thank you.

**Pull request closed without merging**
