### PR TITLE
make the build of flow fully parallelizable

### PR DESCRIPTION
**Pull request by andlaus**
this is the continuation of #1578 with installation hopefully being fixed.

so far, the actual instances of the simulators were compiled into the `libopmsimulators` library and the build the glue code (`flow.cpp`) thus needed to be deferred until the library was fully build. Since the compilation of the glue code requires a full property hierarchy for handling command line parameters, this significantly increases the build time for systems with a sufficient number of parallel build processes. ("sufficient" here means 8 or more threads, i.e., a quadcore system with hyperthreading is sufficient provided that it has enough main memory.)

the new approach is not to include these objects in `libopmsimulators`, but to directly deal with them in the `flow` binary. this allows all of them and the glue code to be compiled in parallel.

compilation time on my machine before this change:

```
> touch ../opm/autodiff/BlackoilModelEbos.hpp; time make -j32 flow 2> /dev/null
Scanning dependencies of target opmsimulators
[  2%] Building CXX object CMakeFiles/opmsimulators.dir/opm/simulators/flow_ebos_gasoil.cpp.o
[  2%] Building CXX object CMakeFiles/opmsimulators.dir/opm/simulators/flow_ebos_oilwater.cpp.o
[  2%] Building CXX object CMakeFiles/opmsimulators.dir/opm/simulators/flow_ebos_blackoil.cpp.o
[  2%] Building CXX object CMakeFiles/opmsimulators.dir/opm/simulators/flow_ebos_solvent.cpp.o
[  4%] Building CXX object CMakeFiles/opmsimulators.dir/opm/simulators/flow_ebos_polymer.cpp.o
[  6%] Building CXX object CMakeFiles/opmsimulators.dir/opm/simulators/flow_ebos_energy.cpp.o
[  6%] Building CXX object CMakeFiles/opmsimulators.dir/opm/simulators/flow_ebos_oilwater_polymer.cpp.o
[  6%] Linking CXX static library lib/libopmsimulators.a
[ 97%] Built target opmsimulators
Scanning dependencies of target flow
[100%] Building CXX object CMakeFiles/flow.dir/examples/flow.cpp.o
[100%] Linking CXX executable bin/flow
[100%] Built target flow

real    1m45.692s
user    8m47.195s
sys     0m11.533s
```

after:

```
> touch ../opm/autodiff/BlackoilModelEbos.hpp; time make -j32 flow 2> /dev/null
[ 91%] Built target opmsimulators
Scanning dependencies of target flow
[ 93%] Building CXX object CMakeFiles/flow.dir/flow/flow.cpp.o
[ 95%] Building CXX object CMakeFiles/flow.dir/flow/flow_ebos_gasoil.cpp.o
[ 97%] Building CXX object CMakeFiles/flow.dir/flow/flow_ebos_oilwater_polymer.cpp.o
[100%] Building CXX object CMakeFiles/flow.dir/flow/flow_ebos_polymer.cpp.o
[100%] Building CXX object CMakeFiles/flow.dir/flow/flow_ebos_oilwater.cpp.o
[100%] Building CXX object CMakeFiles/flow.dir/flow/flow_ebos_solvent.cpp.o
[100%] Building CXX object CMakeFiles/flow.dir/flow/flow_ebos_blackoil.cpp.o
[100%] Building CXX object CMakeFiles/flow.dir/flow/flow_ebos_energy.cpp.o
[100%] Linking CXX executable bin/flow
[100%] Built target flow

real    1m21.597s
user    8m49.476s
sys     0m10.973s
```

(this corresponds to a ~20% reduction of the time spend on waiting for the compiler.)

### CODE REVIEW

**Comment by andlaus** [comment]
jenkins build this please

**Comment by joakim-hove** [comment]
> the new approach is not to include these objects in libopmsimulators, but to directly deal with them in the flow binary. this allows all of them and the glue code to be compiled in parallel.

I realize that: 

1. I carry very limited weight around here.
2. My arguments are very much subjective - and maybe not relevant yet?

But I will nevertheless bite: *what is so f...ing wrong with libraries?* In my opinion libraries is a well established and working abstraction. Right now you seem to be pushing the flow build in the direction of:
```cmake
add_application(flow ${endless_long_list_source_files})
```

Apart from my subjective grunting I have one objective argument: To faciliate use of `flow` code from other codebases, and wrapping it other languages, the `libopmsimulators.so` needs to be a reasonably complete picture of the simulator. I sincerely hope we can get going with wrapping of simulator in the not-so-distant future, and I must admit I get weary of changes which will make `libopmsimuators` less relevant. Just my 0.02$

**Comment by andlaus** [comment]
> But I will nevertheless bite: what is so f...ing wrong with libraries?

nothing. in this case `libopmsimulator` just causes me to wait 20 seconds more for the compiler every time I remove a semicolon somewhere in opm-material, ewoms or opm-simulators. (also, one can argue that the value of these objects outside of `flow` is exactly zero so they don't belong into a library.)

**Comment by andlaus** [comment]
>  I sincerely hope we can get going with wrapping of simulator in the not-so-distant future, [...]

let's stick to our battle-proven approach in this case as well: let's burn that bridge when we come to it.

**Comment by joakim-hove** [comment]
I'm still on the hunt:

>i n this case libopmsimulator just causes me to wait 20 seconds more for the compiler every time I remove a semicolon somewhere in opm-material, ewoms or opm-simulators.

Maybe the problem is that modules do not produce proper libraries?

**Comment by joakim-hove** [comment]
>let's burn that bridge when we come to it.

I agree that is in general a good approach.

**Comment by andlaus** [comment]
> Maybe the problem is that modules do not produce proper libraries?

I agree for opm-simulators. opm-material and eWoms do not produce any libraries and for opm-common plus opm-grid the classic library concept arguably applies.

**Comment by andlaus** [comment]
jenkins build this please

**Comment by akva2** [comment]
this doesn't really change anything, and if it is of help for peeps, i see now reason to hold it back.

language bindings will have to be built in very different ways from these objects, so i don't think it will influence those much.

**Comment by andlaus** [comment]
can this please be merged? in contrast to curly braces, build times are a real problem for me. (I admit that people who use 1 or 7 build processes are currently not getting any improvement out of this, though.)

**Comment by andlaus** [comment]
jenkins build this please

**Comment by atgeirr** [comment]
> this doesn't really change anything, and if it is of help for peeps, i see now reason to hold it back.

@akva2 If you think there are no adverse consequences w.r.t. packaging etcetera then please merge.

**Pull request merged**
