### PR TITLE
Call Summary::eval() and ::add_timestep separately 

### PR DESCRIPTION
**Pull request by joakim-hove**
Followup to: https://github.com/OPM/opm-common/pull/795

Again a step in UDQ/ACTIONX sequel

### CODE REVIEW

**Comment by joakim-hove** [comment]
jenkins build this opm-common=795

**Comment by joakim-hove** [comment]
jenkins build this opm-common=795

**Comment by akva2** [comment]
jenkins build this opm-common=795 please

**Comment by bska** [comment]
Thanks for merging.  Sorry for the breakage.

**Comment by joakim-hove** [comment]
Hehe - no sweat, it is "good" to see that you also trip once in a while ☺

**Pull request merged**
