### PR TITLE
Put well BHP/THP calculations in separate class

### PR DESCRIPTION
**Pull request by akva2**
This splits out the Wellinterface/StandardWell/Multisegment bhp/thp related calculations to a separate class.

### CODE REVIEW

**Comment by akva2** [comment]
jenkins build this please

**Comment by alfbr** [comment]
Sorry, but you will probably need to wait for the merge of https://github.com/OPM/opm-tests/pull/830

**Comment by bska** [comment]
jenkins build this please

**Comment by akva2** [comment]
jenkins build this please

**Comment by akva2** [comment]
jenkins build this please

**Comment by akva2** [comment]
jenkins build this please

**Comment by akva2** [comment]
jenkins build this please

**Comment by bska** [comment]
jenkins build this please

**Comment by GitPaean** [comment]
With some testing, it is the commit 6e214557e223dc44abacbd01195c5420837c0c36 that causes the difference for the network solution.

**Pull request merged**
