### PR TITLE
use compressed field properties setting up rock parameters

### PR DESCRIPTION
**Pull request by akva2**
Extracted from https://github.com/OPM/opm-simulators/pull/2374

### CODE REVIEW

**Comment by akva2** [comment]
jenkins run norne norne_parallel please

**Comment by blattms** [comment]
Where is this specific to CpGrid?

**Comment by bska** [comment]
> Where is this specific to `CpGrid`?

The statement
```C++
rockTableIdx_[elemIdx] = num[elemIdx] - 1;
```
implicitly assumes that the active element ordering in `EclProblem <>` is the same as the one in the input file (i.e., an IJK-like ordering with I increasing the most rapidly).

**Comment by akva2** [comment]
this would have been remapped earlier on when setting up the distributed properties. granted, not implemented for non-cpgrid yet, but that's the idea.

**Pull request merged**
