### PR TITLE
AdaptiveTimeSteppingEbos: some cleanups

### PR DESCRIPTION
**Pull request by akva2**
- include required headers
- using instead of typedef
- no reason to initialize string with ""

### CODE REVIEW

**Comment by akva2** [comment]
jenkins build this please

**Review by blattms — APPROVED** [review]

**Comment by akva2** [comment]
note i had to make a change due to dune 2.7 having the exception defined in ilu.hh

**Comment by akva2** [comment]
jenkins build this please

**Comment by bska** [comment]
jenkins build this please

**Review by bska — APPROVED** [review]
Thanks.  I'll merge into master.

**Pull request merged**
