### PR TITLE
changed: consistently use stack/C arrays

### PR DESCRIPTION
**Pull request by akva2**
Downstream of https://github.com/OPM/opm-material/pull/528

### CODE REVIEW

**Comment by bska** [comment]
I'm conflicted.  Does this have a measurable impact on (compile-time) performance&mdash;e.g., peak memory use or total time?  If not, I'd really prefer that we stick to `std::array<>` which is a strictly better type than built-in arrays not least because it knows its own size.

**Comment by akva2** [comment]
Not really a significant impact on compile time but is is measurably lowered (half a sec or so but i havent really done a wide enough study to have any kind of statistics). I do agree in principle, but i assumed the use of stack arrays had been measured and found preferable earlier as that is what most code paths use. I will prepare a PR with consistent use of array so we can get some numbers.

**Comment by akva2** [comment]
benchmark please

**Comment by akva2** [comment]
benchmark please opm-material=528

**Comment by ytelses** [comment]
Benchmark result overview: 




| Test    | Configuration                                                                                   | Relative |
| ------- | ----------------------------------------------------------------------------------------------- | -------- |
| opm-git | OPM Benchmark: flow_mpi_extra - Threads: 1                                                      | 0.967    |
| opm-git | OPM Benchmark: flow_mpi_extra - Threads: 1 - FOPT (Total Oil Production At End Of Run)          | 1        |
| opm-git | OPM Benchmark: flow_mpi_extra - Threads: 1 - FGPT (Total Gas Production At End Of Run)          | 1        |
| opm-git | OPM Benchmark: flow_mpi_extra - Threads: 1 - FWPT (Total Water Production At End Of Run)        | 1        |
| opm-git | OPM Benchmark: flow_mpi_extra - Threads: 1 - FOIT (Total Oil Injection At End Of Run)           | 1        |
| opm-git | OPM Benchmark: flow_mpi_extra - Threads: 1 - FGIT (Total Gas Injection At End Of Run)           | 1        |
| opm-git | OPM Benchmark: flow_mpi_extra - Threads: 1 - FWIT (Total Water Injection At End Of Run)         | 1        |
| opm-git | OPM Benchmark: flow_mpi_extra - Threads: 8                                                      | 1.002    |
| opm-git | OPM Benchmark: flow_mpi_extra - Threads: 8 - FOPT (Total Oil Production At End Of Run)          | 1        |
| opm-git | OPM Benchmark: flow_mpi_extra - Threads: 8 - FGPT (Total Gas Production At End Of Run)          | 1        |
| opm-git | OPM Benchmark: flow_mpi_extra - Threads: 8 - FWPT (Total Water Production At End Of Run)        | 1        |
| opm-git | OPM Benchmark: flow_mpi_extra - Threads: 8 - FOIT (Total Oil Injection At End Of Run)           | 1        |
| opm-git | OPM Benchmark: flow_mpi_extra - Threads: 8 - FGIT (Total Gas Injection At End Of Run)           | 1        |
| opm-git | OPM Benchmark: flow_mpi_extra - Threads: 8 - FWIT (Total Water Injection At End Of Run)         | 1        |
| opm-git | OPM Benchmark: flow_mpi_norne - Threads: 1                                                      | 0.999    |
| opm-git | OPM Benchmark: flow_mpi_norne - Threads: 1 - FOPT (Total Oil Production At End Of Run)          | 1        |
| opm-git | OPM Benchmark: flow_mpi_norne - Threads: 1 - FGPT (Total Gas Production At End Of Run)          | 1        |
| opm-git | OPM Benchmark: flow_mpi_norne - Threads: 1 - FWPT (Total Water Production At End Of Run)        | 1        |
| opm-git | OPM Benchmark: flow_mpi_norne - Threads: 1 - FOIT (Total Oil Injection At End Of Run)           | 1        |
| opm-git | OPM Benchmark: flow_mpi_norne - Threads: 1 - FGIT (Total Gas Injection At End Of Run)           | 1        |
| opm-git | OPM Benchmark: flow_mpi_norne - Threads: 1 - FWIT (Total Water Injection At End Of Run)         | 1        |
| opm-git | OPM Benchmark: flow_mpi_norne - Threads: 1 - FGASMBE                                            | 1        |
| opm-git | OPM Benchmark: flow_mpi_norne - Threads: 1 - FWATMBE                                            | 1        |
| opm-git | OPM Benchmark: flow_mpi_norne - Threads: 8                                                      | 0.987    |
| opm-git | OPM Benchmark: flow_mpi_norne - Threads: 8 - FOPT (Total Oil Production At End Of Run)          | 1        |
| opm-git | OPM Benchmark: flow_mpi_norne - Threads: 8 - FGPT (Total Gas Production At End Of Run)          | 1        |
| opm-git | OPM Benchmark: flow_mpi_norne - Threads: 8 - FWPT (Total Water Production At End Of Run)        | 1        |
| opm-git | OPM Benchmark: flow_mpi_norne - Threads: 8 - FOIT (Total Oil Injection At End Of Run)           | 1        |
| opm-git | OPM Benchmark: flow_mpi_norne - Threads: 8 - FGIT (Total Gas Injection At End Of Run)           | 1        |
| opm-git | OPM Benchmark: flow_mpi_norne - Threads: 8 - FWIT (Total Water Injection At End Of Run)         | 1        |
| opm-git | OPM Benchmark: flow_mpi_norne - Threads: 8 - FGASMBE                                            | 1        |
| opm-git | OPM Benchmark: flow_mpi_norne - Threads: 8 - FWATMBE                                            | 1        |
| opm-git | OPM Benchmark: flow_mpi_norne_4c_msw - Threads: 1                                               | 1.003    |
| opm-git | OPM Benchmark: flow_mpi_norne_4c_msw - Threads: 1 - FOPT (Total Oil Production At End Of Run)   | 1        |
| opm-git | OPM Benchmark: flow_mpi_norne_4c_msw - Threads: 1 - FGPT (Total Gas Production At End Of Run)   | 1        |
| opm-git | OPM Benchmark: flow_mpi_norne_4c_msw - Threads: 1 - FWPT (Total Water Production At End Of Run) | 1        |
| opm-git | OPM Benchmark: flow_mpi_norne_4c_msw - Threads: 1 - FOIT (Total Oil Injection At End Of Run)    | 1        |
| opm-git | OPM Benchmark: flow_mpi_norne_4c_msw - Threads: 1 - FWIT (Total Water Injection At End Of Run)  | 1        |
| opm-git | OPM Benchmark: flow_mpi_norne_4c_msw - Threads: 1 - FGASMBE                                     | 1        |
| opm-git | OPM Benchmark: flow_mpi_norne_4c_msw - Threads: 1 - FWATMBE                                     | 1        |
| opm-git | OPM Benchmark: flow_mpi_norne_4c_msw - Threads: 8                                               | 0.99     |
| opm-git | OPM Benchmark: flow_mpi_norne_4c_msw - Threads: 8 - FOPT (Total Oil Production At End Of Run)   | 1        |
| opm-git | OPM Benchmark: flow_mpi_norne_4c_msw - Threads: 8 - FGPT (Total Gas Production At End Of Run)   | 1        |
| opm-git | OPM Benchmark: flow_mpi_norne_4c_msw - Threads: 8 - FWPT (Total Water Production At End Of Run) | 1        |
| opm-git | OPM Benchmark: flow_mpi_norne_4c_msw - Threads: 8 - FOIT (Total Oil Injection At End Of Run)    | 1        |
| opm-git | OPM Benchmark: flow_mpi_norne_4c_msw - Threads: 8 - FWIT (Total Water Injection At End Of Run)  | 1        |
| opm-git | OPM Benchmark: flow_mpi_norne_4c_msw - Threads: 8 - FGASMBE                                     | 1        |
| opm-git | OPM Benchmark: flow_mpi_norne_4c_msw - Threads: 8 - FWATMBE                                     | 1        |
* Speed-up = Total time master / Total time pull request. Above 1.0 is an improvement. *



View result details @ https://www.ytelses.com/opm/?page=result&id=1746

**Comment by ytelses** [comment]
Benchmark result overview: 




| Test    | Configuration                                                                                   | Relative |
| ------- | ----------------------------------------------------------------------------------------------- | -------- |
| opm-git | OPM Benchmark: flow_mpi_extra - Threads: 1                                                      | 0.998    |
| opm-git | OPM Benchmark: flow_mpi_extra - Threads: 1 - FOPT (Total Oil Production At End Of Run)          | 1        |
| opm-git | OPM Benchmark: flow_mpi_extra - Threads: 1 - FGPT (Total Gas Production At End Of Run)          | 1        |
| opm-git | OPM Benchmark: flow_mpi_extra - Threads: 1 - FWPT (Total Water Production At End Of Run)        | 1        |
| opm-git | OPM Benchmark: flow_mpi_extra - Threads: 1 - FOIT (Total Oil Injection At End Of Run)           | 1        |
| opm-git | OPM Benchmark: flow_mpi_extra - Threads: 1 - FGIT (Total Gas Injection At End Of Run)           | 1        |
| opm-git | OPM Benchmark: flow_mpi_extra - Threads: 1 - FWIT (Total Water Injection At End Of Run)         | 1        |
| opm-git | OPM Benchmark: flow_mpi_extra - Threads: 8                                                      | 1        |
| opm-git | OPM Benchmark: flow_mpi_extra - Threads: 8 - FOPT (Total Oil Production At End Of Run)          | 1        |
| opm-git | OPM Benchmark: flow_mpi_extra - Threads: 8 - FGPT (Total Gas Production At End Of Run)          | 1        |
| opm-git | OPM Benchmark: flow_mpi_extra - Threads: 8 - FWPT (Total Water Production At End Of Run)        | 1        |
| opm-git | OPM Benchmark: flow_mpi_extra - Threads: 8 - FOIT (Total Oil Injection At End Of Run)           | 1        |
| opm-git | OPM Benchmark: flow_mpi_extra - Threads: 8 - FGIT (Total Gas Injection At End Of Run)           | 1        |
| opm-git | OPM Benchmark: flow_mpi_extra - Threads: 8 - FWIT (Total Water Injection At End Of Run)         | 1        |
| opm-git | OPM Benchmark: flow_mpi_norne - Threads: 1                                                      | 0.997    |
| opm-git | OPM Benchmark: flow_mpi_norne - Threads: 1 - FOPT (Total Oil Production At End Of Run)          | 1        |
| opm-git | OPM Benchmark: flow_mpi_norne - Threads: 1 - FGPT (Total Gas Production At End Of Run)          | 1        |
| opm-git | OPM Benchmark: flow_mpi_norne - Threads: 1 - FWPT (Total Water Production At End Of Run)        | 1        |
| opm-git | OPM Benchmark: flow_mpi_norne - Threads: 1 - FOIT (Total Oil Injection At End Of Run)           | 1        |
| opm-git | OPM Benchmark: flow_mpi_norne - Threads: 1 - FGIT (Total Gas Injection At End Of Run)           | 1        |
| opm-git | OPM Benchmark: flow_mpi_norne - Threads: 1 - FWIT (Total Water Injection At End Of Run)         | 1        |
| opm-git | OPM Benchmark: flow_mpi_norne - Threads: 1 - FGASMBE                                            | 1        |
| opm-git | OPM Benchmark: flow_mpi_norne - Threads: 1 - FWATMBE                                            | 1        |
| opm-git | OPM Benchmark: flow_mpi_norne - Threads: 8                                                      | 0.999    |
| opm-git | OPM Benchmark: flow_mpi_norne - Threads: 8 - FOPT (Total Oil Production At End Of Run)          | 1        |
| opm-git | OPM Benchmark: flow_mpi_norne - Threads: 8 - FGPT (Total Gas Production At End Of Run)          | 1        |
| opm-git | OPM Benchmark: flow_mpi_norne - Threads: 8 - FWPT (Total Water Production At End Of Run)        | 1        |
| opm-git | OPM Benchmark: flow_mpi_norne - Threads: 8 - FOIT (Total Oil Injection At End Of Run)           | 1        |
| opm-git | OPM Benchmark: flow_mpi_norne - Threads: 8 - FGIT (Total Gas Injection At End Of Run)           | 1        |
| opm-git | OPM Benchmark: flow_mpi_norne - Threads: 8 - FWIT (Total Water Injection At End Of Run)         | 1        |
| opm-git | OPM Benchmark: flow_mpi_norne - Threads: 8 - FGASMBE                                            | 1        |
| opm-git | OPM Benchmark: flow_mpi_norne - Threads: 8 - FWATMBE                                            | 1        |
| opm-git | OPM Benchmark: flow_mpi_norne_4c_msw - Threads: 1                                               | 1.001    |
| opm-git | OPM Benchmark: flow_mpi_norne_4c_msw - Threads: 1 - FOPT (Total Oil Production At End Of Run)   | 1        |
| opm-git | OPM Benchmark: flow_mpi_norne_4c_msw - Threads: 1 - FGPT (Total Gas Production At End Of Run)   | 1        |
| opm-git | OPM Benchmark: flow_mpi_norne_4c_msw - Threads: 1 - FWPT (Total Water Production At End Of Run) | 1        |
| opm-git | OPM Benchmark: flow_mpi_norne_4c_msw - Threads: 1 - FOIT (Total Oil Injection At End Of Run)    | 1        |
| opm-git | OPM Benchmark: flow_mpi_norne_4c_msw - Threads: 1 - FWIT (Total Water Injection At End Of Run)  | 1        |
| opm-git | OPM Benchmark: flow_mpi_norne_4c_msw - Threads: 1 - FGASMBE                                     | 1        |
| opm-git | OPM Benchmark: flow_mpi_norne_4c_msw - Threads: 1 - FWATMBE                                     | 1        |
| opm-git | OPM Benchmark: flow_mpi_norne_4c_msw - Threads: 8                                               | 1.005    |
| opm-git | OPM Benchmark: flow_mpi_norne_4c_msw - Threads: 8 - FOPT (Total Oil Production At End Of Run)   | 1        |
| opm-git | OPM Benchmark: flow_mpi_norne_4c_msw - Threads: 8 - FGPT (Total Gas Production At End Of Run)   | 1        |
| opm-git | OPM Benchmark: flow_mpi_norne_4c_msw - Threads: 8 - FWPT (Total Water Production At End Of Run) | 1        |
| opm-git | OPM Benchmark: flow_mpi_norne_4c_msw - Threads: 8 - FOIT (Total Oil Injection At End Of Run)    | 1        |
| opm-git | OPM Benchmark: flow_mpi_norne_4c_msw - Threads: 8 - FWIT (Total Water Injection At End Of Run)  | 1        |
| opm-git | OPM Benchmark: flow_mpi_norne_4c_msw - Threads: 8 - FGASMBE                                     | 1        |
| opm-git | OPM Benchmark: flow_mpi_norne_4c_msw - Threads: 8 - FWATMBE                                     | 1        |
* Speed-up = Total time master / Total time pull request. Above 1.0 is an improvement. *



View result details @ https://www.ytelses.com/opm/?page=result&id=1747

**Pull request closed without merging**
