### PR TITLE
The missing features check takes a ParseContext argument

### PR DESCRIPTION
**Pull request by joakim-hove**
Downstream of: https://github.com/OPM/opm-common/pull/617

### CODE REVIEW

**Comment by joakim-hove** [comment]
jenkins build this opm-common=617 please

**Comment by joakim-hove** [comment]
jenkins build this opm-common=617 please

**Comment by joakim-hove** [comment]
jenkins build this opm-common=617 please

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by totto82** [comment]
Any reasons for not merging this? This gives us more flexibility in the strictness on handling non-supported keywords.

**Comment by joakim-hove** [comment]
> Any reasons for not merging this?

Not as far as I can see - I am as usual totally shameless when it comes to self-merging after some time. Will push the green later today unless someone takes this opportunity to scream and shout.

**Comment by joakim-hove** [comment]
jenkins build this please

**Pull request merged**
