### PR TITLE
update update_reference_data.sh to also update the flow_ebos reference solutions

### PR DESCRIPTION
**Pull request by andlaus**
this patch has been factored out of #1133 and maybe it even works, but the reasoning for the merge commit probably needs some improvement. (right @akva2?) Thus, this PR is mainly meant as a starting point for further discussions.

### CODE REVIEW

**Comment by andlaus** [comment]
Let's use this one as a canary for Jenkins:

**Comment by andlaus** [comment]
jenkins build this please

**Comment by andlaus** [comment]
jenkins run norne_ebos ewoms=170 please

**Comment by atgeirr** [comment]
Merging this now, @andlaus perhaps you could make a dummy PR that causes changes to verify that it does what it is supposed to do?

**Comment by akva2** [comment]
this was incomplete. i will revisit after packaging chores.

**Comment by atgeirr** [comment]
Sorry if I merged it too early. I don't think we will merge any more PRs requiring data updates until after the release though, so hopefully it should cause no major problems.

**Comment by akva2** [comment]
it won't cause any problem, it's just (useful) cosmetics missing.

**Comment by andlaus** [comment]
I think there's no need for a revert because this probably doesn't need to go into the release branch anyway. Seems like this was the point of both of you, right?

**Comment by akva2** [comment]
yes and yes.

**Pull request merged**
