### PR TITLE
extrapolate saltvd table

### PR DESCRIPTION
**Pull request by totto82**
When reading the release 2020.10 announcement I came over issue #2889. 
This is a fix.

### CODE REVIEW

**Comment by totto82** [comment]
jenkins build this please

**Comment by totto82** [comment]
I added a release tag. No need to let the issue survive two releases.

**Comment by bska** [comment]
> This is a fix.

Right&mdash;I'd forgotten about that issue.  Did you test this on several models?

**Comment by totto82** [comment]
Only on the case in the issue. 

Extrapolation is what we do for similar properties. So at-least the code becomes consistent. 
See for instance 

https://github.com/OPM/opm-simulators/blob/32a035f8a54eccffa7572eadc661aa40c71ff720/ebos/equil/initstateequil.hh#L183

in the same file.

**Comment by bska** [comment]
>> Did you test this on several models?
>
> Only on the case in the issue.

I see.  In that case I'm still a little wary of enabling this.  As I said [earlier](https://github.com/OPM/opm-simulators/issues/2889#issuecomment-720163102), extrapolating that case's `SALTVD` table is trivial since the concentration is constant with respect to depth but in other models we probably will not be that lucky.  On the other hand, in a real simulation model the engineer will **hopefully** know better than to end the depth table a full 2825 ft above the top of the formation so it might not be a big problem in practice.

**Comment by totto82** [comment]
>  In that case I'm still a little wary of enabling this

Extrapolation is how we handle all similar properties. Usually without warnings. Adding checks in the input layer in opm-common that produces a warning or throw if the depths is outside the range could be a way to warn the user. I still think this can be merged as is.

**Comment by alfbr** [comment]
> I see. In that case I'm still a little wary of enabling this. As I said [earlier](https://github.com/OPM/opm-simulators/issues/2889#issuecomment-720163102), extrapolating that case's `SALTVD` table is trivial since the concentration is constant with respect to depth but in other models we probably will not be that lucky. On the other hand, in a real simulation model the engineer will **hopefully** know better than to end the depth table a full 2825 ft above the top of the formation so it might not be a big problem in practice.

Thanks for checking this thoroughly! At some point we should do a coordinated effort to provide good warning messages when tables are extrapolated. I agree with your assessment, in this case the engineer will hopefully know better, so from our end we do not need to handle this better now.

**Comment by bska** [comment]
> in this case the engineer will hopefully know better, so from our end we do not need to handle this better now.

Noted.  I'll merge this then and just **hope** we don't get hard-to-debug problems later on.

**Pull request merged**
