### PR TITLE
changed: avoid usage of eclipseGrid on non-root processes setting up transmissibilities

### PR DESCRIPTION
**Pull request by akva2**
obtain data from root process

@blattms I am sure you do not like the bare MPI calls, please advice which construct to use for non-collective communication.

### CODE REVIEW

**Comment by akva2** [comment]
jenkins build this please

**Comment by blattms** [comment]
Concerning the MPI calls: Well if we could be sure that this code is
just run with CpGrid we could use `CpGrid::scatterData` for this.
the problem is that we seem to support other grids (in downstream modules,
@drrobertk?) and they only allow distributing data during loadbalance.

Hence the clean way would be to distribute it with loadbalance. But we will
need to distribute other stuff, too. So maybe we should leave this for another
day and open an issue for it?

**Comment by akva2** [comment]
i kinda want to do it properly immediately cause there are a lot of places i have to write code equivalent to this.

**Comment by blattms** [comment]
The proper way to do this is in the grid vanguards. In [eclalugridvanguard.hh#L147](blob/ecfbb0e4919a52b93c97d8c8dfd9164d99bcfada/ebos/eclalugridvanguard.hh#L147) we already used a datahandle for distributing the cartesian index when loadbalancing.

I guess the centroids are only for CpGrid? Then we need to create a Datahandle
```
struct MyHandle{
  using DataType = std::array<double, 3>;
  bool fixedsize(int /* dim */, int /* codim */) const {return true;}
  bool contains (int /* dim /, int codim) const { return codim==0;}
  template<class Entity>
  size_t size (const Entity e) const ( return 1;}
  template<class MessageBufferImp , class EntityType > 
  void gather (MessageBufferImp &buff, const EntityType &e) const
  {
      buffer.write(eclGrid.getCellCenter(elemMapper.index(e)));
  }
  template<class MessageBufferImp , class EntityType > 
  void scatter (MessageBufferImp &buff, const EntityType &e, size_t) const
  {
     buffer.read(centroids[elemMapper.index(e)]);
  }
};
```
and pass that to loadbalance in eclcpgridvanguard. Later we probably need to extend the handle to communicate more.

**Comment by blattms** [comment]
[Datahandle interface](https://www.dune-project.org/doxygen/master/classDune_1_1CommDataHandleIF.html)

**Comment by blattms** [comment]
Not sure whether it is this PR or previous (maybe be me). But using the mpiwrapper from OpenMPI
and 2 processes `LD_PRELOAD=/usr/lib/x86_64-linux-gnu/valgrind/libmpiwrap-amd64-linux.so mpirun -np 2 valgrind ../../opm-simulators/opm-parallel-debug/bin/flow SPE9_CP_GROUP`,  with the stuff marked with `[TEMP]` reverted, shows some problems. See
[valgrind.log](https://github.com/OPM/opm-simulators/files/4070811/valgrind.log).

These [wrappers](https://www.valgrind.org/docs/manual/mc-manual.html#mc-manual.mpiwrap) are quite handy. (bummer, that I always forget how to activate them)

HTH

**Comment by blattms** [comment]
They could be false positives of course.

**Comment by akva2** [comment]
at least that gives me some crumbs to follow. thanks!

**Comment by blattms** [comment]
Arrgh. Wrong PR. Sorry.

**Comment by blattms** [comment]
somehow this is quite different from my approach at akva2/opm-simulators#11. I am a bit surprised that both should accomplish the same.

**Comment by blattms** [comment]
jenkins run norne_parallel please

**Comment by blattms** [comment]
jenkins run norne parallel please

**Comment by blattms** [comment]
jenkins run norne_parallel please

**Comment by blattms** [comment]
can this be closed?

**Pull request closed without merging**
