### PR TITLE
ecltracermodel: split in typetag dependent and typetag-independent parts

### PR DESCRIPTION
**Pull request by akva2**
this allows using explicit template instantation to only
compile this code per grid, not per simulator object

### CODE REVIEW

**Comment by akva2** [comment]
jenkins build this please

**Comment by bska** [comment]
No opinion on the code yet because I've not read it.  I just wonder if some of the new [warnings](https://ci.opm-project.org/job/opm-simulators-PR-builder/2279/gcc/new/) might come from missing `config.h` somewhere.

**Comment by akva2** [comment]
not config.h but rather the header defining OPM_UNUSED macros. Personally i am trying to get rid of those and just use c++17 [[maybe_unused]]. did that locally but forgot to include as it is in a different repo.

**Comment by bska** [comment]
> I am trying to get rid of [`OPM_UNUSED`] and just use c++17 `[[maybe_unused]]`. did that locally but forgot to include as it is in a different repo.

Understood.  I support the work of converting from `OPM_UNUSED` to `[[maybe_unused]]`.

**Comment by akva2** [comment]
jenkins build this opm-models=657 please

**Comment by akva2** [comment]
jenkins build this opm-models=657 please

**Comment by joakim-hove** [comment]
It's green - I'll merge.

**Pull request merged**
