### PR TITLE
Group tests4

### PR DESCRIPTION
**Pull request by alfbr**
Last know good test added. The remaining data sets need more work.

### CODE REVIEW

**Comment by alfbr** [comment]
jenkins build this update_data please

**Comment by bska** [comment]
jenkins build this opm-tests=313 please

**Comment by bska** [comment]
We're getting a test failure in the New Reference case due to OPM/opm-common#1769 and OPM/opm-tests#312 being merged in the interim:
```
  > 'GULPR1:LOWER'
  > 'GULPR1:MOD4'
  > 'GULPR1:UPPER'
  > 'GULPR2:LOWER'
  > 'GULPR2:MOD4'
  > 'GULPR2:UPPER'
  > 'GULPR3:LOWER'
  > 'GULPR3:MOD4'
  > 'GULPR3:UPPER'
  > 'GUOPR1:LOWER'
  > 'GUOPR1:MOD4'
  > 'GUOPR1:UPPER'
  > 'GUOPR2:LOWER'
  > 'GUOPR2:MOD4'
  > 'GUOPR2:UPPER'
  > 'GUOPR3:LOWER'
  > 'GUOPR3:MOD4'
  > 'GUOPR3:UPPER'
```
I'll try to re-update OPM/opm-tests#313 (I'll close/reopen first) to bring in those changes too.

**Comment by bska** [comment]
jenkins build this update_data please

**Comment by bska** [comment]
jenkins build this opm-tests=313 please

**Comment by bska** [comment]
Merging this now to activate the tests as part of our continuous integration builds.  Thanks a lot for expanding our test coverage.

**Pull request merged**
