### PR TITLE
Frankenstein fip output

### PR DESCRIPTION
**Pull request by totto82**
Implements FIP for flow_ebos

Known issues
1) Not tested for 2p and in parallel. 
2) Original FIP is calculated after the first time step instead of before. 

@babrodtk There is slight mismatch between the FIP calculated with flow_ebos and flow. Could you test this PR and judge whether the mismatch is acceptable or not. 

When this PR is merged. Flow and flow_ebos is supposed to have the same ecl output capabilities.

### CODE REVIEW

**Comment by andlaus** [comment]
could you please rebase your PR on top of the current `frankenstein` branch'? (that would get rid of all those useless merge commits.)

except for that (and the improvement which we already discussed privately via email), the PR looks fine to me.

**Comment by babrodtk** [comment]
@totto82: I had some troubles compiling this (without MPI), and created a PR (into this PR) with a fix that works on my end.

**Comment by totto82** [comment]
@babrodtk Thanks for the fix. I will merge it.

**Comment by babrodtk** [comment]
I've taken a look at the numbers (with some help from @atgeirr), and they appear plausible, considering the differences in the simulation model. 

The only thing that sticks out is that "Originally in place" is zero for all fields in the first print of FIP, and this appears to be an error. Also, all of the FIP regions are missing in the first printout.

**Comment by totto82** [comment]
> The only thing that sticks out is that "Originally in place" is zero for all fields in the first print of FIP, and this appears to be an error. Also, all of the FIP regions are missing in the first printout. 

See known issue in the PR description. 

I will fix this and update. Thanks for the check and the fix.

**Comment by totto82** [comment]
The known issues is fixed. Sorry for the delay.

**Comment by andlaus** [comment]
> The known issues is fixed. Sorry for the delay.

do you consider it mergeable?

**Comment by totto82** [comment]
> do you consider it mergeable?

Yes

**Comment by andlaus** [comment]
ok, merging then. Thanks.

**Pull request merged**
