### PR TITLE
removing --relaxed-max-pv-fraction for num aquifer tests

### PR DESCRIPTION
**Pull request by GitPaean**
to be careful, make it draft first for testing.

### CODE REVIEW

**Comment by GitPaean** [comment]
jenkins build this please

**Comment by GitPaean** [comment]
the relative errors are pretty small, (e-5 level), a update_data can be performed.

**Comment by GitPaean** [comment]
jenkins build this update_data please

**Comment by GitPaean** [comment]
jenkins build this update_data please

**Comment by GitPaean** [comment]
jenkins build this opm-tests=669 please

**Comment by bska** [comment]
jenkins build this opm-tests=669 please

**Comment by bska** [comment]
Okay.  Let's run with this.  If the tests become too unstable with the default value of 0.03 we can always reinstall the zero limit.

**Pull request merged**
