### PR TITLE
Add and move tests

### PR DESCRIPTION
**Pull request by akva2**
this
- moves the MSW_2D_H test to flow
- adds polymer_simple2D to flow
- moves the spe5 solvent test to flow
- moves the parallel spe3 test to flow (no idea why i didn't do that in the previous PR..)
- adds the msw_3d_hfa test for flow
- update the reference data update script to allow addition of new data

### CODE REVIEW

**Comment by akva2** [comment]
jenkins build this update_data please

**Comment by GitPaean** [comment]
jenkins build this opm-data=274 please

**Comment by GitPaean** [comment]
For SPE3CASE1, 
```
43: Comparing '/home/kaib/OPM-master-test/debug/opm-simulators-build/tests/results/parallel/flow+spe3/SPE3CASE1' to '/home/kaib/OPM-master-test/debug/opm-simulators-build/tests/results/parallel/flow+spe3/mpi/SPE3CASE1'.
43: Comparing 178 steps.
43: For keyword WBHP:INJ
43: (days, reference value) and (days, check value) = (3801, 2283.96) and (3801, 2283.99)
43: The absolute deviation is 0.032959. The tolerance limit is 0.02
43: The relative deviation is 1.44304e-05. The tolerance limit is 1e-05
43: Program threw an exception: [/home/kaib/OPM-master-test/debug/opm-output/opm/test_util/summaryRegressionTest.cpp:116] Deviation exceed the limit.
43: 1 summary keyword(s) exhibit failures
43: 	 WBHP:INJ
43: 	 	 Fails for: 30 / 178 steps.
43: 		 Largest absolute error: 3.979860e+00
43: 		 Largest relative error: 2.470940e-03
```

**Comment by akva2** [comment]
i know, which is why i didn't the jenkins re-run. it seems to be actual breakage.

**Comment by GitPaean** [comment]
Locally, SPE5CASE1 also fails. It is good other people can help to confirm. 

```
4: 
34: Failure for keyword DOUBHEAD
34: 	 Fails for 1 entries
34: 	 Largest absolute deviation: 7.365000e+03
34: 	 Largest relative deviation: 9.167290e-01
34: Failure for keyword OPM_XWEL
34: 	 Fails for 2 entries
34: 	 Largest absolute deviation: 1.543870e+00
34: 	 Largest relative deviation: 9.666230e-01
34: Failure for keyword PRESSURE
34: 	 Fails for 147 entries
34: 	 Largest absolute deviation: 1.033450e+03
34: 	 Largest relative deviation: 3.648960e-01
34: Failure for keyword RS
34: 	 Fails for 147 entries
34: 	 Largest absolute deviation: 1.966540e-01
34: 	 Largest relative deviation: 3.174150e-01
34: Failure for keyword SWAT
34: 	 Fails for 147 entries
34: 	 Largest absolute deviation: 3.891400e-01
34: 	 Largest relative deviation: 5.554640e-01
34: Failure for keyword OILKR
34: 	 Fails for 73 entries
34: 	 Largest absolute deviation: 4.096530e-01
34: 	 Largest relative deviation: 1.000000e+00
34: Failure for keyword SOMAX
34: 	 Fails for 2 entries
34: 	 Largest absolute deviation: 4.397330e-02
34: 	 Largest relative deviation: 6.624570e-02
34: Failure for keyword WATKR
34: 	 Fails for 146 entries
34: 	 Largest absolute deviation: 4.782260e-01
34: 	 Largest relative deviation: 9.910280e-01
34: Failure for keyword OPMEXTRA
34: 	 Fails for 1 entries
34: 	 Largest absolute deviation: 3.835710e+05
34: 	 Largest relative deviation: 4.556140e-02
34: === Executing comparison for init file ===
34: Comparing '/home/kaib/OPM-master-test/debug/opm-simulators-build/tests/results/flow+spe5/SPE5CASE1' to '/home/kaib/OPM-master-test/debug/opm-simulators/../opm-data/spe5/opm-simulation-reference/flow/SPE5CASE1'.
34: Comparing INTEHEAD...done.
```

**Comment by atgeirr** [comment]
I get a different set of local test failures:
```
	 30 - compareECLFiles_flow+2D_H__ (Failed)
	 32 - compareECLFiles_flow+2D_THREEPHASE_POLY_HETER (Failed)
	 43 - compareParallelSim_flow+SPE3CASE1 (Failed)
```
Will investigate the magnitude of the failures.

**Comment by GitPaean** [comment]
The SPE5CASE1 did not finish running. 
```
Time step   24 at day 730/8034, date = 31-Dec-1988
  Substep 0, stepsize 31 days.
flow: /home/kaib/OPM-master-test/debug/opm-simulators/opm/autodiff/WellInterface_impl.hpp:303: double Opm::WellInterface<TypeTag>::wsolvent() const [with TypeTag = Ewoms::Properties::TTag::EclFlowSolventProblem]: Assertion `false' failed.
Aborted

```

**Comment by atgeirr** [comment]
For my local tests, curves are visually indistinguishable from the reference (I could see a single pixel difference in one curve). If the same holds for the SPE5 test failure @GitPaean described, I suggest we use a coarser tolerance for these *new* tests, as it is better to have them with a coarse tolerance than not at all. (Note that I think that the tests are still quite tight -- ensuring visually indistinguishable curves is quite valuable.)

**Comment by GitPaean** [comment]
For the SPE3CASE1, the well curves show perfect match. 
[spe3case1.pdf](https://github.com/OPM/opm-simulators/files/1466129/spe3case1.pdf)

**Comment by atgeirr** [comment]
> The SPE5CASE1 did not finish running.

Did not notice this before I wrote my comment. We have to investigate this a little more.

**Comment by GitPaean** [comment]
> Did not notice this before I wrote my comment. We have to investigate this a little more.

It looks like all my repos are updated and the major difference is that I compiled with `-g` compiling option. 

Could someone confirm the test failure with `-g` compiling option?

And also, can we put `-g` option in Jenkins?

**Comment by akva2** [comment]
-g makes no difference to results, only binary size. if you compiled without optimizations however, that might make a difference.

**Comment by GitPaean** [comment]
> -g makes no difference to results, only binary size. if you compiled without optimizations however, that might make a difference.

Sorry for the misleading statement, it should be removing `-DNDEBUG` option to catch the `assert` failure.

**Comment by atgeirr** [comment]
Bug found, fix to be proposed as a PR to your branch, together with suggested tolerance coarsenings for new tests.

**Comment by atgeirr** [comment]
Further issue also found with RS values, on two of the same test cases
```
	 30 - compareECLFiles_flow+2D_H__ (Failed)
	 32 - compareECLFiles_flow+2D_THREEPHASE_POLY_HETER (Failed)
```

**Comment by atgeirr** [comment]
The RS discrepancies occur in cells with oil saturation of 0, where the RS values are meaningless. So I will propose this as planned. For some time I'll have local test failures due to this.

Perhaps we should change the tests to compare (RS * (1 - SWAT - SGAS)) instead of RS, and (RV * SGAS) instead of RV? (Not in this PR anyway.)

@alfbr I seem to remember that you had some opinion related to this, or perhaps it was related to what values we write for inactive cells?

**Comment by akva2** [comment]
jenkins build this opm-data=274 please

**Comment by akva2** [comment]
i realize it will fail, but i want to see the parallel test pass before i do the other steps.

**Comment by alfbr** [comment]
> @alfbr I seem to remember that you had some opinion related to this, or perhaps it was related to what values we write for inactive cells?

Actually I do not remember. Please ping me if you want me to dig into the issues at hand.

**Comment by akva2** [comment]
actually everything passed of course cause the assert didnt bite in a release build.

**Comment by GitPaean** [comment]
> actually everything passed of course cause the assert didnt bite in a release build.

Actually, the assert failure related to SPE5CASE1 is fixed with  @atgeirr 's branch. Anyway, it think we should test assert s in Jenkins, sometimes help to recover the related problems.

**Comment by akva2** [comment]
okay, i will do the buildsystem bits, but it's separate from this.

**Comment by atgeirr** [comment]
I consider this ready to merge as-is (with the two opm-data PRs), agree @akva2?

**Comment by akva2** [comment]
i'm not sure the removal pr is complete yet so hold on that until i say go.

**Comment by akva2** [comment]
okay, it's good. all ready for merge from my side.

**Pull request merged**
