### PR TITLE
Add ascii diff of changes to data update PR

### PR DESCRIPTION
**Pull request by akva2**
requested here; https://github.com/OPM/opm-tests/pull/192

Downstream of https://github.com/OPM/opm-common/pull/1263

### CODE REVIEW

**Comment by akva2** [comment]
jenkins build this opm-common=1263 update_data please

**Comment by akva2** [comment]
jenkins build this opm-common=1263 update_data please

**Comment by akva2** [comment]
slight road bump. i am using curl to post the comment and it easily exceeds the max command line. i'll have change to some other tool to interact with github, will take some more time.

**Comment by akva2** [comment]
would it be acceptable to instead upload the diff to the CI server? that would be a lot easier. @bska @joakim-hove opinions.

**Comment by bska** [comment]
> would it be acceptable to instead upload the diff to the CI server? that would be a lot easier

That's perfectly fine.  Would you additionally be able to automatically post a link to the diff in a Github comment?

**Comment by akva2** [comment]
no, that would be a chicken-hen problem. but it's easily found, you just go to the details under the check and it will be right there.

**Comment by joakim-hove** [comment]
> would it be acceptable to instead upload the diff to the CI server? that would be a lot easier.

Of course. I guess I should be slightly more careful with suggestions and loose thoughts - you jump fast!

**Comment by akva2** [comment]
jenkins build this update_data please

**Comment by akva2** [comment]
okay, see under details now. sadly this approach will not pick up all changes. in particular, lots of files were changed but only the forced file appears in the diff since the formatted files are identical.

**Comment by joakim-hove** [comment]
> okay, see under details now

The "data_diff" view? Looks fine - we'll leave it here. I was just voicing a question which I thought could be valuable - not a real need.

**Pull request merged**
