### PR TITLE
Bugfix sign of gpmaint prod

### PR DESCRIPTION
**Pull request by totto82**
A sign was removed in #4664.

I notice that we don't have any `GPMAINT` cases under regression testing. I will put this as draft until we have double checked that this does not create an issue for the other gpmaint cases in https://github.com/OPM/opm-tests/tree/master/gpmaint

And we should out them under regression testing asap.

### CODE REVIEW

**Comment by totto82** [comment]
jenkins build this please

**Comment by totto82** [comment]
jenkins build this please

**Review by bska — APPROVED** [review]
Good catch.  I'll generate the reference solution for the new test case and then I'll merge this.

**Comment by bska** [comment]
jenkins build this update_data please

**Comment by bska** [comment]
jenkins build this opm-tests=1097 please

**Comment by bska** [comment]
The new reference solutions have been installed on the CI system.  Merging this now to fix the issue and activate the new regression test.

**Pull request merged**
