### PR TITLE
Remove Fip, Init and Egrid output

### PR DESCRIPTION
**Pull request by totto82**
The removed features are re-implemented in OPM/ewoms#272

Tested on norne and model 2. 
Depends on OPM/opm-parser#1118 and OPM/ewoms#272

TODO: 
- [x] Test MPI on model 2  
- [x] Fix test failures

### CODE REVIEW

**Comment by totto82** [comment]
jenkins build this opm-parser=1118 ewoms=272 please

**Comment by totto82** [comment]
jenkins build this ewoms=272 please

**Comment by totto82** [comment]
Comments on the test failures: 

-  mpi.compareECLFiles_flow+2D_H__
Some of the summary output for FIP is 0 in the reference case, but not with this PR. 
-    mpi.compareECLFiles_flow+3D_MSW
Some of the summary output for FIP is 0 in the reference case, but not with this PR. 
-    mpi.compareECLFiles_flow+2D_THREEPHASE_POLY_HETER
Some of the summary output for FIP is 0 in the reference case, but not with this PR. 
-    mpi.compareParallelSim_flow+SPE9_CP_SHORT
Some of the summary output for FIP is 0 in the mpi case, but not without 
-    mpi.compareParallelRestartedSim_flow+SPE1CASE2_ACTNUM
It works when I manually run it from the terminal. 

Q1: Why is some of the summary output zero at "random" timestep both in the current reference solution and with this PR?
Q2: Why doesn't parallel restart works in the test suite, while working when called manually? Could this be related to specification of output_dir?

**Comment by akva2** [comment]
regarding Q2, see the error log on jenkins. something threw stuff. doesn't look output_dir related, https://ci.opm-project.org/job/opm-simulators-PR-builder/797/testReport/junit/(root)/mpi/compareParallelRestartedSim_flow_SPE1CASE2_ACTNUM/

**Comment by totto82** [comment]
> make sure you run in a clean dir. it may be using old leftovers or something?

You where right, old leftovers triggered false positive. It should be fixed now. Lets see if Jenkins agrees.

**Comment by totto82** [comment]
jenkins build this ewoms=272 please

**Comment by totto82** [comment]
@GitPaean Do you understand the remaining test failures? See Q1 in comment above.

**Comment by totto82** [comment]
The remaining failures is cased by wrong reference solution. Lets ask jenkins to provide a correct one.

**Comment by totto82** [comment]
jenkins build this ewoms=272 update_data please

**Comment by GitPaean** [comment]
> @GitPaean Do you understand the remaining test failures? See Q1 in comment above.

Sorry, I did not follow this topic closely. I do not have a idea about it.

**Comment by totto82** [comment]
> I do not have a idea about it.

Me neither. Anyway, it is fixed in the new code.

**Comment by totto82** [comment]
jenkins build this ewoms=272 opm-data=295 please

**Comment by totto82** [comment]
jenkins build this ewoms=272 opm-data=298 please

**Comment by totto82** [comment]
I have added some more to this and made a new PR. Closing this.

**Pull request closed without merging**
