### PR TITLE
Dummy commit

### PR DESCRIPTION
**Pull request by totto82**
Only to update_data

### CODE REVIEW

**Comment by totto82** [comment]
jenkins build this opm-output=185 update_data please

**Comment by totto82** [comment]
@akva2 Will this work?

**Comment by akva2** [comment]
that good enough an answer ^^^ (apart from the long queue on jenkins atm).

**Comment by totto82** [comment]
@akva2 Shouldn't 

> jenkins build this opm-output=185 update_data please

create a PR in opm-output?

**Comment by akva2** [comment]
no, it will create a pr in opm-data. however as i feared the comment after trigger caused issues, the pr builder saw '@akva2 Will this work?' as the comment.

**Comment by akva2** [comment]
jenkins build this opm-output=185 update_data please

**Comment by akva2** [comment]
jenkins build this opm-output=185 opm-data=216 please

**Comment by joakim-hove** [comment]
OK - in they go.

**Comment by akva2** [comment]
i think this warrants a quick history rewrite!

**Comment by atgeirr** [comment]
> i think this warrants a quick history rewrite! this pr was not intended for merge.

It may already be too late, as people may have updated their repos already because of other recent changes that went in etc. I suggest we do not worry about this.

**Comment by akva2** [comment]
yes, i posted that immediately after merge, now it's too late indeed.

**Comment by joakim-hove** [comment]
> i think this warrants a quick history rewrite! this pr was not intended for merge.

OK - that was my bad; sorry. Although I of course understand this PR was not very interesting to merge in it's own right I thought it was essential to get the sha listing in the opm-data commit message correct?

**Comment by akva2** [comment]
ah i didn't take that into consideration. yes you are correct on that.

**Comment by atgeirr** [comment]
Since update_data is now available on every repository (although one must remember to do it "with downstreams") I guess there is no more need for making such dummy PRs, except if you need to make Jenkins run Norne or SPE?

**Comment by akva2** [comment]
adding the run triggers is near the top of my list, expect it early next week.

**Pull request merged**
