### PR TITLE
RateConverter: throw an exception, not a bare string

### PR DESCRIPTION
**Pull request by akva2**
Unless I'm missing something..

### CODE REVIEW

**Comment by akva2** [comment]
jenkins build this please

**Comment by akva2** [comment]
jenkins build this please

**Review by bska — APPROVED** [review]
This is fine as is.  I **might** consider using `std::range_error` instead of `std::runtime_error`, but that's possibly too finicky.  On the other hand, the actual message&mdash;introduced in #4292&mdash;is not helpful to anyone but the original author.  The part concerning "only support" **may** be useful, but the fact that both numbers refer to `detR` means we lose information that might have been useful.

I'll defer to @totto82 to fix the actual message.

**Comment by akva2** [comment]
changed to range_error

**Review by bska — COMMENTED** [review]
> changed to range_error

Thanks.  This looks good to me now.  I'll just run a build check to ensure I haven't overlooked anything.  I'll merge when that's successful.

**Comment by bska** [comment]
jenkins build this please

**Comment by bska** [comment]
> I'll just run a build check to ensure I haven't overlooked anything. I'll merge when that's successful.

Build check is successful.  I'll merge this into the master branch now.

**Pull request merged**
