### PR TITLE
[For testing] Set new defaults for relaxed-max-pv-fraction and max-strict-iter

### PR DESCRIPTION
**Pull request by alfbr**
This PR sets new defaults using the new criterion introduced in https://github.com/OPM/opm-simulators/pull/2701

### CODE REVIEW

**Comment by alfbr** [comment]
benchmark please

**Comment by ytelses** [comment]
Benchmark result overview: 




| Test    | Configuration                              | Relative |
| ------- | ------------------------------------------ | -------- |
| opm-git | OPM Benchmark: flow_mpi_extra - Threads: 1 | 1.042    |
| opm-git | OPM Benchmark: flow_mpi_extra - Threads: 8 | 1.139    |
| opm-git | OPM Benchmark: flow_mpi_norne - Threads: 1 | 1.133    |
| opm-git | OPM Benchmark: flow_mpi_norne - Threads: 8 | 1.111    |
* Speed-up = Total time master / Total time pull request. Above 1.0 is an improvement. *



View result details @ https://www.ytelses.com/opm/?page=result&id=867

**Comment by blattms** [comment]
:partying_face: At least ytelses agrees with my machine.

**Comment by alfbr** [comment]
Indeed it does! I need to build a new workstation more suitable, this home office thing seems to be dragging out :-)

**Comment by alfbr** [comment]
superseeded by #2788

**Pull request closed without merging**
