### PR TITLE
restore all flags for alugrid test

### PR DESCRIPTION
**Pull request by akva2**

### CODE REVIEW

**Comment by akva2** [comment]
jenkins build this update_data please

**Comment by bska** [comment]
jenkins build this serial please

**Comment by bska** [comment]
The build check is green without updating the reference solutions.  I'm very tempted to merge this as is and not worry too much about it right now, but this does suggest that there's **something** about the new defaults that makes the tests more sensitive.

**Comment by akva2** [comment]
agreed, passing test beats not passing.

**Comment by bska** [comment]
>> I'm very tempted to merge this as is and not worry too much about it right now,
>
> agreed, passing test beats not passing.

Very good then.  I'll merge this into the master branch as is.

**Pull request merged**
