### PR TITLE
get connection length and radius from the connection object

### PR DESCRIPTION
**Pull request by totto82**
Depends on OPM/opm-common#2244

### CODE REVIEW

**Comment by totto82** [comment]
jenkins build this opm-common=2244 please

**Comment by GitPaean** [comment]
The changes introduced by this PR I can see mostly the following two: 
1. now the equivalent radius and connection length will be calculated always
2. these calculations are based on EclipseGrid instead of processed CpGrid. It might be different for some complicated situation, but we do not have such test case either. 

The above are just observation and comments. Not against this PR since we do not have a case to make the above difference.

**Comment by totto82** [comment]
> now the equivalent radius and connection length will be calculated always

It was already calculated in the wellConnections so this set of PRs just store them in the connection class instead of recalculating them. 

>these calculations are based on EclipseGrid instead of processed CpGrid. It might be different for some complicated situation, but we do not have such test case either.

The only thing I could think of is MINPV-PINCH. What happens to a connection that perforate a cell that is pinched-out?

**Comment by GitPaean** [comment]
> It was already calculated in the wellConnections so this set of PRs just store them in the connection class instead of recalculating them.

Yes. That is new in the PR from opm-common

> The only thing I could think of is MINPV-PINCH. What happens to a connection that perforate a cell that is pinched-out?

Currently, we remove that connection from the EclipseState.  I am not familiar with MINPV-PINCH, will it change the thickness of a cell during PINCH process? That is the tricky part. But I am not sure it should make in the way of the PR.  Just for commenting and discussion (if interested), possibly helpful if in future we have problem related to this(I highly doubt it.).

**Comment by totto82** [comment]
> But I am not sure it should make in the way of the PR. 

@GitPaean  Does that mean that you approve this PR?

**Comment by GitPaean** [comment]
> @GitPaean Does that mean that you approve this PR?

Sure. I can do that. We can revisit it if it causes problem.

**Comment by GitPaean** [comment]
jenkins build this please

**Pull request merged**
