### PR TITLE
Use fluidsystem in blackoilpropsadfromdeck

### PR DESCRIPTION
**Pull request by andlaus**
this makes the fluid system available via the `BlackoilPropsAdFromDeck` class (allows gradual conversion of code to the new PVT approach), removes the `BlackoilPropsAdInterface` class (because the only implementation of it was `BlackoilPropsAdFromDeck`) and converts the "rate converter" code to the new PVT approach.

### CODE REVIEW

**Comment by andlaus** [comment]
jenkins run norne norne_ebos please

**Comment by atgeirr** [comment]
The code is fine and should be merged eventually.

The well solutions (from jenkins) look fine, but are a little different from the opm reference (flow and flow-ebos seem practically identical though). This PR should not change the solution at all, so it is a little suspicious. It could be caused by outdated reference solution though.

@andlaus can you check this? If you can confirm that you get identical (not just equivalent) results with and without this, in particular for Model 2, we'll merge. Otherwise we must investigate first why we get a difference.

**Comment by andlaus** [comment]
I'll check. is the OPM reference solution different from the the one produced by the current master version?

**Comment by andlaus** [comment]
ok. I just checked: I could the "Model 2" results produced by the master version of `flow_ebos` is 'exactly' the same as the results with this branch.

possibly there were other recent changes which made the the results slightly different. (e.g, the recent SWATINIT changes.) deviate the new results more from those produced by E100 or are they just different from the reference solution?

**Comment by atgeirr** [comment]
> ok. I just checked: I could the "Model 2" results produced by the master version of flow_ebos is 'exactly' the same as the results with this branch.

Good, will merge.

**Pull request merged**
