### PR TITLE
Well interface refactoring

### PR DESCRIPTION
**Pull request by GitPaean**
This PR is created for reviewing and discussion. Some more small cleaning up is still ongoing. 

By refactoring the interfaces of the well models, StandardWells and MultisegmentWells, now the BlackoilMultisegmentModel only have one MultisegmentWells member, instead of having StandardWells as an extra member to fix the running. 

From what I saw, this PR does not cause changes in results for flow, flow_polymer, flow_solvent and flow_multisegment.

### CODE REVIEW

**Comment by alfbr** [comment]
At this point in time we should check the mpi version to prevent further fall-outs there.

**Comment by GitPaean** [comment]
> At this point in time we should check the mpi version to prevent further fall-outs there.

I tested a little bit for some running. I will test more for confirmation.

**Comment by GitPaean** [comment]
@totto82 , which is the test case for well potential calculation? Thanks.

**Comment by totto82** [comment]
I have a test case for group controls  based on SPE9. Do you want me to add it to opm-data?

**Comment by GitPaean** [comment]
Either you send it to me in email or put it in opm-data works for me. If you think the test case is ready (no big modification in future) to be put in opm-data, I think it will be good to put in the opm-data. Thanks.

**Comment by totto82** [comment]
Check out OPM/opm-data#105

**Comment by GitPaean** [comment]
I do not know what caused the following error for travis. I did not reproduce it in my computer. 

```
      Start 18: compare_restart_files
18/18 Test #18: compare_restart_files ............***Failed    0.01 sec
Running 1 test case...
unknown location(0): fatal error in "CompareRestartFileResults": memory access violation at address: 0x00000018: no mapping at fault address

*** 1 failure detected in test suite "RestartTests"


94% tests passed, 1 tests failed out of 18

Total Test time (real) =  16.04 sec

The following tests FAILED:
	 18 - compare_restart_files (Failed)
Errors while running CTest
```

**Comment by pgdr** [comment]
Travis fails on master now, and it seems like this is the reason:

> `Program threw an exception: Restart file SPE1CASE2.UNRST does not contain data for report step 60!`

We should probably make an issue and move the discussion there.

**Comment by GitPaean** [comment]
rebased while having the following test error. investigating. 

```
opm-simulators-build/bin/test_boprops_ad': corrupted double-linked list: 0x0000000001d15a20 ***
```

**Comment by GitPaean** [comment]
It looks like something from parser causes the problem, while the `test_boprops_ad` does not fail in the master branch. 

```
*** Error in `/home/kaib/OPM-devel/debug/opm-simulators-build/bin/test_boprops_ad': corrupted double-linked list: 0x0000000000e8ea20 ***

Program received signal SIGABRT, Aborted.
0x00007ffff592ccc9 in __GI_raise (sig=sig@entry=6) at ../nptl/sysdeps/unix/sysv/linux/raise.c:56
56	../nptl/sysdeps/unix/sysv/linux/raise.c: No such file or directory.
(gdb) backtrace 
#0  0x00007ffff592ccc9 in __GI_raise (sig=sig@entry=6) at ../nptl/sysdeps/unix/sysv/linux/raise.c:56
#1  0x00007ffff59300d8 in __GI_abort () at abort.c:89
#2  0x00007ffff5969394 in __libc_message (do_abort=do_abort@entry=1, fmt=fmt@entry=0x7ffff5a77b28 "*** Error in `%s': %s: 0x%s ***\n") at ../sysdeps/posix/libc_fatal.c:175
#3  0x00007ffff5974c12 in malloc_printerr (ptr=0xe8ea20, str=0x7ffff5a73bfc "corrupted double-linked list", action=1) at malloc.c:4996
#4  malloc_consolidate (av=av@entry=0x7ffff5cb4760 <main_arena>) at malloc.c:4157
#5  0x00007ffff5975df8 in _int_malloc (av=0x7ffff5cb4760 <main_arena>, bytes=1024) at malloc.c:3423
#6  0x00007ffff59787b0 in __GI___libc_malloc (bytes=1024) at malloc.c:2891
#7  0x00007ffff6235dad in operator new(unsigned long) () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#8  0x00007ffff7968257 in boost::re_detail::raw_storage::resize(unsigned long) () from /usr/lib/x86_64-linux-gnu/libboost_regex.so.1.54.0
#9  0x00007ffff7942ee8 in boost::re_detail::basic_regex_creator<char, boost::regex_traits<char, boost::cpp_regex_traits<char> > >::append_state(boost::re_detail::syntax_element_type, unsigned long) () from /usr/lib/x86_64-linux-gnu/libboost_regex.so.1.54.0
#10 0x00007ffff7952d2d in boost::re_detail::basic_regex_parser<char, boost::regex_traits<char, boost::cpp_regex_traits<char> > >::parse(char const*, char const*, unsigned int) () from /usr/lib/x86_64-linux-gnu/libboost_regex.so.1.54.0
#11 0x00007ffff7953139 in boost::basic_regex<char, boost::regex_traits<char, boost::cpp_regex_traits<char> > >::do_assign(char const*, char const*, unsigned int) () from /usr/lib/x86_64-linux-gnu/libboost_regex.so.1.54.0
#12 0x0000000000a34daa in boost::basic_regex<char, boost::regex_traits<char, boost::cpp_regex_traits<char> > >::assign (this=0x7fffffffc330, p1=0xe93288 "BU.+|BTIPF.+|BTIPS.+|BTCNF.+|BTCNS.+|BTCN[1-9][0-9]*.+|BTIPT.+|BTIPF.+|BTIPS.+|BTIP[1-9][0-9]*.+|BTADS.+|BTDCY", 
    p2=0xe932f6 "", f=0) at /usr/include/boost/regex/v4/basic_regex.hpp:382
#13 0x0000000000a34813 in boost::basic_regex<char, boost::regex_traits<char, boost::cpp_regex_traits<char> > >::assign<std::char_traits<char>, std::allocator<char> > (this=0x7fffffffc330, 
    s="BU.+|BTIPF.+|BTIPS.+|BTCNF.+|BTCNS.+|BTCN[1-9][0-9]*.+|BTIPT.+|BTIPF.+|BTIPS.+|BTIP[1-9][0-9]*.+|BTADS.+|BTDCY", f=0) at /usr/include/boost/regex/v4/basic_regex.hpp:420
#14 0x0000000000a3407c in boost::basic_regex<char, boost::regex_traits<char, boost::cpp_regex_traits<char> > >::basic_regex<std::char_traits<char>, std::allocator<char> > (this=0x7fffffffc330, 
    p="BU.+|BTIPF.+|BTIPS.+|BTCNF.+|BTCNS.+|BTCN[1-9][0-9]*.+|BTIPT.+|BTIPF.+|BTIPS.+|BTIP[1-9][0-9]*.+|BTADS.+|BTDCY", f=0) at /usr/include/boost/regex/v4/basic_regex.hpp:395
#15 0x0000000000a314c5 in Opm::ParserKeyword::setMatchRegex (this=0xe93700, deckNameRegexp="BU.+|BTIPF.+|BTIPS.+|BTCNF.+|BTCNS.+|BTCN[1-9][0-9]*.+|BTIPT.+|BTIPF.+|BTIPS.+|BTIP[1-9][0-9]*.+|BTADS.+|BTDCY")
    at /home/kaib/OPM-devel/debug/opm-parser/opm/parser/eclipse/Parser/ParserKeyword.cpp:532
#16 0x00000000008fc634 in Opm::ParserKeywords::BLOCK_PROBE::BLOCK_PROBE (this=0xe93700) at /home/kaib/OPM-devel/debug/opm-parser-build/generated-source/ParserKeywords.cpp:623
#17 0x00000000009fbae0 in Opm::Parser::addKeyword<Opm::ParserKeywords::BLOCK_PROBE> (this=0xe894f0) at /home/kaib/OPM-devel/debug/opm-parser/opm/parser/eclipse/Parser/Parser.hpp:94
#18 0x00000000009faf91 in Opm::ParserKeywords::addDefaultKeywords0 (p=...) at /home/kaib/OPM-devel/debug/opm-parser-build/generated-source/ParserKeywords0.cpp:26
#19 0x00000000009d0f5e in Opm::Parser::addDefaultKeywords (this=0xe894f0) at /home/kaib/OPM-devel/debug/opm-parser-build/generated-source/ParserKeywords.cpp:13729
#20 0x00000000008c23be in Opm::Parser::Parser (this=0xe894f0, addDefault=true) at /home/kaib/OPM-devel/debug/opm-parser/opm/parser/eclipse/Parser/Parser.cpp:571
#21 0x0000000000733952 in SetupSimple::SetupSimple (this=this@entry=0x7fffffffce90) at /home/kaib/OPM-devel/debug/opm-simulators/tests/test_boprops_ad.cpp:52
#22 0x00000000007341cd in TestFixtureAd<SetupSimple>::TestFixtureAd (this=this@entry=0x7fffffffce90) at /home/kaib/OPM-devel/debug/opm-simulators/tests/test_boprops_ad.cpp:94
#23 0x000000000072dfed in SubgridConstruction (this=0x7fffffffce90) at /home/kaib/OPM-devel/debug/opm-simulators/tests/test_boprops_ad.cpp:111
#24 SubgridConstruction_invoker () at /home/kaib/OPM-devel/debug/opm-simulators/tests/test_boprops_ad.cpp:111
#25 0x000000000072e407 in invoke<void (*)()> (this=<optimized out>, f=<optimized out>) at /usr/include/boost/test/utils/callback.hpp:56
#26 boost::unit_test::ut_detail::callback0_impl_t<boost::unit_test::ut_detail::unused, void (*)()>::invoke (this=<optimized out>) at /usr/include/boost/test/utils/callback.hpp:89
#27 0x00007ffff65431f1 in ?? () from /usr/lib/x86_64-linux-gnu/libboost_unit_test_framework.so.1.54.0
#28 0x00007ffff651e546 in boost::execution_monitor::catch_signals(boost::unit_test::callback0<int> const&) () from /usr/lib/x86_64-linux-gnu/libboost_unit_test_framework.so.1.54.0
#29 0x00007ffff651ed83 in boost::execution_monitor::execute(boost::unit_test::callback0<int> const&) () from /usr/lib/x86_64-linux-gnu/libboost_unit_test_framework.so.1.54.0
#30 0x00007ffff65432f2 in boost::unit_test::unit_test_monitor_t::execute_and_translate(boost::unit_test::test_case const&) () from /usr/lib/x86_64-linux-gnu/libboost_unit_test_framework.so.1.54.0
#31 0x00007ffff652cf94 in boost::unit_test::framework_impl::visit(boost::unit_test::test_case const&) () from /usr/lib/x86_64-linux-gnu/libboost_unit_test_framework.so.1.54.0
#32 0x00007ffff655bd23 in boost::unit_test::traverse_test_tree(boost::unit_test::test_suite const&, boost::unit_test::test_tree_visitor&) () from /usr/lib/x86_64-linux-gnu/libboost_unit_test_framework.so.1.54.0
#33 0x00007ffff65284ba in boost::unit_test::framework::run(unsigned long, bool) () from /usr/lib/x86_64-linux-gnu/libboost_unit_test_framework.so.1.54.0
#34 0x00007ffff6540ed4 in boost::unit_test::unit_test_main(bool (*)(), int, char**) () from /usr/lib/x86_64-linux-gnu/libboost_unit_test_framework.so.1.54.0
#35 0x00007ffff5917ec5 in __libc_start_main (main=0x7282e0 <main(int, char**)>, argc=1, argv=0x7fffffffde58, init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7fffffffde48) at libc-start.c:287
#36 0x000000000072ba10 in _start ()
```

**Comment by GitPaean** [comment]
Travis is happy, which does not make things any better.

**Comment by pgdr** [comment]
I cannot reproduce this, and while I don't claim parser to be without guilt, `opmi` runs just fine on `fluid.data`.

I see one difference; you are using `boost::regex` whereas I use `std::regex`.

**Comment by GitPaean** [comment]
Thanks for the testing. The problem disappeared after a rebooting and re-compilation. I am not sure what triggered the problem.  Thanks. 

I saw the problem yesterday and reproduced it several times this morning.

**Comment by jokva** [comment]
Gut feeling says linking to an incompatible .so which wrecked libc++'s pointer management.

**Comment by atgeirr** [comment]
Thanks for the patch! I have now gone through the changes and they look fine. Will merge.

**Pull request merged**
