### PR TITLE
add regression test for flow_polymer

### PR DESCRIPTION
**Pull request by akva2**
Note: This is just a suggestion, if you prefer to not add this, just say so.

The current files in opm-data will fail, so an update_data has to be performed if this is wanted. You have to merge https://github.com/OPM/opm-data/pull/217 before doing the update.

### CODE REVIEW

**Comment by atgeirr** [comment]
jenkins build this please

**Comment by atgeirr** [comment]
@akva2 the test failure for the polymer case is expected, but it also fails for the two-phase test, with this exception:

Program threw an exception: Cannot find input case /var/lib/jenkins/workspace/opm-simulators-PR-builder/deps/opm-data/spe1_2p/SPE1CASE2_2P

Do you know what causes this? I am reluctant to go through the update_data dance until I understand this.

**Comment by akva2** [comment]
just me forgetting to commit last version. fixed now (wasn't in my office yesterday hence late response..)

**Comment by akva2** [comment]
jenkins build this please

**Comment by atgeirr** [comment]
jenkins build this update_data please

**Comment by akva2** [comment]
grrrr..

**Comment by akva2** [comment]
jenkins build this update_data please

**Comment by akva2** [comment]
jenkins build this opm-data=222 please

**Comment by akva2** [comment]
sorry for just jumping in but i felt reponsible.. was a silly 2d vs 2D issue.

**Comment by akva2** [comment]
all green

**Comment by atgeirr** [comment]
So now we have a polymer integration test! Solvent next...

**Comment by akva2** [comment]
i need to know the best deck to use for solvent.

**Comment by atgeirr** [comment]
> i need to know the best deck to use for solvent.

@totto82 that one is yours!

**Comment by totto82** [comment]
I think SPE5CASE1 is the best deck to use. An alternative is SPE1CASE2_SOLVENT_MISC_TL if the SPE5 case is to slow. You will find them in solvent_test_suite/

**Pull request merged**
