### PR TITLE
Install bc in travis.

### PR DESCRIPTION
**Pull request by joakim-hove**

### CODE REVIEW

**Comment by blattms** [comment]
Great! Thanks!

**Comment by atgeirr** [comment]
I'll use this PR to test Jenkins, since it should not do anything remotely affecting it.

**Comment by atgeirr** [comment]
jenkins build this please

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by joakim-hove** [comment]
jenkins build this ert=1467 update_data please

**Comment by joakim-hove** [comment]
jenkins build this ert=1467 opm-data=194 please

**Pull request merged**
