### PR TITLE
Change wellStateFromTarget to virtual to make sure the MSW part is run

### PR DESCRIPTION
**Pull request by totto82**

### CODE REVIEW

**Comment by totto82** [comment]
jenkins build this please

**Comment by totto82** [comment]
This fix a fallout and just be merged. I have checked the test failures and tested this on some selected norne msw prediction models. I will run an update data. Thanks to @atgeirr for noticing the issue.

**Comment by totto82** [comment]
jenkins build this update_data please

**Review by atgeirr — APPROVED** [review]

**Comment by bska** [comment]
jenkins build this opm-tests=555 please

**Comment by totto82** [comment]
I have merged the ref data. How can I know when it is safe to merge this.

**Comment by bska** [comment]
> I have merged the ref data. How can I know when it is safe to merge this.

I generally wait until the [opm-tests](https://ci.opm-project.org/job/opm-tests/) job actually **runs**, i.e., that the post-commit build is not just in the build queue.

**Pull request merged**
