### PR TITLE
add ewoms to the list upstream modules for jenkins

### PR DESCRIPTION
**Pull request by andlaus**
thanks goes to @akva2 for pointing this out...

I'll self merge this once jenkins is happy because it is only for the frankenstein branch and pretty trivial.

### CODE REVIEW

**Comment by andlaus** [comment]
jenkins build this opm-common=162 please

**Comment by akva2** [comment]
Please remove the @ from commit message. Every time somebody rebase that commit i get a mail.

**Comment by andlaus** [comment]
done.

**Comment by andlaus** [comment]
jenkins build this opm-common=162 please

**Comment by andlaus** [comment]
jenkins is happy! merge this please.

**Pull request merged**
