### PR TITLE
Start using face geometry computed the Ecl way

### PR DESCRIPTION
**Pull request by totto82**
Face centers are computed using the cell corners. With this
implementation the face center seen from a cell may be different from the
face center seen from its neighbor.

Face normals with area lengths are calculated using the face corners
directly not using a triangulation point in the center of the face.

This gives transmissibility almost equal to eclipse.

Depends on OPM/opm-grid#261

### CODE REVIEW

**Comment by atgeirr** [comment]
jenkins run norne please

**Comment by atgeirr** [comment]
jenkins run norne please

**Comment by totto82** [comment]
The Jenkins failure is expected as this will effect results. But 
why is travis failing? OPM/opm-grid#261 is merged.

**Comment by joakim-hove** [comment]
> But why is travis failing?

Same reason as Jenkins - Travis will run all the tests configured.

**Comment by atgeirr** [comment]
jenkins run norne_ebos please

**Comment by andlaus** [comment]
this should only affect flow_legacy, so:

**Comment by andlaus** [comment]
jenkins run norne please

**Comment by alfbr** [comment]
> this should only affect flow_legacy, so:

Are you sure? I thought this impacted the transmissibilities on the output side for flow_ebos.

**Comment by andlaus** [comment]
> Are you sure? I thought this impacted the transmissibilities on the output side for flow_ebos.

yes, that's true as far as I know. On the other hand, I'm pretty sure that the GeoProps do not affect the dynamic simulation results of the reservoir or the summary curves of flow_ebos.

**Comment by atgeirr** [comment]
jenkins build this update_data please

**Comment by atgeirr** [comment]
jenkins build this opm-data=181 please

**Pull request merged**
