### PR TITLE
fixing and improvement of the Aquifer models

### PR DESCRIPTION
**Pull request by GitPaean**
The major fixes include two parts, incorporating the derivatives from pressure difference, and correcting the way to calculate the initial aquifer pressure, which is important when the initial aquifer pressure is not specified. 

With this PR and the several merged PRs from opm-common, flow managed to give very good results in the targeting aquifer case with Fetkovich aquifers.  

There will be some cleaning up related to aquifer models, maybe also some fixes should be applied to CT aquifer too.

### CODE REVIEW

**Comment by GitPaean** [comment]
jenkins build this please

**Comment by GitPaean** [comment]
jenkins build this please

**Comment by GitPaean** [comment]
Due to the lack of the working example for Carter Tracy aquifer, the refactoring of the both models will remain to be done later.  I am removing the [WIP] tag now. 

In the previous jenkins test, there is the following test failure, which is totally expected. 
```
mpi.compareECLFiles_flow+2D_FETKOVICHAQUIFER
```

I am preforming the `update_data` now.

**Comment by GitPaean** [comment]
jenkins build this update_data please

**Comment by GitPaean** [comment]
jenkins build this opm-tests=184 please

**Comment by GitPaean** [comment]
jenkins build this opm-tests=184 please

**Comment by alfbr** [comment]
> Due to the lack of the working example for Carter Tracy aquifer

@GitPaean  please elaborate. I believe there is one 2D example in opm-tests under aquifer-oilwater. Do you miss reference results for that one or do you need another case. If so, do you have specific requirements for a new case?

**Comment by GitPaean** [comment]
> @GitPaean please elaborate. I believe there is one 2D example in opm-tests under aquifer-oilwater.

That is a simple case that the master branch handles well. We need a test case with more complicated setup that the master branch can not handle.

For the Fetkowich aquifer, we have a real case, which is the reason we created this PR and the several PRs in opm-common. 

But we do not have something similar for the Carter Tracy aquifer.

**Comment by GitPaean** [comment]
>  do you need another case. If so, do you have specific requirements for a new case?

We will need an another case, with multiple connections, and default initial aquifer pressure with reference result. 

Sorry for not answering the message all by once. It was a little busy here.

**Pull request merged**
