### PR TITLE
I have included the regression test for SPE1CASE1 using flow.

### PR DESCRIPTION
**Pull request by andreatlonn**

### CODE REVIEW

**Comment by akva2** [comment]
good start, but you also have to update tests/update_reference_data.sh

**Comment by akva2** [comment]
i can't decide whether tests or not make sense, but there is no technical reason this can't be merged now.

**Comment by akva2** [comment]
jenkins build this please

**Comment by GitPaean** [comment]
this PR needs to adapt to the change of the merged PR https://github.com/OPM/opm-simulators/pull/1528 .

**Comment by akva2** [comment]
no, we don't do it like that. we use rebase functionality

1) git fetch upstream
2) git rebase upstream/master
   - fix the conflicts, then git add <files in conflict>
   - use git rebase --continue

**Comment by joakim-hove** [comment]
I am sorry; but I just could not resist:

> Manually updated update_reference_data.sh

if we are now moving into a situation where different people are making changes and updates to this machinery, could I suggest an alternative to bash?

I have put on my full asbestos - so just fire away; I will not answer the fire :-)

**Comment by akva2** [comment]
show me the language that doesn't conflict when the script is rewritten and i will consider it.

**Comment by alfbr** [comment]
Please guys, just ignore for a while. The appropriate conflict resolution is on its way.

**Comment by akva2** [comment]
jenkins build this update_data please

**Comment by akva2** [comment]
jenkins build this opm-tests=37 please

**Comment by akva2** [comment]
all green, merging. congrats with your first opm contribution!

**Pull request merged**
