### PR TITLE
Using optional restart loading instead of extra.

### PR DESCRIPTION
**Pull request by joakim-hove**
Followup to: https://github.com/OPM/opm-output/pull/180

### CODE REVIEW

**Comment by joakim-hove** [comment]
jenkins build this opm-output=180 please

**Comment by atgeirr** [comment]
Is there something wrong with Jenkins privileges? I'll start a job.

**Comment by atgeirr** [comment]
jenkins build this opm-output=180 please

**Comment by joakim-hove** [comment]
> Is there something wrong with Jenkins privileges? I'll start a job.

Thank you - a typo sneaked in; but I guess this is post-release stuff anyway.

**Comment by atgeirr** [comment]
jenkins build this opm-output=180 please

**Comment by joakim-hove** [comment]
jenkins build this opm-output=180 please

**Comment by joakim-hove** [comment]
OK - I managed to dot all the I's and cross all the t's before midnight, so in some sense you could say I managed the release deadline?! If someone wants to merge this and  https://github.com/OPM/opm-output/pull/180 that is cool; otherwise I will come back to it after the release/easter holiday.

**Comment by atgeirr** [comment]
Looks good, will merge as requested as it was done in time :-)

**Pull request merged**
