### PR TITLE
Parts of the distributed well work backported to original approach.

### PR DESCRIPTION
**Pull request by blattms**
This PR contains changes I did when working on supporting on distributed wells that should work with the current approach, too.

It is posted to:
- get at least some smaller PRs
- Easily test changes that do not rely on wells being distrubuted with the current approach.

Would be nice to merge this if it is ok.

### CODE REVIEW

**Comment by blattms** [comment]
jenkins build this please

**Comment by blattms** [comment]
jenkins build this please

**Comment by blattms** [comment]
jenkins run norne please

**Comment by atgeirr** [comment]
This is good, merging.

**Comment by blattms** [comment]
Thanks.

**Pull request merged**
