### PR TITLE
move solveWellEquation inside prepareTimeStep

### PR DESCRIPTION
**Pull request by totto82**
Due to the many test failures of #3158 I decided to chop in into three.This is the first part. 

This is almost a pure refactoring, but note that the  the `updateWellControls(local_deferredLogger, /* check group controls */ false);
` inside the `if (param_.solve_welleq_initially_ && iterationIdx == 0) {` is missing.

### CODE REVIEW

**Comment by totto82** [comment]
jenkins build this please

**Comment by totto82** [comment]
benchmark please

**Comment by ytelses** [comment]
Benchmark result overview: 




| Test    | Configuration                                     | Relative |
| ------- | ------------------------------------------------- | -------- |
| opm-git | OPM Benchmark: flow_mpi_extra - Threads: 1        | 1.022    |
| opm-git | OPM Benchmark: flow_mpi_extra - Threads: 8        | 0.997    |
| opm-git | OPM Benchmark: flow_mpi_norne - Threads: 1        | 1.001    |
| opm-git | OPM Benchmark: flow_mpi_norne - Threads: 8        | 0.961    |
| opm-git | OPM Benchmark: flow_mpi_norne_4c_msw - Threads: 1 | 0.989    |
| opm-git | OPM Benchmark: flow_mpi_norne_4c_msw - Threads: 8 | 0.831    |
* Speed-up = Total time master / Total time pull request. Above 1.0 is an improvement. *



View result details @ https://www.ytelses.com/opm/?page=result&id=1167

**Comment by totto82** [comment]
jenkins build this please

**Comment by totto82** [comment]
benchmark please

**Comment by totto82** [comment]
jenkins build this please

**Comment by ytelses** [comment]
Benchmark result overview: 




| Test    | Configuration                                     | Relative |
| ------- | ------------------------------------------------- | -------- |
| opm-git | OPM Benchmark: flow_mpi_extra - Threads: 1        | 1.019    |
| opm-git | OPM Benchmark: flow_mpi_extra - Threads: 8        | 0.998    |
| opm-git | OPM Benchmark: flow_mpi_norne - Threads: 1        | 1.001    |
| opm-git | OPM Benchmark: flow_mpi_norne - Threads: 8        | 0.999    |
| opm-git | OPM Benchmark: flow_mpi_norne_4c_msw - Threads: 1 | 0.964    |
| opm-git | OPM Benchmark: flow_mpi_norne_4c_msw - Threads: 8 | 0.924    |
* Speed-up = Total time master / Total time pull request. Above 1.0 is an improvement. *



View result details @ https://www.ytelses.com/opm/?page=result&id=1173

**Comment by totto82** [comment]
benchmark please

**Comment by ytelses** [comment]
Benchmark result overview: 




| Test    | Configuration                                     | Relative |
| ------- | ------------------------------------------------- | -------- |
| opm-git | OPM Benchmark: flow_mpi_extra - Threads: 1        | 1.008    |
| opm-git | OPM Benchmark: flow_mpi_extra - Threads: 8        | 0.991    |
| opm-git | OPM Benchmark: flow_mpi_norne - Threads: 1        | 0.984    |
| opm-git | OPM Benchmark: flow_mpi_norne - Threads: 8        | 0.999    |
| opm-git | OPM Benchmark: flow_mpi_norne_4c_msw - Threads: 1 | 0.692    |
| opm-git | OPM Benchmark: flow_mpi_norne_4c_msw - Threads: 8 | 0.764    |
* Speed-up = Total time master / Total time pull request. Above 1.0 is an improvement. *



View result details @ https://www.ytelses.com/opm/?page=result&id=1178

**Comment by totto82** [comment]
jenkins build this please

**Comment by totto82** [comment]
benchmark please

**Comment by ytelses** [comment]
Benchmark result overview: 




| Test    | Configuration                                     | Relative |
| ------- | ------------------------------------------------- | -------- |
| opm-git | OPM Benchmark: flow_mpi_extra - Threads: 1        | 0.993    |
| opm-git | OPM Benchmark: flow_mpi_extra - Threads: 8        | 1.097    |
| opm-git | OPM Benchmark: flow_mpi_norne - Threads: 1        | 1        |
| opm-git | OPM Benchmark: flow_mpi_norne - Threads: 8        | 1.048    |
| opm-git | OPM Benchmark: flow_mpi_norne_4c_msw - Threads: 1 | 1.128    |
| opm-git | OPM Benchmark: flow_mpi_norne_4c_msw - Threads: 8 | 1.279    |
* Speed-up = Total time master / Total time pull request. Above 1.0 is an improvement. *



View result details @ https://www.ytelses.com/opm/?page=result&id=1186

**Comment by totto82** [comment]
I have manually investigate the test failures. They are minor for most parts. Some noise in the convergence. The only systematic difference I noticed is some extra iterations for the UDQ related test cases. I will investigate them I bit more closely.  


```
mpi.compareECLFiles_flow+SPE1CASE1_METRIC_VFP1 ok
mpi.compareECLFiles_flow+SPE9_CP_SHORT ok
mpi.compareECLFiles_flow+SPE9_CP_GROUP ok
mpi.compareECLFiles_flow+2D_POLYMER_INJECTIVITY ok
mpi.compareECLFiles_flow+BASE_MODEL_1 ok
mpi.compareECLFiles_flow+MSW_MODEL_1 ok
mpi.compareECLFiles_flow+0A1_GRCTRL_LRAT_ORAT_BASE_MODEL2_STW ok
mpi.compareECLFiles_flow+FAULTS_MODEL_1 ok
mpi.compareECLFiles_flow+0A1_GRCTRL_LRAT_ORAT_BASE_MODEL2_MSW ok
mpi.compareECLFiles_flow+0A2_GRCTRL_LRAT_ORAT_GGR_BASE_MODEL2_STW ok
mpi.compareECLFiles_flow+0A2_GRCTRL_LRAT_ORAT_GGR_BASE_MODEL2_MSW ok
mpi.compareECLFiles_flow+0A3_GRCTRL_LRAT_LRAT_BASE_MODEL2_STW ok
mpi.compareECLFiles_flow+0A3_GRCTRL_LRAT_LRAT_BASE_MODEL2_MSW ok
mpi.compareECLFiles_flow+0A4_GRCTRL_LRAT_LRAT_GGR_BASE_MODEL2_STW ok
mpi.compareECLFiles_flow+UDQ_ACTIONX (33 != 37)
mpi.compareECLFiles_flow+0A4_GRCTRL_LRAT_LRAT_GGR_BASE_MODEL2_MSW ok
mpi.compareECLFiles_flow+UDQ_WCONPROD (31 != 30)
mpi.compareECLFiles_flow+0_BASE_MODEL2 (65 != 67)
mpi.compareECLFiles_flow+ACTIONX_M1 (186 != 185)
mpi.compareECLFiles_flow+UDQ_M2 ok
mpi.compareECLFiles_flow+UDQ_M3 (22 != 24)
mpi.compareECLFiles_flow+UDQ_M1 (49 != 52)
mpi.compareECLFiles_flow+PYACTION_WCONPROD (31 != 30)
mpi.compareECLFiles_flow+1_MULTREGT_MODEL2 (71 != 73)
mpi.compareECLFiles_flow+2_MULTXYZ_MODEL2 ok
mpi.compareECLFiles_flow+3_MULTFLT_MODEL2 (62 != 60)
mpi.compareECLFiles_flow+4_MINPVV_MODEL2 (62 != 60)
mpi.compareECLFiles_flow+5_SWATINIT_MODEL2 ok
mpi.compareECLFiles_flow+6_ENDSCALE_MODEL2 (62 != 60)
mpi.compareECLFiles_flow+8_MULTIPLY_TRANXYZ_MODEL2 (65 != 64)
mpi.compareECLFiles_flow+7_HYSTERESIS_MODEL2 ok
mpi.compareECLFiles_flow+9_1A_DEPL_MAX_RATE_MIN_BHP_STW ok
mpi.compareECLFiles_flow+9_EDITNNC_MODEL2 (63 != 62)
mpi.compareECLFiles_flow+9_1B_DEPL_MAX_RATE_MIN_THP_STW (32 != 30)
mpi.compareECLFiles_flow+9_2A_DEPL_GCONPROD_1L_STW (30 != 32)
mpi.compareECLFiles_flow+9_2B_DEPL_GCONPROD_2L_STW ok
mpi.compareECLFiles_flow+9_2A_DEPL_GCONPROD_1L_MSW (32 != 33)
mpi.compareECLFiles_flow+9_3A_GINJ_REIN-G_STW (34 != 33)
mpi.compareECLFiles_flow+9_2B_DEPL_GCONPROD_2L_MSW ok
mpi.compareECLFiles_flow+9_3B_GINJ_GAS_EXPORT_STW (34 != 33)
mpi.compareECLFiles_flow+9_3A_GINJ_REIN-G_MSW (30 != 31)
mpi.compareECLFiles_flow+9_3C_GINJ_GAS_GCONSUMP_STW ok 
mpi.compareECLFiles_flow+9_3B_GINJ_GAS_EXPORT_MSW (30 != 31)
mpi.compareECLFiles_flow+9_3E_GAS_MIN_EXPORT_STW (25 != 26)
mpi.compareECLFiles_flow+9_3D_GINJ_GAS_MAX_EXPORT_STW (39 != 37)
mpi.compareECLFiles_flow+9_3C_GINJ_GAS_GCONSUMP_MSW (30 != 31)
mpi.compareECLFiles_flow+9_3E_GAS_MIN_EXPORT_MSW (25 != 26)
mpi.compareECLFiles_flow+9_3D_GINJ_GAS_MAX_EXPORT_MSW (32 != 33)
mpi.compareECLFiles_flow+9_4A_WINJ_MAXWRATES_MAXBHP_GCONPROD_1L_STW (31 != 32)
mpi.compareECLFiles_flow+9_4B_WINJ_VREP-W_STW (33 != 32)
mpi.compareECLFiles_flow+9_4A_WINJ_MAXWRATES_MAXBHP_GCONPROD_1L_MSW (32 != 31)
mpi.compareECLFiles_flow+9_4C_WINJ_GINJ_VREP-W_REIN-G_STW (39 != 43)
mpi.compareECLFiles_flow+9_4B_WINJ_VREP-W_MSW (31 != 32)
mpi.compareECLFiles_flow+9_4D_WINJ_GINJ_GAS_EXPORT_STW (39 != 43)
mpi.compareECLFiles_flow+9_4C_WINJ_GINJ_VREP-W_REIN-G_MSW (32 != 31)
mpi.compareECLFiles_flow+9_4D_WINJ_GINJ_GAS_EXPORT_MSW (32 != 31)
mpi.compareECLFiles_flow+BASE_MSW_WSEGAICD ok
mpi.compareECLFiles_flow+COMPL_SMRY ok
mpi.compareECLFiles_flow+NORNE_ATW2013_B1H_RE-PERF ok
mpi.compareECLFiles_flow+MOD4_UDQ_ACTIONX (91 != 96)
mpi.compareECLFiles_flow+MOD4_GRP (95 != 105)
```

**Comment by totto82** [comment]
jenkins build this please

**Comment by totto82** [comment]
This is ready to be merged. I will start the update data process when #3184 is merged.

**Comment by GitPaean** [comment]
Do you understand why this PR causes the result different?

**Comment by totto82** [comment]
It changes the order of updateWellControl and solveWellEq.
Before its was 
```
1) updateWellControls(..., check group control = true)
2) solve well eq
3) updateWellControls(..., check group control = false)
```

Now it is
```
1) solve well eq
2) updateWellControls(..., check group control = true)
```

I have tested different version of this. Look for all the benchmark logs in the PR. It seems the logic as in the PR today gives best performance.

**Comment by GitPaean** [comment]
I think the main difference between this approach is the wells can be under different controls when `solveWellEq`. But it is very difficult to evaluate the consequence of this. Testing running can be one way to help. We can take your observation from the testing.

**Comment by totto82** [comment]
jenkins build this update_data please

**Comment by totto82** [comment]
jenkins build this opm-tests=530 please

**Comment by totto82** [comment]
@GitPaean What do think about merging this. From point of view it is ready.

**Comment by GitPaean** [comment]
> @GitPaean What do think about merging this. From point of view it is ready.

I have no objections if the test results are well checked. The bechmark result from `ytelses`  looks good.

**Pull request merged**
