### PR TITLE
Fully implicit incompressible oil-water simulator

### PR DESCRIPTION
**Pull request by qilicun**
This PR  introduces the fully implicit incompressible oil-water simulator, include follow features.
- Incompressible properties based on AD, which will is used not only just here, but also for the  upcoming fully implicit incompressible oil-water-polymer simulator.
  - IncompPropsAdBasic.cpp is used to create a fast and simple prototype.
- sim_fi2p_incomp_ad is the simulator, can handle BHP and SURFACE_RATE type well controls, the same with sim_fibo_ad.
-  for .gitignore file, this my local setting, usually I build the code in `build/` directory, to be honest I don't want to push this file to the base, but the problem is that I don't how to not include it ...

Any comment is appreciated!

### CODE REVIEW

**Comment by atgeirr** [comment]
This has been left out to dry for far too long, for which I am sorry. To be clear, I do want this simulator capability to be included and merged! However, I am not sure we are able to get this into a mergeable state before the 2015.04 release. The following at least needs to be done:
 - The PR must be made mergeable again. This should not be too much work, as it consists mostly of entirely new files.
 - It must compile properly. Since the PR was created there have been some API changes (for example in AutoDiffBlock, also the property classes now expect a temperature argument) that must be adapted to before it will compile. This may be a bit of work.
 - It must run properly. Do we have any test cases for this code? Even just running a quarter-five-spot properly would be enough for me to merge it.
 - It must be reviewed at least to some extent (my task). Although running a test case is more important.

For now I add this PR to the fall release milestone (2015.10). @qilicun, if you think it can be finished for the spring release, please say so and I'll reconsider.

**Comment by qilicun** [comment]
@atgeirr 
Thanks for your comments, but I'm sorry that I don't think I can finish that before the coming release, I would hope I can finish it before the next release!

**Comment by atgeirr** [comment]
> I would hope I can finish it before the next release, I mean 2015.10.

I hope so too, and I will make an effort to get it merged before that.

**Comment by atgeirr** [comment]
> I hope so too, and I will make an effort to get it merged before that.

As it turned out, we did not have the time to make that effort, while it is clear that we want this simulator (and its support classes) to be merged eventually. Postponing it to the next release (again).

**Comment by andlaus** [comment]
I suppose this one can be closed: it's quite old, not mergeable and if I see this correctly both `flow_legacy` and `flow_ebos` now support water-oil simulations, so maybe an incompressible solver is not required? @qilicun: do you plan to work this?

**Comment by atgeirr** [comment]
I agree, we will close this now. @qilicun feel free to resurrect it if you feel it is worth the time to complete it.

**Pull request closed without merging**
