### PR TITLE
Fixing MSW connection pressure output

### PR DESCRIPTION
**Pull request by vkip**
Fixing connection pressure output for the MSW model (currently the grid block pressures corrected to perforation depth is output instead).

### CODE REVIEW

**Comment by blattms** [comment]
jenkins build this please

**Comment by vkip** [comment]
To see the problem, add the following to the SUMMARY section in opm-tests/MSW_MODEL_1.DATA 

CPR 
  '*' /
/

Attached image demonstrates that the new version corresponds to the reference simulator. 
image

**Review by bska — COMMENTED** [review]
I think this looks like the correct fix, but I'd like @GitPaean to have a look too.  The [regression failures](https://ci.opm-project.org/job/opm-simulators-PR-builder/4568/testReport/) are all because we store the connection pressure in the restart file's `XCON` array and they all look reasonable.  We'll have to update the reference solutions in order to merge this.  I will do that once the change itself is approved.

**Review by GitPaean — APPROVED** [review]
Thanks a lot for the contribution and it looks correct to me. With the verification against reference results, this is the way to go!

**Comment by GitPaean** [comment]
We ran into the same question when implementing the WINJMULT for MSW, which requires the perforation pressure.  It looks like we adopted the same formula as in this PR, while we did not think about fix the output related to CPR back then. 

Very great it gets fixed now for the output.

**Comment by GitPaean** [comment]
Jenkins build this update_data please

**Comment by bska** [comment]
jenkins build this opm-tests=899 please

**Comment by bska** [comment]
The new reference solutions have been installed on the CI system.  Merging this now to bring the overall system back to a consistent state.

**Pull request merged**
