### PR TITLE
removing white spaces in the wells folder

### PR DESCRIPTION
**Pull request by GitPaean**
mostly to test the benchmark for the master branch. But the PR iteself can be merged.  

It is to check the benchmark for PR https://github.com/OPM/opm-simulators/pull/4902 . One case did not run through with the PR, while not sure it is because of the PR.

### CODE REVIEW

**Comment by GitPaean** [comment]
benchmark please

**Comment by GitPaean** [comment]
jenkins build this please

**Comment by ytelses** [comment]
Benchmark result overview: 




| Test | Configuration | Relative |
| ---- | ------------- | -------- |
* Speed-up = Total time master / Total time pull request. Above 1.0 is an improvement. *

FAILED RUNS: 
OPM Benchmark: drogon - Threads: 1 - 2023-10-09 Master Reference: The test run did not produce a result. E: mpirun was unable to launch the specified application as it could not access
OPM Benchmark: drogon - Threads: 1 - opm-simulators 4918: testing removing white spaces in the wells folder: The test run did not produce a result. E: mpirun was unable to launch the specified application as it could not access
OPM Benchmark: drogon - Threads: 8 - 2023-10-09 Master Reference: The test run did not produce a result. E: mpirun was unable to launch the specified application as it could not access
OPM Benchmark: drogon - Threads: 8 - opm-simulators 4918: testing removing white spaces in the wells folder: The test run did not produce a result. E: mpirun was unable to launch the specified application as it could not access
OPM Benchmark: punqs3 - Threads: 1 - 2023-10-09 Master Reference: The test run did not produce a result. E: mpirun was unable to launch the specified application as it could not access
OPM Benchmark: punqs3 - Threads: 1 - opm-simulators 4918: testing removing white spaces in the wells folder: The test run did not produce a result. E: mpirun was unable to launch the specified application as it could not access
OPM Benchmark: punqs3 - Threads: 8 - 2023-10-09 Master Reference: The test run did not produce a result. E: mpirun was unable to launch the specified application as it could not access
OPM Benchmark: punqs3 - Threads: 8 - opm-simulators 4918: testing removing white spaces in the wells folder: The test run did not produce a result. E: mpirun was unable to launch the specified application as it could not access
OPM Benchmark: smeaheia - Threads: 1 - 2023-10-09 Master Reference: The test run did not produce a result. E: mpirun was unable to launch the specified application as it could not access
OPM Benchmark: smeaheia - Threads: 1 - opm-simulators 4918: testing removing white spaces in the wells folder: The test run did not produce a result. E: mpirun was unable to launch the specified application as it could not access
OPM Benchmark: smeaheia - Threads: 8 - 2023-10-09 Master Reference: The test run did not produce a result. E: mpirun was unable to launch the specified application as it could not access
OPM Benchmark: smeaheia - Threads: 8 - opm-simulators 4918: testing removing white spaces in the wells folder: The test run did not produce a result. E: mpirun was unable to launch the specified application as it could not access
OPM Benchmark: spe10_model_1 - Threads: 1 - 2023-10-09 Master Reference: The test run did not produce a result. E: mpirun was unable to launch the specified application as it could not access
OPM Benchmark: spe10_model_1 - Threads: 1 - opm-simulators 4918: testing removing white spaces in the wells folder: The test run did not produce a result. E: mpirun was unable to launch the specified application as it could not access
OPM Benchmark: spe10_model_1 - Threads: 8 - 2023-10-09 Master Reference: The test run did not produce a result. E: mpirun was unable to launch the specified application as it could not access
OPM Benchmark: spe10_model_1 - Threads: 8 - opm-simulators 4918: testing removing white spaces in the wells folder: The test run did not produce a result. E: mpirun was unable to launch the specified application as it could not access
OPM Benchmark: flow_mpi_extra - Threads: 1 - 2023-10-09 Master Reference: The test run did not produce a result. E: mpirun was unable to launch the specified application as it could not access
OPM Benchmark: flow_mpi_extra - Threads: 1 - opm-simulators 4918: testing removing white spaces in the wells folder: The test run did not produce a result. E: mpirun was unable to launch the specified application as it could not access
OPM Benchmark: flow_mpi_extra - Threads: 8 - 2023-10-09 Master Reference: The test run did not produce a result. E: mpirun was unable to launch the specified application as it could not access
OPM Benchmark: flow_mpi_extra - Threads: 8 - opm-simulators 4918: testing removing white spaces in the wells folder: The test run did not produce a result. E: mpirun was unable to launch the specified application as it could not access
OPM Benchmark: flow_mpi_norne - Threads: 1 - 2023-10-09 Master Reference: The test run did not produce a result. E: mpirun was unable to launch the specified application as it could not access
OPM Benchmark: flow_mpi_norne - Threads: 1 - opm-simulators 4918: testing removing white spaces in the wells folder: The test run did not produce a result. E: mpirun was unable to launch the specified application as it could not access
OPM Benchmark: flow_mpi_norne - Threads: 8 - 2023-10-09 Master Reference: The test run did not produce a result. E: mpirun was unable to launch the specified application as it could not access
OPM Benchmark: flow_mpi_norne - Threads: 8 - opm-simulators 4918: testing removing white spaces in the wells folder: The test run did not produce a result. E: mpirun was unable to launch the specified application as it could not access
OPM Benchmark: flow_mpi_norne_4c_msw - Threads: 1 - 2023-10-09 Master Reference: The test run did not produce a result. E: mpirun was unable to launch the specified application as it could not access
OPM Benchmark: flow_mpi_norne_4c_msw - Threads: 1 - opm-simulators 4918: testing removing white spaces in the wells folder: The test run did not produce a result. E: mpirun was unable to launch the specified application as it could not access
OPM Benchmark: flow_mpi_norne_4c_msw - Threads: 8 - 2023-10-09 Master Reference: The test run did not produce a result. E: mpirun was unable to launch the specified application as it could not access
OPM Benchmark: flow_mpi_norne_4c_msw - Threads: 8 - opm-simulators 4918: testing removing white spaces in the wells folder: The test run did not produce a result. E: mpirun was unable to launch the specified application as it could not access

View result details @ https://www.ytelses.com/opm/?page=result&id=2258

**Comment by GitPaean** [comment]
It looks like the benchmark indeed not working.

**Comment by GitPaean** [comment]
I saw many other white spaces when working on another PR. I think it is good to remove white spaces. Let get this PR in.

**Comment by GitPaean** [comment]
jenkins build this please

**Comment by GitPaean** [comment]
jenkins build this please

**Review by bska — APPROVED** [review]
Thanks for cleaning this up.  I'll merge into master.

**Pull request merged**
