### PR TITLE
EclGenericProblem: add serialization support

### PR DESCRIPTION
**Pull request by akva2**
Sits on top of https://github.com/OPM/opm-simulators/pull/4422

For restart.

### CODE REVIEW

**Comment by akva2** [comment]
jenkins build this opm-common=3383 opm-models=780 please

**Comment by akva2** [comment]
jenkins build this opm-common=3383 opm-models=780 please

**Comment by akva2** [comment]
jenkins build this please

**Review by bska — APPROVED** [review]
Looks good to me and I'll merge into master.

**Pull request merged**
