### PR TITLE
Refactor away flow_tag.hpp

### PR DESCRIPTION
**Pull request by hakonhagland**
Refactor away `flow_tag.hpp`.

NOTE this PR depends on PR #2523 which should be merged first.

Refactors away `flow_tag.hpp` by having `flow_blackoil_dunecpr.cpp`, `flow_onephase.cpp`, and `flow_onephase_energy.cpp` use the updated `Main.hpp` from PR #2523. This will eliminate the previous code duplication in `Main.hpp` and `flow_tag.hpp` discussed in PR #2521.

### CODE REVIEW

**Comment by atgeirr** [comment]
This is fine, but must be rebased on the new master, since it includes commits already merged in a different PR.

**Comment by hakonhagland** [comment]
Great! How do I do the rebase on master? Like this:

```
git checkout master
git fetch upstream
git merge upstream/master
git checkout flow_tag2
git merge master
git push origin -f flow_tag2
```

**Comment by bska** [comment]
> ```
> git checkout master
> git fetch upstream
> git merge upstream/master
> git checkout flow_tag2
> git merge master
> git push origin -f flow_tag2
> ```

Almost.  Instead of `git merge master` you run
```sh
git rebase master
```

**Comment by akva2** [comment]
```
git checkout flow_tag2
git fetch upstream
git rebase upstream/master
`` `

**Comment by hakonhagland** [comment]
@bska  and @akva2  Thanks! Done.

**Comment by atgeirr** [comment]
jenkins build this please

**Pull request merged**
