### PR TITLE
fixed: add missing HAVE_MPI ifs

### PR DESCRIPTION
**Pull request by akva2**
One never learns it seems..

### CODE REVIEW

**Comment by akva2** [comment]
jenkins build this serial please

**Comment by bska** [comment]
> jenkins build this serial please

Build check successful.  Merging this now to restore the sequential build.

**Comment by atgeirr** [comment]
Should we simply require MPI going forward? What would be the drawbacks, and for who? @akva2 @bska @alf @blattms

**Comment by bska** [comment]
> What would be the drawbacks, and for who?

For me, personally, the main drawback would be losing the ability to debug the main logic without the option of completely excluding MPI contributions.  I hardly ever run a case in sequential mode outside of a debugging context, but it's very useful to me in that specific situation.

**Pull request merged**
