### PR TITLE
Added more supported PINCH test cases to regression testing.

### PR DESCRIPTION
**Pull request by blattms**
Namely T2A_NOPINCH, T2A_GAP, and T2A_NOGAP supported with #665

### CODE REVIEW

**Comment by blattms** [comment]
jenkins build this please

**Comment by blattms** [comment]
jenkins build this update_data please

**Comment by bska** [comment]
jenkins build this opm-tests=1000 please

**Comment by akva2** [comment]
There is no T2A_NOGAP,  https://ci.opm-project.org/job/opm-simulators-PR-builder/lastCompletedBuild/testReport/(root)/mpi/compareECLFiles_flow_T2A_NOGAP/

**Comment by blattms** [comment]
update_data had no effect. @akva2 I am really not good at this. What am I missing this time?

**Comment by blattms** [comment]
Thanks, will fix.

**Comment by blattms** [comment]
jenkins build this update_data please

**Comment by akva2** [comment]
Thanks

**Pull request merged**
