### PR TITLE
Remove unused methods from wellmodel

### PR DESCRIPTION
**Pull request by joakim-hove**
These methods are not called - removing.

Maybe they *should* have been called?

### CODE REVIEW

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by GitPaean** [comment]
maybe some ebos related called it? But if you find this out with `grep`, it is probably correct.

**Comment by bska** [comment]
> maybe some ebos related called it?

Maybe at one time.  At present [`EclProblem<>::endEpisode()`](https://github.com/OPM/opm-simulators/blob/12880be916dc8568fccebb361b3109cb4136baf6/ebos/eclproblem.hh#L1253-L1268) does **not** call `wellModel_.endEpisode()`.  On the other hand, [`EclProblem<>::beginEpisode()`](https://github.com/OPM/opm-simulators/blob/12880be916dc8568fccebb361b3109cb4136baf6/ebos/eclproblem.hh#L1036) **does** call [`wellModel_.beginEpisode()`](https://github.com/OPM/opm-simulators/blob/12880be916dc8568fccebb361b3109cb4136baf6/ebos/eclproblem.hh#L1092-L1093) so from symmetry arguments alone `EclProblem::endEpisode()` should probably call `wellModel_.endEpisode()` too.

**Comment by totto82** [comment]
> Maybe they should have been called?

They should be called from `endEpisode()` in` eclproblem.hh` to be consistent with the the rest i.e. `endTimeStep` etc. 
So please do not merge this. We should rather fix this by adding in to `eclproblem.hh`

**Comment by joakim-hove** [comment]
https://github.com/OPM/opm-simulators/pull/3181

**Pull request closed without merging**
