### PR TITLE
Restart test

### PR DESCRIPTION
**Pull request by joakim-hove**
Depends on: https://github.com/OPM/opm-simulators/pull/763

1 Using Python to run flow repeatedly and compare results.
2. Cleaned up and removed unnecessary SPE1 runs from testing

NB: The initial goal when creating this PR was to create a restart integration test based on the `SPE1CASE2_ACTNUM` case. I sort of succeeded in doing that - the test would run without blowing up due to cell mismatch or other problem typically originating in inactive cells, however I had to turn the `epsilon` value *very high* to get the test through. Also for the current all-cells-active `SPE1CASE2` test the epsilon value is 1e-3 - which is not particularly small. 

When restarting a simulation the solution data have gone through a `double -> float -> double` conversion process, but apart from that I insist we should get bitwise equality when restarting. So all in all my conclusion is that:  **Restart does not really work**

### CODE REVIEW

**Comment by blattms** [comment]
@joakim-hove Adaptive time stepping will also lead to different results due to different size of the time steps. If we want to check with adaptive time stepping we need to be able to pass an initial time step.

**Comment by joakim-hove** [comment]
@Blattms:  Thank you for the comment about adaptive timestepping - that was an important point.

**Comment by alfbr** [comment]
I am not sure bitwise equality is a good choice when dealing with double and float. It is prone to cause false positives. Using tolerance close to numerical precision will probably be just as effective in capturing regressions while avoiding false positives.

**Comment by jokva** [comment]
There's no bitwise equality checking as far as I can tell.

**Comment by bska** [comment]
> I am not sure bitwise equality is a good choice when dealing with double and float.

It's not immediately obvious from this patch, but setting `abs_epsilon = 0` does not imply bitwise equality.  Rather, this means "do not consider absolute differences separately" (or, equvialently, "use only relative comparisons").  The actual implementation ends up in ERT's `CMP_double` function that is generated from the `CMP` macro in [`ecl_kw.c`](https://github.com/Ensembles/ert/blob/master/devel/libecl/src/ecl_kw.c#L410-L429)

**Comment by joakim-hove** [comment]
>@alfbr: I am not sure bitwise equality is a good choice

> @bska: It's not immediately obvious from this patch, but setting abs_epsilon = 0 does not imply bitwise equality. 

You guys are taking me a bit to literal; my point is the following:

1. When restarting a simulation we should recover the state which has been saved to with *veeeery* good precision, and consequently the final state should correspond to the non-restarted state with correspondingly good precision. Since the restarted case go through the `double -> float -> double` conversion we can *not* expect bitwise equality - but barring that conversion we should in my opinion expect bitwise equality between a restarted and a non-restarted case.

2. For the test in question a relative epsilon value of 1e-3 is used to pass the test - this is a quite large tolerance value.

> @jokva: but @joakim-hove claims that we should be able to observe it.

Well - as mentioned the `double -> float -> double` conversion bitwise equality is out of the question, but we should get *very close* results - much closer than an epsilon value of 1e-3. So my - main point is that in my opinion these two points lead to the conclusion: **Restart does not really work**.

@blattms: Had a good point about the adaptive time-stepper though, which might mess up the conclusion.

**Comment by bska** [comment]
Sorry for being dense, but it is not clear to me how you're affecting the actual comparison between restarted and non-restarted.  Do you do something akin to

   1. Capture simulation state in a restart file at time T1.
   2. Simulate to some final time T2, save state.
   3. Start new simulation at T1 using previously saved restart file
   4. Simulate to T2, save state
   5. Compare the two states at T2

❓ 

If so, there is one more potential pitfall.  Since our simulator uses automatic differentiation we depend not only on the simulation state (pressure, saturation &c), but also on the derivatives of various quantities.  To the extent that we transfer derivatives from one time-step to the next (it's been a while since I looked at the details) we need to be able to reconstruct the derivatives too if we are to make meaningful comparisons of the restart vectors at time T2.

**Comment by joakim-hove** [comment]
>Do you do something akin to

>1. Capture simulation state in a restart file at time T1.
2. Simulate to some final time T2, save state.
3. Start new simulation at T1 using previously saved restart file
4. Simulate to T2, save state
5. Compare the two states at T2

>:question:

Yes - that is exactly what the test does. And my claim is that modulo the `double -> float -> double` issue the conclusion at 5. should be that the two states at T2 *should be* bitwise equal.

> Since our simulator uses automatic differentiation we depend not only on the simulation state (pressure, saturation &c), but also on the derivatives of various quantities.

Well - this might be a good point; I really do not know - but I insist that the use of automatic differentiation is an implementation detail. The state is fully specified as saved to disk - and restart should be possible. But we might need some extra logic to cold-start the AD implementation after restart - that might be an explanation to my claim: **Restart does not really work!**

**Comment by bska** [comment]
>> Do you do something akin to [snip procedure]?
>
> Yes - that is exactly what the test does. And my claim is that modulo the `double -> float -> double` issue the conclusion at [the end] should be that the two states at T2 should be bitwise equal.

I don't disagree.

> I insist that the use of automatic differentiation is an implementation detail.

Clearly.

>[W]e might need some extra logic to cold-start the AD implementation after restart

Yes.  At the very least we need to be able to restore all well-flows (i.e., the pressure distribution along the well bore) and to establish the flow regime (saturated vs. unsaturated) in each cell.  Really, we will only know the extent of the work if we output the complete system of linear and non-linear equations immediately after restarting the simulation and comparing that to the systems we get (at the same time point) without restarting.

**Comment by pgdr** [comment]
#763 is merged and thus this looks ready to merge now.  @bska, @alfbr, @atgeirr: Do you have any objections or questions that are not addressed for this PR?

**Comment by atgeirr** [comment]
Back to work today, have not yet had the time to look at it. It's not clear to me if @bska considered this ready to be merged, so I'd prefer to have a little time to look over the PR and the comments first. Is tomorrow or Wednesday ok?

**Comment by pgdr** [comment]
@atgeirr Sure, take your time!

**Comment by atgeirr** [comment]
Merging now..

**Pull request merged**
