### PR TITLE
Add build time to flow startup banner

### PR DESCRIPTION
**Pull request by joakim-hove**

### CODE REVIEW

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by blattms** [comment]
Please enlighten me. When and how can knowledge of the build time help me?

**Comment by alfbr** [comment]
> Please enlighten me. When and how can knowledge of the build time help me?

It gives an upper time limit to how new the code is I guess.  But don't we already print out the latest commit hash of opm-simulators?

**Comment by joakim-hove** [comment]
> When and how can knowledge of the build time help me?

When debugging an existing simulation - I get a good guesstimate of whether feature 'X' is included.

> But don't we already print out the latest commit hash of opm-simulators?

Yes we do - in many cases that will serve the purpose; but when someone has assembled their own version developer Joe might have that commit at his place.

**Comment by atgeirr** [comment]
I agree that more information is good! But what is BUILD_TIMESTAMP? My google-fu is insufficient on this one, and a tiny "hello build_timestamp" test locally failed to see it?

**Comment by atgeirr** [comment]
> But don't we already print out the latest commit hash of opm-simulators?

We do for release builds, but not for debug builds. I guess the idea is that debug builds are often in flux anyway, with uncommitted minor changes under testing.

**Comment by akva2** [comment]
i'm going to flip the question: what harm would having compile time do?

**Comment by joakim-hove** [comment]
> But what is BUILD_TIMESTAMP?

It is a string generated by the build system: https://github.com/OPM/opm-common/pull/1653 - strictly speaking "CMAKE_CONFIGURE_TIMESTAMP" would be more correct - that could of course be improved.

**Comment by atgeirr** [comment]
> It is a string generated by the build system

Thanks, that explains why it failed standalone...

You should `#include "project-version.h"` though, right?

**Comment by alfbr** [comment]
>i'm going to flip the question: what harm would having compile time do?

Takes up some space in the banner I guess, giving ambiguous information. Personally, I believe it is useful, so I support this. Only developers knows how to track commit hashes, build time is easy for most people to relate to. Hence, they both serve the same purpose, but for different audiences.

**Comment by joakim-hove** [comment]
> You should #include "project-version.h" though, right?

No - the `compileTimestamp()` is a naked function in `moduleVersion.hpp`; which includes `project-version.h`. But you must regenerate the header file based on a grand new opm-common.

**Comment by blattms** [comment]
I guess your workflow is different from mine and if it makes sense there then just go for it. It does not harm at all. I was just trying to understand the need.

For me it does not help if compile time really is when I compiled/cmaked stuff. I usually have multiple checkouts and for me the time I compiled each of them does not mean much as they are on different branches.

**Comment by joakim-hove** [comment]
> For me it does not help if compile time really is when I compiled/cmaked stuff.

This is not about *my* compile time - that I can manage; it is when get a simulation from someone where something has broken.

**Comment by atgeirr** [comment]
All seems ok here, merging.

**Pull request merged**
