### PR TITLE
add well_test_state to WGState

### PR DESCRIPTION
**Pull request by totto82**
If the simulator fails after a well opens due to well testing we want to also revert the wellTestState. Adding the wellTestState to the WGState class automatically includes it in the resetWGState and commitWGState logic.

### CODE REVIEW

**Comment by totto82** [comment]
jenkins build this please

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by totto82** [comment]
jenkins build this please

**Comment by joakim-hove** [comment]
Good that the logic can be reused and extended - merging!

**Pull request merged**
