### PR TITLE
Add adjoint

### PR DESCRIPTION
**Pull request by hnil**
This is a test pull request to discuss changes to get adjoint working. It has been limmited tested. It depend on pull request for in ewoms of branch add_adjoint.

### CODE REVIEW

**Comment by atgeirr** [comment]
Very good! I look forward to getting this feature.

Just a brief first impression, unrelated to the feature itself: the changes to CMakeLists_files.cmake seem excessive -- did you accidentally commit more than intended?

**Comment by GitPaean** [comment]
Great work! Please make a running test out of it so this functionality is protected from being broken by other development. This functionality is kind built upon classes still under active developments.

**Comment by kingaj12** [comment]
@hnil What is the plan with this?  I would like to use it / contribute, if possible.

**Comment by atgeirr** [comment]
This has been replaced by #1559, which rebases it on a more current master.

**Pull request closed without merging**
