### PR TITLE
Rely on local ids being persistent across grid modifications

### PR DESCRIPTION
**Pull request by blattms**
as the issue in CpGrid was fixed, recently. See PRs #2458 and OPM/opm-grid#459.

### CODE REVIEW

**Comment by blattms** [comment]
jenkins build this please

**Comment by blattms** [comment]
On my system these seemingly unrelated tests are failing:
```
The following tests FAILED:
	 37 - compareECLFiles_flow+3D_MSW (Failed)
	 57 - compareECLFiles_flow+TEST_WSEGSICD (Failed)
Errors while running CTest
```
Any ideas?

**Comment by bska** [comment]
> On my system these seemingly unrelated tests are failing:

Those are regression tests for multi-segmented wells.  We've had a lot of difficulty getting reproducible results across computer systems for those.  @GitPaean and @alfbr went through an exercise recently of tightening the convergence tolerances for these (and some polymer tests), but I don't think we're completely stable yet.  I too often have trouble running those tests, even on unchanged master branches so I typically compare results on my development branches to runs made on the unchanged master branches instead of the reference data produced by our Jenkins CI system.

**Comment by blattms** [comment]
Well on jenkins it seemed to have worked.

**Comment by bska** [comment]
jenkins build this please

**Pull request merged**
