### PR TITLE
Add pyaction/PYACTION_GRUPTREE_INSERT_KW.DATA to pyactionComparisons.…

### PR DESCRIPTION
**Pull request by lisajulia**
…cmake so it is compared with actionx/ACTIONX_GRUPTREE.DATA

### CODE REVIEW

**Comment by blattms** [comment]
This needs OPM/opm-tests#1157 to work, right?

**Comment by lisajulia** [comment]
> This needs [OPM/opm-tests#1157](https://github.com/OPM/opm-tests/pull/1157) to work, right?

Yes.

**Comment by bska** [comment]
jenkins build this please

**Comment by lisajulia** [comment]
jenkins build this please

**Review by bska — APPROVED** [review]
Very good.  I'll merge into master.

**Pull request merged**
