### PR TITLE
Update for writing initial values to restart file

### PR DESCRIPTION
**Pull request by babrodtk**
This PR is for @andlaus to possibly fix it "the right way". What I've done below does not appear to be correct, and I'm unsure what is actually wrong.

### CODE REVIEW

**Comment by babrodtk** [comment]
@andlaus I think I get different results in the output on Norne, perhaps relating to different ordering of cells? So in my head this may not be correct, but let's hear what our favorite butler says.

**Comment by andlaus** [comment]
> I think I get different results in the output on Norne

do you mean as in significantly different or differences in the order of the floating  point precision?

**Comment by babrodtk** [comment]
I only checked superficially, but it appeared to give significant differences for me which are far larger than what I would expect from FP.

**Comment by andlaus** [comment]
I cannot explain how this could be. oh well, I guess I'll need to have a deeper look.

**Comment by andlaus** [comment]
ok, let's have a look at the summary curves (not that they should be affected as far as I can see):

**Comment by andlaus** [comment]
jenkins run norne_ebos please

**Comment by andlaus** [comment]
the Norne curves seem to be unaffected by this as expected. Since I have absolutely no idea how this PR could cause *any* differences, I'll merge it for now. if I turn out to be wrong, I'll take the blame...

**Pull request merged**
