### PR TITLE
Only update TUNING after event

### PR DESCRIPTION
**Pull request by totto82**
Depends on OPM/opm-parser#1159

### CODE REVIEW

**Comment by atgeirr** [comment]
jenkins build this opm-parser=1159

**Comment by atgeirr** [comment]
jenkins build this opm-parser=1159 please

**Comment by totto82** [comment]
jenkins build this update_data please

**Comment by atgeirr** [comment]
jenkins build this opm-data=278 please

**Comment by atgeirr** [comment]
jenkins build this opm-data=278 please

**Comment by atgeirr** [comment]
This is green, merging it and the opm-data PR! After that, jenkins should start working again.

**Pull request merged**
