### PR TITLE
Minor cleanups

### PR DESCRIPTION
**Pull request by andlaus**
remove the unused `initialTemperature_` array in `EclProblem` and do not use the uninitialized `isIoRank_` member in `ISTLSolverEbos` anymore.

### CODE REVIEW

**Comment by andlaus** [comment]
jenkins build this please

**Comment by bska** [comment]
> remove the unused `initialTemperature_` array in `EclProblem`

Is #1453, which resulted in OPM/ewoms#311, no longer an issue?

**Comment by andlaus** [comment]
I bet a beer that this PR does not change the state of this in any regard: if you look at the changes, you might notice that the `initialTemperature_` array was never initialized anywhere.

**Comment by bska** [comment]
>> Is #1453 [...] no longer an issue?
>
> This PR does not change the state of this in any regard:

That's not what I asked.  I asked if the reason why introduced the data member in the first place still exists.  If the issue is still present, then we need to keep the data member (and initialise it properly).

**Comment by andlaus** [comment]
> I asked if the reason why introduced the data member in the first place still exists.

As stated above: I'm reasonably sure that the answer to that question is "no".

**Comment by bska** [comment]
> > asked if the reason why introduced the data member in the first place still exists.
> 
> As stated above: I'm reasonably sure that the answer to that question is "no".

That's not a good enough answer.  You need to be able to point to a sequence of changes that explicitly solve the problem.

**Comment by andlaus** [comment]
is the statement "the `initialTemperature_`  array was not initialized and used and using it would have resulted in a segmentation fault" a "good enough" answer for you?

**Comment by bska** [comment]
> is the statement "the `initialTemperature_` array was not initialized and used and using it would have resulted in a segmentation fault" a "good enough" answer for you?

It's not.

There are at least two possible reasons for the member to be unused.  One is that it was inadvertently dropped in a refactoring and the other is that it was intentionally dropped because the underlying issue (accessing non-existent temperature data during system assembly of non-thermal problems) was solved differently.  If it is the former then the original, underlying problem still exists and we need to deal with it somehow.  If it is the latter then we can safely remove the data member.

**Comment by andlaus** [comment]
interesting theories. I'd like to request a reversal of the "burden of proof".

**Comment by joakim-hove** [comment]
image

But seriously guys - we have a testsuite?!

**Comment by bska** [comment]
Just for context: The test suite did not catch the original issue, #1453.

**Comment by joakim-hove** [comment]
> Just for context: The test suite did not catch the original issue, #1453.

Well - then that is where focus should be.

**Comment by totto82** [comment]
Jenkins is happy, so I will merge. Thanks for the clean up.

**Pull request merged**
