### PR TITLE
Fix some warnings in the OpenCl Solver.

### PR DESCRIPTION
**Pull request by blattms**
PR #2682 introduced some new warnings (shadowing variables, and catching exceptions by value). This PR fixes them.

Would be nice if @Tongdongq would tell his 2 cents on this (especially the shadowed variables).

### CODE REVIEW

**Comment by blattms** [comment]
jenkins build this please

**Comment by Tongdongq** [comment]
Looks good.
I also found an 'unused variable' warning at `WellContributions.cpp:95`. The `addMatrix()` takes some arguments. These arguments are passed to `addMatrixGpu()` if CUDA is found, otherwise an exception is thrown. However, when CUDA is not found, the arguments are not used.

**Comment by blattms** [comment]
fixed that also, thanks.

**Comment by blattms** [comment]
jenkins build this please

**Comment by blattms** [comment]
jenkins is happy and in it goes.

**Pull request merged**
