### PR TITLE
clamp rs/rv in rate converter between 0.0 and rs/rv max

### PR DESCRIPTION
**Pull request by totto82**
Noticed while working on #4292

### CODE REVIEW

**Comment by totto82** [comment]
jenkins build this please

**Comment by totto82** [comment]
> To be honest if we're going to do this anyway, I'd really prefer we go the [BURN_RESV_BRIDGES](https://github.com/OPM/opm-simulators/blob/f99b125156ef7fdeb0ea680943d6ba1ed0f4dee2/opm/simulators/wells/RateConverter.hpp#L586-L595) route instead.

Do you know the motivation of "BURN_RESV_BRIDGES" I haven't notices this before today. And yes the code within BURN_RESV_BRIDGES should do the trick, but why is this not the default behavior.

**Comment by bska** [comment]
> > To be honest if we're going to do this anyway, I'd really prefer we go the [BURN_RESV_BRIDGES](https://github.com/OPM/opm-simulators/blob/f99b125156ef7fdeb0ea680943d6ba1ed0f4dee2/opm/simulators/wells/RateConverter.hpp#L586-L595) route instead.
> 
> Do you know the motivation of "BURN_RESV_BRIDGES" I haven't notices this before today

Yes.  I added that block in #4164 (commit f0e2a1efe0) because I considered it to be a better way of doing what the current master does.  I also made that code conditional on `BURN_RESV_BRIDGES` (commit d388ce40e) because it changes the simulation results and I didn't want to deal with that while I was working on something else (#4180).

> why is this not the default behavior.

Because I didn't have time to verify that every change generated by switching the algorithm was well within the acceptable limits.

**Comment by totto82** [comment]
Thanks, I will update the PR so we start using the code inside BURN_RESV_BRIDGES instead

**Review by bska — APPROVED** [review]
This is fine provided the new simulation results are okay.

**Comment by totto82** [comment]
I have manually checked the failures with most deviations. 
	 82 - compareECLFiles_flow+UDQ_M1 (Failed)
	125 - compareECLFiles_flow+MOD4_UDQ_ACTIONX (Failed)
	163 - compareECLFiles_flow+WVFPEXP-02 (Failed) 
The rest pass when only comparing restart steps and with looser tolerances.
I will start the updated process.

**Comment by totto82** [comment]
jenkins build this update_data please

**Comment by totto82** [comment]
jenkins build this opm-tests=874 please

**Pull request merged**
