### PR TITLE
convert MSW_2D_H__ into a regression test

### PR DESCRIPTION
**Pull request by akva2**

### CODE REVIEW

**Comment by akva2** [comment]
jenkins build this opm-data=144 please

**Comment by akva2** [comment]
jenkins build this opm-data=144 please

**Comment by akva2** [comment]
jenkins build this opm-data=144 please

**Comment by akva2** [comment]
jenkins build this opm-data=144 please

**Comment by akva2** [comment]
jenkins build this opm-data=188 please

**Comment by akva2** [comment]
with the FIP support added to flow_multisegment i think this can be enabled.

**Comment by akva2** [comment]
ping

**Comment by atgeirr** [comment]
Local testing confirms this is ok, merging.

Thanks for the improvement!

**Pull request merged**
