### PR TITLE
Split out FluidSystem dependent code from WellInterface

### PR DESCRIPTION
**Pull request by akva2**
This sits on top of #3236 which should be processed first.

### CODE REVIEW

**Comment by akva2** [comment]
jenkins build this please

**Comment by akva2** [comment]
jenkins build this please

**Comment by akva2** [comment]
jenkins build this please

**Comment by akva2** [comment]
jenkins build this please

**Comment by akva2** [comment]
jenkins build this please

**Comment by akva2** [comment]
jenkins build this please

**Comment by akva2** [comment]
Rebasing this is not getting any more fun over time. Anything holding it back?

**Comment by bska** [comment]
> Anything holding it back?

Lack of reviewers with expertise in the well code.

**Review by bska — APPROVED** [review]
The code changes here look okay and the build check is green.  I'll take a little leap of faith that we don't break any hidden assumptions and merge this into master.

**Pull request merged**
