### PR TITLE
Preparatory changes for single-process parsing

### PR DESCRIPTION
**Pull request by akva2**
Avoid some deck usage, avoid some dereferencing.

The deck-access avoid is done simple right now, ideally these things would be internalized in EclipseState, but I don't want to be held up by them right now. Furthermore,  since neither tracers nor aquifers currently work in parallel, it's not that big of a deal.

### CODE REVIEW

**Comment by akva2** [comment]
jenkins build this please

**Comment by blattms** [comment]
Looks good.

**Comment by blattms** [comment]
All these synchronization points will make us (or at least me) really dizzy in the future. I guess they should not stay for long.

**Comment by akva2** [comment]
i agree that it's nasty. they will go away once the need for deck access is gone by the data being internalized in the eclipse state.

**Pull request merged**
