### PR TITLE
[testing] sequential running for flow

### PR DESCRIPTION
**Pull request by GitPaean**

### CODE REVIEW

**Comment by GitPaean** [comment]
jenkins build this update_data please

**Comment by GitPaean** [comment]
jenkins build this please

**Comment by GitPaean** [comment]
jenkins build this please

**Comment by GitPaean** [comment]
jenkins build this please

**Comment by GitPaean** [comment]
jenkins build this please

**Comment by GitPaean** [comment]
jenkins build this please

**Comment by GitPaean** [comment]
jenkins build this please

**Comment by GitPaean** [comment]
jenkins build this please

**Comment by GitPaean** [comment]
jenkins build this please

**Comment by GitPaean** [comment]
jenkins build this please

**Comment by GitPaean** [comment]
jenkins build this please

**Comment by GitPaean** [comment]
jenkins build this please

**Comment by GitPaean** [comment]
jenkins build this opm-models=624 please

**Comment by GitPaean** [comment]
jenkins build this opm-models=624 please

**Comment by GitPaean** [comment]
jenkins build this opm-models=624 please

**Comment by GitPaean** [comment]
jenkins build this opm-models=624 please

**Comment by GitPaean** [comment]
jenkins build this opm-models=624 please

**Comment by GitPaean** [comment]
It looks like jenkins did not catch all the commits in OPM/opm-models#624 .

**Comment by GitPaean** [comment]
jenkins build this opm-models=624 please

**Comment by GitPaean** [comment]
there is some bug in the Jenkins script. It could not get the latest commit from the opm-models.

**Comment by bska** [comment]
@GitPaean : Is this work still relevant?

**Comment by GitPaean** [comment]
>  @GitPaean : Is this work still relevant?

four years ago. Let us close it.

**Pull request closed without merging**
