### PR TITLE
some dummy commit for github

### PR DESCRIPTION
**Pull request by andlaus**
cf. https://github.com/OPM/opm-common/pull/222#issuecomment-267049244

### CODE REVIEW

**Comment by andlaus** [comment]
jenkins run norne_ebos opm-common=222 opm-material=186 ewoms=113 please

**Comment by andlaus** [comment]
*arg* stupid typo

**Comment by andlaus** [comment]
jenkins run norne_ebos opm-common=222 opm-material=186 ewoms=113 please

**Comment by andlaus** [comment]
I cannot find any errors in the build/simulation log and the summary results seem to be fine as well. why does jenkins think it was unsuccessful?

**Comment by akva2** [comment]
Follow the link and it tells you right there that one test failed. It failed due to a pr in opm-data being merged without consideration for the restart test the file was used for. It is related to the appleyard stuff.

**Comment by andlaus** [comment]
ok, so at least the tested PRs are innocent.

**Comment by akva2** [comment]
Yah

**Comment by andlaus** [comment]
PR successful, jenkins fails anyway. closing.

**Pull request closed without merging**
