### PR TITLE
BlackoilModel: drop ebos in variable names

### PR DESCRIPTION
**Pull request by akva2**
Either ebos -> model or ebos -> nothing

### CODE REVIEW

**Comment by akva2** [comment]
jenkins build this please

**Comment by blattms** [comment]
Just my two cents:
Does changing ebos to model really make sense? Now we have modelSimulator, modeResId, etc. How about stripping model and going with simulator, resId, etc,

**Comment by akva2** [comment]
I am open to any changes, and I do agree it seems maybe a bit redundant.  But before I do a second round I do insist on consensus to avoid back and forth.

**Comment by blattms** [comment]
To be honest, I don't really care and can live with everything. Anything is better than ebos.

**Comment by atgeirr** [comment]
I think "model" is fine if not perfect. There is no perfect name change here perhaps... At least I do not have a better proposal! I think this is good, and as @blattms I can live with any reasonable alternative.

**Comment by akva2** [comment]
since there is no strong opinion I went with my own preference which is to drop the prefixes.

**Comment by akva2** [comment]
jenkins build this please

**Review by bska — APPROVED** [review]
I prefer dropping `ebos` too, so the current version is fine by me.  I'll merge into master.

**Pull request merged**
