### PR TITLE
Fix drsdt

### PR DESCRIPTION
**Pull request by hnil**
Tried to Get drsdt integrated, Aldo fixed bug for somax for solvent. Test show sone differences. This depends on the same branch name in ewoms, opm materials

### CODE REVIEW

**Comment by atgeirr** [comment]
jenkins build this opm-material=262 ewoms=239 please

**Comment by hnil** [comment]
jenkins run norne please

**Comment by hnil** [comment]
jenkins run norne please

**Comment by atgeirr** [comment]
@akva2 please add @hnil to the list of people allowed to trigger Jenkins.

**Comment by atgeirr** [comment]
jenkins run norne please

**Comment by akva2** [comment]
done.

**Comment by totto82** [comment]
Not needed anymore

**Pull request closed without merging**
