### PR TITLE
Also perform regression tests for PINCH(4) being ALL.

### PR DESCRIPTION
**Pull request by blattms**
These tests will make sure that fixes of #5577 are preserved.

### CODE REVIEW

**Comment by blattms** [comment]
jenkins build this please

**Comment by blattms** [comment]
jenkins build this update_data please

**Comment by blattms** [comment]
Somehow we missing the mentioning of the created opm-tests PR OPM/opm-test#1237

**Comment by blattms** [comment]
jenkins build this opm-tests=1237 please

**Review by bska — APPROVED** [review]
Very good.  I'll merge into master.

**Pull request merged**
