### PR TITLE
[bugfix] Only create asyncOutput when output is enabled globally.

### PR DESCRIPTION
**Pull request by dr-robertk**
This resolves the segfault when output=false is used.

### CODE REVIEW

**Comment by dr-robertk** [comment]
jenkins build this please

**Comment by atgeirr** [comment]
Looks fine, I have not set up with pthreads locally so I cannot verify it on my system though.

@blattms do you agree this should be merged and #1200 closed?

**Comment by blattms** [comment]
Honestly, I do not care. The effect of the fix is exactly the same. My diff is one line change (as it does not merge the second if to into the frist one and does abstain from more rewrites than needed and this one is a bit more lines.

**Comment by blattms** [comment]
Merge whatever you want it is fine with me.

**Comment by atgeirr** [comment]
Upon reading #1200 it seems to me that it will indeed always disable async output, as @dr-robertk indicated, as the asyncOutput_ member will be default-initialized at the point of the if-test.

So either the logic is wrong, or it is too obscure for me to understand it properly :-)

I'll therefore merge this and close #1200.

**Pull request merged**
