### PR TITLE
eclthresholdpressure: split in typetag dependent/independent parts

### PR DESCRIPTION
**Pull request by akva2**
this allows using explicit template instantation to only
compile this code per grid, not per simulator object

### CODE REVIEW

**Comment by akva2** [comment]
jenkins build this please

**Comment by akva2** [comment]
jenkins build this please

**Comment by akva2** [comment]
jenkins build this please

**Comment by bska** [comment]
It's tangential to the current PR, but would you mind having a go at eliminating the sequential build [warnings](https://ci.opm-project.org/job/opm-simulators/825/gcc/) from [`eclgenericcpgridvanguard.cc`](https://github.com/OPM/opm-simulators/blob/138caade06779a93cd1258fa9f7a589bc1cf839a/ebos/eclgenericcpgridvanguard.cc).

**Pull request merged**
