### PR TITLE
White spcae change.

### PR DESCRIPTION
**Pull request by joakim-hove**
The sole purpose of this PR is to trigger the functionality to update reference data; it must be merged though to get a valid sha in the opm-data commit messages.

### CODE REVIEW

**Comment by joakim-hove** [comment]
jenkins run norne opm-output=167 opm-parser=1043 update_data please

**Comment by akva2** [comment]
as i said elsewhere you do not have to update the integration test data here. norne's init file is a *regression test*, it's only if you want to update the *summary* reference that this is needed.

**Comment by joakim-hove** [comment]
> as i said elsewhere you do not have to update the integration test data here. norne's init file is a regression test

Now - I am religious zealot when it comes to testing, but quite frankly the difference between *integration test* and *regression test* eludes me. For the particular change I am working with now the INIT file created by `flow/flow_ebos` when running norne - will change. So?

**Comment by akva2** [comment]
well what constitutes a regression and an integration tests can be discussed hours on end ;)

regression tests runs on every 'make test'. integration tests, such as norne, that takes some 1h to finish is not part of the built-in test suite, and is only run when requested (through the trigger, using separate scripts). however, doing the initialization only for norne i bearable (15 sec), so a regression test is in place for that part.

**Comment by joakim-hove** [comment]
> regression tests runs on every 'make test'. integration tests, such as norne, that takes some 1h to finish is not part of the built-in test suite,

OK - thank you; that was a good explanation. The regression tests are then just what I would call *"the tests"* - and for this particular case I do *not* need to run norne. Will poke jenkins again.

**Comment by joakim-hove** [comment]
jenkins build this opm-output=167 opm-parser=1043 update_data please

**Comment by joakim-hove** [comment]
jenkins build this opm-data=182 opm-parser=1043 opm-output=167 please

**Pull request merged**
