### PR TITLE
Scale target with resv conversion factor

### PR DESCRIPTION
**Pull request by totto82**
Fix for #3347

### CODE REVIEW

**Comment by totto82** [comment]
jenkins build this please

**Comment by totto82** [comment]
image

**Comment by totto82** [comment]
@bska I assume this is closer to the results you expected.

**Comment by bska** [comment]
> I assume this is closer to the results you expected.

Yes it is, thank you very much.  I'll try this PR on the model where I noticed this symptom originally.

**Comment by bska** [comment]
> > assume this is closer to the results you expected.
> 
> Yes it is, thank you very much. I'll try this PR on the model where I noticed this symptom originally.

This PR is **much** better than current master, but we do not quite match ECLIPSE yet.  Below is a plot of the group-level reservoir volume injection rate when the model is constrained as
```
GCONINJE
-- nm         ph           cm         sir          rvir      rifr      vrfr     rhl
 'INJE'      'GAS'      'RATE'       1000000.       1000.     1*      1*       YES   /
/
```
and the reservoir volume injection rate constraint is active.  The value should be very close to (or, strictly speaking, exactly equal to) 1000, but we're a little off at roughly 976 even with this PR.

I can share this model with you offline if you'd like to have a look.  There's also a possibly related issue with `VREP`, but we can address that in a later PR.

---

INJE_Res_Volume_Injection_Rate

**Comment by bska** [comment]
In any case, I'll merge this PR to get us closer to the target.

**Pull request merged**
