### PR TITLE
remove libecl dependency

### PR DESCRIPTION
**Pull request by akva2**
Downstream-ish of https://github.com/OPM/opm-common/pull/1107

### CODE REVIEW

**Comment by akva2** [comment]
jenkins build this opm-common=1107 opm-material=350 opm-grid=397 opm-models=550 opm-upscaling=281 please

**Comment by akva2** [comment]
jenkins build this opm-common=1107 opm-material=350 opm-grid=397 opm-models=559 opm-upscaling=281 please

**Comment by bska** [comment]
jenkins build this opm-common=1107 opm-material=350 opm-grid=397 opm-models=559 opm-upscaling=281 please

**Comment by bska** [comment]
Merging into master now to account for build-system changes in upstream module opm-common.

**Comment by blattms** [comment]
Backported to release via #2069

**Pull request merged**
