### PR TITLE
mebos: hook up gas-water simulator

### PR DESCRIPTION
**Pull request by akva2**
This seems to have been forgotten when the gas-water model was added.

### CODE REVIEW

**Comment by akva2** [comment]
jenkins build this please

**Comment by bska** [comment]
> This seems to have been forgotten when the gas-water model was added.

I don't think that's an accurate assessment.  Note that gas/water simulations are [disabled](https://github.com/OPM/opm-simulators/blob/dae6b61370747fb5f47ea63718f2feeddff668fc/opm/simulators/flow/Main.hpp#L223-L226) in the main `flow` binary too.  I seem to recall that the feature was not fully functional yet, but I may be mistaken.

@plgbrts: Would you like to comment on the current state of gas/water simulations?

**Comment by goncalvesmachadoc** [comment]
Gas/water is not fully functional yet. We have now a working version locally, there are some things/fixes to be pushed to the master.

**Comment by bska** [comment]
Thank you for your update, @goncalvesmachadoc. I think we should close this particular PR then and let your team enable the feature when you think it's ready.

**Pull request closed without merging**
