### PR TITLE
fix regression in wells

### PR DESCRIPTION
**Pull request by akva2**
we need to call WellInterface::getTHPConstraint,
not WellBhpThpCalculator::getTHPConstraint

### CODE REVIEW

**Comment by GitPaean** [comment]
thanks for the PR. If I did not see it wrong, it looks like for producers, we should check the dynamic_thp_limit from the network nodes. For injectors, we just need to check the thp limit from the EclipseState. 

Is this what this PR is trying to do? Thanks.

**Comment by akva2** [comment]
yes, basically. that's what was done before.

**Comment by GitPaean** [comment]
Thanks for the clarification. But I think #4288 should also fix it if we do not give dynamic_thp_limit for injectors (which should be case). Correct me if I am wrong there. This is somehow I got confused with.

Anyway, we will try to get this PR in after confirmation with testing.

**Comment by GitPaean** [comment]
jenkins build this please

**Comment by GitPaean** [comment]
The PR works as intended. Getting the PR in when jenkins is done.

**Comment by GitPaean** [comment]
jenkins build this please

**Pull request merged**
