### PR TITLE
Dynamically update Opm::Schedule from Python

### PR DESCRIPTION
**Pull request by hakonhagland**
Depends on upstream https://github.com/OPM/opm-common/pull/3020

Adds some methods that enables `Opm::Schedule` to be dynamically modified from Python. A test case, `test_schedule.py` illustrates the use case.

### CODE REVIEW

**Comment by hakonhagland** [comment]
jenkins build this opm-common=3020

**Comment by akva2** [comment]
where's your manners

**Comment by akva2** [comment]
jenkins build this opm-common=3020 please

**Comment by totto82** [comment]
jenkins build this please

**Comment by totto82** [comment]
Thanks. Looks good to me.

**Pull request merged**
