### PR TITLE
Remove first perf member from Well classes

### PR DESCRIPTION
**Pull request by joakim-hove**
The new perforation datastructeres in WellState do not need this any longer.

### CODE REVIEW

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by joakim-hove** [comment]
Comments?

**Review by bska — APPROVED** [review]
Yes, this does simplify the logic quite a bit.  I'll merge into master.

**Pull request merged**
