### PR TITLE
 Merge wellstate

### PR DESCRIPTION
**Pull request by joakim-hove**
Merge the `WellState`and `WellStateFullyImplcitBlackOil`classes. The final merged class will be named `WellState`

### CODE REVIEW

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by joakim-hove** [comment]
Comments?

**Comment by totto82** [comment]
I like this. @atgeirr @bska are we still keeping the legacy branch that use the pure wellState for some of the simpler simulators.

**Comment by atgeirr** [comment]
> are we still keeping the legacy branch that use the pure wellState for some of the simpler simulators

It exists, but is in no way actively maintained, it must be combined with old versions of the other modules in any case. So if there is nothing that uses it in the current code, we do not worry.

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by joakim-hove** [comment]
I'll merge this when green.

**Pull request merged**
