### PR TITLE
fixed: regression from 82d2146c90ce74677bd8f04c745c31cd08b430de

### PR DESCRIPTION
**Pull request by akva2**
missing PRT header

### CODE REVIEW

**Comment by akva2** [comment]
jenkins build this please

**Review by bska — APPROVED** [review]
Thanks, this is a good work-around and I'll merge into master.  I suppose an additional step might be to move the `printPRTHeader()` function out of `FlowMainEbos.hpp`, and to have the new function take a callback to print the actual parameter values to a `std::ostream&` but I haven't thought through the implications yet.

For now we'll just use this to restore the feature.

**Comment by blattms** [comment]
*sarcastic mode on*
What a wonderful declarative subject! So clear what this fixes in no time. :wink: 
*sarcastic mode off*

Really: Good subjects save *a lot* of valuable time in a collaborative projects.

Maybe close #4410 ?

**Comment by akva2** [comment]
It tells you it fixes a regression, what commit caused the regression and what the regression was. Should I also give my grandmother's life story?

**Pull request merged**
