### PR TITLE
checking Producer or Injector when comparing bhp against BHP constraint during well operability check

### PR DESCRIPTION
**Pull request by GitPaean**
It fixes a reported issue regarding shutting injectors.

### CODE REVIEW

**Comment by GitPaean** [comment]
jenkins build this please

**Comment by GitPaean** [comment]
It was tested and reported as fixing the issue. Let us get it in soon.

**Comment by GitPaean** [comment]
jenkins build this please

**Comment by GitPaean** [comment]
I consider this PR is not controversial and it fixes a reported issue. I am self-merging it to get the issue removed from the list.

**Comment by OPMUSER** [comment]
@GitPaean Did this make it into 2023-04-RC1?

**Comment by GitPaean** [comment]
>  @GitPaean Did this make it into 2023-04-RC1?

no, it did not.

**Comment by akva2** [comment]
note: if you want it to, you have to set the milestone on the PRs in question, I will not backport otherwise.

**Comment by akva2** [comment]
also, this is in rc1.

**Pull request merged**
