### PR TITLE
updating perforation pressure and rates for MSW well

### PR DESCRIPTION
**Pull request by GitPaean**
It is not used in the simulation, while it is good to keep them updated for output and analysis purpose. 

It expects to fail the tests related to MS wells.

### CODE REVIEW

**Comment by GitPaean** [comment]
jenkins build this please

**Comment by GitPaean** [comment]
jenkins build this please

**Comment by GitPaean** [comment]
jenkins build this please

**Comment by GitPaean** [comment]
jenkins build update_data please

**Comment by GitPaean** [comment]
jenkins build this update_data please

**Comment by GitPaean** [comment]
jenkins build this opm-tests=107 please

**Comment by GitPaean** [comment]
perforation pressure and pressure rates are updated for output and analysis purpose. they do not change any simulation results.

**Comment by bska** [comment]
Thanks.  This is much appreciated!  I'll merge this and the companion PR in opm-tests now.

**Pull request merged**
