### PR TITLE
Reformulate ipr to handle cross-flow in wells

### PR DESCRIPTION
**Pull request by totto82**
This is only for standard wells. A similar reformulation is needed for msw wells.

### CODE REVIEW

**Comment by totto82** [comment]
jenkins build this please

**Comment by steink** [comment]
Just a comment: for ms wells I have a version in the pipeline that computes ipr using the Jacobian of the converged well-equations to obtain dq/dp. It can also be used for standard wells, but there it is less accurate due to the explicit treatment of dp along the well.

**Comment by totto82** [comment]
> Just a comment: for ms wells I have a version in the pipeline that computes ipr using the Jacobian of the converged well-equations to obtain dq/dp. It can also be used for standard wells, but there it is less accurate due to the explicit treatment of dp along the well.

Sounds like a good solution. A problem with the current approach is that it basically need to duplicate the code that computes the rate in the well model. Looking forward to the PR. Do you think this should be merged first or should we wait for your solution. A draft PR from you would be nice. I am eager to test it on the model that motivated my to provide this fix.

**Comment by steink** [comment]
> Do you think this should be merged first or should we wait for your solution. A draft PR from you would be nice. I am eager to test it on the model that motivated my to provide this fix.
Might take some time before this is ready for merging, but I can make a quick PR for testing on standard wells.

**Pull request closed without merging**
