### PR TITLE
Two more enhancements concerning NONNC

### PR DESCRIPTION
**Pull request by lisajulia**
Add NONNC regression test and change the copyright owner of test_nonnc.cpp to Equinor ASA

### CODE REVIEW

**Comment by akva2** [comment]
jenkins build this update_data please

**Comment by akva2** [comment]
jenkins build this opm-tests=1128 please

**Review by bska — APPROVED** [review]
Thanks.  The new reference solutions have been installed on the CI system.  Merging this now to activate the new test.

**Comment by akva2** [comment]
@lisajulia please have a look at debug iterator failure, https://ci.opm-project.org/job/opm-simulators-static-analysis/348/testReport/junit/(root)/debug_iterator/nonnc/

**Comment by lisajulia** [comment]
> @lisajulia please have a look at debug iterator failure, https://ci.opm-project.org/job/opm-simulators-static-analysis/348/testReport/junit/(root)/debug_iterator/nonnc/

Is there more context on how to reproduce this? The test `test_nonnc` is passing for me, for sequential as well as parallel  runs.

**Comment by akva2** [comment]
you have to run with the debug/ranged checked iterators (-D_GLIBCXX_DEBUG). however, setting this up is a bit of pain as you have to build boost, dune etc with that option as well. an easier alternative is to use valgrind. what happens is that the NTG vector returns from fieldprops is of length 358, not 360. For some reason num_active is 358, not 360. I didn't dig further.

**Comment by blattms** [comment]
@akva2 I am a bit surprised that there are no line numbers. Why don't we build this with debugging symbols?

**Comment by blattms** [comment]
As this just adds a test, chances are that this was introduced by somebody else.

**Comment by akva2** [comment]
absolutely. i'm not concerned about blame, but i assume julia has more knowledge about the details here than me hence the request.

it is a debug build, the output from the debug iterators simply does not include line numbers. have to attach the debugger for that.

**Comment by akva2** [comment]
```
==352513== Process terminating with default action of signal 6 (SIGABRT)
==352513==    at 0x55789FC: __pthread_kill_implementation (pthread_kill.c:44)
==352513==    by 0x55789FC: __pthread_kill_internal (pthread_kill.c:78)
==352513==    by 0x55789FC: pthread_kill@@GLIBC_2.34 (pthread_kill.c:89)
==352513==    by 0x5524475: raise (raise.c:26)
==352513==    by 0x550A7F2: abort (abort.c:79)
==352513==    by 0x52081FA: ??? (in /usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.30)
==352513==    by 0x1A2575: std::__debug::vector<double, std::allocator<double> >::operator[](unsigned long) const (vector:445)
==352513==    by 0x1A52F4: Opm::LookUpData<Dune::CpGrid, Dune::GridView<Dune::DefaultLeafGridViewTraits<Dune::CpGrid> > >::assignFieldPropsDoubleOnLeaf(Opm::FieldPropsManager const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const (LookUpData.hh:335)
==352513==    by 0x19B0C9: Opm::Transmissibility<Dune::CpGrid, Dune::GridView<Dune::DefaultLeafGridViewTraits<Dune::CpGrid> >, Dune::MultipleCodimMultipleGeomTypeMapper<Dune::GridView<Dune::DefaultLeafGridViewTraits<Dune::CpGrid> > >, Dune::CartesianIndexMapper<Dune::CpGrid>, double>::update(bool, std::function<unsigned int (unsigned int)> const&, bool) (Transmissibility_impl.hpp:171)
==352513==    by 0x1718FC: main (test_nonnc.cpp:122)
```
valgrind output but you will in any case have to dig to figure out which vectors and such so yeah..

**Pull request merged**
