### PR TITLE
Refactor main() in flow.cpp.

### PR DESCRIPTION
**Pull request by hakonhagland**
A refactoring of `main()` in [`flow.cpp`](https://github.com/OPM/opm-simulators/blob/master/flow/flow.cpp) to address the [comments](https://github.com/OPM/opm-simulators/pull/2127#issuecomment-596529720) on PR #2127 and as preparation for implementing the Python bindings described in PR #2403.

### CODE REVIEW

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by hakonhagland** [comment]
I have updated this PR to include the new development in PR #2521, PR #2535, and PR #2524.

**Comment by atgeirr** [comment]
jenkins build this please

**Comment by atgeirr** [comment]
Looks good, will merge.

**Pull request merged**
