### PR TITLE
Always allocate buffers when restarting

### PR DESCRIPTION
**Pull request by totto82**

### CODE REVIEW

**Comment by blattms** [comment]
So previously, the buffers were only written in `beginRestart` if (accidentally) `restartConfig.getWriteRestartFile(reportStepNum, log)` was false. Now they always are.

Release or not Release?

**Comment by totto82** [comment]
Jostein confirms it works.  Release

**Comment by alfbr** [comment]
This is critical on our side, it restores the ability to restart with flow. Hence, I believe it is a strong candidate for release. We already pull it in, but it may bite others for the half year to come.

**Comment by totto82** [comment]
jenkins build this please

**Comment by bska** [comment]
I'm going to merge this now as it fixes an important use-case for Flow.  Thanks a lot for the quick analysis of the issue and the turn-around on providing a solution.

**Comment by blattms** [comment]
backported to release via #2083

**Pull request merged**
