### PR TITLE
Feature/ms wells fix restart file error

### PR DESCRIPTION
**Pull request by lisajulia**
Fix error in restart files for parallel runs and remove option to not compare them since this is not needed anymore now.
FYI: I used the undo debugger to trace this bug: https://docs.undo.io/GettingStartedWithUDB.html.

This bugfix repairs the known issues of PR #5746.

### CODE REVIEW

**Comment by lisajulia** [comment]
jenkins build this please

**Review by bska — COMMENTED** [review]
Very good.  Other than the fact that we might be able to get away with a single call to the cross-rank `sum()` function, this looks good to me.

**Comment by lisajulia** [comment]
jenkins build this please

**Review by bska — APPROVED** [review]
Thanks a lot for the updates.  This looks good to me now and I'll merge into master.

**Pull request merged**
