### PR TITLE
enabling use_multisegment_well by default.

### PR DESCRIPTION
**Pull request by GitPaean**
It will only impact models containing multisegment wells, for now the two test cases in opm-data and also model 2. 

With model 2, my testing shows a few percents first, while not sure how it impact other realizations and also the parallel.  Please suggest what we should test through before we make it in.

### CODE REVIEW

**Comment by GitPaean** [comment]
jenkins build this please

**Comment by alfbr** [comment]
> With model 2, my testing shows a few percents first

I do not understand, please elaborate.

Generally, I believe this warrants running the Model 2 realisations you have available to check for performance impact.

**Comment by GitPaean** [comment]
> I do not understand, please elaborate.

I mean the original model 2 (I am not sure if it is the realization 0).   I have a few realizations while not many. I can test them and report back.

**Comment by GitPaean** [comment]
Testing with some realizations of model 2 reveals some problems with removed perforations in dead blocks.  Basically, it causes the perforations number of well in parser and Well structure different and some consistency needs to be enforced. I will fix that first then do the testing.

**Comment by GitPaean** [comment]
Basically, before this PR, the multisegment wells are generated based on the Well information from the opm-parser. However, WellsManager might remove some perforations due to inactive cells. It did not exist in any models we have been testing before and was not considered. 
In some realizations of model 2 other than the original DATA file, some wells, although single branched, are represented with multisegment wells, and some of the perforations were ignored / removed.

I suggested some changes trying to incorporate these kind of situations. More testing and improvements will come later.

**Comment by GitPaean** [comment]
It has difficulties in running other realizations. Closing the PR. The fix related to removed perforations will be put in a new PR.

**Pull request closed without merging**
