### PR TITLE
Refactor BDA well contributions

### PR DESCRIPTION
**Pull request by akva2**
split in API specific classes for Cuda/OpenCL
    
this to
1) it's cleaner
2) it avoids pulling in openCL code in cuda classes which leads to clashes between nvidia headers and opencl.hpp
    
there is still too much API specific things in interface between the
bda components to work through a virtual interface so we still have to cast
to the relevant implementation in various places.

sits on top of #3690 which should be processed first.

### CODE REVIEW

**Comment by akva2** [comment]
jenkins build this cuda please

**Comment by Tongdongq** [comment]
I'm trying it now.
It looks like the first 3 commits are the same as in #3690.
Doesn't that mean that one is obsolete?

**Comment by akva2** [comment]
As I noted in pr description that should be processed separately as it is the simple things. I'll move some more commits from here to there, so this PR only holds the refactoring eventually but I have to go get my kid in the kindergarden now.

**Comment by Tongdongq** [comment]
I only tested the first few linear systems for now.
It runs normally with CUDA and OpenCL, and with just OpenCL for all reordering methods.
cusparseSolver also works like expected.

**Comment by akva2** [comment]
great. then we need to figure out why the exception handling in test_cusparsesolver fails to do its job unlike the test_openclsolver and we can enable ci for the cuda code.

**Comment by akva2** [comment]
jenkins build this cuda please

**Pull request merged**
