### PR TITLE
Add few missing unsupported keywords to the list

### PR DESCRIPTION
**Pull request by goncalvesmachadoc**
Added the unsupported keywords WBP, WBP4, WBP5, WBP9, NLINEARS to the list in MissingFeatures.cpp.

### CODE REVIEW

**Comment by joakim-hove** [comment]
just like the doctor ordered - thank you

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by blattms** [comment]
This should go into release as #2024 is based on it and also marked for release

**Comment by blattms** [comment]
backported to release via #2085

**Pull request merged**
