### PR TITLE
Adding --num-pressure-points-equil as a developer parameter 

### PR DESCRIPTION
**Pull request by vkip**
Adding a developer parameter (invisible to end users) to change the number of pressure table points used in equilibration.

### CODE REVIEW

**Comment by bska** [comment]
Nice.  Could we also co-opt [`EQLDIMS(2)`](https://github.com/OPM/opm-common/blob/c6d4a635e3a139fbbd970c413412d9c5e91576bb/src/opm/input/eclipse/share/keywords/000_Eclipse100/E/EQLDIMS#L13-L17) for this purpose, or does that not make sense?

**Comment by vkip** [comment]
> Nice. Could we also co-opt [`EQLDIMS(2)`](https://github.com/OPM/opm-common/blob/c6d4a635e3a139fbbd970c413412d9c5e91576bb/src/opm/input/eclipse/share/keywords/000_Eclipse100/E/EQLDIMS#L13-L17) for this purpose, or does that not make sense?

That probably makes a lot of sense, just didn't think of it! Will give it a shot.

**Comment by bska** [comment]
jenkins build this please

**Comment by vkip** [comment]
Now depends on opm-common PRs 3581 and 3582

**Comment by vkip** [comment]
jenkins build this opm-common=3581 opm-common=3582 please

**Comment by akva2** [comment]
nah, only one PR per repo.

**Comment by vkip** [comment]
jenkins build this opm-common=3582 please

**Comment by vkip** [comment]
jenkins build this opm-common=3582 opm-tests=1002 please

**Comment by vkip** [comment]
jenkins build this opm-common=3582 opm-tests=1002 please

**Comment by vkip** [comment]
any further input on this?

**Review by bska — APPROVED** [review]
> any further input on this?

None&ndash;this is fine.  I'm not completely thrilled about including `E.hpp` in `eclproblem.hh`, but I don't see a way around it.  I'll merge into master.

**Pull request merged**
