### PR TITLE
make group constrain check conditional

### PR DESCRIPTION
**Pull request by totto82**
As a general rule we don't want to check the current group control. A naive implementation of this did however not work since well controls may change during simulations due to input in the Schedule or closing of wells etc. This PR tries to circumvent this by always checking the first two iterations. An alternative solution is to add an epsilon to avoid switching as has been used in testing branches for groups [#2273] for a long time. The solution suggested in this PR seems more robust.

### CODE REVIEW

**Comment by totto82** [comment]
jenkins build this please

**Comment by totto82** [comment]
jenkins build this please

**Comment by totto82** [comment]
jenkins build this please

**Comment by totto82** [comment]
I have double-checked the failing test. The results are fine.

**Comment by totto82** [comment]
@atgeirr review?

**Comment by totto82** [comment]
Can we merge this?

**Comment by atgeirr** [comment]
I think this can be merged, but Jenkins does not agree...

Also, I am a bit hesitant about the update being decided by report steps and not timesteps in general, is this really thought through? I would think it more appropriate to check every timestep.

**Comment by totto82** [comment]
> is this really thought through

I thought so too, but checking every timestep led to issues for several of the norne models. We still need to iterate on this, but I think this is a move in the right direction. Merging this makes testing easier and hopefully we can improve on this later. It has already gone 3 weeks sine it appeared. I have verified the test failure.  update_data should do the trick.

**Comment by atgeirr** [comment]
jenkins build this update_data please

**Comment by atgeirr** [comment]
jenkins build this opm-tests=236 please

**Pull request merged**
