### PR TITLE
Calculate Hydrocarbon Pore-Volumes if Requested

### PR DESCRIPTION
**Pull request by bska**
This commit separates the computation of hydrocarbon pore-volumes out from the context of average pressure values.  These pore-volumes go into the `xHPV` summary vectors and are, therefore, useful in their own right&ndash;not just as a means to computing average pressure values.

### CODE REVIEW

**Comment by bska** [comment]
I'm creating this PR in draft mode because it depends on, and contains, PR #4874.  I will keep the PR in draft state until such time as it is ready for review and merging.

**Comment by bska** [comment]
The upstream PR has been merged into the master branch.  I'm marking this as "ready for review" now and I'm running a build check.

**Comment by bska** [comment]
jenkins build this please

**Review by akva2 — APPROVED** [review]
Looks good.

**Review by bska — COMMENTED** [review]
Build check is green.  Merging per prior approval.

**Pull request merged**
