### PR TITLE
Remove FIPNUM From List of Unsupported Keywords

### LINKED ISSUE #1875: Why is FIPNUM Listed as Unsupported
Our list of unsupported simulator keywords includes [FIPNUM](https://github.com/OPM/opm-simulators/blob/d42c5426b2bbc925901b07473cc39ac93eaa073d/opm/autodiff/MissingFeatures.cpp#L109).  Is there a reason for this keyword being marked unsupported, especially since we appear to support the vector being defined by `EQUALS` or similar mechanisms?

### PR DESCRIPTION
**Pull request by bska**
We've supported the keyword&mdash;both in the deck reader (parser) and in the simulator&mdash;for a long time.

Fixes #1875.

### CODE REVIEW

**Comment by bska** [comment]
jenkins build this please

**Comment by bska** [comment]
jenkins build this please

**Comment by GitPaean** [comment]
since you are cleaning up this, maybe you can also help to remove the following three keywords?

COMPLUMP
AQUTAB
AQUCT

**Comment by bska** [comment]
> since you are cleaning up this, maybe you can also help to remove the following three keywords?

I can.  Update pushed in commit 123b578.

**Comment by GitPaean** [comment]
jenkins build this please

**Comment by GitPaean** [comment]
Thanks for the efforts.

**Pull request merged**
