### PR TITLE
we only use drift compensation when wells are active

### PR DESCRIPTION
**Pull request by GitPaean**
The targeting situation is that for one case, the wells are not running for some report steps with only aquifers. Drift compensation really impacts the convergence for that running. 

The alternative can be to make `aquifer.active()` based on how much flux the aquifer is doing. 

This PR sits on top of https://github.com/OPM/opm-simulators/pull/4101 .

### CODE REVIEW

**Comment by totto82** [comment]
Thanks. This can be merged when #4101 is merged.

**Comment by GitPaean** [comment]
A note here is that a better criteria will be how much injection/production flux or aquifer flux is ongoing. Because wells and aquifer can be open while not running much, then drift compensation will impacting the convergence behavior.

**Comment by GitPaean** [comment]
I will trigger a benchmark test to see the performance change with this PR.

**Comment by GitPaean** [comment]
benchmark please

**Comment by GitPaean** [comment]
benchmark please

**Comment by ytelses** [comment]
Benchmark result overview: 




| Test    | Configuration                              | Relative |
| ------- | ------------------------------------------ | -------- |
| opm-git | OPM Benchmark: flow_mpi_extra - Threads: 1 | 0.985    |
| opm-git | OPM Benchmark: flow_mpi_extra - Threads: 8 | 1.009    |
| opm-git | OPM Benchmark: flow_mpi_norne - Threads: 1 | 0.994    |
| opm-git | OPM Benchmark: flow_mpi_norne - Threads: 8 | 0.946    |
* Speed-up = Total time master / Total time pull request. Above 1.0 is an improvement. *



View result details @ https://www.ytelses.com/opm/?page=result&id=1786

**Comment by GitPaean** [comment]
I think there is some messing up of `benchmark` of this PR and https://github.com/OPM/opm-simulators/pull/4116 .  Let me trigger the benchmark again to see. The previous benchmark results are seriously different from the local testing.

**Comment by ytelses** [comment]
Benchmark result overview: 




| Test    | Configuration                              | Relative |
| ------- | ------------------------------------------ | -------- |
| opm-git | OPM Benchmark: flow_mpi_extra - Threads: 1 | 1        |
| opm-git | OPM Benchmark: flow_mpi_extra - Threads: 8 | 1.021    |
| opm-git | OPM Benchmark: flow_mpi_norne - Threads: 1 | 1.009    |
| opm-git | OPM Benchmark: flow_mpi_norne - Threads: 8 | 0.982    |
* Speed-up = Total time master / Total time pull request. Above 1.0 is an improvement. *



View result details @ https://www.ytelses.com/opm/?page=result&id=1788

**Comment by ytelses** [comment]
Benchmark result overview: 




| Test    | Configuration                              | Relative |
| ------- | ------------------------------------------ | -------- |
| opm-git | OPM Benchmark: flow_mpi_extra - Threads: 1 | 0.996    |
| opm-git | OPM Benchmark: flow_mpi_extra - Threads: 8 | 1.022    |
| opm-git | OPM Benchmark: flow_mpi_norne - Threads: 1 | 1.015    |
| opm-git | OPM Benchmark: flow_mpi_norne - Threads: 8 | 0.973    |
* Speed-up = Total time master / Total time pull request. Above 1.0 is an improvement. *



View result details @ https://www.ytelses.com/opm/?page=result&id=1789

**Comment by GitPaean** [comment]
jenkins build this please

**Comment by GitPaean** [comment]
jenkins build this update_data please

**Comment by GitPaean** [comment]
jenkins build this opm-tests=805 please

**Comment by GitPaean** [comment]
jenkins build this update_data please

**Comment by GitPaean** [comment]
jenkins build this opm-tests=806 please

**Comment by GitPaean** [comment]
jenkins build this opm-tests=806 please

**Comment by GitPaean** [comment]
I do not understand here. The `update_data` created the update for the opm-tests, but the jenkins will not give green to the update from `update_data`. @bska @akva2 , do you have some suggestions? Thanks.

**Comment by bska** [comment]
> jenkins will not give green to the update from `update_data`

It's a bit more subtle than that, unfortunately.  The [regression failures](https://ci.opm-project.org/job/opm-simulators-PR-builder/4017/testReport/) are all for `mpi.compareParallelSim_*`-type runs.  These do not compare to a "known good" reference solution, but rather to a sequential run (effectively `mpirun -np 1`) of the same binary on the same case.  There is no way to fix those with `update_data` so you'll either have to understand what the difference is between the sequential and parallel runs&mdash;and ideally fix it too&mdash;or possibly make the comparison tolerances less strict.

**Comment by totto82** [comment]
There is some issue with the parallel support. Is wellsActive communicated?

**Comment by GitPaean** [comment]
Let us try again, since after the master branch changes.

**Comment by GitPaean** [comment]
jenkins build this update_data please

**Comment by GitPaean** [comment]
jenkins build this opm-tests=806 please

**Comment by GitPaean** [comment]
benchmark please

**Comment by GitPaean** [comment]
The test failure https://ci.opm-project.org/job/opm-simulators-PR-builder/4029/testReport/junit/(root)/mpi/compareParallelSim_flow_3_A_MPI_MULTFLT_SCHED_MODEL2/ 

is the one stopping the PR goes in. 

The comparison plot is in this pdf file. 
[3_A_MPI_MULTFLT_SCHED_MODEL2_fix.pdf](https://github.com/OPM/opm-simulators/files/9656156/3_A_MPI_MULTFLT_SCHED_MODEL2_fix.pdf)

It appears to be there is a little different time stepping between `01/01/2021` and `01/02/2021`. The serial running takes two extra shorter time steps there and it is where the visual difference shown in the plot. 

To me, it is not worrying for the comparison, but it is not easy for jenkins to approve it either.

**Comment by GitPaean** [comment]
because the problem happens when there is relatively bigger step (31 days), I suggest we use moderate time steps to avoid these types of not easy to fix time stepping problems. 

Let us try with 10days.

**Comment by GitPaean** [comment]
It looks like the case had been previously difficult to fix the comparison. 

The following arguments have been put there for the comparison, 

```
--linear-solver-reduction=1e-7 --tolerance-cnv=5e-6 --tolerance-mb=1e-8
```

Strict tolerance will also make the time stepping hard. Maybe tightening tolerances was not the optimal way of fixing the comparison.

**Comment by GitPaean** [comment]
jenkins build this opm-tests=806 please

**Comment by GitPaean** [comment]
Just for comparison, when adding `--solver-max-time-step-in-days=10` to the running of the case 3_A_MPI_MULTFLT_SCHED_MODEL2 , the parallel comparison is as follows, 

[3_A_MPI_MULTFLT_SCHED_MODEL2_fix.pdf](https://github.com/OPM/opm-simulators/files/9656459/3_A_MPI_MULTFLT_SCHED_MODEL2_fix.pdf)

basically visually identical.

**Comment by blattms** [comment]
As jenkins fails whenever the time stepping is different (e.g. different number of time steps), we need to make sure that the time stepping is the same for the serial and parallel run (there is no guarantee that it is as the (non-)linear solvers might behave slightly different).

Hence the question is whether the time stepping is the same now with your additional parameter. If that is the case, then we should probably add that option to compareECLFiles.cmake. Unless @akva2 objects.

**Comment by GitPaean** [comment]
> Hence the question is whether the time stepping is the same now with your additional parameter. If that is the case, then we should probably add that option to compareECLFiles.cmake.

Yes, for the example `compareParallelSim_flow_3_A_MPI_MULTFLT_SCHED_MODEL2`, adding `time-step-in-days=10` does make the time stepping the same between serial running and parallel running. As a result, it fixes the comparison.

**Comment by GitPaean** [comment]
And also, one observation is that, if the serial running needs to chop time steps, it is very hard to guarantee the parallel running behaves exactly the same.  

I think limiting the time step sizes are an viable approach here.

**Comment by GitPaean** [comment]
jenkins build this opm-tests=806 please

**Comment by GitPaean** [comment]
For the remaining failure, 
https://ci.opm-project.org/job/opm-simulators-PR-builder/4035/testReport/(root)/mpi/compareParallelSim_flow_TEST_RXFT/

the well curve comparison is  good. 
[TEST_RXFT_fix.pdf](https://github.com/OPM/opm-simulators/files/9659896/TEST_RXFT_fix.pdf)

But the following are exceeding the tolerances, 
```
	RGFT-:1-4: Summary file
		Fails for 1 entries
		Largest absolute error: 5.3650879e+01
		Largest relative error: 1.6932280e-02
	RGFT:1-2: Summary file
		Fails for 2 entries
		Largest absolute error: 6.5027344e+02
		Largest relative error: 4.7599140e-01
	RGFT:1-4: Summary file
		Fails for 1 entries
		Largest absolute error: 5.3650879e+01
		Largest relative error: 1.6932280e-02
	RGFT:3-4: Summary file
		Fails for 6 entries
		Largest absolute error: 6.4686719e+02
		Largest relative error: 1.4048543e-02
	ROFT-:1-4: Summary file
		Fails for 1 entries
		Largest absolute error: 4.4709396e-01
		Largest relative error: 1.6932405e-02
	ROFT:1-2: Summary file
		Fails for 2 entries
		Largest absolute error: 5.9317017e+00
		Largest relative error: 1.3549482e-02
	ROFT:1-4: Summary file
		Fails for 1 entries
		Largest absolute error: 4.4709396e-01
		Largest relative error: 1.6932405e-02
	ROFT:3-4: Summary file
		Fails for 7 entries
		Largest absolute error: 5.4766541e+00
		Largest relative error: 1.6980304e-02
	RWFT-:1-4: Summary file
		Fails for 1 entries
		Largest absolute error: 5.8640862e-01
		Largest relative error: 1.9329853e-02
	RWFT:1-4: Summary file
		Fails for 1 entries
		Largest absolute error: 5.8640862e-01
		Largest relative error: 1.9329853e-02
```

I relax the relative tolerance further to be 2.e-2 from 1.e-2.

**Comment by GitPaean** [comment]
jenkins build this opm-tests=806 please

**Comment by GitPaean** [comment]
o, I oversaw the following comparison failure, 

```

Value index                 = 47
(first value, second value) = (-714.761, -1364.03)

Program threw an exception: [/var/lib/jenkins/workspace/opm-simulators-PR-builder/deps/opm-common/test_util/EclRegressionTest.cpp:202] Deviations exceed tolerances.
The absolute deviation is 649.265, and the tolerance limit is 0.02.
The relative deviation is 0.475991, and the tolerance limit is 0.02.
```

which is a little unfortunate.  

Will check this value on local running.

**Comment by GitPaean** [comment]
The well curve comparison for `RGFT:1-2` is 

image

**Comment by GitPaean** [comment]
jenkins build this please

**Comment by GitPaean** [comment]
jenkins build this opm-tests=806 please

**Comment by GitPaean** [comment]
From the local testing, the following two options are making the parallel regression tests harder, 

```
--ecl-enable-drift-compensation
```
and 
```
--relaxed-max-pv-fraction
```

When they are disabled, the parallel regression tests are much easier. 
Will update the PR.

**Comment by GitPaean** [comment]
I can be wrong, for the specific case `TEST_RXFT`, the `--ecl-enable-drift-compensation` will affect the time stepping due to nonlinear convergence for the parallel regression test, and the option `--relaxed-max-pv-fraction` affects the digital comparison of the results in the parallel setting. 

maybe we can check whether `--relaxed-max-pv-fraction` is done well for parallel running?

**Comment by GitPaean** [comment]
jenkins build this opm-tests=806 please

**Comment by ytelses** [comment]
Benchmark result overview: 




| Test    | Configuration                              | Relative |
| ------- | ------------------------------------------ | -------- |
| opm-git | OPM Benchmark: flow_mpi_extra - Threads: 1 | 1.021    |
| opm-git | OPM Benchmark: flow_mpi_extra - Threads: 8 | 1.023    |
| opm-git | OPM Benchmark: flow_mpi_norne - Threads: 1 | 1.005    |
| opm-git | OPM Benchmark: flow_mpi_norne - Threads: 8 | 1.03     |
* Speed-up = Total time master / Total time pull request. Above 1.0 is an improvement. *



View result details @ https://www.ytelses.com/opm/?page=result&id=1799

**Comment by GitPaean** [comment]
jenkins build this opm-tests=806 please

**Comment by GitPaean** [comment]
jenkins build this opm-tests=806 please

**Comment by GitPaean** [comment]
At the end and I should tried this option earlier, it is the drift compensation activated by this PR makes the parallel regression testing difficult, which is the direct cause without saying it is the root problem. 

Although adjusting other options like `--relaxed-max-pv-fraction` and `--solver-max-time-step-in-days` can fix the regression test, but at the end, I decided to disable the drift compensation for these failed parallel regression tests. 

> There is some issue with the parallel support. Is wellsActive communicated?

I checked for two of the cases, it is not the cause.

**Comment by GitPaean** [comment]
jenkins build this opm-tests=806 please

**Comment by GitPaean** [comment]
The jenkins test is green now and the code self was approved by @totto82 . 

At the end, due to the parallel regression testing failures, I had to disable the drift compensation for those tests. I would like some approval regarding the adjustments regarding to those parallel tests. 

@totto82 @bska @akva2

**Comment by totto82** [comment]
I am fine with disabling drift compensation for the failing tests. Thanks for the thorough testing.

**Comment by GitPaean** [comment]
> I am fine with disabling drift compensation for the failing tests. Thanks for the thorough testing.

Then let us get it in. We will see how things will turn out since it will turn on the drift compensation for the majority of the cases now.

**Pull request merged**
