### PR TITLE
fixed: division by zero if no gpu device was found

### PR DESCRIPTION
**Pull request by akva2**
Fixes regression from https://github.com/OPM/opm-simulators/pull/5611 if no gpu devices are available on system

### CODE REVIEW

**Comment by akva2** [comment]
jenkins build this hipify please

**Comment by bska** [comment]
@kjetilly, @multitalentloes: This looks good to me, but as I'm not an accelerator expert I defer to you to review the details here.

**Comment by multitalentloes** [comment]
Looks good to me too

**Comment by bska** [comment]
> Looks good to me too

Thanks!  I'll merge into master, then.

**Pull request merged**
