### PR TITLE
Use RestartValue when saving eclipse output

### PR DESCRIPTION
**Pull request by joakim-hove**
See: https://github.com/OPM/opm-common/pull/391

~~The failed second commit does not even compile.~~

### CODE REVIEW

**Comment by joakim-hove** [comment]
Hold back on this - wil work more with the OPM-common part.

**Comment by joakim-hove** [comment]
jenkins build this ewoms=316 opm-common=391 please

**Comment by atgeirr** [comment]
This in itself looks fine, I will be making any comments in the opm-common PR.

**Comment by atgeirr** [comment]
jenkins build this ewoms=316 opm-common=391 please

**Comment by joakim-hove** [comment]
jenkins build this ewoms=316 opm-common=391 please

**Pull request merged**
