### PR TITLE
[testing] Tighten tolerance standard wells to 1.e-8

### PR DESCRIPTION
**Pull request by GitPaean**

### CODE REVIEW

**Comment by GitPaean** [comment]
benchmark please

**Comment by ytelses** [comment]
Benchmark result overview: 




| Test    | Configuration                              | Relative |
| ------- | ------------------------------------------ | -------- |
| opm-git | OPM Benchmark: drogon - Threads: 1         | 0.98     |
| opm-git | OPM Benchmark: drogon - Threads: 8         | 1.009    |
| opm-git | OPM Benchmark: smeaheia - Threads: 1       | 0.929    |
| opm-git | OPM Benchmark: smeaheia - Threads: 8       | 0.992    |
| opm-git | OPM Benchmark: spe10_model_1 - Threads: 1  | 1.054    |
| opm-git | OPM Benchmark: spe10_model_1 - Threads: 8  | 1.064    |
| opm-git | OPM Benchmark: flow_mpi_extra - Threads: 1 | 0.987    |
| opm-git | OPM Benchmark: flow_mpi_extra - Threads: 8 | 1.091    |
| opm-git | OPM Benchmark: flow_mpi_norne - Threads: 1 | 1.007    |
| opm-git | OPM Benchmark: flow_mpi_norne - Threads: 8 | 1.052    |
* Speed-up = Total time master / Total time pull request. Above 1.0 is an improvement. *



View result details @ https://www.ytelses.com/opm/?page=result&id=2018

**Comment by GitPaean** [comment]
tested with norne and model 2(assuming the same with flow_mpi_norne) locally,  the change of the performance is very minimal. 

Not sure which model is used for the test with `smeaheia` in the benchmark.

**Comment by GitPaean** [comment]
I am looking into tightening the tolerance (for StandarWell for now) due to a recent reported issue regarding the BHP value with zero rate controlled wells.  It appears the root cause is that we are using not tight enough tolerance (1.e-4) for the well equations (so far, the issue case is a StandardWell model case). 

I did some initial testing with Norne and Model 2,  it looks similar to the performance results reported by benchmark. Performance change is minimal. But what other tests should we do to justify that the tightening the tolerance is okay? 

@alfbr @tskille @atgeirr @totto82 @vkip @bska @hnil 

BTW: tightening tolerance to 1.e-7 or 1.e-8 both work, somehow tolerance with 1.e-8 has slightly better performance for Norne and model 2.

**Comment by GitPaean** [comment]
jenkins build this please

**Comment by GitPaean** [comment]
jenkins build this please

**Comment by GitPaean** [comment]
For the example ACTIONX_M1, with this PR, there is significant difference in term of WBHP and FPR. Not sure which one is better. 

image

**Comment by GitPaean** [comment]
Thanks for the investigation, @tskille . 

At the same time, using stricter tolerance makes the well targets better enforced and also the well curves are smoother. 

For example, the below is the one wells under ORAT control.  Although the difference is not significant, while looking better. 

Screenshot from 2023-04-11 13-08-56

**Comment by bska** [comment]
@GitPaean : Is this the same as, or superseded by, #5280?

**Comment by GitPaean** [comment]
> @GitPaean : Is this the same as, or superseded by, #5280?

it is superseded by https://github.com/OPM/opm-simulators/pull/5280 . 

At the end, this PR was merged in the form of #5232.  I consider this PR should be closed now. 

#5280 is a separate issue. Will find time to see how to get #5280 in (assuming benchmark reliable), because it will simplify some special treatment related to tolerance (e.g. #5232) and some other scenarios call for tighter tolerance. Not fond of introducing more complicated logic. 

Closing this PR now and there will be some discussion related to #5280 .

**Pull request closed without merging**
