### PR TITLE
add support for FBHPDEF keyword

### PR DESCRIPTION
**Pull request by akva2**
Downstream of https://github.com/OPM/opm-common/pull/3747

### CODE REVIEW

**Comment by akva2** [comment]
[bhp_no_limit.pdf](https://github.com/OPM/opm-simulators/files/13247934/bhp_no_limit.pdf)
Without the keyword, no limits are applied and INJ is above 500, while PROD2 is below 50

[bhp.pdf](https://github.com/OPM/opm-simulators/files/13247927/bhp.pdf)

Results from the test case, INJ1 is limited to 500 from above and PROD2 is limited to 50 from below

**Comment by akva2** [comment]
jenkins build this update_data please

**Comment by akva2** [comment]
jenkins build this opm-tests=1084 please

**Review by bska — APPROVED** [review]
Very good.   The reference solutions have been installed on the CI system, so I'll merge this now to activate the feature test.

**Pull request merged**
