### PR TITLE
Added MULTXYZ tests as regression tests.

### PR DESCRIPTION
**Pull request by blattms**
The tests can be found in OPM/opm-tests#1142.

Together with OPM/opm-common#3997 this will make sure that the fix in OPM/opm-common#4002 stays.

### CODE REVIEW

**Comment by bska** [comment]
jenkins build this update_data please

**Comment by bska** [comment]
> ```
> update_data please
> ```

That created PR/Issue OPM/opm-tests#1147, but there are no new/updated files in that PR.  The last part of the [build transcript](https://ci.opm-project.org/job/opm-simulators-PR-builder/6090/console) has the following command sequence

> ```
> Listing '/var/lib/jenkins/workspace/opm-simulators-PR-builder/mpi/install/lib/python3.9/site-packages/opm/tools'...
> Listing '/var/lib/jenkins/workspace/opm-simulators-PR-builder/mpi/install/lib/python3.9/site-packages/opm/util'...
> ~/workspace/opm-simulators-PR-builder
> compareECLFiles_flow.MULTXYZ05 flow  MULTXYZ05 05_multxyz
> compareECLFiles_flow.MULTXYZ06 flow  MULTXYZ06 06_multxyz
> compareECLFiles_flow.MULTXYZ07 flow  MULTXYZ07 07_multxyz
> compareECLFiles_flow.MULTXYZ08 flow  MULTXYZ08 08_multxyz
> compareECLFiles_flow.MULTXYZ11 flow  MULTXYZ11 11_multxyz
> Switched to a new branch 'update_opm-simulators_5274'
> Branch 'update_opm-simulators_5274' set up to track remote branch 'master' from 'origin'.
> On branch update_opm-simulators_5274
> Your branch is up to date with 'origin/master'.
> ```

but there is none of the tell-tale signs of new files being created.  @akva2 : Do you see anything obviously missing in this PR, or did Something[tm] just go wrong the CI system?

**Comment by akva2** [comment]
https://ci.opm-project.org/job/opm-simulators-PR-builder/6090/testReport/junit/(root)/mpi/compareECLFiles_flow_MULTXYZ05/

**Comment by bska** [comment]
> missing include file.

Doh.  I should have caught that whilst reviewing OPM/opm-tests#1142.  Sorry.  @blattms : Please upload the `t1_3x2x1.grdecl` include file to OPM-Tests.

**Comment by blattms** [comment]
Sorry, that should not have happend. Fixed in OPM/opm-tests#1148

**Comment by bska** [comment]
jenkins build this please

**Comment by bska** [comment]
> jenkins

The test cases run now, following OPM/opm-tests#1148.  I'll create reference solutions and activate these tests.

**Comment by bska** [comment]
jenkins build this update_data please

**Comment by bska** [comment]
jenkins build this opm-tests=1149 please

**Review by bska — APPROVED** [review]
The new reference solutions have been merged into the master branch.  Merging this now to activate the new regression tests.

**Pull request merged**
