### PR TITLE
GridManager - is it in use?

### PR DESCRIPTION
**Pull request by joakim-hove**
This commit just removes some unused references to `GridManager.hpp`. Can the complete `GridManager` class be removed?

### CODE REVIEW

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by bska** [comment]
> Can the complete `GridManager` class be removed?

Possibly.  The following files (in master) reference at least the header.  Some of these instantiate objects too.

* `./opm-simulators/tests/test_stoppedwells.cpp`
* `./opm-simulators/tests/test_ecl_output.cc`
* `./opm-simulators/tests/test_thresholdpressure.cpp`
* `./opm-simulators/tests/test_wellmodel.cpp`
* `./opm-simulators/tests/test_wellstatefullyimplicitblackoil.cpp`
* `./opm-simulators/tests/test_equil.cc`
* `./opm-simulators/tests/test_relpermdiagnostics.cpp`
* `./opm-simulators/tests/test_wellsmanager.cpp`
* `./opm-simulators/opm/core/props/satfunc/RelpermDiagnostics.hpp`
* `./opm-grid/tests/test_gridutilities.cpp`
* `./opm-grid/tests/test_velocityinterpolation.cpp`
* `./opm-grid/tests/test_wachspresscoord.cpp`
* `./opm-grid/tests/test_compressedpropertyaccess.cpp`
* `./opm-grid/tests/test_quadratures.cpp`
* `./opm-grid/tests/test_column_extract.cpp`
* `./opm-grid/tests/test_ug.cpp`
* `./opm-grid/opm/grid/GridManager.hpp`
* `./opm-grid/opm/grid/polyhedralgrid/grid.hh`
* `./opm-grid/opm/grid/GridManager.cpp`

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by atgeirr** [comment]
I think we can remove all usage in opm-simulators at least. The class should remain while the UnstructuredGrid remains (which in turn is also used by PolyhedralGrid). I'll comment briefly below on the opm-simulators usage, we might not want to prioritize this ahead of the release though.  I note that many of the GridManager objects have been named "vanguard", I suspect a runaway search-replace we did not notice...

> * `./opm-simulators/tests/test_stoppedwells.cpp`

Can be completely removed. Tests about-to-be-unused well control code.

> * `./opm-simulators/tests/test_thresholdpressure.cpp`

Should have been removed. Not even compiled today!

> * `./opm-simulators/tests/test_ecl_output.cc`
> * `./opm-simulators/opm/core/props/satfunc/RelpermDiagnostics.hpp`

Does not use the class, surplus inclusion.

> * `./opm-simulators/tests/test_wellstatefullyimplicitblackoil.cpp`
> * `./opm-simulators/tests/test_wellmodel.cpp`
> * `./opm-simulators/tests/test_relpermdiagnostics.cpp`
> * `./opm-simulators/tests/test_wellsmanager.cpp`

Needs refactoring to use CpGrid instead. For the most part, should be as simple as constructing a CpGrid instead and passing that around.

> * `./opm-simulators/tests/test_equil.cc`

Has been partially refactored to build an ebos-simulator object with vanguard and use that, but needs more refactoring to get rid of some residual usage.

**Comment by joakim-hove** [comment]
> I think we can remove all usage in opm-simulators at least.

The current PR has the even more modest ambition of removing it from flow codepath; it is still in use in tests. But this should be a small step in the Right&trade; direction.

**Comment by joakim-hove** [comment]
This is a small step in the right direction - merging.

**Pull request merged**
