### PR TITLE
[bugfix] make code compile when GridView is not Grid::LeafGridView.

### PR DESCRIPTION
**Pull request by dr-robertk**
This fixes a minor issue when GridView defined in ewoms is not Grid::LeafGridView.

### CODE REVIEW

**Comment by andlaus** [comment]
I think this that making non-leaf grid views work is good thing to have, but I cannot what the patch changes semantically?

**Comment by atgeirr** [comment]
> This fixes a minor issue when GridView defined in ewoms is not Grid::LeafGridView.

In what setting do you see this become important? If you choose to use a non-leaf grid view, I would think that you wanted everything, including the function modified here, to honor that choice? (I.e give out ranks for entities in the chosen grid view.)

**Comment by dr-robertk** [comment]
It does not really matter. The code as it is there is wrong, because if one calls grid.leafGridView then one should not use GridView defined somewhere but Grid::LeafGridView.

**Comment by atgeirr** [comment]
> if one calls grid.leafGridView

That is of course an excellent point... Merging!

**Pull request merged**
