### PR TITLE
adding --use-multisegment-well=true to msw-model-1 test

### PR DESCRIPTION
**Pull request by GitPaean**

### CODE REVIEW

**Comment by GitPaean** [comment]
The jenkins test will fail for the test msw-model-1.

**Comment by GitPaean** [comment]
jenkins  build this please

**Comment by GitPaean** [comment]
jenkins build this please

**Comment by GitPaean** [comment]
jenkins build this update_data please

**Comment by GitPaean** [comment]
I do not understand why this PR will update so many reference results. It is only related to one test, while much more tests need to be updated in https://github.com/OPM/opm-tests/pull/82 .

**Comment by GitPaean** [comment]
jenkins build this opm-tests=82 please

**Comment by bska** [comment]
> I do not understand why this PR will update so many reference results

One possibility is that the other changes we've made since previously running `update_data` have accumulated enough differences that the runs are no longer exactly equal despite `--use-multisegment-well` affecting only a single test case.

**Comment by GitPaean** [comment]
jenkins build this update_data please

**Comment by GitPaean** [comment]
Most of the updates are `SMSPEC` files. The only `UNSMRY` file is updated is related to `msw-model-1`, there is a couple of `INIT` and `UNRST` file updated in OPM/opm-tests#82. Maybe people working on output can have some clue?

**Comment by GitPaean** [comment]
jenkins build this opm-tests=82 please

**Comment by GitPaean** [comment]
jenkins build this update_data please

**Comment by GitPaean** [comment]
jenkins build this opm-tests=82 please

**Comment by bska** [comment]
Something went wrong here.  The post-commit CI build now [fails](https://ci.opm-project.org/job/opm-simulators/645/testReport/junit/(root)/mpi/compareECLFiles_flow_MSW_MODEL_1/) both the MPI and the sequential (serial) configurations.

**Comment by GitPaean** [comment]
I will make a test locally.

**Comment by atgeirr** [comment]
I have queued a rerun of the post-builder. We'll see if it was a sync problem.

**Pull request merged**
