### PR TITLE
fixed: broadcasting an int and receiving as a size_t is a very bad idea

### PR DESCRIPTION
**Pull request by akva2**
pointy-hat: me

### CODE REVIEW

**Comment by akva2** [comment]
jenkins build this please

**Comment by bska** [comment]
Is this the reason that the [nightly-bionic-docker](https://ci.opm-project.org/job/opm-nightly-bionic-docker/) build has been failing lately?

**Comment by akva2** [comment]
very likely.

**Comment by akva2** [comment]
shameful self-merge.

**Comment by bska** [comment]
>> Is this the reason that the nightly-bionic-docker build has been failing lately?
>
> very likely.

Very good.  In any case, this is obviously an improvement, so even if it does not end up fixing the nightly build it should go into master.

> shameful self-merge.

If you didn't merge it yourself I would have.

**Pull request merged**
