### PR TITLE
removing the 1bar limit for bhp/segment pressure during newton update

### PR DESCRIPTION
**Pull request by GitPaean**

### CODE REVIEW

**Comment by GitPaean** [comment]
jenkins build this please

**Comment by GitPaean** [comment]
benchmark please

**Comment by GitPaean** [comment]
I am not done checking the jenkins yet. But it looks like this one changes the results related to WECON, WTEST and UDQ. Basically these types of cases depending on the resulting well values to determine later behavoirs. 

image

**Comment by ytelses** [comment]
Benchmark result overview: 




| Test    | Configuration                                     | Relative |
| ------- | ------------------------------------------------- | -------- |
| opm-git | OPM Benchmark: drogon - Threads: 1                | 1.002    |
| opm-git | OPM Benchmark: drogon - Threads: 8                | 1.12     |
| opm-git | OPM Benchmark: punqs3 - Threads: 1                | 1.002    |
| opm-git | OPM Benchmark: punqs3 - Threads: 8                | 1.015    |
| opm-git | OPM Benchmark: smeaheia - Threads: 1              | 1.003    |
| opm-git | OPM Benchmark: smeaheia - Threads: 8              | 1.013    |
| opm-git | OPM Benchmark: spe10_model_1 - Threads: 1         | 1.027    |
| opm-git | OPM Benchmark: spe10_model_1 - Threads: 8         | 0.999    |
| opm-git | OPM Benchmark: flow_mpi_extra - Threads: 1        | 0.857    |
| opm-git | OPM Benchmark: flow_mpi_extra - Threads: 8        | 0.797    |
| opm-git | OPM Benchmark: flow_mpi_norne_4c_msw - Threads: 1 | 0.988    |
| opm-git | OPM Benchmark: flow_mpi_norne_4c_msw - Threads: 8 | 1.001    |
* Speed-up = Total time master / Total time pull request. Above 1.0 is an improvement. *



View result details @ https://www.ytelses.com/opm/?page=result&id=2185

**Comment by GitPaean** [comment]
Let us use 0. bar limit for now instead of removing it by all.

**Pull request closed without merging**
