### PR TITLE
add molar fraction of CO2 in brine to RST output

### PR DESCRIPTION
**Pull request by totto82**
The output is given if CO2STORE, DISGASW and `--enable-opm-rst-file=true`.

### CODE REVIEW

**Comment by totto82** [comment]
jenkins build this please

**Comment by totto82** [comment]
jenkins build this opm-common=3448 please

**Comment by bska** [comment]
jenkins build this please

**Review by bska — APPROVED** [review]
Thanks.  I'll merge into master.

**Pull request merged**
