### PR TITLE
[WIP] trying to refactor the network update

### PR DESCRIPTION
**Pull request by GitPaean**
In the hope it is easier to use. 

More specifically, we can solve the network in an iterative manner until we are happy.  Evaluating how this PR can help is ongoing. 

There is also suggestions to decouple/split/simplify updateWellControls further. It is not taken care in its current form of this PR yet.

### CODE REVIEW

**Comment by GitPaean** [comment]
jenkins build this please

**Comment by GitPaean** [comment]
jenkins build this please

**Comment by GitPaean** [comment]
For the testing results in https://ci.opm-project.org/job/opm-simulators-PR-builder/4166/ 

many failures are associated with different time stepping due to time step chopping. master branch does better in some cases and this PR does better in some other cases. 

But for [MOD4_GRP](https://ci.opm-project.org/job/opm-simulators-PR-builder/4166/testReport/junit/(root)/mpi/compareECLFiles_flow_MOD4_GRP/) , this PR does much worse when coming to time stepping.

**Comment by GitPaean** [comment]
For https://ci.opm-project.org/job/opm-simulators-PR-builder/4163/ , it looks like similar, while more cases are involved. 

And similarly, more serious problems for the case 
https://ci.opm-project.org/job/opm-simulators-PR-builder/4163/testReport/junit/(root)/mpi/compareECLFiles_flow_MOD4_GRP/

**Comment by GitPaean** [comment]
benchmark please

**Comment by GitPaean** [comment]
For the case `MOD4_GRP`, local running shows the time stepping is pretty random due to a couple of report steps. In the local running, this PR is as bad as the master branch.  Maybe this is a test should be improved.

**Comment by GitPaean** [comment]
jenkins build this please

**Comment by GitPaean** [comment]
jenkins build this please

**Comment by GitPaean** [comment]
benchmark please

**Comment by ytelses** [comment]
Benchmark result overview: 




| Test    | Configuration                                     | Relative |
| ------- | ------------------------------------------------- | -------- |
| opm-git | OPM Benchmark: flow_mpi_extra - Threads: 1        | 0.944    |
| opm-git | OPM Benchmark: flow_mpi_extra - Threads: 8        | 0.997    |
| opm-git | OPM Benchmark: flow_mpi_norne - Threads: 1        | 1.008    |
| opm-git | OPM Benchmark: flow_mpi_norne - Threads: 8        | 1.018    |
| opm-git | OPM Benchmark: flow_mpi_norne_4c_msw - Threads: 1 | 0.961    |
| opm-git | OPM Benchmark: flow_mpi_norne_4c_msw - Threads: 8 | 0.854    |
* Speed-up = Total time master / Total time pull request. Above 1.0 is an improvement. *



View result details @ https://www.ytelses.com/opm/?page=result&id=1834

**Comment by ytelses** [comment]
Benchmark result overview: 




| Test    | Configuration                                                                                 | Relative |
| ------- | --------------------------------------------------------------------------------------------- | -------- |
| opm-git | OPM Benchmark: flow_mpi_extra - Threads: 1                                                    | 0.608    |
| opm-git | OPM Benchmark: flow_mpi_extra - Threads: 8                                                    | 0.507    |
| opm-git | OPM Benchmark: flow_mpi_norne - Threads: 1                                                    | 0.969    |
| opm-git | OPM Benchmark: flow_mpi_norne - Threads: 8                                                    | 0.995    |
| opm-git | OPM Benchmark: flow_mpi_norne_4c_msw - Threads: 1 - FOPT (Total Oil Production At End Of Run) | 0.979    |
| opm-git | OPM Benchmark: flow_mpi_norne_4c_msw - Threads: 8 - FOPT (Total Oil Production At End Of Run) | 0.922    |
* Speed-up = Total time master / Total time pull request. Above 1.0 is an improvement. *



View result details @ https://www.ytelses.com/opm/?page=result&id=1835

**Comment by GitPaean** [comment]
jenkins build this please

**Comment by GitPaean** [comment]
jenkins build this please

**Comment by GitPaean** [comment]
jenkins build this please

**Comment by GitPaean** [comment]
jenkins build this please

**Comment by GitPaean** [comment]
jenkins build this please

**Comment by GitPaean** [comment]
jenkins build this please

**Comment by GitPaean** [comment]
a new PR was created to replace this PR.

**Pull request closed without merging**
