### PR TITLE
fix typo in fip output

### PR DESCRIPTION
**Pull request by totto82**
Found a bug in ecloutputblackoilmodule.hh

### CODE REVIEW

**Comment by bska** [comment]
What was the practical outcome of this bug? Incorrect values, out-of-bounds indexing or something else?

**Comment by totto82** [comment]
> out-of-bounds indexing

**Comment by atgeirr** [comment]
jenkins build this please

**Comment by bska** [comment]
Okay, so this fixes a real problem and does not impact any existing test cases. I'll merge into master.  Thanks a lot!

**Pull request merged**
